import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { ArtifactTriple } from './artifact-triple';
import { CorrectionLifecycle } from './correction-lifecycle';
import { CreationWorkflow } from './creation-workflow';
import { DeploymentSnapshot } from './deployment-snapshot';
import { GovernanceRisk } from './governance-risk';
import { HandbookAnalogy } from './handbook-analogy';
import { HandbookKit } from './handbook-kit';
import { InspectableContrast } from './inspectable-contrast';
import { PipelineMap } from './pipeline-map';
import { ReleaseBoundary } from './release-boundary';
import { TraceScope } from './trace-scope';
import { TrackSplit } from './track-split';
import { BoundedArtifact } from './bounded-artifact';
import { ClaimQuiz } from './claim-quiz';
import { PipelineLens } from './pipeline-lens';
import { TraceStory } from './trace-story';
import { ExpertOpening } from './expert-opening';
import { NotAvatarAnalogy } from './not-avatar-analogy';
import { PipelineMachineAnalogy } from './pipeline-machine-analogy';
import { SkillEvolutionAnalogy } from './skill-evolution-analogy';
import { LifecycleCorrectionLab } from './lifecycle-correction-lab';
import { DeploymentRouteAnalogy } from './deployment-route-analogy';
import { DeploymentLab } from './deployment-lab';
import { S1EvidenceAnalogy } from './s1-evidence-analogy';
import { S6ClosingAnalogy } from './s6-closing-analogy';
import { ClosingJourney } from './closing-journey';
import { ContributionMap } from './contribution-map';
import { LimitationsLab } from './limitations-lab';
import { FutureEvaluation } from './future-evaluation';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['artifact-triple'] = ArtifactTriple;
widgetRegistry['correction-lifecycle'] = CorrectionLifecycle;
widgetRegistry['creation-workflow'] = CreationWorkflow;
widgetRegistry['deployment-snapshot'] = DeploymentSnapshot;
widgetRegistry['governance-risk'] = GovernanceRisk;
widgetRegistry['handbook-analogy'] = HandbookAnalogy;
widgetRegistry['handbook-kit'] = HandbookKit;
widgetRegistry['inspectable-contrast'] = InspectableContrast;
widgetRegistry['pipeline-map'] = PipelineMap;
widgetRegistry['release-boundary'] = ReleaseBoundary;
widgetRegistry['trace-scope'] = TraceScope;
widgetRegistry['track-split'] = TrackSplit;
widgetRegistry['bounded-artifact'] = BoundedArtifact;
widgetRegistry['claim-quiz'] = ClaimQuiz;
widgetRegistry['pipeline-lens'] = PipelineLens;
widgetRegistry['trace-story'] = TraceStory;
widgetRegistry['expert-opening'] = ExpertOpening;
widgetRegistry['not-avatar-analogy'] = NotAvatarAnalogy;
widgetRegistry['pipeline-machine-analogy'] = PipelineMachineAnalogy;
widgetRegistry['skill-evolution-analogy'] = SkillEvolutionAnalogy;
widgetRegistry['lifecycle-correction-lab'] = LifecycleCorrectionLab;
widgetRegistry['deployment-route-analogy'] = DeploymentRouteAnalogy;
widgetRegistry['deployment-lab'] = DeploymentLab;
widgetRegistry['s1-evidence-analogy'] = S1EvidenceAnalogy;
widgetRegistry['s6-closing-analogy'] = S6ClosingAnalogy;
widgetRegistry['closing-journey'] = ClosingJourney;
widgetRegistry['contribution-map'] = ContributionMap;
widgetRegistry['limitations-lab'] = LimitationsLab;
widgetRegistry['future-evaluation'] = FutureEvaluation;
