import React,{useEffect,useId,useRef,useState} from 'react';
export const palette={ink:'#21324a',muted:'#68778f',green:'#228d5c',red:'#c43f52',orange:'#f07e47',blue:'#27446e',line:'#d7deea',paper:'#ffffff',soft:'#eef3fb'};
export function usePlayback(resetKey:string,seconds=14){const [time,setTime]=useState(0),[playing,setPlaying]=useState(true),[restart,setRestart]=useState(0);const elapsed=useRef(0);useEffect(()=>{elapsed.current=0;setTime(0);setPlaying(true);},[resetKey,restart]);useEffect(()=>{if(!playing)return;let raf=0,last=0,paint=0;const tick=(now:number)=>{if(last&&!document.hidden)elapsed.current+=(now-last)/1000;last=now;if(now-paint>32){setTime(elapsed.current%seconds);paint=now;}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[playing,seconds,resetKey,restart]);return {time,p:time/seconds,playing,seek:(fraction:number)=>{elapsed.current=Math.max(0,Math.min(.999,fraction))*seconds;setTime(elapsed.current);setPlaying(false);},toggle:()=>setPlaying(x=>!x),replay:()=>setRestart(x=>x+1)};}
export function Svg({children,label,onPointerDown,onPointerMove,onPointerUp}:{children:React.ReactNode;label:string;onPointerDown?:React.PointerEventHandler<SVGSVGElement>;onPointerMove?:React.PointerEventHandler<SVGSVGElement>;onPointerUp?:React.PointerEventHandler<SVGSVGElement>}){return <svg className="scene-svg" viewBox="0 0 900 480" role="img" aria-label={label} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp}><rect width="900" height="480" fill="#f5f8f0" rx="8"/>{children}</svg>;}
export function Text({x,y,children,size=18,fill=palette.ink,anchor='start',weight=450}:{x:number;y:number;children:React.ReactNode;size?:number;fill?:string;anchor?:'start'|'middle'|'end';weight?:number}){return <text x={x} y={y} fill={fill} textAnchor={anchor} fontSize={size} fontWeight={weight} fontFamily="'Segoe UI', 'Microsoft YaHei', sans-serif">{children}</text>;}
export function Card({x,y,w,h,title,active=false,children,tone='green'}:{x:number;y:number;w:number;h:number;title?:string;active?:boolean;children?:React.ReactNode;tone?:'green'|'red'|'blue'}){return <g><rect x={x} y={y} width={w} height={h} rx="8" fill={active?'#eef3fb':palette.paper} stroke={active?palette[tone]:palette.line} strokeWidth={active?2.5:1.4}/>{title&&<><circle cx={x+21} cy={y+27} r="4" fill={active?palette[tone]:palette.muted}/><Text x={x+35} y={y+33} size={17} weight={650}>{title}</Text></>}{children}</g>;}
export function Lines({x,y,lines,size=18,gap=28,fill=palette.ink}:{x:number;y:number;lines:string[];size?:number;gap?:number;fill?:string}){return <>{lines.map((s,i)=><Text key={i} x={x} y={y+i*gap} size={size} fill={fill}>{s}</Text>)}</>;}
export function Typed({text,x,y,size=18}:{text:string;progress:number;x:number;y:number;size?:number}){return <Text x={x} y={y} size={size}>{text}</Text>;}
export function Link({d,active,time=0,color=palette.green}:{d:string;active:boolean;time?:number;color?:string}){return <><path d={d} fill="none" stroke={palette.line} strokeWidth="3"/><path d={d} fill="none" stroke={color} strokeWidth="3" strokeDasharray="9 8" strokeDashoffset={-time*22} opacity={active?1:.08}/></>;}
export function Badge({x,y,text,color=palette.green}:{x:number;y:number;text:string;color?:string}){return <g><rect x={x} y={y-21} width={text.length*16+26} height="31" fill="#ffffff" rx="15" stroke={palette.line}/><Text x={x+13} y={y} size={15} fill={color}>{text}</Text></g>;}
export const cupPaths={red:{body:'M75 110 C75 98 149 98 149 110 L143 181 Q112 202 80 181Z',handle:'M144 120 C181 119 180 169 144 168 L145 157 C165 160 166 130 144 131Z'},blue:{body:'M192 125 C192 114 253 114 253 125 L249 185 Q224 199 196 184Z',handle:'M250 132 C282 129 283 174 252 175 L252 166 C269 166 270 140 251 142Z'}};
let hitContext:CanvasRenderingContext2D|null=null;
export function cupAt(point:{x:number;y:number}):'red'|'blue'|'background'{hitContext??=document.createElement('canvas').getContext('2d');for(const name of ['red','blue'] as const){if(Object.values(cupPaths[name]).some(d=>hitContext?.isPointInPath(new Path2D(d),point.x*320,point.y*240)))return name;}return 'background';}
export function CupMask({target='red',progress=1,fill='#69a78b',opacity=.24,stroke=palette.green}:{target?:'red'|'blue';progress?:number;fill?:string;opacity?:number;stroke?:string}){return <g data-mask={target}>{Object.values(cupPaths[target]).map((d,i)=><g key={i}><path d={d} fill={fill} opacity={opacity*progress}/><path d={d} fill="none" stroke={stroke} strokeWidth="2" pathLength="1" strokeDasharray="1" strokeDashoffset={1-progress}/></g>)}</g>;}
export function Photo({x,y,w=320,h=240,time=0,target,mask=0,box=false,point,edit=0,editTarget='red',underwater=0,scan=true,onClick}:{x:number;y:number;w?:number;h?:number;time?:number;target?:'red'|'blue'|'background';mask?:number;box?:boolean;point?:{x:number;y:number};edit?:number;editTarget?:'red'|'blue';underwater?:number;scan?:boolean;onClick?:()=>void}){const uid=useId().replace(/:/g,'');const id='photo-'+uid;const rect=target==='blue'?{x:190,y:115,w:85,h:79}:{x:73,y:100,w:99,h:95};const trace=Math.min(1,Math.max(0,mask));const q=Math.max(0,Math.min(1,edit));return <svg x={x} y={y} width={w} height={h} viewBox="0 0 320 240" onClick={onClick} style={{cursor:onClick?'pointer':'default'}}>
 <defs><clipPath id={id}><rect x="1" y="1" width="318" height="238" rx="17"/></clipPath></defs>
 <g clipPath={`url(#${id})`}><rect width="320" height="240" fill="#e9eee3"/><rect width="320" height="240" fill="#a5d5df" opacity={underwater}/><circle cx={280} cy={36+Math.sin(time*.5)*2} r="20" fill="#d1dec7"/><rect y="183" width="320" height="57" fill="#d2b995"/><path d="M0 199 H320 M0 222 H320" stroke="#b79e7c" strokeWidth="1"/>
 <rect x="27" y="28" width="190" height="49" rx="7" fill="#fffdf1" stroke="#c6d3c2"/><Text x={122} y={60} size={22} anchor="middle" weight={650}>OPEN 08:00</Text>
 <g transform={`rotate(${Math.sin(time)*1.6},283,179)`}><path d="M282 170 Q262 108 278 95 M282 150 Q311 116 307 94" fill="none" stroke="#688363" strokeWidth="4"/><ellipse cx="270" cy="117" rx="11" ry="23" fill="#8aab7c" transform="rotate(-25 270 117)"/><ellipse cx="301" cy="120" rx="10" ry="21" fill="#8aab7c" transform="rotate(25 301 120)"/></g><path d="M261 157 H303 L298 196 H267Z" fill="#b29273"/>
 <ellipse cx="112" cy="194" rx="46" ry="8" fill="#b5a187"/>
 {(['red','blue'] as const).map(c=><g key={c} data-cup={c}><path d={cupPaths[c].handle} fill={c==='red'?'#ba675d':'#718fa0'}/><path d={cupPaths[c].body} fill={c==='red'?'#c47667':'#7e9cab'}/><g opacity={editTarget===c?q:0} data-edit={c}><path d={cupPaths[c].handle} fill="#96749e"/><path d={cupPaths[c].body} fill="#b390ba"/></g><ellipse cx={c==='red'?112:222} cy={c==='red'?111:125} rx={c==='red'?37:30} ry={c==='red'?9:8} fill={c==='red'?'#e2ab92':'#b0c7cd'}/><ellipse cx={c==='red'?112:222} cy={c==='red'?111:125} rx={c==='red'?37:30} ry={c==='red'?9:8} fill="#d1b9d7" opacity={editTarget===c?q:0}/>{c==='red'&&<ellipse cx="112" cy="111" rx="28" ry="5" fill="#72523d"/>}</g>)}
 <path d={`M104 ${92-Math.sin(time*1.4)*3} Q95 78 104 68 M124 ${93-Math.sin(time*1.4+1)*3} Q116 79 124 66`} stroke="#fff" strokeWidth="3" opacity={.75*(1-underwater)} fill="none"/>
 {underwater>0&&<g opacity={underwater}><path d={`M10 ${28+Math.sin(time)*4} Q100 8 185 29 T335 24`} stroke="#e5faff" strokeWidth="5" fill="none" opacity=".45"/>{[0,1,2,3,4].map(i=><circle key={i} cx={25+i*65+Math.sin(time+i)*4} cy={225-((time*23+i*43)%230)} r={3+i%3*2} fill="#dffaff" stroke="#8bbfcd" opacity=".65"/>)}</g>}
 {scan&&<rect x="8" y={83+(Math.sin(time*.9)+1)*52} width="302" height="3" rx="2" fill={palette.green} opacity=".3"/>}
 {target&&target!=='background'&&mask>0&&<CupMask target={target} progress={trace}/>}
 {box&&target!=='background'&&<rect x={rect.x-4} y={rect.y-4} width={rect.w+8} height={rect.h+8} rx="4" fill="none" stroke={palette.blue} strokeWidth="2.3" strokeDasharray="6 4"/>}
 {point&&<g><circle cx={point.x*320} cy={point.y*240} r={8+Math.sin(time*3)*2} fill="none" stroke={palette.orange} strokeWidth="2"/><circle cx={point.x*320} cy={point.y*240} r="4" fill={palette.orange}/></g>}
 </g><rect x="1" y="1" width="318" height="238" rx="17" fill="none" stroke="#d2dccd" strokeWidth="2"/>
 </svg>;}
export function Tool({x,y,name,sub,active,time=0,icon='scan'}:{x:number;y:number;name:string;sub:string;active:boolean;time?:number;icon?:string}){return <Card x={x} y={y} w={178} h={105} active={active}><g transform={`translate(${x+26},${y+33})`} stroke={active?palette.green:palette.muted} fill="none" strokeWidth="2"><rect width="27" height="30" rx="5"/>{icon==='text'?<Text x={7} y={22} size={18} fill={active?palette.green:palette.muted}>A</Text>:<><path d="M5 8H22 M5 23H22"/><path d={`M3 ${8+(Math.sin(time*2)+1)*8}H24`}/></>}</g><Text x={x+66} y={y+48} size={16} weight={650}>{name}</Text><Text x={x+20} y={y+82} size={15} fill={palette.muted}>{sub}</Text></Card>;}
export function PlayerButtons({playing,toggle,replay}:{playing:boolean;toggle:()=>void;replay:()=>void}){return <div className="player-controls"><button onClick={toggle} aria-label={playing?'暂停动画':'播放动画'}>{playing?'Ⅱ':'▷'}</button><button onClick={replay} aria-label="重新播放动画">↻</button><span>{playing?'动画演示中':'动画已暂停'}</span></div>;}
export function Choice({items,value,onChange}:{items:string[];value:number;onChange:(i:number)=>void}){return <div className="choices">{items.map((s,i)=><button key={s} className={i===value?'selected':''} aria-pressed={i===value} onClick={()=>onChange(i)}>{s}</button>)}</div>;}
export function phase(p:number,from:number,to:number){return Math.max(0,Math.min(1,(p-from)/(to-from)));}
