import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { FigArch } from './fig-arch';
import { FigCapabilities } from './fig-capabilities';
import { FigDataRecipe } from './fig-data-recipe';
import { FigEdit } from './fig-edit';
import { FigResults } from './fig-results';
import { FigSpatial } from './fig-spatial';
import { FigTwnv } from './fig-twnv';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { Sec1Ana } from './sec1-ana';
import { Sec1Mod1 } from './sec1-mod1';
import { Sec2Ana } from './sec2-ana';
import { Sec2Mod1 } from './sec2-mod1';
import { Sec3Ana } from './sec3-ana';
import { Sec3Mod1 } from './sec3-mod1';
import { Sec4Ana } from './sec4-ana';
import { Sec4Mod1 } from './sec4-mod1';
import { SecGenerationRoadmap } from './sec-generation-roadmap';
import { SecEditMod1 } from './sec-edit-mod1';
import { SecEditingRoadmap } from './sec-editing-roadmap';
import { Sec5Ana } from './sec5-ana';
import { Sec5Mod1 } from './sec5-mod1';
import { Sec6Ana } from './sec6-ana';
import { Sec6Mod1 } from './sec6-mod1';
import { SecTwnvReconstruction } from './sec-twnv-reconstruction';
import { SecTwnvCases } from './sec-twnv-cases';
import { SecSummaryLoop } from './sec-summary-loop';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['fig-arch'] = FigArch;
widgetRegistry['fig-capabilities'] = FigCapabilities;
widgetRegistry['fig-data-recipe'] = FigDataRecipe;
widgetRegistry['fig-edit'] = FigEdit;
widgetRegistry['fig-results'] = FigResults;
widgetRegistry['fig-spatial'] = FigSpatial;
widgetRegistry['fig-twnv'] = FigTwnv;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['sec1-ana'] = Sec1Ana;
widgetRegistry['sec1-mod1'] = Sec1Mod1;
widgetRegistry['sec2-ana'] = Sec2Ana;
widgetRegistry['sec2-mod1'] = Sec2Mod1;
widgetRegistry['sec3-ana'] = Sec3Ana;
widgetRegistry['sec3-mod1'] = Sec3Mod1;
widgetRegistry['sec4-ana'] = Sec4Ana;
widgetRegistry['sec4-mod1'] = Sec4Mod1;
widgetRegistry['sec-generation-roadmap'] = SecGenerationRoadmap;
widgetRegistry['sec-edit-mod1'] = SecEditMod1;
widgetRegistry['sec-editing-roadmap'] = SecEditingRoadmap;
widgetRegistry['sec5-ana'] = Sec5Ana;
widgetRegistry['sec5-mod1'] = Sec5Mod1;
widgetRegistry['sec6-ana'] = Sec6Ana;
widgetRegistry['sec6-mod1'] = Sec6Mod1;
widgetRegistry['sec-twnv-reconstruction'] = SecTwnvReconstruction;
widgetRegistry['sec-twnv-cases'] = SecTwnvCases;
widgetRegistry['sec-summary-loop'] = SecSummaryLoop;
