import React, { useId, useState } from 'react';
import { useLessonPlayback, type LessonPlayback } from './useLessonPlayback';
import type { WidgetProps } from './registry';

export function PlaybackBar({ player, label = '演示进度' }: { player: LessonPlayback; label?: string }) {
 const id = useId();
 return <div className="lesson-playback"><div className="lesson-playback-buttons"><button type="button" className="lesson-primary" aria-label={player.playing ? '暂停演示' : '播放演示'} onClick={player.toggle}>{player.playing ? 'Ⅱ 暂停' : '▶ 播放'}</button><button type="button" onClick={player.advance} disabled={player.progress >= 1}>单步</button><button type="button" onClick={player.reset}>↺ 重置</button></div><label className="lesson-scrubber" htmlFor={id}><span>{label}</span><input id={id} type="range" min="0" max="100" value={Math.round(player.progress * 100)} onChange={e => player.seek(Number(e.target.value) / 100)} /></label></div>;
}
const brainPath='M50 128 C20 110 22 73 43 62 C39 28 76 8 100 23 C123 4 165 17 169 48 C199 57 201 96 181 112 C185 141 153 163 129 153 C100 176 61 159 50 128Z';
export function SignalJourney({ detailed = false }: { detailed?: boolean }) {
 const player = useLessonPlayback(detailed ? 7 : 4, 12);
 const [scene, setScene] = useState<'movie'|'podcast'|'silent'>('movie');
 const labels = detailed ? ['感官输入','冻结特征','384D 对齐','Transformer','2 → 1 Hz','被试路线','BOLD 输出'] : ['感官刺激','冻结模型提取特征','长时间上下文','预测 BOLD'];
 const stage = player.step;
 const lanes = [{name:'文本',code:'T',dim:'2048D',active:scene!=='silent',color:'#8b5bb1'},{name:'音频',code:'A',dim:'1024D',active:scene!=='silent',color:'#bc6a34'},{name:'视频',code:'V',dim:'1280D',active:scene!=='podcast',color:'#326c9d'}];
 const caption = scene==='movie'?'窗边的人说了一句「你好」。':scene==='podcast'?'听一段带有文字转写的播客。':'观看一段没有声音的视频。';
 const descriptions=detailed?['研究中可用多少模态，就提供多少模态；缺失模态保留对应槽位。','Llama、Wav2Vec-BERT 与 V-JEPA 提取冻结的多层特征。','层分组平均、拼接，再分别投影至 384D；三条槽位拼成 1152D。','8 层、8 头 Transformer 在 100 秒上下文中整合时间信息。','自适应平均池化：2 Hz 刺激表示 → 1 Hz fMRI 表示。','已见被试走个体映射；未见被试走独立共享线性层。','输出是预测脑响应。这里的脑图只示意任务方向，不是真实模型预测。']:['先给模型一段视频、音频或文字。它的任务是预测观看或聆听时的脑响应。','三种冻结编码器把原始刺激变成特征。缺少的模态不会被凭空补出。','共享 Transformer 整合约 100 秒的上下文，而不是只看当前一瞬间。','从共享表示映射到预测 BOLD。此动画不运行模型，颜色与波形仅作教学示意。'];
 return <div className="signal-journey lesson-lab" ref={player.root} data-testid={detailed?'architecture-journey':'hero-journey'}>
 <div className="lesson-lab-header"><span className="lesson-eyebrow">{detailed?'MODEL WALKTHROUGH':'一次脑编码之旅'}</span><span className="lesson-source">教学示意</span></div>
 <div className="lesson-tabs" aria-label="选择刺激类型">{([['movie','有声电影'],['podcast','播客 + 转写'],['silent','静音视频']] as const).map(([key,label])=><button type="button" key={key} aria-pressed={scene===key} onClick={()=>{setScene(key);player.reset()}}>{label}</button>)}</div>
 <div className="journey-stage" data-stage={stage}>
 <div className={'stimulus-screen '+scene}><div className="stimulus-scene"><div className="scene-window"/><div className="scene-person" style={{transform:`translateX(${player.progress*84}px)`}}><i/><b/><em/></div><div className="scene-audio" aria-hidden="true">{Array.from({length:15},(_,i)=><i key={i} style={{height:9+Math.abs(Math.sin(i*1.3+player.progress*24))*31}}/>)}</div></div><div className="stimulus-caption">{caption}</div></div>
 <div className="journey-lanes">{lanes.map((lane,i)=><div className={'journey-lane '+(!lane.active?'is-masked':'')} key={lane.code} style={{'--lane-color':lane.color} as React.CSSProperties}><span>{lane.code}</span><b>{lane.name}</b><div className="journey-track"><i style={{left:`${(player.progress*180+i*17)%100}%`,opacity:lane.active?1:0}}/></div><small>{lane.active?(stage>0?(detailed&&stage<2?lane.dim:'384D'):'输入'):'缺失'}</small></div>)}</div>
 <div className={'journey-model '+(stage>=Math.floor(labels.length/2)?'is-lit':'')}><span>TRIBE v2</span><div className="model-layers">{Array.from({length:8},(_,i)=><i key={i} style={{opacity:stage>=Math.floor(labels.length/2)? .3+ .7*((i+Math.floor(player.progress*24))%8)/7:.15}}/>)}</div><small>共享 Transformer</small></div>
 <div className="journey-brain"><svg viewBox="0 0 225 190" role="img" aria-label="预测脑响应示意"><path d={brainPath} fill="#edf2e9" stroke="#497655" strokeWidth="2"/>{[[70,65],[107,51],[144,71],[70,107],[113,114],[149,119]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r={9+Math.sin(player.progress*20+i)*2} fill={lanes[i%3].color} opacity={stage===labels.length-1&&lanes[i%3].active?.55:.08}/>)}<path d="M100 30 C80 70 141 75 112 145 M44 83 C85 60 137 127 173 86" fill="none" stroke="#bdcdb9" strokeWidth="2"/></svg><strong>预测 BOLD</strong><small>脑区与颜色均为示意</small></div>
 </div><div className="journey-steps">{labels.map((s,i)=><button key={s} type="button" className={i===stage?'current':i<stage?'done':''} aria-current={i===stage?'step':undefined} onClick={()=>player.seek(i/(labels.length-1))}><span>{String(i+1).padStart(2,'0')}</span>{s}</button>)}</div><p className="lesson-feedback" aria-live="polite">{descriptions[stage]}</p><PlaybackBar player={player}/>{detailed&&<p className="lesson-footnote">论文 Methods §5.2–5.3。音频编码使用双向上下文，整套系统并非严格在线因果模型。</p>}
 </div>;
}
export const ArchitectureJourney:React.FC<WidgetProps>=()=> <SignalJourney detailed/>;

export const TemporalAlignmentLab:React.FC<WidgetProps>=()=>{
 const player=useLessonPlayback(16,12);const [aligned,setAligned]=useState(true);const t=Math.round(player.progress*15);const lag=aligned?5:0;const stim=t-lag;
 const x=(value:number)=>100+(value+5)*30;
 return <div className="lesson-lab temporal-lab" ref={player.root}><div className="lesson-lab-header"><span className="lesson-eyebrow">同一个时刻，要配哪段刺激？</span><span className="lesson-source">Methods §5.8</span></div><div className="lesson-tabs"><button type="button" aria-pressed={!aligned} onClick={()=>setAligned(false)}>未做偏移 · 对照</button><button type="button" aria-pressed={aligned} onClick={()=>setAligned(true)}>论文设置 · 5 秒</button></div>
 <div className="temporal-readout"><div><span>要预测的 BOLD 时刻</span><strong>{t}<small> 秒</small></strong></div><span>←</span><div><span>对应刺激时刻</span><strong>{stim}<small> 秒</small></strong></div><div className="temporal-equation">t<sub>stim</sub> = t<sub>BOLD</sub> − {lag}s</div></div>
 <svg className="temporal-axis" viewBox="0 0 820 190" role="img" aria-label={`BOLD ${t} 秒对应刺激 ${stim} 秒，偏移 ${lag} 秒`}><text x="7" y="53">刺激 · 2 Hz</text><text x="7" y="128">BOLD · 1 Hz</text><path d="M100 49H760 M100 124H760" stroke="#d2dcd3" strokeWidth="2"/>{Array.from({length:43},(_,i)=><circle key={i} cx={100+i*15} cy="49" r={Math.abs((-5+i*.5)-stim)<.6?6:3} fill={Math.abs((-5+i*.5)-stim)<.6?'#356d4e':'#c9d6cc'}/>)}{Array.from({length:22},(_,i)=><React.Fragment key={i}><circle cx={100+i*30} cy="124" r={-5+i===t?7:4} fill={-5+i===t?'#875ba6':'#d3c8dc'}/>{i%5===0&&<text x={100+i*30} y="166" textAnchor="middle">{i-5}s</text>}</React.Fragment>)}<path d={`M${x(stim)} 49L${x(t)} 124`} stroke={aligned?'#356d4e':'#bc6a34'} strokeWidth="3"/><circle cx={x(stim)} cy="49" r="10" fill="none" stroke="#356d4e"/><circle cx={x(t)} cy="124" r="12" fill="none" stroke="#875ba6"/></svg>
 <p className="lesson-feedback" aria-live="polite">{aligned?`预测 ${t} 秒的 BOLD，配对 ${stim} 秒的刺激。5 秒用于血流动力学时间对齐；2 Hz → 1 Hz 是另一项采样率转换。`:'同一时刻直接配对忽略了血流动力学延迟。切换到论文设置，观察连接线怎样指向更早的刺激。'}</p><PlaybackBar player={player} label="目标时刻"/><p className="lesson-footnote">负时间表示目标窗口之前的上下文；直线仅表示时间配对，不是实测 BOLD 波形。论文采用固定 5 秒，没有在此搜索最优延迟。</p></div>;
};

export const ModalityDropLab:React.FC<WidgetProps>=()=>{
 const player=useLessonPlayback(6,8);const [mask,setMask]=useState([true,true,true]);const [notice,setNotice]=useState('');const names=['文本','音频','视频'];
 const toggle=(i:number)=>{if(mask[i]&&mask.filter(Boolean).length===1){setNotice('至少保留一种模态。三条都被遮蔽时，论文会重新采样。');return}setMask(m=>m.map((v,k)=>k===i?!v:v));setNotice('')};
 return <div className="lesson-lab dropout-lab" ref={player.root}><div className="lesson-lab-header"><span className="lesson-eyebrow">试着拿掉一条输入</span><span className="lesson-source">Methods §5.3</span></div><div className="dropout-stage">{names.map((n,i)=><button key={n} type="button" className={'dropout-channel '+(!mask[i]?'off':'')} aria-pressed={mask[i]} onClick={()=>toggle(i)}><span className="dropout-switch">{mask[i]?'● 开启':'○ 置零'}</span><strong>{n}</strong><div className="feature-bars">{Array.from({length:16},(_,k)=><i key={k} style={{height:mask[i]?12+Math.abs(Math.sin(k*.8+player.progress*16+i))*35:2,opacity:mask[i]?.4+(k%3)*.2:.25}}/>)}</div><small>{mask[i]?'384D 特征':'384D 零张量'}</small></button>)}</div><div className="dropout-output"><span>输入槽位固定</span><strong>384 + 384 + 384 = 1152D</strong><span>共享网络保持不变</span></div><p className="lesson-feedback" aria-live="polite">{notice||`当前保留 ${names.filter((_,i)=>mask[i]).join('、')}。缺失模态的对应张量置零，网络不会更换结构。`}</p><PlaybackBar player={player}/><p className="lesson-footnote">训练时每模态以 p=0.3 独立遮蔽，并保证至少保留一条。柱条为特征示意，不代表真实激活或预测准确率。</p></div>;
};

export function ContextWindowLab(){
 const player=useLessonPlayback(10,10);const selected=Math.min(19,Math.floor(player.progress*20));
 return <div className="lesson-lab context-lab" ref={player.root}><div className="lesson-lab-header"><span className="lesson-eyebrow">相同特征，不同时间建模</span><span className="lesson-source">教学示意</span></div><div className="context-rows">{['Deep FIR','Transformer'].map((name,row)=><div className={'context-row '+(row?'long':'short')} key={name}><header><strong>{name}</strong><span>{row?'100 秒上下文 · 非线性整合':'9 TR 卷积窗口 · 线性映射'}</span></header><div className="context-cells">{Array.from({length:20},(_,i)=><span key={i} className={(i<=selected&&(row||i>=selected-3)?'active ':'')+(i===selected?'cursor':'')}><i style={{height:12+Math.abs(Math.sin(i*1.2))*26}}/></span>)}</div></div>)}</div><p className="lesson-feedback">移动播放头，比较局部窗口与长上下文的覆盖方式。Transformer 可以学习更长时段的非线性关系；这不是人脑采用 Transformer 的证明。</p><PlaybackBar player={player}/><p className="lesson-footnote">两行色块均作归一化示意，不用宽度换算 9 TR 与 100 秒，也不是论文的真实注意力权重。</p></div>;
}
