import { ArchitectureJourney, TemporalAlignmentLab, ModalityDropLab } from './lesson-labs';
import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AnalogyCh1 } from './analogy-ch1';
import { AnalogyCh10 } from './analogy-ch10';
import { AnalogyCh2 } from './analogy-ch2';
import { AnalogyCh3 } from './analogy-ch3';
import { AnalogyCh4 } from './analogy-ch4';
import { AnalogyCh5 } from './analogy-ch5';
import { AnalogyCh6 } from './analogy-ch6';
import { AnalogyCh7 } from './analogy-ch7';
import { AnalogyCh8 } from './analogy-ch8';
import { AnalogyCh9 } from './analogy-ch9';
import { FinetuneRank } from './finetune-rank';
import { FragmentationStress } from './fragmentation-stress';
import { HeroFragmented } from './hero-fragmented';
import { HeroUnified } from './hero-unified';
import { InsilicoMap, InsilicoResults } from './insilico-map';
import { LinearVsTransformer } from './linear-vs-transformer';
import { ModalityAligner } from './modality-aligner';
import { ModalityDropout } from './modality-dropout';
import { PaperFigureOnly } from './paper-figure-only';
import { IcaExplorer, MultimodalIca, MultimodalMap } from './multimodal-ica';
import { Figure2Highlights, Figure3Highlights } from './result-highlights';
import { ResultRace } from './result-race';
import { StudioBase } from './studio-base';
import { SubjectRoute } from './subject-route';
import { TimeAlignment } from './time-alignment';
import { TrainingValidation } from './training-validation';
import { TribeArchitecture } from './tribe-architecture';
import { UnifiedCoverage } from './unified-coverage';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['analogy-ch1'] = AnalogyCh1;
widgetRegistry['analogy-ch10'] = AnalogyCh10;
widgetRegistry['analogy-ch2'] = AnalogyCh2;
widgetRegistry['analogy-ch3'] = AnalogyCh3;
widgetRegistry['analogy-ch4'] = AnalogyCh4;
widgetRegistry['analogy-ch5'] = AnalogyCh5;
widgetRegistry['analogy-ch6'] = AnalogyCh6;
widgetRegistry['analogy-ch7'] = AnalogyCh7;
widgetRegistry['analogy-ch8'] = AnalogyCh8;
widgetRegistry['analogy-ch9'] = AnalogyCh9;
widgetRegistry['finetune-rank'] = FinetuneRank;
widgetRegistry['fragmentation-stress'] = FragmentationStress;
widgetRegistry['hero-fragmented'] = HeroFragmented;
widgetRegistry['hero-unified'] = HeroUnified;
widgetRegistry['insilico-map'] = InsilicoMap;
widgetRegistry['insilico-results'] = InsilicoResults;
widgetRegistry['linear-vs-transformer'] = LinearVsTransformer;
widgetRegistry['modality-aligner'] = ModalityAligner;
widgetRegistry['modality-dropout'] = ModalityDropLab;
widgetRegistry['paper-figure-only'] = PaperFigureOnly;
widgetRegistry['multimodal-ica'] = MultimodalIca;
widgetRegistry['ica-explorer'] = IcaExplorer;
widgetRegistry['multimodal-map'] = MultimodalMap;
widgetRegistry['figure2-highlights'] = Figure2Highlights;
widgetRegistry['figure3-highlights'] = Figure3Highlights;
widgetRegistry['result-race'] = ResultRace;
widgetRegistry['studio-base'] = StudioBase;
widgetRegistry['subject-route'] = SubjectRoute;
widgetRegistry['time-alignment'] = TemporalAlignmentLab;
widgetRegistry['training-validation'] = TrainingValidation;
widgetRegistry['tribe-architecture'] = ArchitectureJourney;
widgetRegistry['unified-coverage'] = UnifiedCoverage;
