import React,{useRef,useState} from 'react';
import {useEditingSession} from '../lib/EditingSession';

const cookingVideoUrl = `${import.meta.env.BASE_URL}videos/cooking-seasoning.mp4`;

const missionAgents=['VideoPreloader','VideoSearcher','RhythmDetector','VideoEditor'];
const missionAgentInfo=[
  {zh:'视频预加载智能体',fn:'读取视频并建立可检索的帧索引'},
  {zh:'视频检索智能体',fn:'根据分镜文本找出候选镜头'},
  {zh:'节奏检测智能体',fn:'从音频中提取节拍时间点'},
  {zh:'视频编辑智能体',fn:'接收镜头与节奏提示，生成最终成片'},
];
const nodePos=[[18,25],[18,75],[82,25],[82,75]];
type Edge=[number,number];
const required=new Set(['0-1','1-3','2-3']);
function cycle(edges:Edge[]){const a=missionAgents.map(()=>[] as number[]);edges.forEach(([x,y])=>a[x].push(y));const s=[0,0,0,0];const d=(n:number):boolean=>{s[n]=1;for(const x of a[n])if(s[x]===1||(!s[x]&&d(x)))return true;s[n]=2;return false};return s.some((_,i)=>!s[i]&&d(i))}
function comps(edges:Edge[]){const a=missionAgents.map(()=>[] as number[]);edges.forEach(([x,y])=>{a[x].push(y);a[y].push(x)});let c=0;const seen=new Set<number>();for(let i=0;i<4;i++)if(!seen.has(i)){c++;const q=[i];seen.add(i);while(q.length)for(const x of a[q.pop()!])if(!seen.has(x)){seen.add(x);q.push(x)}}return c}

export function VideoAgentMission(){const [level,setLevel]=useState(1);const {shot,setShot,start,setStart,end,setEnd,intent,clips,reset}=useEditingSession();const [edges,setEdges]=useState<Edge[]>([]);const [from,setFrom]=useState<number>();const [fixed,setFixed]=useState(false);const video=useRef<HTMLVideoElement>(null);const trimGood=end-start>=3&&end-start<=8;const graphGood=!cycle(edges)&&comps(edges)===1&&[...required].every(k=>edges.some(([a,b])=>`${a}-${b}`===k));const inspect=(id:string,time:number)=>{setShot(id);if(video.current){video.current.currentTime=time;void video.current.play().catch(()=>{})}};const preview=()=>{if(video.current){video.current.currentTime=start;void video.current.play().catch(()=>{})}};const add=(i:number)=>{if(from===undefined){setFrom(i);return}if(from!==i&&!edges.some(e=>e[0]===from&&e[1]===i))setEdges([...edges,[from,i]]);setFrom(undefined)};const restart=()=>{reset();setEdges([]);setFrom(undefined);setFixed(false);setLevel(1)};const done=level===5;
return <section className="mission" id="videoagent-mission"><header><span className="mission-kicker">VIDEOAGENT 交互式任务</span><h2>现在，你就是 VideoAgent</h2><p>把一段烹饪视频剪成简洁、具有电影感的故事。</p><small>教学模拟（Illustrative Simulation）· 不运行真实 VideoAgent 模型。</small></header><nav className="mission-progress">{['找镜头','精裁剪','建图','优化'].map((x,i)=><span className={level>i+1?'done':level===i+1?'active':''} key={x}>{i+1}. {x}</span>)}</nav>
{level===1&&<div className="mission-level"><h3>第 1 关 — 找到目标镜头</h3><div className="mission-brief">分镜要求 · “找到正在加入调味料的镜头。”</div><video ref={video} className="paper-video mission-video" src={cookingVideoUrl} controls muted playsInline/><div className="mission-shots">{[['A','1.5s · 动作前',1.5],['B','6.5s · 撒盐中',6.5],['C','14.2s · 动作后',14.2]].map(([id,label,time])=><button className={`mission-shot shot-${id} ${shot===id?'selected':''}`} onClick={()=>inspect(String(id),Number(time))} key={String(id)}><span className="video-timecode">{label}</span><b>候选镜头 {id}</b><small>查看真实视频片段</small></button>)}</div>{shot&&<div className={`feedback ${shot==='B'?'good':'bad'}`}>{shot==='B'?'✓ 正确 — 跨模态检索（Cross-modal Retrieval）：候选 B 位于调味动作发生窗口。':`候选 ${shot} 位于目标动作${shot==='A'?'开始之前':'结束之后'}。`}</div>}<button className="mission-next" disabled={shot!=='B'} onClick={()=>setLevel(2)}>继续精细裁剪 →</button></div>}
{level===2&&<div className="mission-level"><h3>第 2 关 — 精裁关键时刻</h3><video ref={video} className="paper-video mission-video" src={cookingVideoUrl} controls muted playsInline onTimeUpdate={e=>{if(e.currentTarget.currentTime>=end){e.currentTarget.currentTime=start;e.currentTarget.pause()}}}/><button className="preview-cut" onClick={preview}>▶ 预览所选片段</button><div className="mission-timeline"><span style={{left:`${start/14.8*100}%`}}>起点 {start.toFixed(1)}s</span><i style={{left:`${start/14.8*100}%`,width:`${(end-start)/14.8*100}%`}}/><span style={{left:`${end/14.8*100}%`}}>终点 {end.toFixed(1)}s</span></div><div className="dual-range"><label>起点 START<input type="range" min="0" max="13" step="0.2" value={start} onChange={e=>setStart(Math.min(+e.target.value,end-.4))}/></label><label>终点 END<input type="range" min="1" max="14.8" step="0.2" value={end} onChange={e=>setEnd(Math.max(+e.target.value,start+.4))}/></label></div><div className={`feedback ${trimGood?'good':'bad'}`}>{end-start<3?'太短（Too Short）— 关键动作不完整。':end-start>8?'太长（Too Long）— 包含无关前后文。':'合适（Good）— 细粒度裁剪保留了完整关键动作。'}</div><button className="mission-next" disabled={!trimGood} onClick={()=>setLevel(3)}>构建智能体图 →</button></div>}
{level===3&&<div className="mission-level"><h3>第 3 关 — 构建智能体图（Agent Graph）</h3><p className="lab-help">像连接剪辑台线缆一样：先点输出节点，再点输入节点。每个节点都标出了中文名称和具体职责。</p><div className="agent-order-guide"><b>推荐依赖顺序</b><div className="agent-order-flow"><span>① VideoPreloader<br/>读取并索引视频</span><i>→</i><span>② VideoSearcher<br/>检索目标镜头</span><i>→</i><span>④ VideoEditor<br/>生成最终成片</span><span>③ RhythmDetector<br/>提取节奏提示</span><i>↗ 汇入编辑器</i></div></div><div className="mission-graph-stage"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="cable-arrow" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 Z"/></marker></defs>{edges.map(([a,b],i)=><line key={i} x1={nodePos[a][0]} y1={nodePos[a][1]} x2={nodePos[b][0]} y2={nodePos[b][1]} className={required.has(`${a}-${b}`)?'valid-cable':'invalid-cable'}/>)}</svg>{missionAgents.map((n,i)=><button style={{left:`${nodePos[i][0]}%`,top:`${nodePos[i][1]}%`}} className={from===i?'armed':''} onClick={()=>add(i)} key={n}><small>{i===3?'输出':'智能体'}</small>{n}<span className="node-zh">{missionAgentInfo[i].zh}</span><span className="node-fn">{missionAgentInfo[i].fn}</span><i>{from===i?'选择终点…':'●'}</i></button>)}</div><div className="edge-list">{edges.length?edges.map(([a,b],i)=><button key={i} onClick={()=>setEdges(edges.filter((_,j)=>j!==i))}>{missionAgents[a]} → {missionAgents[b]} ×</button>):<span>尚未连接线缆</span>}</div><div className="graph-metrics"><span>τ(G) <b>{cycle(edges)?0:1}</b></span><span>|Γ(G)| <b>{comps(edges)}</b></span><span>κ <b>{(new Set(edges.flat()).size/4).toFixed(2)}</b></span><span>χ <b>{edges.length?(edges.filter(([a,b])=>required.has(`${a}-${b}`)).length/edges.length).toFixed(2):'—'}</b></span></div><div className={`feedback ${graphGood?'good':'bad'}`}>{cycle(edges)?'❌ 检测到环（Cycle）':comps(edges)>1?'❌ 存在未连接的组件':edges.some(([a,b])=>!required.has(`${a}-${b}`))?'❌ 无效边或参数流':graphGood?'✓ 有效的有向无环图（Valid DAG）':'继续连接智能体以覆盖任务意图。'}</div><button className="mission-next" disabled={!graphGood} onClick={()=>setLevel(4)}>优化工作流 →</button></div>}
{level===4&&<div className="mission-level"><h3>第 4 关 — 修复工作流</h3><div className={`workflow-repair ${fixed?'fixed':''}`}><div><span>VideoSearcher</span><i>检索到的镜头</i></div><b>→</b><div><span>VideoEditor</span><i>最终成片</i></div><em>← 无效的反向依赖</em></div><div className="issue-box"><b>检测到问题</b><p>“当前图包含循环依赖。应保持先检索、后编辑，并删除反向边。”</p></div><label className="repair-control"><input type="checkbox" checked={fixed} onChange={e=>setFixed(e.target.checked)}/><span className="repair-switch"/> 断开无效的反向连线</label><div className={`feedback ${fixed?'good':'bad'}`}>{fixed?'✓ 有效 DAG · ✓ 与用户意图一致':'仍然存在环，工作流无法按拓扑顺序执行。'}</div>{fixed&&<p className="success-copy">你刚刚完成了一个简化版的“文本梯度图优化”（Textual-Gradient Graph Optimization）教学模拟。</p>}<button className="mission-next" disabled={!fixed} onClick={()=>setLevel(5)}>完成任务 →</button></div>}
{done&&<div className="mission-complete"><div className="mission-spark">✦</div><h3>VIDEOAGENT 任务完成</h3><p>{intent} 导演意图 · 工作流已锁定</p><div className="final-cut"><video ref={video} className="paper-video" src={cookingVideoUrl} controls muted playsInline onTimeUpdate={e=>{if(e.currentTarget.currentTime>=end)e.currentTarget.pause()}}/><button className="preview-cut" onClick={preview}>▶ 回放你裁出的 {start.toFixed(1)}–{end.toFixed(1)} 秒片段</button><div className="final-cut-strip">{clips.map(c=><span key={c.id}><b>{c.label}</b><small>{c.start.toFixed(1)}–{c.end.toFixed(1)}s</small></span>)}</div></div><div className="completion-grid">{['理解','规划','检索','裁剪','建图','优化'].map(x=><span key={x}>{x} ✓</span>)}</div><div className="replay-flow">{['用户指令','全局理解','分镜规划','镜头检索','细粒度裁剪','智能体选择','智能体图','文本梯度','执行','结果'].map((x,i)=><React.Fragment key={x}><span style={{animationDelay:`${i*.1}s`}}>{x}</span>{i<9&&<i>→</i>}</React.Fragment>)}</div><div className="mission-badge">教学任务已完成</div><button className="mission-restart" onClick={restart}>↻ 从头再玩一次</button></div>}
</section>}
