import React,{useState} from 'react';
import {Scene,C,clearScene,line,box,label,Controls,Button,Feedback,useProgress} from './scene-kit';
type Metric={name:string;protocol:string;source:string;higher:boolean;scale:number;names:string[];values:number[];display?:string[];finding:string};
const metrics:Metric[]=[
{name:'LLaVA-Bench · COCO',protocol:'30张COCO图 / 90问；GPT-4-0314相对参考评分（非准确率）',source:'表4(a)',higher:true,scale:100,names:['LLaVA','仅测试加工具','Plus · All Tools','Plus · Fly','Fly · 无 thoughts'],values:[81.2,59.1,83.9,80.4,79.4],finding:'Fly 80.4 低于原版81.2；All Tools 为83.9。不能将正文的概括解释为所有版本、所有指标都提高。'},
{name:'LLaVA-Bench · In-the-Wild',protocol:'24张网络图 / 60问；GPT-4-0314相对参考评分',source:'表4(a)',higher:true,scale:100,names:['LLaVA','仅测试加工具','Plus · All Tools','Plus · Fly','Fly · 无 thoughts'],values:[57.1,47.5,69.5,59.1,48.7],finding:'相同表中 All Tools 提高，Fly 去掉 thoughts 后下降；这项消融支持该训练格式，但不是通用因果保证。'},
{name:'SEED-Bench · 平均分',protocol:'论文所述约19K多选题；表内同协议平均分',source:'表4(b)',higher:true,scale:100,names:['LLaVA','仅测试加工具','Plus · All Tools','Plus · Fly'],values:[44.45,51.54,55.01,53.25],finding:'仅在测试时加入工具结果从44.45提高到51.54，与 LLaVA-Bench 的下降不同。保留这种跨评测差异。'},
{name:'工具专项 · 总分',protocol:'自建44项：定位10 / 标签12 / 描述12 / OCR10；相对评分（非API调用成功率）',source:'表5',higher:true,scale:100,names:['LLaVA','仅测试加工具','Plus · All Tools','Plus · Fly'],values:[58.7,48.5,82.3,76.5],finding:'All Tools 82.3 在这项小规模工具专项评测中较高；不能将44项结果外推为所有开放任务的可靠保证。'},
{name:'MM-Vet · 同规模7B',protocol:'200图 / 218问；GPT-4-0613评分；作者自行复测的7B模型',source:'表6',higher:true,scale:50,names:['LLaVA-7B','Plus-7B · All Tools'],values:[24.1,27.5],display:['24.1 ± 0.0','27.5 ± 0.3'],finding:'同规模作者复测从24.1到27.5；保留论文误差标记，不把不同参数规模混成受控比较。'},
{name:'VisiT-Bench · 历史Elo',protocol:'截至2023-09-27的榜单；592问 / 1159图 / 70类指令；不是当前排名',source:'表7',higher:true,scale:1400,names:['LLaVA-13B','Plus-13B'],values:[1095,1203],finding:'分别5420与678场匹配。相对人工参考胜率18.53%(475条评分)与35.07%(134条评分)，并非两模型直接对战胜率。'},
{name:'COCO Caption · CLIP score',protocol:'论文附录COCO Caption；表11未给出具体split，不补造',source:'表11',higher:true,scale:1,names:['BLIP2','Plus-7B','LLaVA-7B'],values:[.788,.815,.785],finding:'Plus 的 CLIP score 较高，但下一项 CIDEr 明显低于 BLIP2；视觉贴合与参考文本匹配不能合并成同一指标。'},
{name:'COCO Caption · CIDEr',protocol:'同一COCO Caption实验；不同于CLIP score的文本匹配指标',source:'表11',higher:true,scale:150,names:['BLIP2','Plus-7B','LLaVA-7B'],values:[123.5,31,0],finding:'BLIP2 为123.5，Plus为31.0。即使 CLIP score 改善，CIDEr 也没有领先，不应隐藏这个取舍。'},
{name:'COCO 负提示 · 误检实例数',protocol:'COCO val前100图；全部不存在类别作为负提示；使用对应负例训练',source:'表12',higher:false,scale:100,names:['Grounding DINO','Plus-7B'],values:[90,20],finding:'实例计数90降至20；含误检图像数41降至12。此处越低越好，不能把计数写成误检百分比。'}
];
export function Chapter10Widget(){const [index,setIndex]=useState(0);const {p,start,reset}=useProgress();const m=metrics[index];return <><Scene label="所选评测指标的比较条形图，精确数值见下表" draw={c=>{clearScene(c);label(c,m.higher?'越高越好':'越低越好',25,28);line(c,120,46,1000,46,C.axis,2);m.values.forEach((v,i)=>{const y=66+i*38;label(c,String(i+1),40,y+22,C.blue,21);box(c,120,y,800,25,'#fff');const best=m.higher?v===Math.max(...m.values):v===Math.min(...m.values);box(c,120,y,800*v/m.scale*p,25,best?C.green:C.blue);label(c,String(v),942,y+22,C.ink,20);});}}/><Controls><label htmlFor="metric">评测指标</label><select id="metric" value={index} onChange={e=>{setIndex(Number(e.target.value));reset();}} style={{font:'inherit',maxWidth:'100%',padding:10,border:`1px solid ${C.axis}`,borderRadius:6}}>{metrics.map((x,i)=><option value={i} key={x.name}>{x.name}</option>)}</select><Button onClick={start}>{p>0?'重新比较':'开始比较'}</Button></Controls><Feedback tone={p===1?'green':'blue'}>{p===0?'等待比较。'+m.protocol+'；'+m.source+'。':m.finding}</Feedback><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:'1rem'}}><caption style={{textAlign:'left',padding:'12px 0'}}>{m.source} · {m.protocol} · {m.higher?'越高越好':'越低越好'}</caption><thead><tr><th style={{textAlign:'left',padding:8}}>模型 / 配置</th><th style={{textAlign:'right',padding:8}}>论文数值</th></tr></thead><tbody>{m.names.map((n,i)=><tr key={n}><td style={{borderTop:`1px solid ${C.axis}`,padding:8}}>{i+1}. {n}</td><td style={{borderTop:`1px solid ${C.axis}`,textAlign:'right',padding:8}}>{m.display?.[i]??String(m.values[i])}</td></tr>)}</tbody></table></div></>;}
