import React, {useEffect,useRef,useState} from 'react';
import {setupCanvas,observeCanvas} from '../lib/canvasKit';
export const C={bg:'#f5f8f0',light:'#b8c9a7',dark:'#76906a',brown:'#92400e',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#f07e47',purple:'#7c3aed',ink:'#21324a',axis:'#d7deea'};
export function line(c:CanvasRenderingContext2D,x:number,y:number,X:number,Y:number,color:string=C.axis,width=3){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(x,y);c.lineTo(X,Y);c.stroke();}
export function box(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string,stroke?:string){c.fillStyle=color;c.beginPath();c.roundRect(x,y,w,h,8);c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=3;c.stroke();}}
export function label(c:CanvasRenderingContext2D,s:string,x:number,y:number,color:string=C.ink,size=24){c.fillStyle=color;c.font=`${size}px "Microsoft YaHei", sans-serif`;c.fillText(s,x,y);}
export function circle(c:CanvasRenderingContext2D,x:number,y:number,r:number,color:string){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();}
export function clearScene(c:CanvasRenderingContext2D,w=1080,h=280){c.clearRect(0,0,w,h);c.fillStyle=C.bg;c.fillRect(0,0,w,h);}
export function vasePath(c:CanvasRenderingContext2D,x:number,y:number,s:number){c.beginPath();c.moveTo(x+44*s,y+20*s);c.lineTo(x+76*s,y+20*s);c.bezierCurveTo(x+67*s,y+65*s,x+99*s,y+76*s,x+89*s,y+112*s);c.quadraticCurveTo(x+60*s,y+133*s,x+31*s,y+112*s);c.bezierCurveTo(x+21*s,y+76*s,x+53*s,y+65*s,x+44*s,y+20*s);c.closePath();}
export function photo(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,selected=false){box(c,x,y,w,h,'#fff',C.axis);c.fillStyle=C.light;c.fillRect(x+10,y+h*.72,w-20,h*.2);line(c,x+10,y+h*.72,x+w-10,y+h*.72,C.dark,2);const s=Math.min(w/180,h/155);vasePath(c,x+w/2-60*s,y+h*.1,s);c.fillStyle=selected?'#d5eddf':C.dark;c.fill();if(selected){c.lineWidth=4;c.strokeStyle=C.green;c.stroke();}c.fillStyle='#fff8';c.fillRect(x+w*.49,y+h*.34,5,h*.2);}
export function pen(c:CanvasRenderingContext2D,x:number,y:number,color:string=C.blue,angle=-.6){c.save();c.translate(x,y);c.rotate(angle);box(c,-5,-51,10,44,color);c.fillStyle=C.brown;c.beginPath();c.moveTo(-5,-7);c.lineTo(0,3);c.lineTo(5,-7);c.fill();c.restore();}
export function lens(c:CanvasRenderingContext2D,x:number,y:number,r=30){line(c,x+r*.72,y+r*.72,x+r*1.45,y+r*1.45,C.brown,10);c.fillStyle='#ffffff66';c.strokeStyle=C.blue;c.lineWidth=6;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();c.stroke();}
export function frame(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string=C.green,dashed=false){c.save();c.setLineDash(dashed?[8,6]:[]);c.strokeStyle=color;c.lineWidth=4;c.strokeRect(x,y,w,h);c.restore();}
export function arrow(c:CanvasRenderingContext2D,x:number,y:number,X:number,Y:number,color:string=C.axis){line(c,x,y,X,Y,color,3);const a=Math.atan2(Y-y,X-x);line(c,X,Y,X-12*Math.cos(a-.45),Y-12*Math.sin(a-.45),color);line(c,X,Y,X-12*Math.cos(a+.45),Y-12*Math.sin(a+.45),color);}
type CanvasProps={draw:(c:CanvasRenderingContext2D,t:number)=>void;width?:number;height?:number;label?:string;animate?:boolean;onPoint?:(x:number,y:number)=>void;drag?:boolean};
export function Scene({draw,width=1080,height=280,label:alt='交互示意图',animate=false,onPoint,drag=false}:CanvasProps){const ref=useRef<HTMLCanvasElement>(null),drawRef=useRef(draw),held=useRef(false);drawRef.current=draw;
 useEffect(()=>{const cv=ref.current;if(!cv)return;const c=setupCanvas(cv,width,height);cv.style.width='100%';cv.style.height='auto';cv.style.maxWidth='100%';cv.style.display='block';let raf=0,visible=true,paused=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const render=(t:number)=>{drawRef.current(c,reduced?1000:t);cv.classList.add('is-ready');};const tick=(t:number)=>{render(t);raf=animate&&visible&&!paused&&!reduced?requestAnimationFrame(tick):0;};const stop=()=>{visible=false;cancelAnimationFrame(raf);raf=0;};const start=()=>{visible=true;if(!raf)raf=requestAnimationFrame(tick);};const enter=()=>{paused=true;cancelAnimationFrame(raf);raf=0;};const leave=()=>{paused=false;start();};render(performance.now());const disconnect=observeCanvas(cv,start,stop);if(animate){cv.addEventListener('mouseenter',enter);cv.addEventListener('mouseleave',leave);}return()=>{stop();disconnect();cv.removeEventListener('mouseenter',enter);cv.removeEventListener('mouseleave',leave);};},[width,height,animate]);
 useEffect(()=>{const cv=ref.current;if(!cv)return;const c=cv.getContext('2d');if(c)draw(c,performance.now());},[draw]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!onPoint)return;const b=e.currentTarget.getBoundingClientRect();onPoint(Math.max(0,Math.min(width,(e.clientX-b.left)*width/b.width)),Math.max(0,Math.min(height,(e.clientY-b.top)*height/b.height)));};
 return <canvas role="img" aria-label={alt} ref={ref} style={{touchAction:drag?'none':'auto',cursor:onPoint?(drag?'grab':'pointer'):'default'}} onPointerDown={e=>{held.current=true;if(drag)e.currentTarget.setPointerCapture(e.pointerId);point(e);}} onPointerMove={e=>{if(drag&&held.current)point(e);}} onPointerUp={()=>held.current=false} onPointerCancel={()=>held.current=false}/>;
}
export function Controls({children}:{children:React.ReactNode}){return <div className="ctrl" style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center'}}>{children}</div>;}
export function Button({children,onClick,disabled=false,active=false}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean;active?:boolean}){return <button type="button" className={`chip${active?' active':''}`} aria-pressed={active} disabled={disabled} onClick={onClick} style={{padding:'10px 17px',border:`1px solid ${active?C.blue:C.axis}`,borderRadius:7,background:active?C.blue:'#fff',color:active?'#fff':C.ink,font:'inherit',cursor:disabled?'not-allowed':'pointer',opacity:disabled?.45:1}}>{children}</button>;}
export function Feedback({children,tone='blue'}:{children:React.ReactNode;tone?:'blue'|'red'|'green'}){return <div className={`feedback ${tone==='green'?'good':tone==='red'?'bad':''}`} aria-live="polite" style={{minHeight:62}}>{children}</div>;}
export function Detail({children}:{children:React.ReactNode}){return <div style={{minHeight:48,padding:'8px 0',color:C.ink,fontSize:'1rem',overflowWrap:'anywhere'}}>{children}</div>;}
export function useProgress(){const [p,setP]=useState(0);const [run,setRun]=useState(0);useEffect(()=>{if(!run)return;let raf=0;const t0=performance.now();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const tick=(t:number)=>{const v=reduced?1:Math.min(1,(t-t0)/1600);setP(v);if(v<1)raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[run]);return {p,start:()=>{setP(0);setRun(x=>x+1);},reset:()=>{setRun(0);setP(0);}};}
export function Analogy({chapter=1,old=false}:{chapter?:number;old?:boolean}){return <Scene width={560} height={140} animate label="照片编辑的生活类比动画" draw={(c,t)=>{clearScene(c,560,140);const u=(Math.sin(t/1500*Math.PI)+1)/2;photo(c,210,12,150,116,chapter===1&&!old);const x=252+u*55,y=43+u*50;
 if(chapter===1){if(old){for(let i=0;i<3;i++)line(c,382,52+i*14,465-i*10,52+i*14,C.axis,5);pen(c,399+u*15,95,C.red);}else{frame(c,247,30,73,83,C.green);pen(c,x,y,C.green);}}
 if(chapter===2)lens(c,x,68,27);
 if(chapter===3){frame(c,225,30,34,55,C.red,true);box(c,230+u*30,28,29,20,C.orange);c.fillStyle=C.bg;c.fillRect(225,30,30*u,58);}
 if(chapter===4){box(c,215,15,140,111,'#fff',C.axis);for(let i=0;i<3;i++)line(c,237,40+i*28,330,40+i*28,C.light,5);line(c,237,68,237+90*u,68,C.blue,5);pen(c,237+90*u,68);}
 if(chapter===5){box(c,190,104,205,15,C.light);pen(c,265,90-u*42,C.blue,0);}
 if(chapter===6){c.save();c.translate(212,15);c.scale(.25+.75*u,1);box(c,0,0,145,108,'#d7deea99',C.blue);c.restore();}
 if(chapter===7){c.strokeStyle=C.axis;c.lineWidth=9;c.beginPath();c.arc(284,73,36,.3,Math.PI*1.8);c.stroke();c.strokeStyle=C.green;c.beginPath();c.arc(284,73,36,.3,.3+u*4.8);c.stroke();pen(c,284+36*Math.cos(.3+u*4.8),73+36*Math.sin(.3+u*4.8),C.green);}
 if(chapter===8){box(c,220,48,85,57,C.dark);box(c,235,35,28,15,C.dark);circle(c,308+35*(1-u),76,29,C.blue);circle(c,308+35*(1-u),76,19,C.light);}
 if(chapter===9){box(c,225+u*20,25,72,94,'#27446e66',C.blue);}
 if(chapter===10){box(c,204,106-u*25,167,15,C.brown);for(let i=0;i<12;i++)line(c,211+i*13,107-u*25,211+i*13,113-u*25,'#fff',1);}
 }}/>;}

export function SharedKit(){return null;}
