import React from 'react';
import { Yolo26Ana } from './yolo26-ana';
import { Yolo26M1 } from './yolo26-m1';
import { Yolo26M2 } from './yolo26-m2';
import { MambaAna } from './mamba-ana';
import { Ch2M4 } from './ch2-m4';
import { Ch2M5 } from './ch2-m5';
import { Ch3Ana } from './ch3-ana';
import { Ch3M2 } from './ch3-m2';
import { Ch5M1 } from './ch5-m1';
import { Ch6Ana } from './ch6-ana';
import { Ch7Ana } from './ch7-ana';
import { Ch8Ana } from './ch8-ana';
import { Ch8M1 } from './ch8-m1';
import { Ch8M2 } from './ch8-m2';
import { Ch9Ana } from './ch9-ana';
import { Ch9M1 } from './ch9-m1';
import { Ch10Ana } from './ch10-ana';
import { Ch10M1 } from './ch10-m1';
import { BivimM1 } from './bivim-m1';
import { HeroContrast } from './hero-contrast';
import { RwAna } from './rw-ana';
import { RwM1 } from './rw-m1';
import { RwM2 } from './rw-m2';
import { PaperSummary } from './paper-summary';
import { SsmForget } from './ssm-forget';
import { SsmHip } from './ssm-hip';
import { SsmHippoProj } from './ssm-hippo-proj';
import { Yolo26Bottleneck } from './yolo26-bottleneck';
import { Quiz } from './quiz';
import { PipelineVideo } from './pipeline-video';
import { FourProcsVideo } from './four-procs-video';
import { Limitations } from './limitations';
import { SsmScanDemo } from './ssm-scan-demo';
import { SsmWorkedVideo } from './ssm-worked-video';
import { SsmConvVideo } from './ssm-conv-video';
import { WebInfer } from './web-infer';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['yolo26-ana'] = Yolo26Ana;
widgetRegistry['yolo26-m1'] = Yolo26M1;
widgetRegistry['yolo26-m2'] = Yolo26M2;
widgetRegistry['mamba-ana'] = MambaAna;
widgetRegistry['ch2-m4'] = Ch2M4;
widgetRegistry['ch2-m5'] = Ch2M5;
widgetRegistry['ch3-ana'] = Ch3Ana;
widgetRegistry['ch3-m2'] = Ch3M2;
widgetRegistry['ch5-m1'] = Ch5M1;
widgetRegistry['ch6-ana'] = Ch6Ana;
widgetRegistry['ch7-ana'] = Ch7Ana;
widgetRegistry['ch8-ana'] = Ch8Ana;
widgetRegistry['ch8-m1'] = Ch8M1;
widgetRegistry['ch8-m2'] = Ch8M2;
widgetRegistry['ch9-ana'] = Ch9Ana;
widgetRegistry['ch9-m1'] = Ch9M1;
widgetRegistry['ch10-ana'] = Ch10Ana;
widgetRegistry['ch10-m1'] = Ch10M1;
widgetRegistry['bivim-m1'] = BivimM1;
widgetRegistry['hero-contrast'] = HeroContrast;
widgetRegistry['rw-ana'] = RwAna;
widgetRegistry['rw-m1'] = RwM1;
widgetRegistry['rw-m2'] = RwM2;
widgetRegistry['paper-summary'] = PaperSummary;
widgetRegistry['ssm-forget'] = SsmForget;
widgetRegistry['ssm-hip'] = SsmHip;
widgetRegistry['ssm-hippo-proj'] = SsmHippoProj;
widgetRegistry['yolo26-bottleneck'] = Yolo26Bottleneck;
widgetRegistry['quiz'] = Quiz;
widgetRegistry['pipeline-video'] = PipelineVideo;
widgetRegistry['four-procs-video'] = FourProcsVideo;
widgetRegistry['limitations'] = Limitations;
widgetRegistry['ssm-scan-demo'] = SsmScanDemo;
widgetRegistry['ssm-worked-video'] = SsmWorkedVideo;
widgetRegistry['ssm-conv-video'] = SsmConvVideo;
widgetRegistry['web-infer'] = WebInfer;
