import React,{useState} from 'react';
import type {WidgetProps} from './registry';

const comparison=[
 ['VTM-17.0 (LD)','0.0%','0.01','23.6'],['VTM-17.0 (Hierarchical-B)','−33.8%','0.01','23.1'],['DCVC-RT','−21.0%','118.8','105.3'],['DCVC-UF (LD)','−9.5%','313.6','353.8'],['DCVC-UF (HT-S)','−31.6%','655.9','453.3'],['DCVC-UF (HT-L)','−42.2%','371.1','273.6'],
];
const complexity=[
 ['DCVC-RT','−21.0%','385G','20.7M','118.8 / 105.3'],['DCVC-UF (LD)','−9.5%','170G','9.7M','313.6 / 353.8'],['DCVC-UF (HT-S)','−31.6%','211G','81.2M','655.9 / 453.3'],['DCVC-UF (HT-L)','−42.2%','343G','120.5M','371.1 / 273.6'],
];
const ablation=[
 ['A','DCVC-RT → Anchor','−21.0%','105.3'],['B','A + Chunk coding（无帧专属解码器）','−10.1%','349.1'],['C','A + Chunk coding（有帧专属解码器）','−25.3%','343.2'],['D','C + Streamlined entropy model','−23.4%','453.3'],['E','D + 128 帧训练 → DCVC-UF (HT-S)','−31.6%','453.3'],
];

export const PaperExperiments:React.FC<WidgetProps>=()=>{const [tab,setTab]=useState<'compare'|'result'|'ablate'>('compare');return <div><div className="experiment-tabs"><button type="button" className={tab==='compare'?'active':''} onClick={()=>setTab('compare')}><span>方向 1</span><b>对比实验</b><small>Table 1 + Figure 5</small></button><button type="button" className={tab==='result'?'active':''} onClick={()=>setTab('result')}><span>方向 2</span><b>实验结果与复杂度</b><small>Figure 1 + Table 3</small></button><button type="button" className={tab==='ablate'?'active':''} onClick={()=>setTab('ablate')}><span>方向 3</span><b>消融实验</b><small>Table 2</small></button></div>{tab==='compare'?<Compare/>:tab==='result'?<Results/>:<Ablation/>}</div>};

const Compare=()=> <div><div className="metric-explain"><strong>本方向回答什么？</strong><p>在相同测试协议下，DCVC-UF 与传统编码器及已有 NVC 相比，压缩效率是否更好。</p><div className="metric-defs"><p><b>BPP（bits per pixel）：</b>平均每个像素占用的比特数，代表码率；越低表示码流越小。</p><p><b>PSNR（dB）：</b>重建图像与原图的客观质量，越高越好；同一 PSNR 下 BPP 更低者更优。</p><p><b>率失真曲线：</b>横轴 BPP、纵轴 PSNR，曲线越靠左上，表示用更少比特获得更高质量。</p><p><b>BD-Rate（%）：</b>一段质量范围内相对锚点的平均码率变化；负数表示节省码率，越低越好。</p><p><b>Average BD-Rate：</b>Table 1 对 UVG、MCL-JCV、HEVC B、C、D、E 六个测试集结果取平均。</p><p><b>Encoding / Decoding FPS：</b>每秒编码/解码帧数，越高越快；Table 1 使用 4090、1080p 并包含实际码流操作。</p><p><b>UVG / MCL-JCV / HEVC B–E：</b>论文使用的视频测试集或类别，不是指标；用于覆盖不同内容与分辨率。</p><p><b>YUV420 / All frames：</b>测试色彩格式为 YUV420，视频全部帧参与评价，不是只抽关键帧。</p><p><b>LD / Hierarchical-B：</b>LD 是低延迟编码；Hierarchical-B 允许双向参考并引入更长等待。</p></div></div><figure className="paper-result-figure"><img src="/images/figure-5.png" alt="论文 Figure 5：UVG 数据集率失真曲线"/><figcaption>论文 Figure 5 原图：UVG 全质量、低质量和高质量区间的率失真曲线。</figcaption></figure><table className="results-table source-table"><caption>原文 Table 1 摘录：YUV420，所有帧测试；速度为 4090、1080p</caption><thead><tr><th>方法</th><th>平均 BD-Rate ↓</th><th>编码 FPS ↑</th><th>解码 FPS ↑</th></tr></thead><tbody>{comparison.map(r=><tr key={r[0]}>{r.map((v,i)=>i===0?<th key={v}>{v}</th>:<td key={i}>{v}</td>)}</tr>)}</tbody></table><div className="feedback good"><strong>原文结论：</strong>HT-L 平均节省 42.2% 码率，为表中最佳；HT-S 节省 31.6%。Figure 5 显示，在 UVG 较低质量区间 HT-S、HT-L 优于此前方法，但较高质量区间 VTM Hierarchical-B 更好。</div></div>;

const Results=()=> <div><div className="metric-explain"><strong>本方向回答什么？</strong><p>模型在真实码流读写下究竟有多快、计算量和模型规模多大，以及能否随 GPU 升级继续扩展。</p><div className="metric-defs"><p><b>Encoding / Decoding FPS：</b>每秒编码/解码帧数，越高越快；斜线前后依次是编码和解码速度。</p><p><b>Average BD-Rate：</b>六个测试集相对 VTM-17.0（LD）的平均码率变化，越低越好。</p><p><b>MACs / frame：</b>每帧乘加运算次数；G 表示十亿次，反映理论计算量，越低通常越轻。</p><p><b>Params：</b>可学习参数数量；M 表示百万，影响模型存储与容量，但不直接等同于实际速度。</p><p><b>1080p / 720p / 4K：</b>被测视频分辨率；分辨率越高，一帧包含的像素越多，速度通常越低。</p><p><b>2080Ti / 4090 / A100 / H100 / B200：</b>不同代际和定位的 GPU，用于检验吞吐能否随通用硬件升级扩展。</p><p><b>Actual bit-stream：</b>速度包含真实算术编码、码流写入与读取，不是只统计神经网络前向时间。</p><p><b>OOM：</b>Out of Memory，表示该模型在对应设备与分辨率下显存不足，无法完成测试。</p><p><b>模型规模与速度：</b>MACs、Params 是复杂度指标，FPS 是实测系统吞吐，三者不能互相替代。</p></div></div><figure className="paper-result-figure figure-one"><img src="/images/figure-1.png" alt="论文 Figure 1：不同 GPU 上的实际编解码速度和 BD-Rate"/><figcaption>论文 Figure 1 原图：1080p 实际码流编解码速度及不同 GPU 的扩展性。</figcaption></figure><table className="results-table source-table"><caption>原文 Table 3 摘录：平均 BD-Rate、1080p MACs、参数量及 4090 速度</caption><thead><tr><th>模型</th><th>平均 BD-Rate ↓</th><th>MACs/帧</th><th>Params</th><th>4090 编码/解码 FPS ↑</th></tr></thead><tbody>{complexity.map(r=><tr key={r[0]}>{r.map((v,i)=>i===0?<th key={v}>{v}</th>:<td key={i}>{v}</td>)}</tr>)}</tbody></table><div className="feedback good"><strong>原文结论：</strong>4090 上 HT-S 达到 655.9/453.3 FPS；B200 上进一步达到 1415.1/945.8 FPS。作者据此认为该方法能够利用通用 GPU 代际升级扩展吞吐，而无需针对每代硬件重新设计专用编码器。</div></div>;

const Ablation=()=> <div><div className="metric-explain"><strong>本方向回答什么？</strong><p>从 DCVC-RT 基线逐项加入设计，在相同协议下观察 BD-Rate 和解码 FPS 的变化，以识别每个模块的增量贡献。</p><div className="metric-defs"><p><b>ID（A–E）：</b>消融配置编号；从 A 到 E 逐项叠加设计，便于比较相邻两行的增量。</p><p><b>Settings：</b>当前实验包含的组件组合；“+”表示在上一设置上加入模块。</p><p><b>Anchor：</b>比较基线。表中 BD-Rate 统一以 VTM-17.0（LD）为锚点，不是以 A 行作为零点。</p><p><b>BD-Rate（%）：</b>相同画质范围内相对锚点的平均码率变化；负数表示节省，越低越好。</p><p><b>Decoding FPS：</b>4090 上每秒解码帧数，越高越快；该表只报告解码速度。</p><p><b>w/ 与 w/o：</b>分别表示 with（使用）和 without（不使用）某组件。</p><p><b>相邻行差值：</b>A→B、B→C 等用于判断新加入设计的贡献；不能只比较单个绝对值。</p><p><b>−10.1% 并非负效果：</b>仍比 VTM-LD 省码率，但相对 A 的 −21.0% 明显退化。</p><p><b>测试条件：</b>BD-Rate 锚点为 VTM-17.0（LD），解码 FPS 在 RTX 4090 上测试。</p></div></div><table className="results-table source-table"><caption>原文 Table 2：VTM-17.0（LD）为 BD-Rate 锚点；4090 测试解码 FPS</caption><thead><tr><th>ID</th><th>设置</th><th>BD-Rate ↓</th><th>解码 FPS ↑</th></tr></thead><tbody>{ablation.map(r=><tr key={r[0]}>{r.map((v,i)=>i===0?<th key={v}>{v}</th>:<td key={i}>{v}</td>)}</tr>)}</tbody></table><div className="ablation-conclusions"><p><b>A → B：</b>块编码把解码从 105.3 提高到 349.1 FPS，但通用解码器使 BD-Rate 退化到 −10.1%。</p><p><b>B → C：</b>帧专属解码器将 BD-Rate 修复到 −25.3%，速度仍为 343.2 FPS。</p><p><b>C → D：</b>精简熵模型把解码提高到 453.3 FPS，BD-Rate 轻微变化为 −23.4%。</p><p><b>D → E：</b>128 帧训练不改变解码速度，将 BD-Rate 改善到 −31.6%。</p></div></div>;
