import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AnaCalibrate } from './ana-calibrate';
import { AnaChecklist } from './ana-checklist';
import { AnaDrift } from './ana-drift';
import { AnaLogbook } from './ana-logbook';
import { AnaOverview } from './ana-overview';
import { AnaRadio } from './ana-radio';
import { AnaSegments } from './ana-segments';
import { AnaSummit } from './ana-summit';
import { AnaToolbelt } from './ana-toolbelt';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { ModArchitecture } from './mod-architecture';
import { ModChunkDrift } from './mod-chunk-drift';
import { ModChunking } from './mod-chunking';
import { ModCostCompare } from './mod-cost-compare';
import { ModDriftDemo } from './mod-drift-demo';
import { ModDriftMetric } from './mod-drift-metric';
import { ModGcmIntegrate } from './mod-gcm-integrate';
import { ModGcmPlacement } from './mod-gcm-placement';
import { ModLossFormula } from './mod-loss-formula';
import { ModImprove } from './mod-improve';
import { ModLimitations } from './mod-limitations';
import { ModRace } from './mod-race';
import { ModResultsTable } from './mod-results-table';
import { ModScaleWall } from './mod-scale-wall';
import { ModTrainSetup } from './mod-train-setup';
import { ModVideo } from './mod-video';
import { ModTttLoop } from './mod-ttt-loop';
import { ModWhyLinear } from './mod-why-linear';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-calibrate'] = AnaCalibrate;
widgetRegistry['ana-checklist'] = AnaChecklist;
widgetRegistry['ana-drift'] = AnaDrift;
widgetRegistry['ana-logbook'] = AnaLogbook;
widgetRegistry['ana-overview'] = AnaOverview;
widgetRegistry['ana-radio'] = AnaRadio;
widgetRegistry['ana-segments'] = AnaSegments;
widgetRegistry['ana-summit'] = AnaSummit;
widgetRegistry['ana-toolbelt'] = AnaToolbelt;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['mod-architecture'] = ModArchitecture;
widgetRegistry['mod-chunk-drift'] = ModChunkDrift;
widgetRegistry['mod-chunking'] = ModChunking;
widgetRegistry['mod-cost-compare'] = ModCostCompare;
widgetRegistry['mod-drift-demo'] = ModDriftDemo;
widgetRegistry['mod-drift-metric'] = ModDriftMetric;
widgetRegistry['mod-gcm-integrate'] = ModGcmIntegrate;
widgetRegistry['mod-gcm-placement'] = ModGcmPlacement;
widgetRegistry['mod-loss-formula'] = ModLossFormula;
widgetRegistry['mod-improve'] = ModImprove;
widgetRegistry['mod-limitations'] = ModLimitations;
widgetRegistry['mod-race'] = ModRace;
widgetRegistry['mod-results-table'] = ModResultsTable;
widgetRegistry['mod-scale-wall'] = ModScaleWall;
widgetRegistry['mod-train-setup'] = ModTrainSetup;
widgetRegistry['mod-ttt-loop'] = ModTttLoop;
widgetRegistry['mod-video'] = ModVideo;
widgetRegistry['mod-why-linear'] = ModWhyLinear;
