import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { M1_1 } from './m1-1';
import { M1_2 } from './m1-2';
import { M10_1 } from './m10-1';
import { M10_2 } from './m10-2';
import { M2_1 } from './m2-1';
import { M3_1 } from './m3-1';
import { M3_2 } from './m3-2';
import { M4_1 } from './m4-1';
import { M4_2 } from './m4-2';
import { M5_1 } from './m5-1';
import { M5_2 } from './m5-2';
import { M6_1 } from './m6-1';
import { M6_2 } from './m6-2';
import { M7_1 } from './m7-1';
import { M7_2 } from './m7-2';
import { M8_1 } from './m8-1';
import { M8_2 } from './m8-2';
import { M9_1 } from './m9-1';
import { M9_2 } from './m9-2';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['m1-1'] = M1_1;
widgetRegistry['m1-2'] = M1_2;
widgetRegistry['m10-1'] = M10_1;
widgetRegistry['m10-2'] = M10_2;
widgetRegistry['m2-1'] = M2_1;
widgetRegistry['m3-1'] = M3_1;
widgetRegistry['m3-2'] = M3_2;
widgetRegistry['m4-1'] = M4_1;
widgetRegistry['m4-2'] = M4_2;
widgetRegistry['m5-1'] = M5_1;
widgetRegistry['m5-2'] = M5_2;
widgetRegistry['m6-1'] = M6_1;
widgetRegistry['m6-2'] = M6_2;
widgetRegistry['m7-1'] = M7_1;
widgetRegistry['m7-2'] = M7_2;
widgetRegistry['m8-1'] = M8_1;
widgetRegistry['m8-2'] = M8_2;
widgetRegistry['m9-1'] = M9_1;
widgetRegistry['m9-2'] = M9_2;
