import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ch1Analogy } from './ch1-analogy';
import { Ch1Order } from './ch1-order';
import { Ch10Analogy } from './ch10-analogy';
import { Ch10Evidence } from './ch10-evidence';
import { Ch10Gallery } from './ch10-gallery';
import { Ch2Analogy } from './ch2-analogy';
import { Ch2Experts } from './ch2-experts';
import { Ch3Analogy } from './ch3-analogy';
import { Ch3Wheel } from './ch3-wheel';
import { Ch3Multimodal } from './ch3-multimodal';
import { Ch4Analogy } from './ch4-analogy';
import { Ch4Loss } from './ch4-loss';
import { Ch5Analogy } from './ch5-analogy';
import { Ch5Sample } from './ch5-sample';
import { Ch6Analogy } from './ch6-analogy';
import { Ch6Async } from './ch6-async';
import { Ch7Analogy } from './ch7-analogy';
import { Ch7Library } from './ch7-library';
import { Ch7Kilns } from './ch7-kilns';
import { Ch8Analogy } from './ch8-analogy';
import { Ch8Arch } from './ch8-arch';
import { Ch8Cache } from './ch8-cache';
import { Ch9Analogy } from './ch9-analogy';
import { Ch9Arena } from './ch9-arena';
import { Ch9Master } from './ch9-master';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ch1-analogy'] = Ch1Analogy;
widgetRegistry['ch1-order'] = Ch1Order;
widgetRegistry['ch10-analogy'] = Ch10Analogy;
widgetRegistry['ch10-evidence'] = Ch10Evidence;
widgetRegistry['ch10-gallery'] = Ch10Gallery;
widgetRegistry['ch2-analogy'] = Ch2Analogy;
widgetRegistry['ch2-experts'] = Ch2Experts;
widgetRegistry['ch3-analogy'] = Ch3Analogy;
widgetRegistry['ch3-wheel'] = Ch3Wheel;
widgetRegistry['ch3-multimodal'] = Ch3Multimodal;
widgetRegistry['ch4-analogy'] = Ch4Analogy;
widgetRegistry['ch4-loss'] = Ch4Loss;
widgetRegistry['ch5-analogy'] = Ch5Analogy;
widgetRegistry['ch5-sample'] = Ch5Sample;
widgetRegistry['ch6-analogy'] = Ch6Analogy;
widgetRegistry['ch6-async'] = Ch6Async;
widgetRegistry['ch7-analogy'] = Ch7Analogy;
widgetRegistry['ch7-library'] = Ch7Library;
widgetRegistry['ch7-kilns'] = Ch7Kilns;
widgetRegistry['ch8-analogy'] = Ch8Analogy;
widgetRegistry['ch8-arch'] = Ch8Arch;
widgetRegistry['ch8-cache'] = Ch8Cache;
widgetRegistry['ch9-analogy'] = Ch9Analogy;
widgetRegistry['ch9-arena'] = Ch9Arena;
widgetRegistry['ch9-master'] = Ch9Master;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
