import React,{useState} from 'react';
import {Canvas,Feedback,Stats,C,rect,label,Table} from './notebook-scene';
export function redistribute(lengths:number[],correct:boolean[],lambda=.2){const ids=lengths.map((_,i)=>i).filter(i=>correct[i]);const rewards=correct.map(Number);if(!ids.length)return rewards;const scores=ids.map(i=>1/lengths[i]);const mean=scores.reduce((a,b)=>a+b,0)/ids.length;const spread=Math.max(...scores.map(v=>Math.abs(v-mean)));if(spread<1e-14)return rewards;ids.forEach((i,j)=>rewards[i]+=lambda*(scores[j]-mean)/spread);return rewards;}
export function LongShort(){const [lengths,setLengths]=useState([2000,4000,8000]),[correct,setCorrect]=useState([true,true,false]);const rewards=redistribute(lengths,correct);const total=rewards.reduce((a,b)=>a+b,0),original=correct.filter(Boolean).length;return <>
 <Canvas label="三条轨迹长度与再分配奖励" draw={c=>{label(c,'回答长度',75,30);label(c,'调整后奖励',535,30);for(let i=0;i<3;i++){const y=60+i*58;label(c,String(i+1),25,y+21);rect(c,75,y,380,30,'#e2e7df');rect(c,75,y,lengths[i]/12000*380,30,correct[i]?C.blue:C.red);rect(c,535,y,230,30,'#e2e7df');rect(c,535,y,rewards[i]/1.2*230,30,correct[i]?C.green:C.red);label(c,rewards[i].toFixed(3),770,y+22,18);}}}/>
 {lengths.map((v,i)=><div className="ctrl" key={i} style={{gap:12,flexWrap:'wrap'}}><label htmlFor={`length-${i}`}>轨迹{i+1} <strong>{v} tokens</strong></label><input id={`length-${i}`} type="range" onKeyDown={e=>e.stopPropagation()} min="1000" max="12000" step="1000" value={v} onChange={e=>setLengths(lengths.map((l,j)=>j===i?Number(e.target.value):l))} style={{minWidth:110,height:28,minHeight:28,maxHeight:28,flex:'1 1 180px'}}/><button className={`chip ${correct[i]?'selected':''}`} aria-pressed={correct[i]} onClick={()=>setCorrect(correct.map((v,j)=>i===j?!v:v))}>{correct[i]?'正确 ✓':'错误 ×'}</button></div>)}
 <div className="ctrl" style={{gap:8,flexWrap:'wrap'}}><button className="chip" onClick={()=>setLengths([4000,4000,4000])}>等长</button><button className="chip" onClick={()=>setCorrect([false,false,false])}>全错</button><button className="chip" onClick={()=>{setLengths([2000,4000,8000]);setCorrect([true,true,false]);}}>重置</button></div>
 <Stats items={[["原总奖励",String(original)],["新总奖励",total.toFixed(3)],["均值变化",((total-original)/3).toFixed(3)],["λ",'0.2']]}/>
 <Feedback tone={original?'good':'bad'}>{!original?'全组错误：没有正确集合，保持全部奖励为0。':original===1?'只有一条正确：它与正确集合均值相同，分母为0，不调整奖励。':new Set(lengths.filter((_,i)=>correct[i])).size===1?'正确轨迹等长：没有长短偏好，奖励保持不变。':'较短的正确轨迹增加奖励，较长的正确轨迹减少奖励；错误轨迹不参与比较。'} 总改变量为0，守恒的是奖励均值，不是数学上保证准确率不变。</Feedback>
 <Table headers={['轨迹','原奖励','新奖励','改变量']} rows={rewards.map((r,i)=>[String(i+1),Number(correct[i]),r.toFixed(3),(r-Number(correct[i])).toFixed(3)])}/>
 </>;}
