import {useEffect,useRef,useState} from 'react';
import {setupCanvas,observeCanvas} from '../lib/canvasKit';
import {sceneColors as C} from './SharedKit';
import {shoppingRecall as copy} from '../data/tutorial';
export function Analogy1(){
 const ref=useRef<HTMLCanvasElement>(null),[phase,setPhase]=useState(0);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=setupCanvas(canvas,560,140);let raf=0,elapsed=0,last=0,visible=false,hover=false;const media=matchMedia('(prefers-reduced-motion: reduce)');
 const draw=()=>{const t=media.matches?5000:elapsed%7000;setPhase(t<1800?0:t<3400?1:2);const x=130+Math.min(t/3400,1)*95;ctx.clearRect(0,0,560,140);ctx.fillStyle=C.bg;ctx.fillRect(0,0,560,140);ctx.strokeStyle=C.passive;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(25,121);ctx.lineTo(535,121);ctx.stroke();for(let i=0;i<2;i++){ctx.strokeRect(390,30+i*37,125,32);for(let j=0;j<5;j++){ctx.fillStyle=j%2?C.passive:'#e2d5be';ctx.fillRect(400+j*22,38+i*37,13,19);}}
 ctx.save();ctx.translate(x,0);ctx.strokeStyle=C.contour;ctx.lineWidth=3;ctx.fillStyle='#ead8bd';ctx.beginPath();ctx.arc(0,35,12,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=C.blue;ctx.lineWidth=10;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-2,53);ctx.lineTo(-6,84);ctx.stroke();ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-1,58);ctx.lineTo(20,72);ctx.lineTo(36,67);ctx.moveTo(-6,84);ctx.lineTo(-17,115);ctx.moveTo(-5,84);ctx.lineTo(9,115);ctx.stroke();ctx.strokeStyle=C.contour;ctx.lineWidth=3;ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(32,64);ctx.lineTo(40,66);ctx.lineTo(47,99);ctx.lineTo(98,99);ctx.lineTo(106,74);ctx.lineTo(42,74);ctx.moveTo(48,85);ctx.lineTo(101,85);ctx.moveTo(58,76);ctx.lineTo(61,97);ctx.moveTo(80,76);ctx.lineTo(81,97);ctx.stroke();[53,94].forEach(cx=>{ctx.beginPath();ctx.arc(cx,112,6,0,Math.PI*2);ctx.stroke();});ctx.restore();canvas.classList.add('is-ready');};
 const stop=()=>{cancelAnimationFrame(raf);last=0;};const tick=(now:number)=>{if(last)elapsed+=Math.min(now-last,80);last=now;draw();if(visible&&!hover&&!media.matches)raf=requestAnimationFrame(tick);};const start=()=>{stop();draw();if(visible&&!hover&&!media.matches)raf=requestAnimationFrame(tick);};const disconnect=observeCanvas(canvas,()=>{visible=true;start();},()=>{visible=false;stop();});const enter=()=>{hover=true;stop();},leave=()=>{hover=false;start();};canvas.addEventListener('mouseenter',enter);canvas.addEventListener('mouseleave',leave);media.addEventListener('change',start);draw();return()=>{stop();disconnect();canvas.removeEventListener('mouseenter',enter);canvas.removeEventListener('mouseleave',leave);media.removeEventListener('change',start);};},[]);
 return <div className="shopping-recall"><canvas ref={ref} width={560} height={140} role="img" aria-label="一位购物者推着购物车，完整清单仍在，回想时漏了香蕉" style={{width:'100%',height:'auto',display:'block'}}/><div style={{padding:'12px 16px'}}><p style={{margin:'0 0 8px'}}><b>完整清单：</b>{copy.items.map(x=><span key={x} style={{display:'inline-block',marginRight:14,textDecoration:x==='香蕉'&&phase===2?'underline':undefined}}>{x}</span>)}</p><div style={{minHeight:90}}><p style={{margin:'6px 0'}}>{phase===0?copy.intro:copy.recall}</p>{phase===2&&<p style={{margin:'6px 0',color:C.support}}>{copy.question}</p>}</div></div></div>;
}
