import {c123DataFacts,c123DataAdditions,c123DataScenes1,c123Copy} from "../data/tutorial";
import {useEffect,useRef,useState} from 'react';
import {sceneColors} from './SharedKit';

type RecordItem={role:string;text:string;fact?:'AC'|'CB';};
export const c1Facts=c123DataFacts;
const additions=c123DataAdditions;
export function c1Snapshot(index:number){const step=Math.max(0,Math.min(7,Math.trunc(index)));return {step,history:additions.slice(0,step+1).flat(),adopted:step>=7?['AC','CB']:step>=5?['CB']:[],found:step>=3?['AC','CB']:step>=2?['AC']:[]};}
export const c1Scenes=c123DataScenes1;
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
export function C1(){
 const [step,setStep]=useState(0),[progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[started,setStarted]=useState(false),[run,setRun]=useState(0);
 const historyRef=useRef<HTMLDivElement>(null),factRef=useRef<HTMLDivElement>(null),secondFactRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!playing)return;const media=window.matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const finish=()=>{cancelAnimationFrame(frame);setProgress(1);setPlaying(false);};if(media.matches){finish();return;}const began=performance.now();const tick=(now:number)=>{const p=clamp((now-began)/3600);setProgress(p);if(p<1)frame=requestAnimationFrame(tick);else setPlaying(false);};frame=requestAnimationFrame(tick);const changed=()=>{if(media.matches)finish();};media.addEventListener('change',changed);return()=>{cancelAnimationFrame(frame);media.removeEventListener('change',changed);};},[run,playing]);
 const settled=progress>=.78, snap=c1Snapshot(step),previous=step?c1Snapshot(step-1).history:[];
 const history=settled?snap.history:previous;const activeHistory=step===6||step===7;const scene=c1Scenes[step];
 useEffect(()=>{const el=historyRef.current;if(!el)return;const target=activeHistory?factRef.current:step===5?secondFactRef.current:null;if(target)el.scrollTop=target.offsetTop-el.offsetTop-70;else el.scrollTop=el.scrollHeight;},[step,settled]);
 const play=(next:number)=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;setStep(next);setProgress(reduced?1:0);setStarted(true);setPlaying(!reduced);setRun(x=>x+1);};
 const query=step===1?c123Copy.text0:step===3?'人物甲 项目B':step===4?c123Copy.text1:'';
 const typed=query.slice(0,Math.ceil(query.length*clamp(progress/.32)));
 const showPage=step===2||((step===3||step===4)&&progress>.48);
 const fact=step===2?c1Facts.AC:step===3?c1Facts.CB:c1Facts.background;
 const pageTitle=step===2?'公司A的人员资料':step===3?'项目B的介绍资料':c123Copy.text2;
 const reveal=clamp((progress-(step===2?.18:.50))/.25);
 const restored=step===7&&progress>=.78;const adopted=step===5&&progress<.73?[]:step>=5?(restored?['AC','CB']:['CB']):[];
 const transfer=clamp((progress-.18)/.55);
 const finalDraft=step===5&&progress<.73?c123Copy.text3:restored?c123Copy.text4:c123Copy.text5;
 const showCursor=playing&&step>=1&&step<=4;
 return <div className="c1-film" onKeyDown={e=>{if(e.key.startsWith('Arrow'))e.stopPropagation();}}><style>{`
.c1-film{color:#21324a;line-height:1.65;--c1-blue:${sceneColors.blue};--c1-orange:${sceneColors.orange};--c1-green:${sceneColors.green}}
.c1-film *{box-sizing:border-box}.c1-film button{font:inherit;font-size:16px;min-height:44px;padding:9px 13px;border:1px solid #b8c9a7;background:white;border-radius:8px;color:inherit;cursor:pointer}.c1-film button:disabled{opacity:.45;cursor:default}.c1-film button:focus-visible{outline:3px solid #f07e47;outline-offset:3px}
.c1-film .film-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:14px 0}.c1-film .film-next{background:#27446e;color:white;border-color:#27446e;flex:1;min-width:170px}.c1-film .film-position{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:8px;font-size:16px}.c1-film .film-progress{display:flex;gap:5px;margin-bottom:16px}.c1-film .film-progress i{height:4px;flex:1;background:#dde5ed;overflow:hidden}.c1-film .film-progress b{display:block;height:100%;background:#27446e}
.c1-film .computer{border:2px solid #76906a;border-radius:14px;overflow:hidden;background:#f5f8f0;position:relative}.c1-film .computer-top{background:#e9efe3;border-bottom:1px solid #b8c9a7;padding:10px 14px;display:flex;gap:6px;align-items:center;font-size:16px}.c1-film .computer-top i{display:block;width:8px;height:8px;border-radius:50%;background:#b8c9a7}.c1-film .computer-top span{margin-left:8px}.c1-film .task-strip{padding:12px 16px;border-bottom:1px solid #d7deea;font-size:16px}.c1-film .desktop{position:relative;display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.65fr);min-height:440px}.c1-film .history-pane{min-width:0;border-right:1px solid #d7deea;background:#f5f8f0;padding:12px}.c1-film .history-title{font-size:16px;display:flex;justify-content:space-between;gap:6px;margin-bottom:8px}.c1-film .history-scroll{height:350px;overflow:auto;position:relative;scrollbar-width:thin}.c1-film .history-entry{padding:8px 9px;border-left:2px solid #b8c9a7;margin:8px 0;background:#fffef9;font-size:16px;overflow-wrap:anywhere}.c1-film .history-entry b{display:block;font-size:16px;color:#627087}.c1-film .history-entry.fact-ac{border-left:4px solid #27446e}.c1-film .history-entry.fact-cb{border-left:4px solid #7c3aed}.c1-film .history-entry.located{outline:2px solid #f07e47;outline-offset:-2px;background:#fff3e8}.c1-film .new-record{animation:c1-record .45s ease-out both}@keyframes c1-record{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}
.c1-film .workspace{position:relative;min-width:0;padding:16px;background:white}.c1-film .window-label{font-size:16px;color:#627087;border-bottom:1px solid #d7deea;padding-bottom:10px;margin-bottom:18px}.c1-film .message{background:#eef3f8;padding:16px;border-radius:10px;margin:18px 0}.c1-film .message p{margin:8px 0}.c1-film .searchbox{border:2px solid #27446e;border-radius:22px;padding:11px 15px;font-size:18px;min-height:53px;overflow-wrap:anywhere}.c1-film .searchbox .caret{border-right:2px solid #27446e;padding-right:3px}.c1-film .search-result{border-bottom:1px solid #d7deea;padding:17px 0;font-size:16px}.c1-film .search-result b{display:block;color:#27446e;font-size:20px}.c1-film .page-title{font-size:23px;color:#27446e;margin:12px 0}.c1-film .article-line{height:7px;border-radius:3px;background:#e5e9ed;margin:14px 0;max-width:85%}.c1-film .source-sentence{position:relative;padding:12px;border-left:4px solid #27446e;font-size:22px;background:#f2f5f9;margin:24px 0;overflow-wrap:anywhere}.c1-film .source-sentence.cb{border-color:#7c3aed}.c1-film .source-sentence mark{color:inherit;background:linear-gradient(90deg,#ffdfaa var(--reveal),transparent var(--reveal));}.c1-film .source-note{font-size:16px;color:#627087}.c1-film .cursor{position:absolute;pointer-events:none;width:24px;height:30px;z-index:3;filter:drop-shadow(1px 1px 1px #fff)}
.c1-film .transfer{position:absolute;z-index:5;pointer-events:none;background:#fff4d9;border:2px solid #27446e;border-radius:7px;padding:10px 14px;font-size:20px;box-shadow:0 4px 12px #27446e20;transform:translateX(-50%);white-space:nowrap}.c1-film .mobile-evidence{display:none}.c1-film .draft{padding:15px;border:1px solid #d7deea;border-top:3px solid #27446e;border-radius:6px}.c1-film .draft p{margin:10px 0}.c1-film .missing{border:2px dashed #c43f52;padding:12px;color:#a22d3e;margin:15px 0;background:#fff6f6}.c1-film .relation{display:flex;align-items:center;margin:22px 0;font-size:24px}.c1-film .relation b{border:2px solid #27446e;border-radius:8px;min-width:58px;padding:5px;font-size:16px;min-height:43px;flex-shrink:0;display:grid;place-items:center;background:white}.c1-film .relation span{flex:1;border-top:3px solid #7c3aed;position:relative;margin:0 4px;min-width:10px}.c1-film .relation span.gap{border-top:3px dashed #c43f52}.c1-film .relation span.fixed{border-color:#27446e}.c1-film .relation small{position:absolute;bottom:3px;font-size:16px;white-space:nowrap;left:50%;transform:translateX(-50%)}
.c1-film .me-line{display:flex;gap:12px;padding:14px;background:#edf3fb;border-top:1px solid #d7deea;font-size:18px}.c1-film .me-line b{flex-shrink:0;color:#27446e}.c1-film .explanation{margin:16px 0;border-left:4px solid #f07e47;padding:12px 16px;background:#fff7ee}.c1-film .explanation b{font-size:16px;color:#92400e}.c1-film .explanation p{margin:7px 0}.c1-film .history-rule{font-size:16px;color:#627087;margin:12px 0}.c1-film details{font-size:16px;margin-top:16px}.c1-film summary{cursor:pointer}.c1-film .adopted{border-left:3px solid #228d5c;padding-left:10px;font-size:16px;margin:12px 0}.c1-film .revisit{font-size:16px;color:#27446e;border-bottom:2px solid #27446e;padding:8px 0;margin-bottom:12px}
@media(max-width:680px){.c1-film .desktop{grid-template-columns:1fr}.c1-film .transfer{display:none}.c1-film .mobile-evidence{display:block;border-left:4px solid #27446e;background:#eef3f8;padding:10px;font-size:16px;margin-bottom:12px}.c1-film .workspace{grid-row:1;min-height:345px;padding:12px}.c1-film .history-pane{border-right:0;border-top:1px solid #d7deea}.c1-film .history-scroll{height:180px}.c1-film .history-title{font-size:16px}.c1-film .task-strip{padding:10px 12px}.c1-film .film-next{flex-basis:100%;order:-1}.c1-film .relation small{font-size:16px}.c1-film .film-position{align-items:start}.c1-film .me-line{padding:12px;font-size:16px}.c1-film .page-title{font-size:21px}.c1-film .source-sentence{font-size:20px}.c1-film .computer-top{padding:8px}.c1-film .missing{font-size:18px}}
@media(prefers-reduced-motion:reduce){.c1-film .new-record{animation:none}}
`}</style>
 <div className="film-position"><strong>{step+1} / 8 · {scene.title}</strong><span>{playing?'正在播放':started?'本段已停住':'点击开始'}</span></div>
 <div className="film-progress" aria-hidden="true">{c1Scenes.map((_,i)=><i key={i}><b style={{width:i<step?'100%':i===step?progress*100+'%':'0%'}}/></i>)}</div>
 <div className="film-controls"><button className="film-next" disabled={playing||(started&&step===7)} onClick={()=>play(started?step+1:0)}>{!started?'开始演示':step===7?'演示完成':`下一步：${c1Scenes[step+1].title}`}</button><button disabled={step===0} onClick={()=>{setPlaying(false);setStep(step-1);setProgress(1);setStarted(true);}}>上一步</button><button disabled={!started} onClick={()=>play(step)}>重播本段</button>{playing&&<button onClick={()=>{setProgress(1);setPlaying(false);}}>跳到本段结尾</button>}</div>
 <div className="computer"><div className="computer-top"><i/><i/><i/><span>{c123Copy.text6}</span></div><div className="task-strip"><b>用户任务</b>{c123Copy.text7}</div><div className="desktop">
 <section className="history-pane"><div className="history-title"><strong>搜索与阅读记录</strong><span>{history.length} 条记录</span></div><div className="history-scroll" ref={historyRef}>{history.length===0?<p className="source-note">{c123Copy.text8}</p>:history.map((item,i)=><div key={`${step}-${i}`} ref={item.fact==='AC'?factRef:item.fact==='CB'?secondFactRef:undefined} className={`history-entry ${item.fact==='AC'?'fact-ac':item.fact==='CB'?'fact-cb':''} ${activeHistory&&item.fact==='AC'?'located':''} ${settled&&i>=previous.length?'new-record':''}`}><b>{String(i+1).padStart(2,'0')} · {item.role}</b>{item.text}{activeHistory&&item.fact==='AC'&&<b>{restored?'已补进回答':'原句仍在这里'}</b>}</div>)}</div><p className="history-rule">{c123Copy.text9}</p></section>
 <section className="workspace"><div className="window-label">{step===0?'用户消息':step>=5?c123Copy.text10:showPage?c123Copy.text11:c123Copy.text12}</div>
 {step===0&&<><div className="message"><strong>用户</strong><p>{c123Copy.text13}</p></div><div className="message" style={{opacity:started?clamp(progress*3):.65}}><strong>我</strong><p>{c123Copy.text14}</p></div></>}
 {step>=1&&step<=4&&<>{!showPage?<><div className="searchbox"><span className={playing?'caret':''}>{typed||'准备输入查询…'}</span></div>{progress>.35&&<div style={{opacity:clamp((progress-.35)*5)}}><div className="search-result"><b>{step===1?'公司A的人员资料':step===3?'项目B的介绍资料':c123Copy.text15}</b>{c123Copy.text16}</div>{step===1&&<div className="search-result"><b>项目B的介绍资料</b>{c123Copy.text17}</div>}</div>}</>:<><div className="page-title">{pageTitle}</div><div className="article-line"/><div className="article-line" style={{width:'58%'}}/><div className={'source-sentence '+(step===3?'cb':'')}><mark style={{'--reveal':reveal*100+'%'} as React.CSSProperties}>{fact}</mark></div><div className="article-line" style={{width:'71%'}}/><p className="source-note">{c123Copy.text18}</p>{settled&&<p className="adopted">{c123Copy.text19}</p>}</>}</>}
 {step>=5&&<>{step>=6&&<div className="mobile-evidence"><b>之前查到的这句话</b><br/>{snap.history.find(item=>item.fact==='AC')?.text}<br/>{restored?'这句已补进回答':c123Copy.text20}</div>}{step===7&&<div className="revisit">{progress<.78?c123Copy.text21:c123Copy.text22}</div>}<div className="draft"><strong>{c123Copy.text23}</strong><div className="adopted">{adopted.includes('AC')&&<div>{c1Facts.AC}</div>}{adopted.includes('CB')&&<div>{c1Facts.CB}</div>}</div><div className="source-note">由此写下的回答</div><p>{finalDraft}</p>{!restored&&<div className="missing">{c123Copy.text24}<br/>{c123Copy.text25}</div>}</div>{step>=6&&<><div className="relation" aria-label={restored?c123Copy.text26:c123Copy.text27}><b>公司A</b><span className={restored?'fixed':'gap'}><small>{restored?'任职':'漏写'}</small></span><b>人物甲</b><span><small>负责</small></span><b>项目B</b></div><p className="source-note">{restored?c123Copy.text28:c123Copy.text29}</p></>}{restored&&<p className="source-note">{c123Copy.text30}</p>}</>}
 {showCursor&&<svg className="cursor" style={{left:(progress<.4?20+progress*80:68-(progress-.4)*42)+'%',top:(progress<.4?80:100+(progress-.4)*200)+'px'}} viewBox="0 0 24 30" aria-hidden="true"><path d="M2 1L21 17L12 18L8 27Z" fill="#27446e" stroke="white" strokeWidth="2"/></svg>}
 </section>{playing&&(step===5||step===7)&&transfer>0&&transfer<1&&<div className="transfer" aria-hidden="true" style={{left:(19+51*transfer)+'%',top:(160+40*Math.sin(transfer*Math.PI))+'px',opacity:Math.min(1,transfer*8,(1-transfer)*8)}}>{step===5?c1Facts.CB:c1Facts.AC}</div>}</div><div className="me-line"><b>我</b><span>{scene.voice}</span></div></div>
 <div className="explanation" aria-live="polite"><b>这一段说明什么</b><p>{scene.explain}</p></div>
 <details><summary>{c123Copy.text31}</summary><p>{c123Copy.text32}</p><p>{c123Copy.text33}</p><a href="https://arxiv.org/html/2606.02373v1#S1.p2" target="_blank" rel="noreferrer">{c123Copy.text34}</a></details>
 </div>;
}
