import {c123Copy} from "../data/tutorial";
import {displayDoc} from './display';
import {useState,useRef,useLayoutEffect} from 'react';
export type C2Route=null|'search'|'review';
export function c2Derive(route:C2Route){return {route,source:route==='search'?'外部教学语料库':route==='review'?'已保存原文':'尚未读取',action:route==='search'?c123Copy.text35:route==='review'?'review_docs(doc_ids=["dA"])':'先选择搜索或回看',result:route==='search'?c123Copy.text36:route==='review'?c123Copy.text37:'暂无工具返回',P:route==='search'?['dA','dB']:['dA'],D:route==='search'?['dA','dB']:['dA'],C:['dA'],I:{dA:'fair'},next:route==='search'?c123Copy.text38:route==='review'?c123Copy.text39:c123Copy.text40};}
export function C2(){const [route,setRoute]=useState<C2Route>(null);const [focus,setFocus]=useState('input');const mapRef=useRef<HTMLDivElement>(null);const [paths,setPaths]=useState<{d:string;active:boolean}[]>([]);useLayoutEffect(()=>{const root=mapRef.current;if(!root)return;const update=()=>{const base=root.getBoundingClientRect();const box=(id:string)=>root.querySelector<HTMLElement>('#c2-'+id)!.getBoundingClientRect();const edges=[['input','model'],['model','search'],['model','review'],['search','state'],['review','state'],['state','next']];setPaths(edges.map(([from,to])=>{const a=box(from),b=box(to),vertical=from==='input'||from==='state';const x1=(vertical?a.left+a.width/2:a.right)-base.left,y1=(vertical?a.bottom:a.top+a.height/2)-base.top,x2=(vertical?b.left+b.width/2:b.left)-base.left,y2=(vertical?b.top:b.top+b.height/2)-base.top;const d=vertical?`M${x1} ${y1} L${x2} ${y2}`:`M${x1} ${y1} C${x1+24} ${y1} ${x2-24} ${y2} ${x2} ${y2}`;return {d,active:!!route&&((from===route||to===route)||vertical)};}));};update();const observer=new ResizeObserver(update);observer.observe(root);return()=>observer.disconnect();},[route]);const state=c2Derive(route);const choose=(id:string)=>{setFocus(id);if(id==='search'||id==='review')setRoute(id);};const label:{[key:string]:string}={input:'本轮输入',model:'模型动作',search:'搜索新资料',review:'回看文档1',state:'更新记录',next:'下轮输入'};
const button=(id:string,sub:string)=><button id={'c2-'+id} className={'c2-node '+((id==='search'&&!route||id==='review'&&route==='search')?'primary-action ':'')+(focus===id?'focused ':'')+((id===route||route&&['model','state','next'].includes(id))?'active':'')} aria-pressed={focus===id} onClick={()=>choose(id)}><strong>{label[id]}</strong><span>{displayDoc(sub)}</span>{(id==='search'||id==='review')&&<b>{c123Copy.text41}</b>}</button>;
return <div className="c2-scene" onKeyDown={e=>{if(e.key.startsWith('Arrow'))e.stopPropagation()}}><style>{`.c2-scene{color:var(--ink,#21324a)}.c2-scene button{font:inherit;color:inherit;cursor:pointer}.c2-scene button:focus-visible{outline:3px solid #f07e47;outline-offset:3px}.c2-head{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap;margin:18px 0}.c2-head button{padding:8px 14px;border:1px solid #b8c9a7;background:white;border-radius:8px}.c2-map{position:relative;display:grid;grid-template-columns:minmax(0,1fr) 34px minmax(0,1.25fr) 34px minmax(0,1fr);gap:10px;min-height:320px;background:#f5f8f0;padding:20px;border:1px solid #d7deea;border-radius:12px;align-items:center}.c2-stack{display:grid;gap:18px;min-width:0}.c2-node{position:relative;z-index:1;border:2px solid #b8c9a7;border-radius:10px;background:#fff;padding:15px;text-align:left;min-height:85px;display:flex;flex-direction:column;gap:6px;width:100%;overflow-wrap:anywhere}.c2-node span{color:#68778f}.c2-node b{font-weight:500;color:#92400e}.c2-node.active{border-color:#228d5c;background:#eff8f2}.c2-node.focused{box-shadow:0 0 0 3px #27446e}.c2-branch{display:grid;gap:6px}.c2-store{padding:8px;border-bottom:2px solid #b8c9a7;color:#68778f}.c2-branch.active .c2-store{border-color:#228d5c;color:#228d5c}.c2-flow-lines{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;overflow:visible}.c2-arrows{display:grid;gap:115px;text-align:center;color:#b8c9a7;font-size:28px}.c2-arrows .active{color:#228d5c;font-weight:bold}.c2-details{margin:20px 0;border-top:3px solid #27446e;background:#fff;padding:18px}.c2-details dl{margin:0}.c2-details dl>div{display:grid;grid-template-columns:130px 1fr;gap:14px;padding:12px 0;border-bottom:1px solid #d7deea}.c2-details dt{font-weight:bold}.c2-details dd{margin:0;white-space:pre-line;overflow-wrap:anywhere}.c2-action{overflow-wrap:anywhere;display:block;margin:10px 0;background:#f5f8f0;padding:12px}.c2-feedback{padding:16px;border-left:3px solid #27446e;background:#edf3fb;line-height:1.8}.c2-index{margin-top:18px;line-height:1.8}.c2-index summary{cursor:pointer}@media(max-width:680px){.c2-map{grid-template-columns:1fr;padding:12px}.c2-flow-lines{display:none}.c2-stack{grid-template-columns:1fr 1fr;gap:10px}.c2-arrows{display:none}.c2-node{padding:12px}.c2-map>.c2-stack:nth-child(3){align-items:start}.c2-details dl>div{grid-template-columns:1fr;gap:5px}}@media(max-width:380px){.c2-stack{grid-template-columns:1fr}.c2-details{padding:12px}}`}</style>

<p><strong>{c123Copy.text42}</strong></p>
<div className="c2-head"><strong>{c123Copy.text43}</strong><button id="c2-reset" onClick={()=>{setRoute(null);setFocus('input')}}>重置示例</button></div>
<div className="c2-map" ref={mapRef} aria-label={c123Copy.text44}><svg className="c2-flow-lines" aria-hidden="true"><defs><marker id="c2-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="#76906a"/></marker></defs>{paths.map((p,i)=><path key={i} d={p.d} fill="none" stroke={p.active?'#228d5c':'#b8c9a7'} strokeWidth={p.active?2.5:1.5} markerEnd="url(#c2-arrow)"/>)}</svg><div className="c2-stack">{button('input',c123Copy.text45)}{button('model',route?'已选择：'+(route==='search'?'搜索新来源':'取回旧全文'):c123Copy.text46)}</div><div className="c2-arrows" aria-hidden="true"/><div className="c2-stack"><div className={'c2-branch '+(route==='search'?'active':'')}><div className="c2-store">{c123Copy.text47}</div>{button('search','读取新文档 dB')}</div><div className={'c2-branch '+(route==='review'?'active':'')}><div className="c2-store">{c123Copy.text48}</div>{button('review',c123Copy.text49)}</div></div><div className="c2-arrows" aria-hidden="true"/><div className="c2-stack">{button('state',route==='search'?c123Copy.text50:route==='review'?c123Copy.text51:c123Copy.text52)}{button('next',route?c123Copy.text53:'等待一次动作')}</div></div>
<div className="c2-details"><strong>正在检查：{label[focus]}</strong><details><summary>查看工具调用</summary><code className="c2-action">{state.action}</code></details><dl><div><dt>读取来源</dt><dd>{state.source}</dd></div><div><dt>工具返回</dt><dd>{state.result}</dd></div><div><dt>记录变化</dt><dd>候选文档：{'{'+state.P.map(displayDoc).join('、')+'}'}<br/>保存原文：{'{'+state.D.map(displayDoc).join('、')+'}'}<br/>{c123Copy.text54}{route==='search'?c123Copy.text55:'没有新增成员。'}</dd></div><div><dt>下一轮输入</dt><dd>{displayDoc(state.next)}</dd></div></dl></div>
<p className="c2-feedback" role="status" data-tone={route?"success":"info"}><b>{route?"✓ 已读取：":"○ 待选择："}</b>{route==='search'?c123Copy.text56:route==='review'?c123Copy.text57:c123Copy.text58}</p>
<details className="c2-index"><summary>{c123Copy.text59}</summary><p>{c123Copy.text60}</p><p>{c123Copy.text61}</p><a href="https://arxiv.org/html/2606.02373v1#S1.F2" target="_blank" rel="noreferrer">{c123Copy.text62}</a> · <a href="https://arxiv.org/html/2606.02373v1#S2.T1" target="_blank" rel="noreferrer">表1：状态职责</a> · <a href="https://arxiv.org/html/2606.02373v1#alg4" target="_blank" rel="noreferrer">算法4：回看全文</a></details></div>;}
