import {c4Data} from '../data/tutorial';
import {useEffect,useRef,useState} from 'react';
import './c4.css';
import {C56Formula} from './c56-formula';
export const c4Levels=['very_high','high','fair','low'] as const;
export type C4Level=typeof c4Levels[number];
const names=c4Data.names;
export const c4Docs=c4Data.docs;
export function c4Initial(capacity=false):Record<string,C4Level>{return Object.fromEntries(c4Docs.slice(0,capacity?30:8).map((d,i)=>[d.id,capacity?(i===29?'low':'high'):'fair']));}
export function c4Curate(current:Record<string,C4Level>,id:string,level:C4Level){const next={...current}; let removed:string|undefined;let message='只修改标签，精选成员未变';if(id in next)next[id]=level;else if(Object.keys(next).length<30){next[id]=level;message='加入精选，原文仍保存';}else{const worst=Object.keys(next).sort((a,b)=>c4Levels.indexOf(next[b])-c4Levels.indexOf(next[a]))[0];if(c4Levels.indexOf(level)<c4Levels.indexOf(next[worst])){removed=worst;delete next[worst];next[id]=level;message=`${id}替换${worst}，两篇原文都仍保存`;}else message='已选满30篇，新文档与最低等级相同或更低，不能加入';}return {next,removed,message};}
type Motion='idle'|'stamp'|'commit'|'remove';
export function C4(){
const [capacity,setCapacity]=useState(false),[C,setC]=useState<Record<string,C4Level>>(()=>c4Initial()),[selected,setSelected]=useState('d01'),[labels,setLabels]=useState<Record<string,C4Level>>({d01:'very_high',d02:'high',d03:'fair',d09:'low',d31:'fair'}),[marked,setMarked]=useState<string[]>([]),[targets,setTargets]=useState<string[]>([]),[motion,setMotion]=useState<Motion>('idle'),[elapsed,setElapsed]=useState(0),[paused,setPaused]=useState(false),[all,setAll]=useState(false),[review,setReview]=useState<string|null>(null),[ejected,setEjected]=useState<string|null>(null),[feedback,setFeedback]=useState('首次成功搜索已自动初选8篇。先查看文件，再为本次动作生成标签；精选尚未编辑。'),[reduced,setReduced]=useState(false);
const [lastStamped,setLastStamped]=useState<Record<string,C4Level>>({});
const [ejectedLevel,setEjectedLevel]=useState<C4Level|null>(null);
const rootRef=useRef<HTMLDivElement>(null);
const [onScreen,setOnScreen]=useState(true),[pageVisible,setPageVisible]=useState(true);
useEffect(()=>{const node=rootRef.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>setOnScreen(entry.isIntersecting));observer.observe(node);const visibility=()=>setPageVisible(!document.hidden);visibility();document.addEventListener('visibilitychange',visibility);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',visibility);};},[]);
const staged=useRef<{next:Record<string,C4Level>;removed?:string;removedLevel?:C4Level;message:string;duration?:number}|null>(null);
const baseIds=capacity?['d28','d29','d30','d31']:['d01','d02','d03','d09'];
const ids=baseIds.includes(selected)?baseIds:[selected,...baseIds.slice(1)];
const busy=motion!=='idle',duration=motion==='stamp'?900+Math.max(0,targets.length-1)*200:motion==='remove'?240:staged.current?.duration??900;
useEffect(()=>{const m=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(m.matches);update();m.addEventListener('change',update);return()=>m.removeEventListener('change',update);},[]);
useEffect(()=>{if(!busy||paused||!onScreen||!pageVisible)return;let frame=0,last=performance.now();const tick=(now:number)=>{const delta=Math.min(40,now-last);last=now;setElapsed(t=>Math.min(duration,t+delta));frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[busy,paused,duration,motion,onScreen,pageVisible]);
useEffect(()=>{if(!busy||elapsed<duration)return;if(motion==='stamp'){setLastStamped(previous=>({...previous,...Object.fromEntries(targets.map(id=>[id,labels[id]??C[id]??'fair']))}));setMarked(targets);setFeedback(`${targets.length}份文档的示范标签已标记；精选尚未更新。请点击“更新精选”执行 curate。`);}else if(staged.current){setC(staged.current.next);setEjected(staged.current.removed??null);setEjectedLevel(staged.current.removedLevel??null);setFeedback(staged.current.message);setMarked([]);}setMotion('idle');setPaused(false);},[elapsed,duration,busy,motion,targets]);
function reset(cap=capacity){setCapacity(cap);setC(c4Initial(cap));setLastStamped({});setEjectedLevel(null);setAll(false);setLabels({d01:'very_high',d02:'high',d03:'fair',d09:'low',d31:'fair'});setSelected(cap?'d31':'d01');setMarked([]);setTargets([]);setMotion('idle');setElapsed(0);setPaused(false);setEjected(null);setReview(null);staged.current=null;setFeedback(cap?'30篇已精选，d30是唯一最低等级。给d31标一般可替换；改为低则同级不替换。':'首次成功搜索已自动初选8篇。四张文件固定在原位，标签与格式没有固定对应。');}
function stamp(single=false){const list=single?[selected]:capacity?['d31']:ids;setTargets(list);setLastStamped(previous=>Object.fromEntries(Object.entries(previous).filter(([id])=>!list.includes(id))));setMarked([]);setEjected(null);setElapsed(reduced?900+(list.length-1)*200:0);setMotion('stamp');setPaused(false);setFeedback('正在生成本次重要性标签。印章是待提交动作参数，当前 C / I 尚未改变。');}
function commit(){let next={...C};let removed:string|undefined;const messages:string[]=[];for(const id of marked){const r=c4Curate(next,id,labels[id]??C[id]??'fair');next=r.next;removed=r.removed??removed;messages.push(`${id}：${r.message}`);}const changed=JSON.stringify(next)!==JSON.stringify(C);const commitMs=!changed?400:marked.every(id=>id in C)?360:removed?800:900;staged.current={next,removed,removedLevel:removed?C[removed]:undefined,duration:commitMs,message:`按 ${marked.join(' → ')} 的输入顺序执行。${messages.join('；')}。C=${Object.keys(next).length}/30，所有原文仍在 D。`};setElapsed(reduced?commitMs:0);setMotion('commit');setFeedback(removed?`比较重要性：新候选高于最低档 ${removed}，满足替换条件。容量保持30/30。`:'正在校验已有ID与容量，并按输入顺序提交标签。');}
function remove(){const next={...C};delete next[selected];staged.current={next,removed:selected,removedLevel:C[selected],message:`${selected}已移出精选；原文仍保存在 D，可随时回看。`};setElapsed(reduced?240:0);setMotion('remove');}
const sorted=Object.keys(C).sort((a,b)=>c4Levels.indexOf(C[a])-c4Levels.indexOf(C[b])||a.localeCompare(b));
const focus=all?sorted:sorted.filter(id=>ids.includes(id)||id===ejected||id===staged.current?.removed||marked.includes(id));
const hidden=sorted.length-focus.length;
const activeRemoved=motion==='commit'||motion==='remove'?staged.current?.removed:null;
const finalizing=motion==='commit'&&elapsed>=(duration===360?160:420);
const visualC=finalizing&&staged.current?staged.current.next:C;
const visibleIds=Array.from(new Set([...focus,...(finalizing?marked.filter(id=>id in visualC):[])]));
const chosen=c4Docs.find(d=>d.id===selected)!;
return <div className="c4" onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.stopPropagation();}}>
<p className="c4-note">目标：保留实验A的主要结果与限制。文档、格式和模型判断均为教学示范；文件格式不决定重要性。</p>
<div ref={rootRef} className="c4-action-region"><div className="c4-controls"><label>选择示例 <select id="c4-checkpoint" value={capacity?'capacity':'first'} disabled={busy} onChange={e=>reset(e.target.value==='capacity')}><option value="first">自动初选后 · 8/30</option><option value="capacity">容量已满 · 30/30</option></select></label><button id="c4-reset" onClick={()=>reset()}>重置</button></div>
<div className="c4-workspace"><div className="c4-model"><svg viewBox="0 0 64 64" width="45" height="45" aria-hidden="true"><path d="M30 12c-9-8-20 1-18 10-10 4-9 17-1 20-3 10 8 17 18 9V12zm5 0c9-8 20 1 18 10 10 4 9 17 1 20 3 10-8 17-18 9V12zM16 23l8 5-5 10m29-15-8 5 5 10M21 46l8-5m14 5-8-5" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg><b>策略模型</b><span>生成本次标签</span></div>
<div className="c4-documents">{ids.map((id,i)=>{const targetIndex=targets.indexOf(id);const t=motion==='stamp'&&targetIndex>=0?elapsed-targetIndex*200:-1;const completed=Boolean(lastStamped[id]);const pressed=t>=360;const local=Math.max(0,Math.min(900,t));const y=local<160?-28:local<360?-28+28*(local-160)/200:local<450?0:local<650?-28*(local-450)/200:-28;const shownStamp=t>=0&&t<900;const level=pressed?(labels[id]??C[id]??'fair'):(lastStamped[id]??C[id]??'fair');return <button disabled={busy} key={id} className={`c4-document ${selected===id?'is-selected':''}`} onClick={()=>{setSelected(id);setReview(null);}} aria-pressed={selected===id} style={{transform:!reduced&&t>=360&&t<450?'translateY(3px)':'none'}}><span className="c4-format">{c4Data.formats[i]}</span><b>{id}</b><span className="c4-paper-lines" aria-hidden="true">━━━<br/>━━━━<br/>━━</span><span className="c4-doc-description">{id in C?'已在精选':'新候选'}</span>{(pressed||completed)&&<span className={`c4-wax level-${level}`} style={{transform:!reduced&&t>=360&&t<450?'scale(1.08,.88)':'none'}}>{names[c4Levels.indexOf(level)]}</span>}{shownStamp&&!reduced&&<span className="c4-stamp" style={{transform:`translateY(${y}px)`,opacity:local>650?(900-local)/250:1}} aria-hidden="true"><span/><i/></span>}</button>;})}</div></div>
<div className="c4-inspector"><div><b>{selected} · 文档内容</b><p>{chosen.text}</p><span>示范依据：与“实验A结果和限制”的直接关系越强，保留优先级越高；由模型输出标签，框架执行规则。</span></div><label>本次拟提交重要性<select disabled={busy} value={labels[selected]??C[selected]??'fair'} onChange={e=>{setLabels({...labels,[selected]:e.target.value as C4Level});setMarked([]);setFeedback('拟提交等级已更改。请重新压印，再独立更新精选；C / I 尚未改变。');}}>{c4Levels.map((level,i)=><option key={level} value={level}>{names[i]} · rank {i}</option>)}</select></label></div>
<div className="c4-controls"><button className="primary-action" disabled={busy} onClick={()=>stamp()}>① 开始标记{capacity?'新候选':'四份文件'}</button><button disabled={busy} onClick={()=>stamp(true)}>仅为 {selected} 重打章</button><button className="primary-action" disabled={busy||!marked.length} onClick={commit}>② 更新精选</button>{busy&&<><button onClick={()=>setPaused(!paused)}>{paused?'继续':'暂停'}</button><button onClick={()=>{setElapsed(duration);setPaused(false);}}>跳至本步结果</button></>}</div>
<div className="c4-timing" aria-label="动画进度">{motion==='stamp'?`压印 ${Math.min(elapsed/1000,duration/1000).toFixed(2)} / ${(duration/1000).toFixed(2)} 秒 · 起点间隔 0.20 秒`:marked.length?`待提交标签：${marked.join(' → ')} · C / I 尚未改变`:'压印与更新是两个独立动作'}{reduced?' · 已启用减少动态效果':''}</div>
<div className="c4-storage"><section className="c4-curated"><header><b>精选 C</b><span>{Object.keys(C).length}/30 {motion==='commit'&&activeRemoved?'· 替换中':''}</span></header><div className="c4-groups">{c4Levels.map((level,i)=><div className="c4-group" key={level}><h4>{names[i]} <small>rank {i}</small></h4>{visibleIds.filter(id=>visualC[id]===level||id===activeRemoved&&C[id]===level).map(id=><button className={`c4-mini ${id===activeRemoved?'leaving':''}`} key={id} style={id===activeRemoved&&!reduced?{opacity:motion==='remove'?1-elapsed/240:elapsed>780?.2:1,transform:elapsed<320?'none':elapsed<500?'translateY(-6px)':`translate(${Math.min(70,(elapsed-500)/280*70)}px,${-Math.sin(Math.min(1,(elapsed-500)/280)*Math.PI)*30}px) rotate(${Math.min(12,(elapsed-500)/280*12)}deg)`}:undefined} disabled={busy} onClick={()=>setSelected(id)}><b>{id}</b><span className={`c4-mini-seal level-${visualC[id]??C[id]}`}>{names[c4Levels.indexOf(visualC[id]??C[id])]}</span></button>)}</div>)}</div><footer>{hidden>0?`另有 ${hidden} 篇未展开；此视图只聚焦本轮相关文件。`:'当前成员已全部展示。'}<button disabled={busy} onClick={()=>setAll(!all)}>{all?'聚焦本轮':'展开全部成员'}</button></footer></section>
<aside className="c4-original"><b>仍保存原文 D</b><p>退出精选，不等于删除原文。</p>{ejected&&<button className="c4-landed" onClick={()=>setReview(ejected)}>{ejected} · 已移出 C{ejectedLevel&&<span className={`c4-mini-seal level-${ejectedLevel}`}>{names[c4Levels.indexOf(ejectedLevel)]}</span>}<br/><small>点击回看原文</small></button>}<button id="c4-review" onClick={()=>setReview(selected)}>回看 {selected}</button><span>{capacity?31:9} 篇原文持续保存</span></aside></div>
<div className="c4-controls"><button id="c4-remove" disabled={busy||!(selected in C)} onClick={remove}>将 {selected} 移出精选</button></div>
{review&&<div className="c4-readback"><b>从 D 取回 {review}</b><p>{c4Docs.find(d=>d.id===review)?.text}</p><button onClick={()=>setReview(null)}>关闭原文</button></div>}
<div className="c4-feedback" role="status">{feedback}</div></div>
<div className="c4-rule"><b>刚才的操作对应什么机制？</b><p>策略模型在 curate 动作中给出文档ID和重要性标签。框架才会更新重要性映射 I 与精选集合 C。已存在的ID只更新标签；新ID在未满时加入，达到30篇时必须严格高于当前最低档。</p><C56Formula text="rank(新文档) < max rank(当前精选)" symbols={{rank:'重要性等级：极高0、高1、一般2、低3；数值越小，保留优先级越高。',max:'取当前精选中最大的rank，也就是最低重要性。当前 '+(Object.keys(C).length?Math.max(...Object.values(C).map(l=>c4Levels.indexOf(l))):'精选为空，无最低成员')+'。'}}/><p>当前算例：{selected} 拟提交 rank={c4Levels.indexOf(labels[selected]??C[selected]??'fair')}；精选 {Object.keys(C).length}/30。{selected in C?'这是已有成员，将原位重标，不触发容量淘汰。':Object.keys(C).length<30?'尚未满额，可加入，无需比较淘汰。':`当前最低 rank=${Math.max(...Object.values(C).map(l=>c4Levels.indexOf(l)))}，只有拟提交 rank 严格更小时才替换。`}</p><p>数值越小越重要。同级不替换；移出 C 不删除原文存储 D。上式是附录K规则的教学重述，印章不是论文界面，也不是实际运行模型。</p><a href={c4Data.paper} target="_blank" rel="noreferrer">核对论文 Algorithm 3：curate</a> · <a href={c4Data.rules} target="_blank" rel="noreferrer">附录K：重要性与容量规则</a></div>
<section className="c4-evidence" aria-label="论文算法与附录依据"><header><span>论文依据 · 中文重述</span><h4>Algorithm 3：重要性感知的精选与容量管理</h4></header><p>下面按原文算法的条件整理，不是论文原图截取。输入为加入ID集合 A、移除ID集合 R、拟提交重要性 J，以及已有的 C、I、候选池 P；输出为更新后的 C、I 和容量状态提示。</p><ol><li><b>先处理ID与移除。</b> 统一文档ID，然后从 C 移除 R 中的文档，同时删除它们的 I 标签。</li><li><b>依次处理加入项。</b> 对 A 中每篇文档读取 J；缺失或无效的重要性采用 fair。已有成员原位重标，直接继续处理下一篇。</li><li><b>检查容量。</b> 未满 M 时加入文档并写入 I；满额时找到当前最差等级，只有新文档的 rank 更小才替换。</li><li><b>返回真实状态。</b> 无法替换的加入请求被拒绝，并在容量提示中列出；不是覆盖原文，也不是扩容。</li></ol><a href={c4Data.paper} target="_blank" rel="noreferrer">打开论文 Algorithm 3，核对完整原算法 ↗</a><h4>附录K补充了哪些实现细节？</h4><p>原文明确 rank 顺序为 very_high=0、high=1、fair=2、low=3；自动初选进入 fair，容量 M=30。满额拒绝时状态带有 [CAPACITY] 标记，最多列出5个被拒绝的ID。已精选文档的重新标记不触发淘汰，因此成功核验后可以提高其优先级。显示时按重要性分组，最高等级在前，ID旁保留标签。</p><p>本演示已经使用规范化的教学ID，未实现原文完整的分块ID处理；满额初始状态特设唯一最低档，避免把并列时的选择规则误讲成论文结论。横向文件盒和蜡印是教学重绘，四个可见候选不代表容量只有四篇。</p><a href={c4Data.rules} target="_blank" rel="noreferrer">打开附录K，核对等级、替换与显示规则 ↗</a></section>
</div>;
}
