import {useEffect,useState} from 'react';
import {useC56Clock} from './c56-clock';
import {C56Formula} from './c56-formula';
import {c5Data} from '../data/tutorial';
export const c5AuthorEdges:Record<string,string[]>={'Brussels':['22816_0','91442_3','62390_5'],'1878':['22816_0','11293_2'],'Grande Synagogue':['22816_0','91442_3']};
export const c5TeachingEdges:Record<string,string[]>={'建筑A':['T1','T2','T3'],'地点乙':['T1','T2'],'1924':['T1','T2'],'人物甲':['T1','T3'],'地点丙':['T3']};
export const c5Texts:Record<string,string[]>={T1:['建筑A位于地点乙。','它于1924年开放。','设计者是人物甲。'],T2:['地点乙的一份1924年名录提到了建筑A。','名录没有说明它何时开放，也没有说明设计者。'],T3:['人物甲后来在地点丙工作。','这份记录没有说明建筑A的开放年份。']};
export function c5Verify(doc:string,claim:'date'|'dateDesigner'){if(!(doc in c5Texts))return null;return {doc,claim,supported:doc==='T1',dateSpan:doc==='T1'?1:null,designerSpan:doc==='T1'&&claim==='dateDesigner'?2:null};}
export function c5Index(ids:string[]){const edges:Record<string,string[]>={};c5Data.docs.filter(d=>ids.includes(d.id)).forEach(d=>[...new Set(d.entities)].forEach(e=>{(edges[e]??=[]).push(d.id);}));return edges;}
export function C5(){const [ids,setIds]=useState(['D1','D2']),[pending,setPending]=useState(''),[author,setAuthor]=useState(false),[entity,setEntity]=useState(''),[doc,setDoc]=useState('D3'),[claim,setClaim]=useState(0),[result,setResult]=useState<{doc:string;claim:number;supported:boolean}|null>(null);const clock=useC56Clock(1200);useEffect(()=>{if(pending&&!clock.running&&clock.elapsed===1200){setIds(v=>v.includes(pending)?v:[...v,pending]);setPending('');}},[pending,clock.running,clock.elapsed]);const displayIds=pending&&clock.elapsed>=360?[...new Set([...ids,pending])]:ids,edges:Record<string,string[]>=author?c5AuthorEdges:c5Index(displayIds),entities=author?Object.keys(c5AuthorEdges):c5Data.entities,docs=author?['22816_0','91442_3','62390_5','11293_2']:c5Data.docs.map(d=>d.id),current=c5Data.docs.find(d=>d.id===doc),linked=entity?edges[entity]??[]:doc?[doc]:[],high=Object.keys(edges).filter(e=>edges[e].length>=2),docEntities=entities.filter(e=>(edges[e]??[]).includes(doc)),phase=clock.elapsed<120?0:clock.elapsed<360?1:clock.elapsed<600?2:clock.elapsed<960?3:4;function add(id:string){setPending(id);setDoc(id);setEntity('');setResult(null);clock.start();}function reset(){clock.finish();setIds(['D1','D2']);setPending('');setEntity('');setDoc('D3');setResult(null);}const ey=(i:number)=>12+i*76/Math.max(1,entities.length-1),dy=(i:number)=>12+i*76/Math.max(1,docs.length-1);
return <div className="c5-new" ref={clock.ref}><style>{`.c5-new{color:#21324a}.c5-new button,.c5-new select{font:inherit;padding:10px;border:1px solid #b9c8d4;border-radius:8px;color:inherit;background:#fff;cursor:pointer;max-width:100%}.c5-new button:disabled{opacity:.5;cursor:default}.c5-new button[aria-pressed=true]{background:#e3edf8;border-color:#27446e}.c5-new .controls{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.c5-new .scene{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.2fr);gap:16px}.c5-new .panel{padding:18px;border:1px solid #d5dee8;border-radius:12px;margin:14px 0;background:#f7f9fb;overflow-wrap:anywhere}.c5-new .graph{position:relative;height:430px;border:1px solid #d5dee8;border-radius:12px;background:#f5f8fb}.c5-new svg{position:absolute;inset:0;width:100%;height:100%}.c5-new .node{position:absolute;width:39%;padding:8px 3px;transform:translate(-50%,-50%);overflow-wrap:anywhere;line-height:1.3;transition:border-color 120ms,background 120ms}.c5-new .node.linked{border:3px solid #e28748}.c5-new .node.pending{border-style:dashed}.c5-new mark{background:#ffdfb2}.c5-new .formula{padding:12px;background:#eaf0f7;line-height:1.8}.c5-new .index{display:grid;grid-template-columns:1fr 1fr;gap:14px}.c5-new :focus-visible{outline:3px solid #e28748}.c5-new pre{white-space:pre-wrap;font:inherit;overflow-wrap:anywhere}@media(max-width:760px){.c5-new .scene,.c5-new .index{grid-template-columns:1fr}.c5-new .graph{height:480px}}@media(prefers-reduced-motion:reduce){.c5-new *{transition:none!important}}`}</style>
<div className="controls"><button aria-pressed={!author} onClick={()=>{setAuthor(false);reset();}}>合成文本建图</button><button aria-pressed={author} onClick={()=>{clock.finish();setPending('');setAuthor(true);setEntity('');setDoc('22816_0');setResult(null);}}>核对论文原始索引</button></div><p>{author?'这组编号与实体整体取自论文 §2.2 的文本索引展示。二部图根据对应关系重绘，原文不是节点图；原始文档全文未公开。':'初始 D1、D2 已加入。先加入 D3，观察从原句提取实体、更新双向索引、增加边，再检查桥接。节点位置始终固定。'}</p>
<div className="scene"><div className="panel"><h4>{author?'原文索引证据':'当前教学原文'} · {doc||'请选择文档'}</h4>{author?<><p>{doc} 提及：{docEntities.join('、')||'请选择文档'}</p><p>全文未公开，不能对这份原始文档进行语义核验。</p><a href="https://arxiv.org/html/2606.02373v1#S2.SS2.fig1" target="_blank" rel="noreferrer">核对原 Evidence Graph 文本展示块</a></>:current?<><p>{current.text.split(new RegExp(`(${current.entities.join('|')})`,'g')).map((part,i)=>current.entities.includes(part)&&(!pending||clock.elapsed>=120+current.entities.indexOf(part)*80)?<mark key={i}>{part}</mark>:part)}</p><p>{current.zh}</p><p>{displayIds.includes(doc)?'已加入本轮索引':'尚未加入本轮索引'}</p></>:<p>点击文档检查它的原句。</p>}</div>
<div className="graph" aria-label="实体与文档二部图"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{entities.flatMap((e,i)=>(edges[e]??[]).map(d=>{const isNew=d===pending,local=clock.elapsed-600-(c5Data.docs.find(x=>x.id===pending)?.entities.indexOf(e)??0)*100,opacity=isNew?Math.max(0,Math.min(1,local/260)):1;return <line key={e+d} x1="23" y1={ey(i)} x2="77" y2={dy(docs.indexOf(d))} stroke={entity===e||doc===d?'#e28748':'#9bb0c3'} strokeWidth={entity===e||doc===d?'.65':'.35'} opacity={opacity}/>;}))}</svg>{entities.map((e,i)=><button key={e} disabled={clock.running} className={`node ${entity===e||docEntities.includes(e)?'linked':''}`} style={{left:'23%',top:`${ey(i)}%`}} aria-pressed={entity===e} onClick={()=>{setEntity(e);setDoc('');setResult(null);}}>{e}<br/>{(edges[e]??[]).length} 篇</button>)}{docs.map((d,i)=><button key={d} disabled={clock.running} className={`node ${linked.includes(d)?'linked':''} ${!author&&!displayIds.includes(d)?'pending':''}`} style={{left:'77%',top:`${dy(i)}%`}} aria-pressed={doc===d} onClick={()=>{setDoc(d);setEntity('');setResult(null);}}>{d}<br/>{!author&&!displayIds.includes(d)?'待加入':`${entities.filter(e=>(edges[e]??[]).includes(d)).length} 个实体`}</button>)}</div></div>
{!author&&<div className="controls"><button disabled={clock.running||ids.includes('D3')} onClick={()=>add('D3')}>加入 D3</button><button disabled={clock.running||!ids.includes('D3')||ids.includes('D4')} onClick={()=>add('D4')}>加入 D4 · 单例线索</button>{clock.running&&<><button onClick={clock.toggle}>{clock.paused?'继续':'暂停'}</button><button onClick={clock.finish}>直接查看结果</button></>}<button onClick={reset}>重置</button></div>}
<div className="panel" role="status">{clock.running?`步骤 ${phase+1}/5 · ${c5Data.phases[phase]}。`:entity?`${entity} 对应 ${(edges[entity]??[]).join('、')||'尚无文档'}。${(edges[entity]??[]).length===1?'仅出现于一篇，可作为后续线索，不表示无用。':''}`:doc?`${doc} 包含 ${docEntities.filter(e=>high.includes(e)).length} 个当前高频实体；${docEntities.filter(e=>high.includes(e)).length>=2?'满足桥接条件，但不自动支持任何主张。':'尚未满足至少两个高频实体的桥接条件。'}`:'点击实体或文档查看对应关系。'}</div>
<div className="panel index"><div><h4>实体 → 文档（按文档去重）</h4>{Object.entries(edges).map(([e,ds])=><p key={e}>{e} → {ds.join('、')} · df={ds.length}</p>)}</div><div><h4>文档 → 实体</h4>{docs.filter(d=>author||displayIds.includes(d)).map(d=><p key={d}>{d} → {entities.filter(e=>(edges[e]??[]).includes(d)).join('、')}</p>)}</div></div>
<section className="panel"><h4>论文机制：从共同提及到可核验线索</h4><p>{c5Data.principles}</p><C56Formula text={'docs(e) = {d：文档 d 提及实体 e}，df(e) = |docs(e)|\n桥接条件：|{e ∈ F：d ∈ docs(e)}| ≥ 2'} symbols={{'docs(e)':`实体对应文档集合。当前 ${entity||'Alice Morgan'} → ${(edges[entity||'Alice Morgan']??[]).join('、')||'暂无'}`,'df(e)':'包含实体 e 的不同文档数，同文重复不累计。','d':`文档；当前检查 ${doc||'尚未选择'}。`,'e':'从原句中抽取的实体，例如人名、机构名或年份。','F':`当前用于呈现的高频实体集合：${high.join('、')||'暂无'}。`}}/><p>以上为机制的数学重述。原文按文档数选取排名靠前的实体；本小样例为便于观察，仅把 df≥2 的实体纳入 F，不宣称论文设定了统一阈值2。当前高频实体：{high.join('、')||'暂无'}。一个名字在 D3 中重复两次，仍只让 docs(e) 多一个 D3，不把频次加二。</p><p><a href="https://arxiv.org/html/2606.02373v1#S2.SS2.fig1" target="_blank" rel="noreferrer">原文文本索引展示</a> · <a href="https://arxiv.org/html/2606.02373v1#alg2" target="_blank" rel="noreferrer">Algorithm 2：搜索后的状态维护</a> · <a href="https://arxiv.org/html/2606.02373v1#alg4" target="_blank" rel="noreferrer">Algorithm 4：核验与回看</a></p><h4>原文证据 · §2.2 索引内容忠实重排</h4>{Object.entries(c5AuthorEdges).map(([e,ds])=><p key={e} style={{background:author&&(entity===e||ds.includes(doc))?'#fff0dc':undefined,borderLeft:author&&(entity===e||ds.includes(doc))?'3px solid #e28748':undefined,padding:8}}>{e} → {ds.map((d,i)=><span key={d} style={{fontWeight:author&&doc===d?700:400}}>{i?'、':''}{d}</span>)}</p>)}<p>原文另标有2个单例实体但未给名字，本图不补造。点击原文模式的实体或文档时，对应索引行在此高亮。原始编号与上方 D1—D4 教学样本是两套独立材料；仅在切换原文模式时整体切换图中对象。</p>
{!author&&<><h4>查看这条主张的依据</h4><p>点选图中文档，再选择要核验的主张。下方为预设教学判断，不调用模型。</p><div className="controls">{c5Data.claims.map((c,i)=><button key={c} aria-pressed={claim===i} onClick={()=>{setClaim(i);setResult(null);}}>{c}</button>)}<button id="c5-verify" disabled={!current} onClick={()=>setResult({doc,claim,supported:doc==='D3'&&claim===0})}>检查 {doc||'所选文档'} 的原句</button></div>{result?<div role="status"><p>{result.supported?'有依据：D3 的第一句直接陈述到访关系。':'支持不足：所选原文没有直接说明这条完整主张。共同出现不等于创办关系；不足也不等于该主张为假。'}</p><pre>V = {JSON.stringify({doc_id:result.doc,claim:c5Data.claims[result.claim],supported:result.supported,evidence:result.supported?c5Data.docs[2].text.split('. ')[0]+'.':null},null,2)}</pre><p>核验只新增该文档与主张对应的记录；C 没有自动变化。</p></div>:<p>待核验：改变文档或主张后，不沿用旧判断。</p>}</>}<p>{c5Data.boundary}</p></section></div>;}
