import {useState} from 'react';
import {useC56Clock} from './c56-clock';
import {C56Formula} from './c56-formula';
import {c6Data} from '../data/tutorial';
export const c6Sentences:Record<string,string[]>=c6Data.sentences;
const c6Chinese:Record<string,string[]>=c6Data.chinese;
export const c6Chars=(s:string)=>Array.from(s).length;
const tokenize=(s:string):string[]=>s.toLowerCase().match(/[a-z0-9]+/g)??[];
export function c6BM25(sentences:string[],query='report measurement date publication'){if(!sentences.length)return [];const terms=sentences.map(tokenize),avg=terms.reduce((n,t)=>n+t.length,0)/terms.length||1;return sentences.map((_,i)=>[...new Set(tokenize(query))].reduce((score,q)=>{const df=terms.filter(t=>t.includes(q)).length,tf=terms[i].filter(t=>t===q).length,idf=Math.log(1+(terms.length-df+.5)/(df+.5));return score+idf*tf*2.2/(tf+1.2*(.25+.75*terms[i].length/avg));},0));}
export function c6Selected(id:string,query='report measurement date publication'){const s=c6Sentences[id];if(!s||!tokenize(query).length)return [];const scores=c6BM25(s,query);return s.map((_,i)=>i).sort((a,b)=>scores[b]-scores[a]||a-b).slice(0,4).sort((a,b)=>a-b);}
export type C6Mode='raw'|'compressed'|'dedup';
const full=(id:string)=>c6Sentences[id==='d03'?'d02':id].join('\n');
const compressed=(id:string)=>{const key=id==='d03'?'d02':id;return c6Selected(key).map(i=>c6Sentences[key][i]).join('\n');};
const minimal=['You are a search agent.','Tools: search, review, finish.','Why do the measurement and publication dates differ?'].join('\n');
const reasoning='Check the source and compare the two fields. '.repeat(5);
const clip=(s:string,n:number)=>c6Chars(s)<=n?s:Array.from(s).slice(0,n-1).join('')+'…';
export function c6Candidates(mode:C6Mode,reviewed:boolean){const batch=mode==='dedup'?['d01','d02']:['d01','d02','d01','d03'];const pool=mode==='dedup'?['d01','d02']:['d01','d02','d03'];const renderDoc=mode==='raw'?full:compressed;
const recent=[['search report','d01'],['search archive','d02'],['review d02','d02']];
function render(stage:number,drop=0){if(stage===5)return {stage,drop,blocks:[{name:'必要指令与问题',text:minimal}],text:minimal};const curated=`Curated d01 [high]\n${clip(renderDoc('d01'),60)}`;const candidate=`Candidates\n${pool.filter(id=>id!=='d01').map(id=>stage>=2?id:`${id}: ${clip(renderDoc(id),60)}`).join('\n')}`;let memory=[curated,candidate].join('\n');if(stage>=3)memory=clip(memory,1000);const history=recent.slice(drop).map(([action,id],i)=>[i+drop===recent.length-1?reasoning:clip(reasoning,stage>=3?50:150),action,full(id)].join('\n')).join('\n');const returned=reviewed?`review d01\n${full('d01')}`:batch.map(id=>`${id}\n${renderDoc(id)}`).join('\n');const blocks=[{name:'必要指令与问题',text:minimal},{name:'工作记忆（精选与候选）',text:memory},...(history?[{name:'近期历史',text:history}]:[]),{name:'新返回',text:returned}];return {stage,drop,blocks,text:blocks.map(b=>b.text).join('\n')};}
return [render(1),render(2),render(3),render(4,1),render(4,2),render(4,3),render(5)];}
export const c6Bmin=c6Chars(minimal);
export const c6Bmax=Math.max(...(['raw','compressed','dedup'] as C6Mode[]).flatMap(m=>[false,true].map(r=>c6Chars(c6Candidates(m,r)[0].text))));
export function c6Build(mode:C6Mode,reviewed:boolean,budget:number){return c6Candidates(mode,reviewed).find(r=>c6Chars(r.text)<=budget)??c6Candidates(mode,reviewed)[6];}
const stageNames=['正常构建','候选仅留编号','缩短推理与记忆','逐对移除旧历史','仅保留必要输入'];
export function c6Contributions(sentences:string[],query:string,index:number){if(!sentences[index])return [];const tokens=sentences.map(tokenize),avg=tokens.reduce((a,t)=>a+t.length,0)/tokens.length||1;return [...new Set(tokenize(query))].map(term=>{const df=tokens.filter(t=>t.includes(term)).length,f=tokens[index].filter(t=>t===term).length,idf=Math.log(1+(tokens.length-df+.5)/(df+.5)),norm=1.2*(.25+.75*tokens[index].length/avg);return {term,df,f,idf,norm,value:idf*f*2.2/(f+norm)};});}
export function C6(){const [query,setQuery]=useState(0),[previous,setPrevious]=useState(0),[selected,setSelected]=useState(4),[reviewed,setReviewed]=useState(false),[term,setTerm]=useState('');const clock=useC56Clock(900);const sentences=c6Sentences.d01,scores=c6BM25(sentences,c6Data.queries[query]),oldScores=c6BM25(sentences,c6Data.queries[previous]);const keep=scores.map((_,i)=>i).sort((a,b)=>scores[b]-scores[a]||a-b).slice(0,4).sort((a,b)=>a-b),oldKeep=oldScores.map((_,i)=>i).sort((a,b)=>oldScores[b]-oldScores[a]||a-b).slice(0,4).sort((a,b)=>a-b);const progress=clock.elapsed,changing=clock.running,shownScores=changing&&progress<120?oldScores:scores,shownKeep=changing&&progress<360?oldKeep:keep,output=reviewed?[0,1,2,3,4,5]:changing&&progress<540?oldKeep:keep;const max=Math.max(...c6Data.queries.flatMap(q=>c6BM25(sentences,q)),1),contributions=c6Contributions(sentences,c6Data.queries[query],selected),tokens=new Set(tokenize(c6Data.queries[query])),step=changing?(progress<120?0:progress<360?1:progress<540?2:3):4;
function choose(n:number){setPrevious(query);setQuery(n);setTerm('');clock.start();}
return <div className="c6-new" ref={clock.ref}><style>{`.c6-new{color:#21324a}.c6-new button{font:inherit;color:inherit;background:white;border:1px solid #b9c8d4;border-radius:8px;padding:10px;cursor:pointer}.c6-new button[aria-pressed=true]{background:#e2ecf7;border-color:#27446e}.c6-new .controls{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.c6-new .sentence{display:grid;grid-template-columns:minmax(0,1fr) 130px;gap:12px;text-align:left;width:100%;margin:10px 0;line-height:1.6}.c6-new .sentence.kept{border-left:5px solid #3c8360}.c6-new .score{align-self:center}.c6-new .track{height:12px;background:#e3e7ea;border-radius:4px;overflow:hidden}.c6-new .fill{height:100%;background:#416889;transition:width 240ms}.c6-new .english{display:block;overflow-wrap:anywhere}.c6-new mark{background:#ffe0b5}.c6-new .panel{border:1px solid #d5dee8;padding:18px;border-radius:12px;margin:16px 0;background:#f7f9fb}.c6-new .output p{padding:8px;border-left:3px solid #7994ae;animation:c6appear 180ms both}.c6-new .output p.missing{border-color:#e28748;background:#fff5e7}.c6-new .formula{overflow-wrap:anywhere;padding:14px;background:#edf2f7;line-height:1.8}.c6-new table{border-collapse:collapse;width:100%;min-width:480px}.c6-new td,.c6-new th{border-bottom:1px solid #d5dee8;padding:9px;text-align:left}.c6-new .table-wrap{overflow-x:auto}.c6-new .active-term{background:#fff0dc}.c6-new :focus-visible{outline:3px solid #e28748}@keyframes c6appear{from{opacity:.3;transform:translateY(6px)}to{opacity:1;transform:none}}@media(max-width:600px){.c6-new .sentence{grid-template-columns:1fr}.c6-new .score{max-width:200px}}@media(prefers-reduced-motion:reduce){.c6-new *{animation:none!important;transition:none!important}}`}</style>
<p>固定六句英文教学原文。切换查询，观察词项得分如何改变前四句，再点击任一句检查它的得分来源。中文仅作对照。</p><div className="controls">{c6Data.queries.map((q,i)=><button key={q} aria-pressed={query===i} onClick={()=>choose(i)}>{q}</button>)}</div><p role="status">步骤 {step+1}/5 · {c6Data.steps[step]}{changing?'（正在更新，同一查询统一计算）':''}</p>
{sentences.map((sentence,i)=><button className={`sentence ${shownKeep.includes(i)?'kept':''}`} key={sentence} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span><b>句 {i+1} · {shownKeep.includes(i)?'入选':'未入选'}</b><span className="english">{sentence.split(/([A-Za-z0-9]+)/).map((part,n)=>tokens.has(part.toLowerCase())&&(!changing||progress>=120)?<mark key={n}>{part}</mark>:part)}</span>{c6Chinese.d01[i]}</span><span className="score">{shownScores[i].toFixed(3)}<span className="track" style={{display:'block'}}><span className="fill" style={{display:'block',width:`${shownScores[i]/max*100}%`}}/></span></span></button>)}
<div className="controls">{clock.running&&<><button onClick={clock.toggle}>{clock.paused?'继续':'暂停'}</button><button onClick={clock.finish}>直接查看结果</button></>}<button id="c6-review" aria-pressed={reviewed} onClick={()=>{clock.finish();setReviewed(!reviewed);}}>{reviewed?'回到本轮四句':'回看 D 中全文'}</button><button id="c6-reset" onClick={()=>{clock.finish();setQuery(0);setPrevious(0);setSelected(4);setReviewed(false);setTerm('');}}>重置</button></div>
<div className="panel output"><h4>{reviewed?'保存原文 D · 六句完整返回':'本轮展示 · 前四名按原句序号显示'}</h4>{output.map((i,n)=><p key={`${query}-${reviewed}-${i}`} className={reviewed&&!keep.includes(i)?'missing':''} style={{animationDelay:`${n*60}ms`}}><b>句{i+1}</b> {sentences[i]}<br/>{c6Chinese.d01[i]}</p>)}</div><p role="status">{changing?'观察上方评分与入选边框，下方随后恢复原序。':`当前入选句 ${keep.map(i=>i+1).join('、')}。${query===0?'具体采样与发布日期所在句5未入选；回看可恢复这个细节。':'句5匹配 sampling、March、April、public、release，具体日期进入本轮展示。'}`} {reviewed?'全文来自已保存 D；未访问语料库，评分保持不变。':''}</p>
<section className="panel"><h4>论文机制：评分、选句与原序</h4><p>{c6Data.explanation}</p><p><a href="https://arxiv.org/html/2606.02373v1#S2.SS2.p4" target="_blank" rel="noreferrer">原文 §2.2：句级 BM25 压缩</a> · <a href="https://arxiv.org/html/2606.02373v1#alg2" target="_blank" rel="noreferrer">Algorithm 2：搜索与观察</a></p><p style={{borderLeft:'3px solid #e28748',padding:12}}><b>当前原文对应：{reviewed?'从 D 读取全文分支':c6Data.steps[step]}。</b><br/>原文规则的中文重述：对文档逐句评分 → 保留最相关的四句 → 按原文位置呈现。明确调用 read_document 时仍从 D 返回全文。这里的逐句得分图是教学重绘，论文没有该图或这些句子。</p>
<h4>公式与当前句 {selected+1} 的实际计算</h4><C56Formula text={'BM25(s,q) = Σ IDF(t) · f(t,s)(k₁+1) / [f(t,s)+k₁(1−b+b·|s|/avgdl)]\nIDF(t) = ln[1 + (N−df(t)+0.5)/(df(t)+0.5)]'} symbols={{'f(t,s)':'查询词 t 在当前句 s 中的出现次数，点击下方词项可核对。','df(t)':'六句中包含词 t 的句子数，同句重复只计一次。','IDF(t)':'衡量该词在六句中的稀有程度；不是论文提供的实测分数。','|s|':`当前句 ${selected+1} 含 ${tokenize(sentences[selected]).length} 个英文词项。`,'avgdl':`六句平均词数 ${(sentences.map(v=>tokenize(v).length).reduce((a,b)=>a+b,0)/6).toFixed(3)}。`,'k₁':'教学参数1.2，控制词频增益的饱和程度。','b':'教学参数0.75，控制句长归一化强度。','N':'本教学语料包含6句。','s':`当前选中句 ${selected+1}。`,'q':c6Data.queries[query],'t':'一个查询词；下表逐词展示它的贡献。'}}/><p>教学补充：N=6；f为该词在当前句中的次数，df为包含该词的句数，|s|为当前句词数，avgdl为六句平均词数。k₁=1.2、b=0.75；所用IDF变体、参数和同分时按原句序号选择均为教学约定，不是论文公开的具体配置。分词使用小写英文字母与数字，不做停用词过滤或词干化。</p><div className="table-wrap"><table><thead><tr><th>查询词（点选）</th><th>f</th><th>df</th><th>IDF</th><th>词项贡献</th></tr></thead><tbody>{contributions.map(row=><tr key={row.term} className={term===row.term?'active-term':''}><td><button aria-pressed={term===row.term} onClick={()=>setTerm(row.term)}>{row.term}</button></td><td>{row.f}</td><td>{row.df}</td><td>{row.idf.toFixed(3)}</td><td>{row.value.toFixed(3)}</td></tr>)}</tbody></table></div><p>当前句 {selected+1}：{tokenize(sentences[selected]).length} 词；各词项贡献之和 = <b>{scores[selected].toFixed(3)}</b>。{term&&(()=>{const r=contributions.find(v=>v.term===term)!;return `词项 ${term}：分子 ${r.idf.toFixed(3)}×${r.f}×2.2；分母 ${r.f}+${r.norm.toFixed(3)}。`;})()}</p><p>{c6Data.budget}</p><p>{c6Data.context}</p><a href="https://arxiv.org/html/2606.02373v1#alg5" target="_blank" rel="noreferrer">核对 Algorithm 5：完整上下文预算分支</a></section></div>;}
