import {c78FormulaSupport as formulaSupport} from "../data/tutorial";
import {useState} from 'react';
import {c78Ui} from '../data/tutorial';
import {InteractiveFormula} from './InteractiveFormula';
import {rewardFormulas,c78Data as d} from '../data/tutorial';
import {useC78Motion} from './c78-motion';
import './c78.css';
export const terminalSets=[['d1','d2'],['d1'],['d1','d2','d3'],[]] as const;
export function rewardFor(c:readonly string[]){if(!c.length)return {reward:-.2,parts:[] as number[],precision:0,recall:0,f2:0};const hits=c.filter(x=>x==='d1'||x==='d2').length,p=hits/c.length,r=hits/2,f2=(4*p+r)?5*p*r/(4*p+r):0,a=c.includes('d2')?1:0;const parts=[.7*f2,.3,.8*a,.4,a,.1,-.35*(1-a),0];return {reward:Math.max(.001,parts.reduce((a,b)=>a+b,0)),parts,precision:p,recall:r,f2};}
export function rewardGroup(allEmpty=false,kind=0){const initial=terminalSets.flatMap(c=>[rewardFor(c).reward,rewardFor(c).reward]);const values=allEmpty?Array<number>(8).fill(-.2):initial.map((v,i)=>i===0?rewardFor(terminalSets[Math.min(kind,3)]).reward:v);const mean=values.reduce((a,b)=>a+b,0)/values.length,std=values.every(v=>v===values[0])?0:Math.sqrt(values.reduce((sum,v)=>sum+(v-mean)**2,0)/values.length);return {values,mean,std,excluded:std<1e-12};}
export function C7B(){
 const [kind,setKind]=useState(0),[previous,setPrevious]=useState(0),[panel,setPanel]=useState(0),m=useC78Motion(kind===4?240:1100);
 const phase=m.progress<.12/1.1?0:m.progress<.32/1.1?1:m.progress<.58/1.1?2:m.progress<.82/1.1?3:4;
 const shownKind=phase>=3||kind===4?kind:previous,shownSet=phase>=1?kind:previous,c=terminalSets[Math.min(shownSet,3)],r=rewardFor(terminalSets[Math.min(shownKind,3)]),g=rewardGroup(shownKind===4,shownKind),signal=g.excluded?null:(g.values[0]-g.mean)/g.std;
 const select=(i:number)=>{setPrevious(shownKind);setKind(i);m.start()};
 const contribution=rewardFor(terminalSets[Math.min(phase>=2?kind:previous,3)]),priorContribution=rewardFor(terminalSets[Math.min(previous,3)]);
 const y=(v:number)=>210-(v+.4)/4*185;
 return <div className="c78 c7b" ref={m.ref} onKeyDown={e=>{if(e.key.startsWith('Arrow'))e.stopPropagation()}}><p>{d.rewardIntro}</p>
 <div className="c78-controls" role="group" aria-label="终局精选配置">{d.rewardModes.map((x,i)=><button key={x} aria-pressed={kind===i} onClick={()=>select(i)}>{x}</button>)}</div>
 <p className="c78-stage" aria-live="polite">{m.running?'执行中 · ':''}{['选择终局情形','查看精选变化','定位受影响奖励项','重算奖励与全组统计','终局与组内信号已更新'][phase]}</p><div className="c78-track"><span style={{width:m.progress*100+'%'}}/></div>
 <div className="c78-grid"><section className={'c78-cell '+(phase===1?'active':'')}><strong>最终精选 C</strong><div className="c78-docs">{['d1','d2','d3'].map((id,i)=><div key={id} className={'c78-doc '+(c.includes(id as never)?'selected':'')}><b>文档{i+1}</b><p>{i===0?'相关证据':i===1?'答案证据':'无关材料'}</p><p>{c.includes(id as never)?'保留在精选':'曾搜到 · 未保留'}</p></div>)}</div><p>{m.running&&phase<3?'待提交的终局变化；奖励尚未更新。':'当前终局已用于计算。'}</p></section>
 <section className={'c78-cell '+(phase===2?'active':'')}><strong>具名奖励贡献</strong><p>共同零基线 · 每项保留正负方向</p><svg className="c78-chart" viewBox="0 0 320 215" role="img" aria-label="8项带符号奖励贡献"><line x1="15" x2="310" y1={y(0)} y2={y(0)} stroke="#8299a5"/>{(contribution.parts.length?contribution.parts:Array<number>(8).fill(0)).map((v,i)=><rect key={i} x={22+i*35} y={Math.min(y(v),y(0))} width="21" height={Math.abs(y(v)-y(0))} fill={phase===2&&v!==(priorContribution.parts[i]??0)?'#ef824a':v<0?'#bb4d54':'#27446e'}/>)}</svg><p><b>终局奖励 {r.reward.toFixed(4)}</b></p>{phase===2&&<p>橙色项是本次变化；总奖励将在下一步提交。</p>}<p>{r.parts.length?'贡献明细与符号见下表。':'空集合直接−0.2，不计算其余项。'}</p></section>
 <section className={'c78-cell '+(phase>=3?'active':'')}><strong>同题8条教学轨迹</strong><p>橙色为修改的第1条；虚线为均值</p><svg className="c78-chart" viewBox="0 0 320 215" role="img" aria-label={`8条轨迹奖励，均值${g.mean.toFixed(4)}，标准差${g.std.toFixed(4)}`}><line x1="15" x2="310" y1={y(0)} y2={y(0)} stroke="#8299a5"/><line x1="15" x2="310" y1={y(g.mean)} y2={y(g.mean)} stroke="#d9763d" strokeDasharray="5 3"/>{g.values.map((v,i)=><rect key={i} x={22+i*35} y={Math.min(y(v),y(0))} width="21" height={Math.abs(y(v)-y(0))} fill={i===0?'#ef824a':'#698b9f'}/>)}</svg><p>均值 {g.mean.toFixed(4)}<br/>标准差 {g.std.toFixed(4)}<br/><strong>{signal===null?'该组跳过梯度':`第1条相对信号 ${signal>=0?'+':''}${signal.toFixed(4)}`}</strong></p></section></div>
 <div className="c78-controls">{m.running&&<><button onClick={m.pause}>{m.paused?'继续':'暂停'}</button><button onClick={m.finish}>直接查看结果</button></>}<button onClick={()=>{setKind(0);setPrevious(0);m.finish()}}>重置</button></div>
 <p className="c78-feedback" aria-live="polite">{shownKind===4?'8条轨迹全部−0.2，标准差为0；跳过该组梯度，不计算除以0的信号。':shownKind===1?'答案文档已经搜到但未保留：精选答案相关奖励减少，漏选扣分出现。第1条变化同时改变全组均值和标准差。':shownKind===2?'加入无关文档降低精选精确率，相关文档召回保持不变；F₂随之降低。':shownKind===3?'空精选直接得到−0.2。其余7条保持原值，因此这一组仍可能有可区分信号。':'精选覆盖相关资料与答案；奖励评价完整搜索的终局，不是给某一步单独发奖。'}</p>
 <section className="c78-evidence"><h4>论文奖励如何形成学习信号</h4>{rewardFormulas.slice(0,1).map(formula=><InteractiveFormula key={formula.unicode} formula={formula}/>)}<p>{c78Ui.c7bText1}</p><p>当前精选精确率 {r.precision.toFixed(4)}，召回 {r.recall.toFixed(4)}，F₂ {r.f2.toFixed(4)}。已发现相关证据与答案证据的召回均为1，精选答案召回由d2是否保留决定。</p>
 <div className="c78-table"><table><thead><tr><th>奖励项</th><th>贡献</th></tr></thead><tbody>{d.rewardParts.map((x,i)=><tr key={x}><td>{i+1}. {x}</td><td>{r.parts.length?(r.parts[i]>=0?'+':'')+r.parts[i].toFixed(4):'空集：不执行'}</td></tr>)}</tbody></table></div>
 <p>组内算例：先将8个奖励求平均，再计算各奖励离均值的平方偏差平均并开方。{signal===null?'本组标准差为0，跳过更新。':`第1条以 (${g.values[0].toFixed(4)} − ${g.mean.toFixed(4)}) ÷ ${g.std.toFixed(4)} 得到 ${signal.toFixed(4)}。`} 训练算法接收相对信号更新策略；此页不运行参数更新。</p>
 <details><summary>当前8条轨迹的数值与动作记录</summary><p>{c78Ui.c7bText2}</p>{g.values.map((v,i)=><span className="c78-pill" key={i}>轨迹{i+1}：{v.toFixed(4)}</span>)}</details><p>{d.rewardBoundary}</p><p><a href="https://arxiv.org/html/2606.02373v1#A4.T5" target="_blank" rel="noreferrer">Table 5：奖励权重</a> · <a href="https://arxiv.org/html/2606.02373v1#A4.T6" target="_blank" rel="noreferrer">Table 6：RL设置</a></p>
 <h4>论文原图核对：真实训练动态</h4><p>Figure 5是两次实际RL训练的对照，独立于上方教学奖励分布。</p><div className="c78-controls"><button aria-pressed={panel===0} onClick={()=>setPanel(0)}>观察召回</button><button aria-pressed={panel===1} onClick={()=>setPanel(1)}>观察工具种类</button></div><figure className="c78-figure"><div className="c78-original-focus"><a href={import.meta.env.BASE_URL+'images/training-dynamics.svg'} target="_blank" rel="noreferrer"><img src={import.meta.env.BASE_URL+'images/training-dynamics.svg'} alt="论文Figure 5完整原图：上图召回、下图工具种类，对比有无多样性奖励"/></a><span className="c78-panel-outline" style={{top:panel===0?"0":"50%"}} aria-hidden="true"/></div><p aria-live="polite">{formulaSupport.figureFocus[panel]}</p><figcaption>Figure 5 · 点击打开完整原图。{panel===0?'上图：作者报告有多样性奖励最终召回约0.60，无奖励约0.53。':'下图：作者报告无奖励工具种类降至约3.5，有奖励约4.30。'}</figcaption></figure><p>同一起点、其余超参数相同的两次RL训练；这些是原文近似描述，不推断逐点数据，也不说明工具越多总是越好。<a href="https://arxiv.org/html/2606.02373v1#S3.F5" target="_blank" rel="noreferrer">定位Figure 5</a></p></section></div>
}
