import {useEffect,useRef,useState} from 'react';
import {benchmarks,resultData,ablations,c9Copy as copy,paperCitation} from '../data/tutorial';
import './c9.css';
export {benchmarks,resultData,ablations};
export function average(xs:number[]){return xs.reduce((a,b)=>a+b,0)/xs.length;}
export function percentagePoints(after:number,before:number){return (after-before)*100;}
function useChange(duration:number){const [changing,setChanging]=useState(false),timer=useRef<ReturnType<typeof setTimeout>>();useEffect(()=>()=>clearTimeout(timer.current),[]);return {changing,change:(fn:()=>void)=>{clearTimeout(timer.current);fn();setChanging(!matchMedia('(prefers-reduced-motion: reduce)').matches);timer.current=setTimeout(()=>setChanging(false),duration);}};}
function Original({file,title,anchor}:{file:string,title:string,anchor:string}){return <figure className="c9-original"><a href={'images/'+file} target="_blank" rel="noreferrer"><img src={'images/'+file} alt={title} loading="lazy"/></a><figcaption>{title} · <a href={copy.source+anchor} target="_blank" rel="noreferrer">在论文中核对</a> · 点击图像放大</figcaption></figure>;}
export function C9(){const [dataset,setDataset]=useState(0),[metric,setMetric]=useState(0),[all,setAll]=useState(false),[selected,setSelected]=useState('Harness-1 (20B)'),[baseline,setBaseline]=useState('Context-1 (20B)');const {changing,change}=useChange(320);const names=all?Object.keys(resultData):['Harness-1 (20B)',baseline];const sample=(name:string,m=metric)=>dataset<0?average(resultData[name][m]):resultData[name][m][dataset];const delta=percentagePoints(sample('Harness-1 (20B)'),sample(baseline));return <div className="c9" onKeyDown={e=>{if(e.key.startsWith('Arrow'))e.stopPropagation();}}>
<div className="controls"><label>数据集<select value={dataset} onChange={e=>change(()=>setDataset(+e.target.value))}>{benchmarks.map((x,i)=><option key={x} value={i}>{x}</option>)}<option value={-1}>八基准等权平均（由表2重算）</option></select></label><label>比较方法<select value={baseline} onChange={e=>change(()=>setBaseline(e.target.value))}>{Object.keys(resultData).filter(x=>x!=='Harness-1 (20B)').map(x=><option key={x}>{x}</option>)}</select></label><button aria-pressed={all} onClick={()=>change(()=>setAll(!all))}>{all?'只看所选方法':'查看全部方法'}</button></div>
<div className="controls">{copy.metrics.map((x,i)=><button className="chip" key={x} aria-pressed={metric===i} onClick={()=>change(()=>setMetric(i))}>{x}</button>)}</div>
<p className="protocol">{copy.table2Protocol}</p><h4>{dataset<0?'八基准平均':benchmarks[dataset]} · {copy.metrics[metric]} ↑ · {all?'完整方法列表':'所选方法对照'}</h4>
<div className="c9-chart" aria-label="表2数值，零基线0至1">{names.map(name=><div className={'row '+(selected===name?'selected':'')} key={name}><button className="label" aria-pressed={selected===name} onClick={()=>setSelected(name)}><strong>{name}</strong></button><div className="track"><div className="bar" style={{height:sample(name)*100+'%',background:selected===name?'#27446e':'#b8c9a7'}}><span className="c9-value">{sample(name).toFixed(3)}</span></div></div></div>)}<div className="ticks"><span>0</span><span>0.5</span><span>1</span></div></div>
<p className="feedback" role="status" data-tone="info">{changing?'切换中 · 当前数值与条件已同步。':`Harness-1 相对 ${baseline}：${delta>=0?'+':''}${delta.toFixed(2)} 个百分点。`}{copy.metricReading[metric]}</p>
<div className="c9-evidence"><h4>论文机制与指标：找到之后，还要保留</h4><p>{copy.mechanism}</p><div className="c9-pair">{[0,2].map(m=><div key={m}><b>{copy.metrics[m]}</b><div className="track"><div className="bar" style={{height:sample(selected,m)*100+'%'}}/></div><span>{selected}：{sample(selected,m).toFixed(3)}</span></div>)}</div><p>{copy.gapBoundary}</p><dl>{copy.definitions.map(x=><div key={x.term}><dt>{x.term}</dt><dd>{x.description}</dd></div>)}</dl><h4>Table 2 · 当前行列的忠实重排</h4><div className="c9-table"><table><thead><tr><th>方法</th><th>数据集</th><th>{copy.metrics[metric]} ↑</th></tr></thead><tbody>{names.map(name=><tr key={name} className={name===selected?'selected':''}><td><button onClick={()=>setSelected(name)}>{name}</button></td><td>{dataset<0?'八基准平均':benchmarks[dataset]}</td><td>{sample(name).toFixed(dataset<0?6:3)}</td></tr>)}</tbody></table></div><a href={copy.source+'S2.T2'} target="_blank" rel="noreferrer">打开原表2（保留完整实验上下文）</a><p>{copy.sourceDifference}</p><Original file="teaser_recall_barchart.png" title="Figure 1 · 八基准平均检索表现（作者原图）" anchor="S0.F1"/><details><summary>迁移范围与完整八基准数据</summary><p>{copy.transfer}</p><div className="c9-table"><table><thead><tr><th>基准</th><th>Harness-1</th><th>{baseline}</th></tr></thead><tbody>{benchmarks.map((b,i)=><tr key={b}><td>{b}</td><td>{resultData['Harness-1 (20B)'][metric][i].toFixed(3)}</td><td>{resultData[baseline][metric][i].toFixed(3)}</td></tr>)}</tbody></table></div><Original file="ood_asymmetry.svg" title="Figure 3 · 训练家族与迁移范围（作者原图）" anchor="S3.F3"/></details></div></div>;}
export function C9B(){const [mode,setMode]=useState<'ablation'|'fixed'|'answer'>('ablation'),[condition,setCondition]=useState(0);const {changing,change}=useChange(480);const rows=mode==='ablation'?[{name:'完整 Harness-1',v:[.584,.667]},ablations[condition]]:copy.fixedRows;return <div className="c9 c9b" onKeyDown={e=>{if(e.key.startsWith('Arrow'))e.stopPropagation();}}><div className="controls">{copy.modes.map((m,i)=><button className="chip" key={m} aria-pressed={mode===['ablation','fixed','answer'][i]} onClick={()=>change(()=>setMode(['ablation','fixed','answer'][i] as typeof mode))}>{m}</button>)}</div><p className="protocol">{mode==='ablation'?copy.ablationProtocol:mode==='fixed'?copy.fixedProtocol:copy.answerProtocol}</p>
{mode==='ablation'&&<label>关闭哪个组件<select value={condition} onChange={e=>change(()=>setCondition(+e.target.value))}>{ablations.map((a,i)=><option key={a.name} value={i}>{a.name}</option>)}</select></label>}
{mode!=='answer'?<><div className="c9-two">{[0,1].map(m=><div key={m}><h4>{copy.metrics[m]} ↑</h4><div className="c9-chart">{rows.map(row=><div className="row" key={row.name}><div className="label"><b>{row.name}</b></div><div className="track"><div className="bar" style={{height:row.v[m]*100+'%'}}><span className="c9-value">{row.v[m].toFixed(3)}</span></div></div></div>)}<div className="ticks"><span>0</span><span>0.5</span><span>1</span></div></div></div>)}</div><p className="feedback" role="status" data-tone="info">{changing?'切换中 · 当前比较条件已更新。':mode==='ablation'?copy.ablationReading[condition]:copy.fixedReading}</p><h4>公式与当前数据：绝对变化和相对变化</h4><p>{copy.changeExplanation}</p><div className="c9-table"><table><thead><tr><th>指标</th><th>比较基线</th><th>当前条件</th><th>变化（百分点）</th><th>变化（相对%）</th></tr></thead><tbody>{[0,1].map(m=>{const before=rows[mode==='fixed'?1:0].v[m],after=rows[rows.length-1].v[m];return <tr key={m}><th>{copy.metrics[m]}</th><td>{before.toFixed(3)}</td><td>{after.toFixed(3)}</td><td>{((after-before)*100).toFixed(2)}</td><td>{((after-before)/before*100).toFixed(2)}%</td></tr>;})}</tbody></table></div>{mode==='ablation'?<><h4>Table 3 · 论文结果完整重排</h4><div className="c9-table"><table><thead><tr><th>条件</th><th>Recall ↑</th><th>FA Recall ↑</th></tr></thead><tbody><tr><th>完整系统</th><td>0.584</td><td>0.667</td></tr>{ablations.map((r,i)=><tr key={r.name} className={condition===i?'selected':''}><th><button onClick={()=>change(()=>setCondition(i))}>{r.name}</button></th>{r.v.map((v,j)=><td key={j}>{v.toFixed(3)}</td>)}</tr>)}</tbody></table></div><p><a href={copy.source+'S3.T3'} target="_blank" rel="noreferrer">打开论文原表3</a> · <a href={copy.source+'A13'} target="_blank" rel="noreferrer">附录M：各机制的失败分析</a></p></>:<Original file="harness_comparison.png" title="Figure 7 · 固定 GPT-5.4 更换框架（作者原图）" anchor="A16.F7"/>}</>:<><Original file="answer_accuracy.svg" title="Figure 6 · 冻结回答模型的答案准确率（作者原图）" anchor="A15.F6"/><p className="feedback" role="status" data-tone="info">{copy.answerReading}</p><h4>为什么检索召回与回答正确率要分开？</h4><p>{copy.answerMechanism}</p><p>{copy.answerBoundary}</p></>}
<h4>论文题录</h4><p><a href={paperCitation.url} target="_blank" rel="noreferrer">{paperCitation.title}</a><br/>{paperCitation.authors}<br/>{paperCitation.edition}</p><h4>适用范围与局限</h4><p>{copy.limitations}</p><a href={copy.source+'A2'} target="_blank" rel="noreferrer">论文附录B：局限</a></div>;}
