/* Deterministic mechanism checks. Run from the project with node src/modules/model-audit.cjs. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const esbuild = require('esbuild');
const root=path.resolve(__dirname,'../..');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'harness-final-audit-'));
let checks=0;
function check(label,fn){fn();checks++;console.log('PASS '+label);}
function moduleExports(name){const out=path.join(temporary,name+'.cjs');esbuild.buildSync({entryPoints:[path.join(__dirname,name+'.tsx')],outfile:out,bundle:true,platform:'node',format:'cjs',logLevel:'silent'});return require(out);}
function near(a,b){assert.ok(Math.abs(a-b)<1e-10,`${a} differs from ${b}`);}
try {
 const c1=moduleExports('c1');
 check('八段历史只追加，回退不携带未来记录',()=>{assert.equal(c1.c1Scenes.length,8);let previous=[];for(let i=0;i<8;i++){const h=c1.c1Snapshot(i).history;assert.deepEqual(h.slice(0,previous.length),previous);assert.equal(h[0].role,'用户');previous=h;}assert.equal(c1.c1Snapshot(0).history.length,1);assert.equal(c1.c1Snapshot(2).history.some(x=>x.fact==='CB'),false);assert.deepEqual(c1.c1Snapshot(7),c1.c1Snapshot(7));});
 check('遗漏不删除原句，回查恢复两段关系且不扩大结论',()=>{for(const i of [5,6]){const s=c1.c1Snapshot(i);assert.deepEqual(s.found,['AC','CB']);assert.deepEqual(s.adopted,['CB']);assert.equal(s.history.some(x=>x.text===c1.c1Facts.AC),true);}const s=c1.c1Snapshot(7);assert.deepEqual(s.adopted,['AC','CB']);assert.match(s.history.at(-1).text,/不足以/);assert.equal(c1.c1Snapshot(6).history.length,c1.c1Snapshot(5).history.length);});
 const c2=moduleExports('c2');
 check('框架两分支均从同一基线派生，回看不增加候选',()=>{const initial=c2.c2Derive(null),search=c2.c2Derive('search'),review=c2.c2Derive('review');assert.deepEqual(search.P,['dA','dB']);assert.deepEqual(search.D,['dA','dB']);assert.deepEqual(search.C,['dA']);assert.deepEqual(review.P,initial.P);assert.deepEqual(review.D,initial.D);assert.deepEqual(review.C,initial.C);assert.deepEqual(c2.c2Derive('search'),search);assert.equal(initial.next.includes('2014'),false);assert.equal(review.result.includes('2014'),true);});
 const c3=moduleExports('c3');
 check('七段演示从空记录开始，找到与保留分开，回查不增文档',()=>{assert.equal(c3.c3Scenes.length,7);assert.deepEqual(c3.c3FilmSnapshot(0).C,[]);assert.deepEqual(c3.c3FilmSnapshot(2).C,['d1']);assert.deepEqual(c3.c3FilmSnapshot(3).C,['d1','d2']);assert.deepEqual(c3.c3FilmSnapshot(5).P,c3.c3FilmSnapshot(6).P);assert.deepEqual(c3.c3FilmSnapshot(6).C,['d1','d2']);});
 check('同事件等来源对比：发现与保留分开，同文抑制不增状态',()=>{const d=c3.c3Snapshot(1),keep=c3.c3Snapshot(2),dup=c3.c3Snapshot(3);assert.deepEqual(d.C,['d1']);assert.deepEqual(keep.C,['d1','d2']);assert.equal(dup.encountered.length,4);assert.equal(dup.P.length,3);assert.equal(dup.D.length,3);assert.equal(c3.c3Docs.d3.text,c3.c3Docs.d1.text);assert.deepEqual(c3.c3Snapshot(4,'both').gaps,[]);assert.deepEqual(c3.c3Snapshot(4,'d2Only').gaps,['启动日依据']);assert.deepEqual(c3.c3Snapshot(0).encountered,['d1','d4']);});
 const c4=moduleExports('c4');
 check('首次9篇结果仅初选8篇fair',()=>{const i=c4.c4Initial();assert.equal(c4.c4Docs.length,31);assert.equal(Object.keys(i).length,8);assert.deepEqual([...new Set(Object.values(i))],['fair']);assert.equal('d09' in i,false);});
 check('原位改标签只改I且不突变输入快照',()=>{const i=c4.c4Initial();const a=c4.c4Curate(i,'d02','high');assert.equal(a.next.d02,'high');assert.equal(i.d02,'fair');assert.deepEqual(Object.keys(i),Object.keys(a.next));});
 check('容量满时同级拒绝，严格较高替换唯一最差',()=>{const i=c4.c4Initial(true);const low=c4.c4Curate(i,'d31','low');assert.deepEqual(low.next,i);const fair=c4.c4Curate(i,'d31','fair');assert.equal(fair.removed,'d30');assert.equal('d30' in fair.next,false);assert.equal(fair.next.d31,'fair');assert.equal(Object.keys(fair.next).length,30);assert.equal('d31' in i,false);const downgraded=c4.c4Curate(fair.next,'d31','low');assert.equal(downgraded.next.d31,'low');assert.equal('d30' in downgraded.next,false);assert.equal(Object.keys(downgraded.next).length,30);});
 check('固定全文保留d10–d29完整生成规则',()=>{for(let n=10;n<=29;n++){assert.equal(c4.c4Docs[n-1].text,`实验A附属记录${n}：本页登记材料批次${n}，不包含组间结果或推广范围说明。`);}assert.match(c4.c4Docs[30].text,/同一地点/);});
 const c5=moduleExports('c5');
 check('作者实体图7边与桥接候选关系',()=>{assert.equal(Object.values(c5.c5AuthorEdges).flat().length,7);assert.equal(c5.c5AuthorEdges.Brussels.length,3);assert.equal(Object.values(c5.c5AuthorEdges).filter(d=>d.includes('22816_0')).length,3);assert.equal(Object.values(c5.c5AuthorEdges).filter(d=>d.includes('91442_3')).length,2);assert.equal(c5.c5TeachingEdges['人物甲'].includes('T2'),false);});
 check('共现不等于逐文档主张支持，未提供原文保持未知',()=>{assert.equal(c5.c5Verify('22816_0','dateDesigner'),null);for(const claim of ['date','dateDesigner']){assert.equal(c5.c5Verify('T1',claim).supported,true);assert.equal(c5.c5Verify('T2',claim).supported,false);assert.equal(c5.c5Verify('T3',claim).supported,false);}assert.equal(c5.c5Verify('T1','date').designerSpan,null);assert.equal(c5.c5Verify('T1','dateDesigner').designerSpan,2);});
 check('新建图按文档去重，D3构成双高频桥接，D4仍是单例',()=>{const initial=c5.c5Index(['D1','D2']);assert.deepEqual(initial['Alice Morgan'],['D1']);assert.deepEqual(initial['Beta Institute'],['D2']);const joined=c5.c5Index(['D1','D2','D3','D3']);assert.deepEqual(joined['Alice Morgan'],['D1','D3']);assert.deepEqual(joined['Beta Institute'],['D2','D3']);const frequent=Object.keys(joined).filter(e=>joined[e].length>=2);assert.equal(frequent.filter(e=>joined[e].includes('D3')).length,2);assert.deepEqual(c5.c5Index(['D1','D2','D3','D4'])['Gamma Library'],['D4']);assert.deepEqual(c5.c5Index([]),{});assert.deepEqual(initial,c5.c5Index(['D1','D2']));});
 const c6=moduleExports('c6');
 check('BM25实算选择前4句并恢复原顺序',()=>{for(const id of ['d01','d02']){assert.deepEqual(c6.c6Selected(id),[0,1,2,3]);const scores=c6.c6BM25(c6.c6Sentences[id]);assert.equal(scores.length,6);assert.equal(scores[4],0);assert.equal(scores[5],0);}});
 check('查询改变选句，词项贡献精确求和且同分恢复原序',()=>{const q='sampling March April public release',sentences=c6.c6Sentences.d01;assert.deepEqual(c6.c6Selected('d01',q),[0,1,2,4]);const scores=c6.c6BM25(sentences,q);const lengths=sentences.map(s=>(s.toLowerCase().match(/[a-z0-9]+/g)||[]).length);const avg=lengths.reduce((a,b)=>a+b,0)/6;near(scores[4],5*Math.log(1+(6-1+.5)/(1+.5))*2.2/(1+1.2*(.25+.75*lengths[4]/avg)));for(const query of [q,'report measurement date publication','report report']){const values=c6.c6BM25(sentences,query);values.forEach((value,i)=>{const parts=c6.c6Contributions(sentences,query,i);near(parts.reduce((n,p)=>n+p.value,0),value);for(const part of parts){assert.ok(part.f>=0&&part.df>=0&&part.df<=6);assert.ok(Number.isFinite(part.norm));}});}assert.deepEqual(c6.c6BM25(sentences,'report report'),c6.c6BM25(sentences,'report'));});
 check('空查询无伪选句，空语料及空文本不产生NaN',()=>{assert.deepEqual(c6.c6Selected('d01',''),[]);assert.ok(c6.c6BM25(c6.c6Sentences.d01,'').every(n=>n===0));assert.deepEqual(c6.c6BM25([],'report'),[]);assert.deepEqual(c6.c6BM25(['',''],'report'),[0,0]);assert.deepEqual(c6.c6Contributions([],'report',0),[]);});
 check('字符预算所有整数位置均选第一个可容纳候选',()=>{assert.equal(c6.c6Chars('汉😀a'),3);for(const mode of ['raw','compressed','dedup'])for(const reviewed of [false,true]){const options=c6.c6Candidates(mode,reviewed);for(let budget=c6.c6Bmin;budget<=c6.c6Bmax;budget++){const built=c6.c6Build(mode,reviewed,budget);assert.ok(c6.c6Chars(built.text)<=budget);assert.notEqual(built,undefined);const expected=options.find(x=>c6.c6Chars(x.text)<=budget);assert.equal(built.text,expected.text);assert.equal(built.stage,expected.stage);}}});
 check('压缩缺失日期可从外部全文取回，极小预算仍不可见',()=>{const normal=c6.c6Build('compressed',false,c6.c6Bmax);const reviewed=c6.c6Build('compressed',true,c6.c6Bmax);const returned=x=>x.blocks.find(b=>b.name==='新返回')?.text??'';assert.equal(returned(normal).includes('March 4'),false);assert.equal(returned(reviewed).includes('March 4'),true);assert.equal(c6.c6Build('compressed',true,c6.c6Bmin).stage,5);assert.equal(returned(c6.c6Build('compressed',true,c6.c6Bmin)),'');assert.equal(c6.c6Sentences.d01.length,6);});
 const a=moduleExports('c7a');
 check('SFT每个切片目标不泄漏进输入',()=>{assert.equal(a.sftSamples.length,4);for(const sample of a.sftSamples){assert.equal(sample.input.join('\n').includes(sample.future),false);}assert.equal(a.sftSamples[1].input.includes(a.sftSamples[0].future),true);assert.equal(a.sftSamples[3].input.includes(a.sftSamples[2].future),true);assert.equal(a.sftSamples[2].input.join('\n').includes('V新增教学核验结果'),false);assert.equal(a.sftSamples[3].input.join('\n').includes('C={d1,d2}'),false);});
 const b=moduleExports('c7b');
 check('四种终局奖励精确复算',()=>{[3.3,151/180,178/55,-.2].forEach((r,i)=>near(b.rewardFor(b.terminalSets[i]).reward,r));near(b.rewardFor(['d1']).parts[6],-.35);assert.equal(b.rewardFor([]).parts.length,0);});
 check('同题8轨迹组均值固定，常量组排除',()=>{const g=b.rewardGroup(false);assert.equal(g.values.length,8);near(g.mean,14207/7920);assert.equal(g.excluded,false);const z=b.rewardGroup(true);assert.equal(z.excluded,true);z.values.forEach(x=>near(x,-.2));});
 const c8=moduleExports('c8');
 check('两种阅读顺序均能连接身份与日期，未读材料不可精选',()=>{assert.deepEqual(c8.selectEvidence(c8.emptyPractice,'actor'),c8.emptyPractice);for(const order of [['actor','date'],['date','actor']]){let s=c8.emptyPractice;for(const k of order){s=c8.executePractice(s,k);s=c8.selectEvidence(s,k);}assert.deepEqual(c8.practiceSupport(s),{identity:true,date:true});s=c8.selectEvidence(s,'actor');assert.equal(c8.practiceSupport(s).identity,false);assert.equal(c8.practiceSupport(s).date,true);}});
 check('作者来源快照独立于练习修改',()=>{const source=JSON.stringify(c8.sourceSnapshots);let s=c8.executePractice(c8.emptyPractice,'date');s=c8.selectEvidence(s,'date');assert.deepEqual(c8.practiceSupport(s),{identity:false,date:true});assert.equal(JSON.stringify(c8.sourceSnapshots),source);assert.equal(c8.sourceSnapshots.length,7);});
 const c9=moduleExports('c9');
 check('主表八基准均值与反例',()=>{near(c9.average(c9.resultData['Harness-1 (20B)'][0]),.730375);near(c9.average(c9.resultData['Context-1 (20B)'][0]),.603375);near(c9.average(c9.resultData['Tongyi DeepResearch 30B'][0]),.616375);assert.ok(c9.resultData['Tongyi DeepResearch 30B'][0][5]>c9.resultData['Harness-1 (20B)'][0][5]);for(const rows of Object.values(c9.resultData)){assert.equal(rows.length,3);rows.forEach(x=>assert.equal(x.length,8));}});
 check('去重关闭提升2.7个百分点，非2.7相对百分比',()=>{near(c9.percentagePoints(c9.ablations[6].v[0],.584),2.7);near(c9.percentagePoints(.611,.584)/.584,4.62328767123288);assert.equal(c9.ablations.length,8);});
 console.log(`Mechanism audit passed: ${checks} groups.`);
} finally { fs.rmSync(temporary,{recursive:true,force:true}); }
