import React, { useEffect, useRef, useState } from 'react';
import { setupCanvas, observeCanvas, clamp, easeInOutQuad } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

type Config = { kind:string; labels:string[]; feedback:string[]; values?:number[][]; range?:boolean; passive?:boolean };
const C={bg:'#f5f8f0',light:'#b8c9a7',dark:'#76906a',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#d97706',purple:'#7c3aed',text:'#21324a',muted:'#68778f',axis:'#d7deea'};
function rr(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r=8){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function base(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.fillStyle=C.bg;ctx.fillRect(0,0,w,h);ctx.strokeStyle=C.axis;ctx.lineWidth=1;for(let x=30;x<w;x+=60){ctx.beginPath();ctx.moveTo(x,18);ctx.lineTo(x,h-20);ctx.stroke();}ctx.font='14px Segoe UI';ctx.fillStyle=C.text;}
function route(ctx:CanvasRenderingContext2D,w:number,h:number,active:number,fail=-1){const y=h*.55;ctx.lineWidth=4;ctx.strokeStyle=C.axis;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(w-40,y);ctx.stroke();for(let i=0;i<4;i++){const x=80+i*(w-160)/3;ctx.fillStyle=i===fail?C.red:i<=active?C.green:C.bg;ctx.strokeStyle=i===fail?C.red:i<=active?C.green:C.blue;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,13,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=C.text;ctx.fillText('S'+(i+1),x-9,y-23);}const rx=55+Math.max(0,active)*(w-160)/3;ctx.fillStyle=C.orange;ctx.beginPath();ctx.arc(rx,y-28,8,0,Math.PI*2);ctx.fill();}
function draw(ctx:CanvasRenderingContext2D,w:number,h:number,cfg:Config,index:number,value:number,time:number,chapterId:string,moduleId:string){base(ctx,w,h);const k=cfg.kind;
 if(k==='hero'){const isOld=moduleId==='old';route(ctx,w,h,isOld?2:3,isOld?1:-1);ctx.fillStyle=isOld?C.red:C.green;ctx.fillText(isOld?'孤立打勾，看不见传播':'连续门控，同时保留分段诊断',28,30);return;}
 if(k==='analogy'){const n=Number(chapterId.replace('chap-',''))||1;route(ctx,w,h,Math.min(3,(n-1)%4),n===1?1:-1);const x=45+((time/2800)%1)*(w-90);ctx.fillStyle=C.orange;ctx.beginPath();ctx.arc(x,h*.32,6,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.muted;ctx.fillText(['盖章','寻线索','返程','计分','选难度','计时','练习','验路线','查断层','完赛'][n-1]||'定向',12,20);return;}
 if(k==='cascade'||k==='compare'){route(ctx,w,h,index===cfg.labels.length-1?3:2,index===0?0:-1);ctx.fillStyle=index===0?C.red:index===cfg.labels.length-1?C.green:C.blue;ctx.fillText(cfg.labels[index],28,32);}
 else if(k==='clue'){const pts=[[100,150],[260,90],[430,170]];pts.forEach((p,i)=>{ctx.fillStyle=i===index?C.orange:C.light;ctx.beginPath();ctx.arc(p[0],p[1],22,0,Math.PI*2);ctx.fill();});ctx.strokeStyle=C.blue;ctx.lineWidth=3;ctx.beginPath();ctx.arc(pts[index][0],pts[index][1],40,0,Math.PI*2);ctx.stroke();ctx.fillStyle=C.text;ctx.fillText('线索匹配 '+(index+1)+'/3',30,32);}
 else if(k==='stages'){route(ctx,w,h,index);ctx.fillText(['自主搜索','接近并救援','依靠记忆返回','定位并交接'][index],30,32);}
 else if(k==='metric'){const p=value;for(let i=0;i<4;i++){ctx.fillStyle=i===index?C.orange:C.blue;ctx.fillRect(65+i*120,h-45-p*1.5,55,p*1.5);ctx.fillStyle=C.text;ctx.fillText('S'+(i+1),82+i*120,h-20);}ctx.fillText('Stage-TS = '+(p/4).toFixed(1),30,32);}
 else if(k==='difficulty'){const level=index+1;route(ctx,w,h,Math.min(3,level-1));ctx.fillStyle=level>=4?C.purple:C.blue;ctx.fillRect(350,50,22,level*25);ctx.fillStyle=C.text;ctx.fillText('L'+level+' · '+cfg.labels[index],30,32);}
 else if(k==='efficiency'){const colors=[C.red,C.orange,C.green];ctx.strokeStyle=colors[index];ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<12;i++){const x=40+i*38,y=130+Math.sin(i*(index+1))*35*(index===1?1:.35);i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();[.9,.55,.75].forEach((v,i)=>{ctx.fillStyle=i===index?colors[index]:C.light;ctx.fillRect(390+i*45,210-v*120,25,v*120);});ctx.fillStyle=C.text;ctx.fillText(cfg.labels[index],30,32);}
 else if(k==='step'||k==='pipeline'){for(let i=0;i<4;i++){ctx.fillStyle=i===index?C.blue:C.light;rr(ctx,30+i*130,95,105,58);ctx.fill();ctx.fillStyle=i===index?'white':C.text;ctx.fillText(cfg.labels[i],42+i*130,128);}ctx.fillStyle=C.text;ctx.fillText('步骤 '+(index+1)+'/4',30,32);}
 else if(k==='bottleneck'){const vals=(cfg.values||[])[index]||[0,0,0,0];vals.forEach((v,i)=>{ctx.fillStyle=i===0?C.blue:i===1?C.purple:i===2?C.orange:C.green;ctx.fillRect(90+i*115,h-45-v*6,58,v*6);ctx.fillStyle=C.text;ctx.fillText(v.toFixed(1),102+i*115,h-53-v*6);ctx.fillText('S'+(i+1),108+i*115,h-20);});ctx.fillText(cfg.labels[index],30,32);}
 else if(k==='results'){const vals=(cfg.values||[])[index]||[];const p=easeInOutQuad(clamp(value/100,0,1));vals.forEach((v,i)=>{ctx.fillStyle=i<2?C.blue:C.green;ctx.fillRect(135,55+i*45,v*3.4*p,25);ctx.fillStyle=C.text;ctx.fillText(['ROCKET-2(ft)','Uni-NaVid(ft)','Human','Oracle'][i]+' '+v,18,74+i*45);});ctx.fillText(cfg.labels[index]+' · 越高越好',30,30);}
}
export function makeRescueWidget(cfg:Config):React.FC<WidgetProps>{return function RescueWidget({chapterId,moduleId}){const passive=cfg.passive||false;const W=passive?(chapterId==='hero'?420:244):560;const H=passive?(chapterId==='hero'?185:130):250;const ref=useRef<HTMLCanvasElement>(null);const s=useRef({index:0,value:cfg.range?70:0,time:0});const raf=useRef<number|null>(null);const [index,setIndex]=useState(0);const [value,setValue]=useState(cfg.range?70:0);const [running,setRunning]=useState(false);useEffect(()=>{const cv=ref.current;if(!cv)return;let ctx:CanvasRenderingContext2D;try{ctx=setupCanvas(cv,W,H);cv.style.maxWidth='100%';cv.style.height='auto';}catch{return;}const tick=(t:number)=>{s.current.time=t;if(running&&cfg.kind==='results'){s.current.value=Math.min(100,s.current.value+1.4);setValue(s.current.value);if(s.current.value>=100)setRunning(false);}draw(ctx,W,H,cfg,s.current.index,s.current.value,t,chapterId,moduleId);cv.classList.add('is-ready');raf.current=requestAnimationFrame(tick);};const stop=()=>{if(raf.current)cancelAnimationFrame(raf.current);raf.current=null;};const start=()=>{if(!raf.current)raf.current=requestAnimationFrame(tick);};const off=observeCanvas(cv,start,stop);return()=>{stop();off();};},[chapterId,moduleId,running]);const choose=(i:number)=>{s.current.index=i;s.current.value=cfg.range?70:0;setIndex(i);setValue(s.current.value);setRunning(false);};if(passive)return <canvas ref={ref} width={W} height={H} aria-label="校园定向赛动画"/>;return <div><canvas ref={ref} width={W} height={H}/><div className="ctrl">{cfg.labels.map((x,i)=><button key={x} className={`chip ${index===i?'active':''}`} onClick={()=>choose(i)}>{x}</button>)}{cfg.range?<><label>进度 <span className="val">{value}%</span></label><input type="range" min="0" max="100" value={value} onChange={e=>{const v=Number(e.target.value);s.current.value=v;setValue(v);}}/></>:null}{cfg.kind==='results'?<button className="btn" onClick={()=>{s.current.value=0;setValue(0);setRunning(true);}}>开始比较</button>:null}</div><div className={`feedback ${index===0?'bad':index===cfg.labels.length-1?'good':''}`}>{cfg.feedback[index]||cfg.feedback[0]}</div></div>;};}
export const CourseKit:React.FC<WidgetProps>=makeRescueWidget({kind:'analogy',labels:['定向'],feedback:[''],passive:true});
