import React, { useEffect, useMemo, useRef, useState } from 'react';
import { clamp, lerp, observeCanvas, setupCanvas } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const W=560,H=250,MW=244,MH=130;
const C={desk:'#f5f8f0',paper:'#fff',shadow:'#b8c9a7',contour:'#76906a',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#d97706',purple:'#7c3aed',text:'#21324a',muted:'#68778f',border:'#d7deea'};
type Task='semantic'|'depth'|'normal';type Mode='explore'|'quiz';type QuizStatus='idle'|'correct'|'incorrect';
interface InferenceState{task:Task;step:0|1|2|3;mode:Mode;isPlaying:boolean;quizOrder:string[];quizStatus:QuizStatus;reducedMotion:boolean;}
const STEPS=['输入图像与提示词','生成 RGB','按约定解码','得到任务输出'];
function compactMode(id:string){return !/^\d+(\.\d+)?$/.test(id);}
function sheet(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number){ctx.fillStyle=C.shadow;ctx.fillRect(x+3,y+4,w,h);ctx.fillStyle=C.paper;ctx.fillRect(x,y,w,h);ctx.strokeStyle=C.border;ctx.strokeRect(x,y,w,h);}
function seal(ctx:CanvasRenderingContext2D,x:number,y:number){ctx.strokeStyle=C.green;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,20,0,Math.PI*2);ctx.stroke();ctx.fillStyle=C.green;ctx.font='bold 9px Segoe UI';ctx.textAlign='center';ctx.fillText('可解码',x,y+3);ctx.textAlign='left';}
function drawMini(ctx:CanvasRenderingContext2D,now:number,reduced:boolean){ctx.clearRect(0,0,MW,MH);ctx.fillStyle=C.desk;ctx.fillRect(0,0,MW,MH);sheet(ctx,10,15,224,100);ctx.strokeStyle=C.contour;ctx.lineWidth=2;ctx.strokeRect(24,35,98,62);ctx.beginPath();ctx.moveTo(35,84);ctx.lineTo(105,50);ctx.stroke();ctx.fillStyle='#fff3';ctx.fillRect(140,30,72,58);ctx.strokeStyle=C.blue;ctx.strokeRect(140,30,72,58);const p=reduced?1:(now%3400)/3400;const x=lerp(190,80,clamp(p/.65,0,1));const y=lerp(42,39,clamp(p/.65,0,1));ctx.save();ctx.translate(x,y);ctx.rotate(lerp(.18,0,clamp(p/.65,0,1)));ctx.fillStyle='rgba(39,68,110,.18)';ctx.fillRect(-38,0,76,52);ctx.strokeStyle=C.blue;ctx.strokeRect(-38,0,76,52);ctx.restore();if(p>.62||reduced){ctx.fillStyle='rgba(34,141,92,.24)';ctx.fillRect(44,54,52,24);ctx.strokeStyle=C.green;ctx.strokeRect(44,54,52,24);}if(p>.8||reduced)seal(ctx,166,92);}
function drawIcon(ctx:CanvasRenderingContext2D,index:number,x:number,y:number,task:Task){if(index===0){ctx.strokeStyle=C.contour;ctx.strokeRect(x-25,y-22,50,38);ctx.fillStyle=C.orange;ctx.fillRect(x-18,y-16,30,6);ctx.fillStyle=C.blue;ctx.fillRect(x-18,y-5,40,4);}else if(index===1){ctx.strokeStyle=C.blue;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y-4,22,0,Math.PI*2);ctx.stroke();ctx.fillStyle=C.blue;ctx.font='bold 10px Segoe UI';ctx.textAlign='center';ctx.fillText('VB',x,y);ctx.textAlign='left';}else if(index===2){for(let r=0;r<3;r++)for(let c=0;c<4;c++){ctx.fillStyle=['#dc2626','#eab308','#16a34a','#2563eb'][(r+c)%4];ctx.fillRect(x-25+c*13,y-22+r*13,12,12);}}else{ctx.strokeStyle=C.green;ctx.lineWidth=3;if(task==='semantic'){ctx.strokeRect(x-25,y-20,50,38);ctx.fillStyle='rgba(34,141,92,.25)';ctx.fillRect(x-18,y-14,30,20);}else if(task==='depth'){ctx.beginPath();ctx.moveTo(x-25,y+12);ctx.lineTo(x+25,y-16);ctx.stroke();ctx.fillStyle=C.text;ctx.fillText('3.0 m',x-18,y+27);}else{ctx.beginPath();ctx.moveTo(x-20,y+12);ctx.lineTo(x+18,y-18);ctx.stroke();ctx.beginPath();ctx.moveTo(x+18,y-18);ctx.lineTo(x+10,y-15);ctx.lineTo(x+16,y-8);ctx.fill();}}}
function drawMain(ctx:CanvasRenderingContext2D,state:InferenceState){ctx.clearRect(0,0,W,H);ctx.fillStyle=C.desk;ctx.fillRect(0,0,W,H);sheet(ctx,10,10,540,215);const xs=[71,205,339,481];ctx.font='11px Segoe UI';STEPS.forEach((label,i)=>{const active=i===state.step,done=i<state.step;ctx.fillStyle=active?'#eef4ff':'#fff';ctx.fillRect(xs[i]-52,42,104,120);ctx.strokeStyle=active?C.blue:done?C.green:C.border;ctx.lineWidth=active?3:done?2:1;ctx.strokeRect(xs[i]-52,42,104,120);drawIcon(ctx,i,xs[i],100,state.task);ctx.fillStyle=active?C.blue:done?C.green:C.muted;ctx.textAlign='center';ctx.fillText(label,xs[i],151);ctx.textAlign='left';if(i<3){ctx.strokeStyle=i<state.step?C.green:C.border;ctx.lineWidth=i===state.step?3:2;ctx.setLineDash(i>state.step?[5,4]:[]);ctx.beginPath();ctx.moveTo(xs[i]+53,102);ctx.lineTo(xs[i+1]-54,102);ctx.stroke();ctx.setLineDash([]);}});xs.forEach((x,i)=>{ctx.fillStyle=i<state.step?C.green:i===state.step?C.blue:'#e5e7eb';ctx.beginPath();ctx.arc(x,198,12,0,Math.PI*2);ctx.fill();ctx.fillStyle=i<=state.step?'#fff':C.muted;ctx.textAlign='center';ctx.fillText(String(i+1),x,202);ctx.textAlign='left';if(i<3){ctx.strokeStyle=i<state.step?C.green:C.border;ctx.beginPath();ctx.moveTo(x+13,198);ctx.lineTo(xs[i+1]-13,198);ctx.stroke();}});if(state.step===3)seal(ctx,523,198);}

export const InferenceSteps:React.FC<WidgetProps>=({chapterId,moduleId})=>{const compact=compactMode(moduleId);const canvasRef=useRef<HTMLCanvasElement>(null);const [state,setState]=useState<InferenceState>(()=>({task:'depth',step:0,mode:'explore',isPlaying:false,quizOrder:[],quizStatus:'idle',reducedMotion:typeof window!=='undefined'&&window.matchMedia('(prefers-reduced-motion: reduce)').matches}));
  useEffect(()=>{if(compact||!state.isPlaying)return;const timer=window.setTimeout(()=>setState(s=>s.step===3?{...s,isPlaying:false}:{...s,step:(s.step+1) as 0|1|2|3}),900);return()=>window.clearTimeout(timer);},[compact,state.isPlaying,state.step]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;let ctx:CanvasRenderingContext2D;try{ctx=setupCanvas(canvas,compact?MW:W,compact?MH:H);}catch{return;}let raf:number|null=null;const frame=(now:number)=>{compact?drawMini(ctx,now,state.reducedMotion):drawMain(ctx,state);canvas.classList.add('is-ready');raf=compact&&!state.reducedMotion?requestAnimationFrame(frame):null;};const start=()=>{if(raf===null)raf=requestAnimationFrame(frame);};const stop=()=>{if(raf!==null)cancelAnimationFrame(raf);raf=null;};const disconnect=observeCanvas(canvas,start,stop);return()=>{stop();disconnect();};},[compact,state]);
  const feedback=useMemo(()=>{if(state.quizStatus==='correct')return'顺序正确：先约定，再生成，再解码，最后才得到可评测答案。';if(state.quizStatus==='incorrect')return'这一步还接不上：RGB 必须先由模型生成，任务输出也必须经过对应 decoder。';if(state.step===0)return'输入包含两部分：同一张图像，以及说明任务和编码规则的提示词。';if(state.step===1)return'Vision Banana 不直接吐出标签张量；它生成一张遵循约定的 RGB 图像。';if(state.step===2)return state.task==='semantic'?'解码器把每个像素分配给 RGB 空间中最近的目标类别颜色。':state.task==='depth'?'解码器把颜色投影到最近 RGB 路径段，再逆变换为米制距离。':'解码器按固定通道约定把 R、G、B 反缩放为相机空间方向。';return state.task==='semantic'?'得到每像素类别，可计算 mIoU 等标准指标。':state.task==='depth'?'得到每像素度量距离 d，可计算 δ1 与绝对相对误差（AbsRel）。':'得到相机空间单位法线，可计算角度误差。';},[state]);
  if(compact)return <canvas ref={canvasRef} width={MW} height={MH} aria-label="透明地图图层对齐底图并显出可解码任务层"/>;
  const selectQuiz=(label:string)=>setState(s=>{const expected=STEPS[s.quizOrder.length];if(label!==expected)return{...s,quizStatus:'incorrect'};const order=[...s.quizOrder,label];return{...s,quizOrder:order,quizStatus:order.length===4?'correct':'idle',step:Math.min(3,order.length-1) as 0|1|2|3};});
  return <div>
    <div className="paper-choice-group" role="group" aria-label="选择任务">{([['semantic','语义分割'],['depth','度量深度'],['normal','表面法线']] as [Task,string][]).map(([t,l])=><button key={t} type="button" aria-pressed={state.task===t} onClick={()=>setState(s=>({...s,task:t}))}>{l}</button>)}</div>
    <div className="paper-choice-group" role="group" aria-label="模式"><button type="button" aria-pressed={state.mode==='explore'} onClick={()=>setState(s=>({...s,mode:'explore',quizOrder:[],quizStatus:'idle'}))}>观察流程</button><button type="button" aria-pressed={state.mode==='quiz'} onClick={()=>setState(s=>({...s,mode:'quiz',isPlaying:false,quizOrder:[],quizStatus:'idle',step:0}))}>顺序小测</button></div>
    {state.mode==='explore'?<div className="paper-action-group" role="group" aria-label="流程控制"><button type="button" disabled={state.step===0} onClick={()=>setState(s=>({...s,step:(s.step-1) as 0|1|2|3,isPlaying:false}))}>上一步</button><button type="button" disabled={state.step===3} onClick={()=>setState(s=>({...s,step:(s.step+1) as 0|1|2|3,isPlaying:false}))}>下一步</button><button type="button" aria-pressed={state.isPlaying} onClick={()=>setState(s=>({...s,isPlaying:!s.isPlaying}))}>自动演示</button><button type="button" className="paper-reset-button" onClick={()=>setState(s=>({...s,step:0,isPlaying:false}))}>重新开始</button></div>:<><div className="paper-step-group" role="group" aria-label="推理顺序">{STEPS.map(v=><button type="button" key={v} disabled={state.quizOrder.includes(v)} onClick={()=>selectQuiz(v)}>{v}</button>)}</div><div className="paper-action-group"><button type="button" className="paper-reset-button" disabled={!state.quizOrder.length} onClick={()=>setState(s=>({...s,quizOrder:s.quizOrder.slice(0,-1),quizStatus:'idle',step:Math.max(0,s.quizOrder.length-2) as 0|1|2|3}))}>撤销一步</button></div></>}
    <canvas id={`cv-${chapterId}-${moduleId}`} ref={canvasRef} width={W} height={H} style={{maxWidth:'100%',height:'auto'}} aria-label={`四站推理线，当前第 ${state.step+1} 步，共 4 步`}/>
    <div className={`feedback ${state.quizStatus==='incorrect'?'bad':state.step===3||state.quizStatus==='correct'?'good':''}`} role="status" aria-live="polite">当前第 {state.step+1} 步，共 4 步。{feedback}</div>
    <ol>{STEPS.map((v,i)=><li key={v}><strong>{i+1}. {v}</strong>{i===0?'：图像与任务/码本提示。':i===1?'：共享生成器产生 RGB。':i===2?'：任务规则恢复结构化值。':'：类别、米数或相机空间法线。'}</li>)}</ol>
    {state.quizStatus==='correct'&&<p className="feedback good">可读、可解码、可比较</p>}
    <p className="note">本章不引入新公式：教学目标是看清四站顺序与职责边界。深度站只引用 Chapter 4 的 f(d,λ,c)，法线站只引用 Chapter 5 的通道编码；若在此重复推导，会把“共享生成器 + 任务解码器”的系统关系淹没在计算细节中。</p>
    <p className="note">ReasonSeg 可在核心流程之前加入 Gemini 2.5 Pro 的一次查询改写；SA-Co/Gold 可先由 Gemini 3.1 Flash-Lite 过滤负查询，不能把外部步骤藏掉。</p>
    <p className="note">深度值转成三维点云属于后续反投影并需要相机内参；它不是 Vision Banana 深度预测链中的输入条件。</p>
  </div>;
};
export default InferenceSteps;
