import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AblationEvidenceExplorer } from './ablation-evidence-explorer';
import { Analogy01 } from './analogy-01';
import { Analogy02 } from './analogy-02';
import { Analogy03 } from './analogy-03';
import { Analogy04 } from './analogy-04';
import { Analogy05 } from './analogy-05';
import { Analogy06 } from './analogy-06';
import { Analogy07 } from './analogy-07';
import { Analogy08 } from './analogy-08';
import { Analogy09 } from './analogy-09';
import { Analogy10 } from './analogy-10';
import { AxisAttentionExplorer } from './axis-attention-explorer';
import { ContextExplorer } from './context-explorer';
import { EmbeddingComparisonExplorer } from './embedding-comparison-explorer';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { MathSupport } from './math';
import { OrderReadoutExplorer } from './order-readout-explorer';
import { RabelStepper } from './rabel-stepper';
import { RbfLocalExplorer } from './rbf-local-explorer';
import { ResultsBoundaryExplorer } from './results-boundary-explorer';
import { SharedTools } from './shared';
import { SpectrumExplorer } from './spectrum-explorer';
import { TrainingContextStepper } from './training-context-stepper';
import { TruncationEvidence } from './truncation-evidence';
import { ValueLineExplorer } from './value-line-explorer';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ablation-evidence-explorer'] = AblationEvidenceExplorer;
widgetRegistry['analogy-01'] = Analogy01;
widgetRegistry['analogy-02'] = Analogy02;
widgetRegistry['analogy-03'] = Analogy03;
widgetRegistry['analogy-04'] = Analogy04;
widgetRegistry['analogy-05'] = Analogy05;
widgetRegistry['analogy-06'] = Analogy06;
widgetRegistry['analogy-07'] = Analogy07;
widgetRegistry['analogy-08'] = Analogy08;
widgetRegistry['analogy-09'] = Analogy09;
widgetRegistry['analogy-10'] = Analogy10;
widgetRegistry['axis-attention-explorer'] = AxisAttentionExplorer;
widgetRegistry['context-explorer'] = ContextExplorer;
widgetRegistry['embedding-comparison-explorer'] = EmbeddingComparisonExplorer;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['math'] = MathSupport;
widgetRegistry['order-readout-explorer'] = OrderReadoutExplorer;
widgetRegistry['rabel-stepper'] = RabelStepper;
widgetRegistry['rbf-local-explorer'] = RbfLocalExplorer;
widgetRegistry['results-boundary-explorer'] = ResultsBoundaryExplorer;
widgetRegistry['shared'] = SharedTools;
widgetRegistry['spectrum-explorer'] = SpectrumExplorer;
widgetRegistry['training-context-stepper'] = TrainingContextStepper;
widgetRegistry['truncation-evidence'] = TruncationEvidence;
widgetRegistry['value-line-explorer'] = ValueLineExplorer;
