import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana1';
import { Ana10 } from './ana10';
import { Ana2 } from './ana2';
import { Ana3 } from './ana3';
import { Ana4 } from './ana4';
import { Ana5 } from './ana5';
import { Ana6 } from './ana6';
import { Ana7 } from './ana7';
import { Ana8 } from './ana8';
import { Ana9 } from './ana9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { M101 } from './m101';
import { M102 } from './m102';
import { M11 } from './m11';
import { M12 } from './m12';
import { M21 } from './m21';
import { M31 } from './m31';
import { M32 } from './m32';
import { M41 } from './m41';
import { M51 } from './m51';
import { M52 } from './m52';
import { M61 } from './m61';
import { M71 } from './m71';
import { M81 } from './m81';
import { M91 } from './m91';
import { M22 } from './m22';
import { M33 } from './m33';
import { M53 } from './m53';
import { M13 } from './m13';
import { M82 } from './m82';
import { M34 } from './m34';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana1'] = Ana1;
widgetRegistry['ana10'] = Ana10;
widgetRegistry['ana2'] = Ana2;
widgetRegistry['ana3'] = Ana3;
widgetRegistry['ana4'] = Ana4;
widgetRegistry['ana5'] = Ana5;
widgetRegistry['ana6'] = Ana6;
widgetRegistry['ana7'] = Ana7;
widgetRegistry['ana8'] = Ana8;
widgetRegistry['ana9'] = Ana9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['m101'] = M101;
widgetRegistry['m102'] = M102;
widgetRegistry['m11'] = M11;
widgetRegistry['m12'] = M12;
widgetRegistry['m21'] = M21;
widgetRegistry['m31'] = M31;
widgetRegistry['m32'] = M32;
widgetRegistry['m41'] = M41;
widgetRegistry['m51'] = M51;
widgetRegistry['m52'] = M52;
widgetRegistry['m61'] = M61;
widgetRegistry['m71'] = M71;
widgetRegistry['m81'] = M81;
widgetRegistry['m91'] = M91;
widgetRegistry['m22'] = M22;
widgetRegistry['m33'] = M33;
widgetRegistry['m53'] = M53;
widgetRegistry['m13'] = M13;
widgetRegistry['m82'] = M82;
widgetRegistry['m34'] = M34;
