import React, { useState } from 'react';
import type { WidgetProps } from './registry';

const Button = ({ active, children, onClick }: { active?: boolean; children: React.ReactNode; onClick: () => void }) => <button className={`console-btn ${active ? 'active' : ''}`} onClick={onClick}>{children}</button>;

function FrameScan() { const [selected, setSelected] = useState(2); return <div className="panel-scan"><div className="scan-track"><span className="scanline" />{Array.from({ length: 8 }, (_, i) => <button key={i} className={`frame-cell ${selected === i ? 'selected' : ''} ${[2, 6].includes(i) ? 'changed' : ''}`} onClick={() => setSelected(i)}><span>F{i + 1}</span>{[2, 6].includes(i) && <i>Δ</i>}</button>)}</div><div className="scan-readout"><span className="status-dot" />已选 F{selected + 1}<b>{[2, 6].includes(selected) ? '需要复查' : '前缀可复用'}</b></div></div>; }

function StateFlow() { const [step, setStep] = useState(1); const nodes = [['冷启动', '完整视觉前缀'], ['选择性修复', '刷新 K 帧'], ['继承追问', '复用修复状态']]; return <div className="state-flow"><div className="flow-line" style={{ width: `${step * 50}%` }} />{nodes.map((n, i) => <button key={n[0]} className={`flow-node ${i <= step ? 'visited' : ''} ${i === step ? 'current' : ''}`} onClick={() => setStep(i)}><span className="node-index">0{i + 1}</span><strong>{n[0]}</strong><small>{n[1]}</small></button>)}</div>; }

function KRepair() { const [k, setK] = useState(1); const frames = Array.from({ length: 6 }); return <div className="repair-panel"><div className="repair-frames">{frames.map((_, i) => <span key={i} className={i >= 6 - k ? 'refresh' : ''}>{i === 5 ? '最新' : `F${i + 1}`}</span>)}</div><div className="ctrl-row">{[0, 1, 4].map(x => <Button key={x} active={k === x} onClick={() => setK(x)}>K = {x}</Button>)}</div><div className="repair-meter"><span style={{ width: `${k === 4 ? 74 : k === 1 ? 28 : 8}%` }} /></div><div className="tiny-note">{k === 0 ? '成本最低 · 缓存风险最高' : k === 1 ? '固定修复基线 · 刷新最新一帧' : '更保守 · 重新预填充成本更高'}</div></div>; }

function VisionTower() { const [keep, setKeep] = useState(4); const layers = Array.from({ length: 6 }); return <div className="tower-panel"><div className="tower-stack">{layers.map((_, i) => <div key={i} className={`tower-layer ${i < keep ? 'kept' : 'skipped'}`}><span>L{i + 1}</span><b>{i < keep ? 'RUN' : 'CACHE'}</b></div>)}</div><label className="range-label">保留视觉层：{keep}/6<input type="range" min="1" max="6" value={keep} onChange={e => setKeep(+e.target.value)} /></label><div className="tower-stats"><span>视觉阶段 <b>{Math.round(keep / 6 * 100)}%</b></span><span>首问端到端 <b>{(1 + (6 - keep) * 0.063).toFixed(3)}×</b></span></div></div>; }

function Ceiling() { const [v, setV] = useState(40); const [r, setR] = useState(4); const speed = 1 / (1 - v / 100 + (v / 100) / r); return <div className="ceiling-panel"><div className="timeline"><span className="text-phase" style={{ width: `${100 - v}%` }}>文本 / 其他</span><span className="vision-phase" style={{ width: `${v}%` }}>视觉</span></div><div className="range-grid"><label>视觉份额 v <b>{v}%</b><input type="range" min="0" max="100" value={v} onChange={e => setV(+e.target.value)} /></label><label>局部加速 r <b>{r.toFixed(1)}×</b><input type="range" min="1" max="12" step=".5" value={r} onChange={e => setR(+e.target.value)} /></label></div><div className="formula-result">S = 1 / (1 − v + v/r) <strong>{speed.toFixed(2)}×</strong></div></div>; }

function EvidenceCompare() { const [mode, setMode] = useState(1); const rows = [{ name: '固定 K=1', speed: '快', drift: '稀疏漂移', cls: 'warn' }, { name: '自适应', speed: '稳', drift: '0 漂移', cls: 'good' }, { name: '计划刷新', speed: '稳', drift: '0 漂移', cls: 'good' }]; return <div className="evidence-panel">{rows.map((row, i) => <button key={row.name} className={`strategy-row ${mode === i ? 'chosen' : ''}`} onClick={() => setMode(i)}><span className={`led ${row.cls}`} /><b>{row.name}</b><span>{row.speed}</span><em className={row.cls}>{row.drift}</em></button>)}<div className="evidence-foot">50 轮 · 7 个视频 · 343 个配对答案</div></div>; }

function Boundary() { const [claim, setClaim] = useState(true); const yes = ['训练免费复用可减少重算', '指定设置下选择与正确性保持']; const no = ['像素差等于语义重要', 'C-STREAM 已被本文证明']; const list = claim ? yes : no; return <div className={`boundary-panel ${claim ? 'claim-yes' : 'claim-no'}`}><div className="boundary-toggle"><Button active={claim} onClick={() => setClaim(true)}>可主张</Button><Button active={!claim} onClick={() => setClaim(false)}>不能主张</Button></div><div className="claim-list">{list.map(x => <div key={x}><span>{claim ? '✓' : '×'}</span>{x}</div>)}</div></div>; }

const states: Record<string, React.FC> = { '1.1': FrameScan, '2.1': StateFlow, '2.2': KRepair, '3.1': VisionTower, '4.1': Ceiling, '5.1': EvidenceCompare, '6.1': Boundary };
export const RegimeExplorer: React.FC<WidgetProps> = ({ moduleId }) => { const Component = states[moduleId]; if (Component) return <Component />; const [active, setActive] = useState(0); return <div className="fallback-panel">{['首问', '追问', '候选流'].map((x, i) => <Button key={x} active={active === i} onClick={() => setActive(i)}>{x}</Button>)}<p>选择一个状态查看其证据范围。</p></div>; };
