import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Analogy1 } from './analogy-1';
import { Analogy10 } from './analogy-10';
import { Analogy2 } from './analogy-2';
import { Analogy3 } from './analogy-3';
import { Analogy4 } from './analogy-4';
import { Analogy5 } from './analogy-5';
import { Analogy6 } from './analogy-6';
import { Analogy7 } from './analogy-7';
import { Analogy8 } from './analogy-8';
import { Analogy9 } from './analogy-9';
import { ArchitectureLab } from './architecture-lab';
import { BoundaryLab } from './boundary-lab';
import { DecoderLab } from './decoder-lab';
import { EncoderLab } from './encoder-lab';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { HybridLab } from './hybrid-lab';
import { NmsEvidence } from './nms-evidence';
import { NmsLab } from './nms-lab';
import { QueryLab } from './query-lab';
import { ReadingCheck } from './reading-check';
import { ResultsLab } from './results-lab';
import { ScaleLab } from './scale-lab';
import { SharedKit } from './shared-kit';
import { TrainingLab } from './training-lab';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['analogy-1'] = Analogy1;
widgetRegistry['analogy-10'] = Analogy10;
widgetRegistry['analogy-2'] = Analogy2;
widgetRegistry['analogy-3'] = Analogy3;
widgetRegistry['analogy-4'] = Analogy4;
widgetRegistry['analogy-5'] = Analogy5;
widgetRegistry['analogy-6'] = Analogy6;
widgetRegistry['analogy-7'] = Analogy7;
widgetRegistry['analogy-8'] = Analogy8;
widgetRegistry['analogy-9'] = Analogy9;
widgetRegistry['architecture-lab'] = ArchitectureLab;
widgetRegistry['boundary-lab'] = BoundaryLab;
widgetRegistry['decoder-lab'] = DecoderLab;
widgetRegistry['encoder-lab'] = EncoderLab;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['hybrid-lab'] = HybridLab;
widgetRegistry['nms-evidence'] = NmsEvidence;
widgetRegistry['nms-lab'] = NmsLab;
widgetRegistry['query-lab'] = QueryLab;
widgetRegistry['reading-check'] = ReadingCheck;
widgetRegistry['results-lab'] = ResultsLab;
widgetRegistry['scale-lab'] = ScaleLab;
widgetRegistry['shared-kit'] = SharedKit;
widgetRegistry['training-lab'] = TrainingLab;
