import { Budget, Distribution } from './extra';
import React,{useState} from 'react';
import {Canvas,C,wipe,line,stroke,label,Chips,Feedback,Reset} from './kit';
import {rad,round,sum,mean,softmax,proxy,vals,multiply,cosine,bilinear,datasets,mainRows,abRows,hardRows,truth,binaryStats,confusion} from './math';
type CT=CanvasRenderingContext2D;
const paper='https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/08490.pdf';
const supp='https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/08490-supp.pdf';
const names=['背景','叶子','花朵'],colors=['#dfe6e4','#27446e','#b38aac'];
export function LabsRoot(){return null;}
function Source({at,children,supplement=false}:{at:string,children:React.ReactNode,supplement?:boolean}){return <div className="research-note"><a href={supplement?supp:paper} target="_blank" rel="noreferrer">{supplement?'补充材料':'正式论文'} · {at}</a><p>{children}</p></div>;}
function Toy(){return <span className="tag">教学构造 · 未运行模型权重</span>;}
function Details({title='推导与适用条件',children}:{title?:string,children:React.ReactNode}){return <details className="lab-details"><summary>{title}</summary>{children}</details>;}
function NumberBox({name,value,onChange,min=-10,max=10,step=.1}:{name:string,value:number,onChange:(n:number)=>void,min?:number,max?:number,step?:number}){return <label className="num-field">{name}<input aria-label={name} type="number" min={min} max={max} step={step} value={value} onKeyDown={e=>e.stopPropagation()} onChange={e=>{if(e.target.value==='')return;const v=Number(e.target.value);if(Number.isFinite(v))onChange(Math.max(min,Math.min(max,v)));}}/></label>;}
function Range({name,value,onChange,min=0,max=1,step=.05}:{name:string,value:number,onChange:(n:number)=>void,min?:number,max?:number,step?:number}){return <label className="lab-range">{name}<output>{round(value,2)}</output><input aria-label={name} type="range" min={min} max={max} step={step} value={value} onKeyDown={e=>e.stopPropagation()} onChange={e=>onChange(Number(e.target.value))}/></label>;}
function Bars({labels,values,max=1}:{labels:string[],values:number[],max?:number}){return <div className="bars">{values.map((v,i)=><div key={i}><span>{labels[i]}</span><div className="lab-track"><div style={{width:`${Number.isFinite(v)?Math.min(100,Math.abs(v)/max*100):0}%`,background:v<0?C.red:C.blue}}/></div><output>{round(v,3)}</output></div>)}</div>;}
function Matrix({values,title,selected=-1,onSelect,prob=false}:{values:number[][],title:string,selected?:number,onSelect?:(i:number)=>void,prob?:boolean}){return <div className="matrix-wrap"><table className="matrix"><caption>{title}</caption><tbody>{values.map((r,i)=><tr key={i}><th>{onSelect?<button aria-label={`${title}第${i+1}行`} aria-pressed={selected===i} onClick={()=>onSelect(i)}>{i+1}</button>:i+1}</th>{r.map((v,j)=><td key={j} className={i===selected?'active-row':''} style={{background:Number.isFinite(v)?`rgba(39,68,110,${.04+Math.min(1,Math.abs(v))*.28})`:'#f5dce0'}}>{Number.isFinite(v)?round(v,prob?3:2):v===-Infinity?'−∞':'未定义'}</td>)}</tr>)}</tbody></table></div>;}
function Mosaic({values,cols=8,onCell,selected=-1,label:lab='像素',drag=false}:{values:number[],cols?:number,onCell?:(i:number)=>void,selected?:number,label?:string,drag?:boolean}){return <div className="mosaic" style={{gridTemplateColumns:`repeat(${cols},1fr)`}}>{values.map((v,i)=><button key={i} type="button" disabled={!onCell} className={selected===i?'marked':''} style={{background:colors[v]||colors[0],color:v?'white':'#233747'}} aria-label={`${lab}${i+1}：${names[v]||v}`} onClick={()=>onCell?.(i)} onPointerDown={e=>{if(drag){e.preventDefault();onCell?.(i);}}} onPointerEnter={e=>{if(drag&&e.buttons===1)onCell?.(i);}}>{v===0?'·':v===1?'叶':'花'}</button>)}</div>;}
function drawMosaic(c:CT,x:number,y:number,scale=1,selected=-1){c.save();c.translate(x,y);c.scale(scale,scale);stroke(c,-8,-8,248,156,'#92400e');for(let i=0;i<24;i++){c.fillStyle=colors[i%6<3?1:2];c.globalAlpha=.7;c.fillRect((i%6)*39,Math.floor(i/6)*35,36,32);if(i===selected){c.globalAlpha=1;stroke(c,(i%6)*39,Math.floor(i/6)*35,36,32,C.orange);}}c.globalAlpha=1;c.restore();}
export function Analogy({chapterId='chap-1'}:{chapterId?:string}){const n=Math.max(0,Number(chapterId.split('-')[1])-1);return <Canvas width={560} height={140} label="一个修复工具在拼贴画上完成本章动作" animate draw={(c,t)=>{wipe(c,560,140);drawMosaic(c,185,16,.7);const p=(Math.sin(t/1000)+1)/2;c.save();c.translate(n===6||n===9?265:190+p*160,n===9?38+p*30:45+Math.sin(t/800)*18);c.rotate(n===1?t/1600:-.3);c.strokeStyle='#92400e';c.lineWidth=7;c.fillStyle=C.orange;
if(n===1){line(c,0,0,26,-30,'#92400e',7);stroke(c,-14,-5,28,15,C.orange,true);}
else if(n===2){c.beginPath();c.arc(0,0,18,0,7);c.stroke();line(c,12,12,32,36,'#92400e',7);}
else if(n===3){stroke(c,-25,-17,50,34,C.orange);for(let i=-15;i<20;i+=8)line(c,i,-14,i,14,C.muted,1);}
else if(n===4){line(c,0,-34,-9,5,C.muted,4);line(c,0,-34,9,5,C.muted,4);c.fillStyle=C.orange;c.fillRect(-8,4,16,14);}
else if(n===5){line(c,0,0,25,-35,'#92400e',10);c.fillStyle='#839992';c.beginPath();c.moveTo(0,0);c.lineTo(-7,17);c.lineTo(11,-2);c.fill();}
else if(n===6){stroke(c,-9,-20,18,38,C.blue,true);line(c,-8,-18,9,12,C.orange,3);}
else if(n===7){stroke(c,-24,-10,48,20,C.orange,true);line(c,23,1,32,15,C.muted,4);line(c,32,15,32,37,'#92400e',7);}
else if(n===8){stroke(c,-40,-10,80,20,'#92400e');for(let i=-30;i<=30;i+=10)line(c,i,-8,i,i%20?0:6,C.muted,2);}
else if(n===9){stroke(c,-16,-5,32,15,C.blue,true);line(c,0,-5,0,-25,'#92400e',10);}
else{line(c,0,0,22,-36,'#92400e',7);c.beginPath();c.moveTo(-5,0);c.lineTo(5,6);c.lineTo(7,-9);c.fill();}c.restore();}}/>;}
function Hero({good}:{good:boolean}){return <Canvas width={560} height={210} animate label={good?'沿轮廓修复拼贴画':'越界混入周围颜色'} draw={(c,t)=>{wipe(c,560,210);drawMosaic(c,170,38,1);const p=(Math.sin(t/1200)+1)/2;const x=190+p*(good?90:180);c.fillStyle=good?C.green:C.red;c.globalAlpha=.28;c.fillRect(175,40,good?106:200,135);c.globalAlpha=1;line(c,x,55,x+26,20,'#92400e',9);c.fillStyle=good?C.green:C.red;c.beginPath();c.arc(x,61,8,0,7);c.fill();}}/>;}
export function HeroOld(){return <Hero good={false}/>;}export function HeroNew(){return <Hero good/>;}

export function Paint(){const [pred,setPred]=useState(Array(48).fill(0) as number[]),[brush,setBrush]=useState(1);const st=binaryStats(pred,truth);return <><Toy/><div className="lab-columns"><div><h4>参考轮廓</h4><Mosaic values={truth}/></div><div><h4>你的逐格预测</h4><Mosaic values={pred} label="画格" onCell={i=>setPred(p=>p.map((v,j)=>i===j?brush:v))} drag/></div></div><div className="ctrl"><Chips labels={['橡皮：背景','画笔：叶子']} value={brush} onChange={setBrush}/><button className="chip" onClick={()=>setPred(pred.map((_,i)=>i%8>=2&&i%8<=5&&Math.floor(i/8)>=1&&Math.floor(i/8)<=4?1:0))}>填满外接框</button><button className="chip" onClick={()=>setPred([...truth])}>对齐参考轮廓</button><Reset onClick={()=>setPred(Array(48).fill(0))}/></div><Feedback kind={st.iou===1?'good':''}>TP {st.tp} · FP {st.fp} · FN {st.fn}；前景 IoU = {round(st.iou*100,1)}%。{st.fp?'框内的背景也被涂上了颜色，外接框不能替代精确掩码。':st.fn?'仍有前景格未被覆盖。':'每个前景格与参考一致。'}</Feedback><Source at="§1 / §3.1">像素画是任务差异的教学示意，不是 ProxyCLIP 预测。语义分割给每个位置赋予类别；本图只有前景与背景。</Source></>;}

export function Metric(){const actual=[0,0,0,0,0,0,0,0,1,1,2,2];const [pred,setPred]=useState(Array(12).fill(0) as number[]);const s=confusion(pred,actual,3);return <><Toy/><div className="lab-columns"><div><h4>参考标签</h4><Mosaic values={actual} cols={4}/><h4>预测：点一个格循环类别</h4><Mosaic values={pred} cols={4} label="指标格" onCell={i=>setPred(p=>p.map((v,j)=>j===i?(v+1)%3:v))}/></div><div><Matrix values={s.cm} title="混淆矩阵：行真值 / 列预测"/><p>行列顺序：背景、叶子、花朵。</p><Bars labels={names.map(n=>n+' IoU')} values={s.iou}/></div></div><div className="ctrl"><button className="chip" onClick={()=>setPred([...actual])}>全部正确</button><Reset onClick={()=>setPred(Array(12).fill(0))}/></div><Feedback>像素准确率 {round(s.accuracy*100,1)}%；mIoU {round(s.miou*100,1)}%。全预测背景虽有 66.7% 的像素正确，mIoU 只有 22.2%。</Feedback><div className="lab-formula">IoUₖ = TPₖ / (TPₖ + FPₖ + FNₖ)；mIoU = 类别 IoU 的均值。</div><Source at="§4.1 评测指标">本练习计入背景；并集为零的类别显示“未定义”并从均值排除。实际数据集的类别集、背景与ignore标签必须按评测协议处理。</Source></>;}

export function Vector(){const [a,setA]=useState(25),[zero,setZero]=useState(false);const v=zero?[0,0]:[Math.cos(rad(a)),Math.sin(rad(a))];const scores=[0,90,180].map(t=>cosine(v,[Math.cos(rad(t)),Math.sin(rad(t))]));const best=scores.indexOf(Math.max(...scores));return <><Toy/><div className="lab-columns"><Canvas width={520} height={290} label="拖动图像向量方向" drag onPoint={(x,y)=>{setA(Math.round(Math.atan2(145-y,x-240)*180/Math.PI));setZero(false);}} onKey={k=>{setA(a+(k==='ArrowLeft'?-5:5));setZero(false);}} draw={c=>{wipe(c,520,290);line(c,75,145,440,145,C.muted,1);line(c,240,15,240,275,C.muted,1);[0,90,180].forEach((t,i)=>{const x=240+110*Math.cos(rad(t)),y=145-110*Math.sin(rad(t));line(c,240,145,x,y,i===best?C.green:C.muted,4);});line(c,240,145,240+120*v[0],145-120*v[1],C.orange,6);c.beginPath();c.arc(240+120*v[0],145-120*v[1],9,0,7);c.fillStyle=C.orange;c.fill();}}/><Bars labels={['叶子方向 0°','花朵方向 90°','背景方向 180°']} values={scores}/></div><div className="ctrl"><NumberBox name="图像角度" value={a} min={-180} max={180} step={1} onChange={n=>{setA(n);setZero(false);}}/><button className="chip" onClick={()=>setZero(true)}>设为零向量</button><Reset onClick={()=>{setA(25);setZero(false);}}/></div><Feedback kind={zero?'bad':''}>{zero?'零向量没有定义方向：不能计算归一化余弦，也不能合法选择类别。':`当前向量 [${round(v[0])}, ${round(v[1])}]，最相似方向：${['叶子','花朵','背景'][best]}。余弦可为负；这里没有把它当概率。`}</Feedback><Source at="p8 §3.2">真实表示是高维特征。本二维实验只验证 cos(a,b)=a·b/(‖a‖‖b‖)；等分时按固定类别顺序选择。</Source></>;}

export function Vocab(){const [enabled,setEnabled]=useState([true,true,true]);const text=[[1,0],[0,1],[-1,0]],vectors=[[1,.1],[.8,.25],[.15,1],[.1,.8],[-1,.1],[-.8,.2]];const selected=enabled.map((v,i)=>v?i:-1).filter(i=>i>=0);const predicted=vectors.map(v=>{if(!selected.length)return -1;return selected.reduce((b,i)=>cosine(v,text[i])>cosine(v,text[b])?i:b,selected[0]);});return <><Toy/><div className="ctrl">{['叶子','花朵','背景'].map((n,i)=><label className="check" key={n}><input type="checkbox" checked={enabled[i]} onChange={()=>setEnabled(enabled.map((v,j)=>i===j?!v:v))}/>{n}</label>)}<Reset onClick={()=>setEnabled([true,true,true])}/></div><div className="token-cards">{predicted.map((p,i)=><div key={i}><small>画片 {i+1}</small><div className="swatch" style={{background:p<0?'#ddd':colors[[1,2,0][p]]}}/><strong>{p<0?'无预测':['叶子','花朵','背景'][p]}</strong><small>输入 [{vectors[i].join(', ')}]</small></div>)}</div><Feedback kind={!selected.length?'bad':''}>{!selected.length?'候选词表为空：argmax没有合法输入。':!enabled[0]?'删除“叶子”后，原来的叶子画片被迫在剩余类别里选择；开放词汇仍依赖你提供的候选类别。':'候选词表参与分类决策；这些名称对应固定构造向量，未调用真实文本编码器。'}</Feedback><Source at="p8 开放词汇分割">论文按最相似文本标签分类。没有候选词不等于模型会自动发现并命名那个类别；预测分数也不代表真实世界全部概念的概率。</Source></>;}

export function Affinity(){const [seed,setSeed]=useState(9),[mode,setMode]=useState(0),[th,setTh]=useState(.7);const gt=Array.from({length:24},(_,i)=>i%6<2?0:i%6<4?1:2);const angles=gt.map((v,i)=>v*75+(mode?Math.sin(i*2.8)*72:(i%4)*6));const sims=angles.map(a=>Math.cos(rad(a-angles[seed])));const indices=sims.map((_,i)=>i).filter(i=>i!==seed);const calc=(t:number)=>binaryStats(indices.map(i=>sims[i]>=t?1:0),indices.map(i=>gt[i]===gt[seed]?1:0));const s=calc(th);const precision=s.tp+s.fp?s.tp/(s.tp+s.fp):NaN,recall=s.tp/(s.tp+s.fn);const pr=Array.from(new Set([-1,...sims.filter((_,i)=>i!==seed),1.001])).sort((a,b)=>a-b).map(t=>{const z=calc(t);return [z.tp/(z.tp+z.fn),z.tp+z.fp?z.tp/(z.tp+z.fp):1];});return <><Toy/><Chips labels={['空间一致的构造特征','混入跨类噪声']} value={mode} onChange={setMode}/><div className="lab-columns"><div className="aff-grid">{sims.map((v,i)=><button key={i} aria-label={`种子${i+1}`} onClick={()=>setSeed(i)} className={i===seed?'seed':''} style={{background:v>=th?colors[gt[i]]:'#f3f4f3',color:v>=th&&gt[i]?'white':'#233747',borderStyle:v>=th?'solid':'dashed'}}>{i+1}<small>{round(v,2)}</small></button>)}</div><svg viewBox="0 0 440 270" role="img" aria-label="构造样本精确率召回率曲线"><path d="M50 20 V220 H410" fill="none" stroke="#839992"/><polyline points={pr.map(([r,p])=>`${50+r*340},${220-p*190}`).join(' ')} stroke={C.blue} strokeWidth="3" fill="none"/><circle cx={50+recall*340} cy={220-(Number.isFinite(precision)?precision:1)*190} r="7" fill={C.orange}/><text x="150" y="255">召回率 →</text><text x="10" y="16">精确率 ↑</text><text x="50" y="240">0</text><text x="390" y="240">1</text></svg></div><Range name="相似度阈值" value={th} min={-1} max={1} onChange={setTh}/><Feedback>种子 {seed+1}；TP {s.tp} / FP {s.fp} / FN {s.fn}。精确率 {round(precision,2)}，召回率 {round(recall,2)}。图中排除种子自身，避免自相似1抬高指标。</Feedback><Source at="p5–6 §3.1 / Fig1">论文用COCO Stuff真实标签多数投票定义patch类别，再评估同标签关系。本曲线仅来自24个构造格子，不是论文PR曲线，不能据此声称DINO的实测AP。</Source></>;}

export function Normal(){const [angles,setAngles]=useState([0,20,95,120]),[beta,setBeta]=useState(1.2),[gamma,setGamma]=useState(3),[mode,setMode]=useState(2),[row,setRow]=useState(0);const q=proxy(angles,beta,gamma,mode);const valid=q.p[row].every(Number.isFinite);return <><Toy/><Chips labels={['直接 softmax(S)','平移缩放，无mask','平移缩放 + mask']} value={mode} onChange={setMode}/><div className="ctrl">{angles.map((a,i)=><NumberBox key={i} name={`特征角度${i+1}`} value={a} min={0} max={180} step={5} onChange={n=>setAngles(angles.map((v,j)=>j===i?n:v))}/>)}<button className="chip" onClick={()=>setAngles([0,0,0,0])}>所有特征相同</button><Reset onClick={()=>{setAngles([0,20,95,120]);setBeta(1.2);setGamma(3);setMode(2);setRow(0);}}/></div><div className="lab-columns"><Range name="平移系数 β" value={beta} max={2} onChange={setBeta}/><Range name="缩放系数 γ" value={gamma} min={.1} max={6} step={.1} onChange={setGamma}/></div><div className="triple"><Matrix values={q.s} title="S = xxᵀ" selected={row} onSelect={setRow}/><Matrix values={q.a.map(r=>r.map(v=>mode===2&&v<0?-Infinity:v))} title="送入softmax" selected={row}/><Matrix values={q.p} title="P：逐行权重" selected={row} prob/></div><div className="lab-formula">μ = {round(q.mu)}（全部16项含对角线）；βμ = {round(beta*q.mu)}。第 {row+1} 行：ΣP = {round(sum(q.p[row]))}。</div><Feedback kind={!valid?'bad':''}>{!valid?'这一行被全部屏蔽，softmax未定义。示例不会偷偷添加自环；降低β、修改特征或重置后继续。':`保留 ${q.p[row].filter(v=>v>0).length} 个位置。${mode===2?'小于门槛的位置权重严格为0；剩余权重之和为1。':'没有mask时每个位置都获得正权重，统一平移在softmax中抵消。'}`}</Feedback><Details><p>在空间对齐后，L=Lx=Lv。μ=ΣᵢⱼSᵢⱼ/L²。Aᵢⱼ=γ(Sᵢⱼ−βμ)；Aᵢⱼ&lt;0时加−∞，其指数为0。这不是把负值改成0：exp(0)=1仍会获得权重。</p><p>当γ&gt;0时，β改变支持集门槛；γ改变保留项之间的相对强度。单位向量的自相似为1，但若βμ&gt;1，自环也会被屏蔽，所以不能认为任意参数都安全。</p></Details><Distribution/><Source at="p7–8 Eq4–8">默认β=1.2、γ=3。四个角度保证S来自真实单位向量内积，而不是随意编辑成可能不合法的余弦矩阵。</Source></>;}

export function Shift(){const [shift,setShift]=useState(.4),[mask,setMask]=useState(false);const s=[.9,.7,.3,.1],a=s.map(x=>3*(x-shift)),p=softmax(a.map(x=>mask&&x<0?-Infinity:x)),base=softmax(s.map(x=>3*x));return <><Toy/><Range name="统一平移门槛" value={shift} max={1.1} step={.05} onChange={setShift}/><label className="check"><input type="checkbox" checked={mask} onChange={e=>setMask(e.target.checked)}/>在平移后启用负值mask</label><div className="lab-columns"><Bars labels={['原始位置1','原始位置2','原始位置3','原始位置4']} values={base}/><Bars labels={['平移后位置1','平移后位置2','平移后位置3','平移后位置4']} values={p}/></div><Feedback kind={p.some(x=>!Number.isFinite(x))?'bad':''}>{p.some(x=>!Number.isFinite(x))?'全部位置被屏蔽，不能计算概率。':mask?`当前支持集 ${p.filter(x=>x>0).length} 项。平移通过mask改变“谁能参加”，而不是凭空增强语义。`:`无mask时最大概率差 ${Math.max(...p.map((v,i)=>Math.abs(v-base[i]))).toExponential(1)}，只有浮点误差。`}</Feedback><Details title="展开代数：为什么平移被抵消"><p>exp(γ(sⱼ−c))/Σₖexp(γ(sₖ−c))中，分子分母共有exp(−γc)，约去后与softmax(γs)相同。加入依赖符号的mask后，求和集合发生改变，这时不能如此约掉筛选的作用。</p></Details><Source at="Eq6–8 的代数推论">本实验是公式推导，不是新增消融结果。Table4“归一化无mask”的提升可以包含γ缩放作用，不能全归因于均值平移。</Source></>;}

export function Aggregate(){const [row,setRow]=useState(0),[v,setV]=useState(vals.map(x=>[...x])),[wrong,setWrong]=useState(false);const p=proxy(wrong?[0,95,20,120]:[0,20,95,120]).p,z=multiply(p,v)[row];const contribution=v.map((x,i)=>x[0]*p[row][i]);return <><Toy/><Chips labels={['查询画片1','查询画片2','查询画片3','查询画片4']} value={row} onChange={setRow}/><label className="check"><input type="checkbox" checked={wrong} onChange={e=>setWrong(e.target.checked)}/>把画片2和3的空间对应关系交换</label><div className="lab-columns"><div><Matrix values={p} title="P来自VFM关系" selected={row} prob/><div className="ctrl">{v.map((x,i)=><NumberBox key={i} name={`v${i+1}第一维`} value={x[0]} min={-1} max={1} onChange={n=>setV(v.map((r,j)=>i===j?[n,r[1]]:r))}/>)}</div></div><div><Bars labels={v.map((_,i)=>`P${row+1},${i+1} × v${i+1},1`)} values={contribution}/><div className="lab-formula">聚合向量：[{z.map(x=>round(x)).join(', ')}]<br/>方向得分：叶子 {round(cosine(z,[1,0]))} / 花朵 {round(cosine(z,[0,1]))}</div></div></div><Reset onClick={()=>{setRow(0);setV(vals.map(x=>[...x]));setWrong(false);}}/><Feedback>{wrong?'对应关系接错后，来自不同语义画片的value进入聚合；“邻域一致”是需要验证的假设。':'权重决定信息来自哪里，value决定混合的内容。改变v不改变这张代理权重矩阵。'}</Feedback><Details><p>实际P会扩展到n个head，对每个head的v分别聚合，再使用CLIP原来的输出投影。这里展示一个head的二维加权和，没有实现完整投影层，也没有凭空把VFM向量接入文本空间。</p></Details><Source at="p7 Eq4–5 / Fig3">P∈ℝᴸˣᴸ，v∈ℝⁿˣᴸˣᴰᵥ。Proj参数继承自CLIP，ProxyCLIP不为此学习新投影。</Source></>;}

export function Resolution(){const [src,setSrc]=useState([1,0,0,1]),[target,setTarget]=useState(5),[mode,setMode]=useState(1);const b=bilinear(src,target%4,Math.floor(target/4));const values=Array.from({length:16},(_,i)=>mode?bilinear(src,i%4,Math.floor(i/4)).value:src[Math.round(Math.floor(i/4)/3)*2+Math.round((i%4)/3)]);return <><Toy/><Chips labels={['最近邻对照','双线性教学插值']} value={mode} onChange={setMode}/><div className="lab-columns"><div><h4>源语义通道：2×2</h4><div className="source-grid">{src.map((v,i)=><NumberBox key={i} name={`源值${i+1}`} value={v} min={0} max={1} step={.1} onChange={n=>setSrc(src.map((x,j)=>i===j?n:x))}/>)}</div><Bars labels={['左上权重','右上权重','左下权重','右下权重']} values={mode?b.w:src.map((_,i)=>i===Math.round(Math.floor(target/4)/3)*2+Math.round((target%4)/3)?1:0)}/></div><div><h4>对齐后的4×4通道</h4><div className="value-grid">{values.map((v,i)=><button key={i} aria-label={`目标格${i+1}`} className={target===i?'marked':''} onClick={()=>setTarget(i)} style={{background:`rgba(39,68,110,${.1+.7*v})`,color:v>.5?'white':'#233747'}}>{round(v,2)}</button>)}</div></div></div><Feedback>目标格 {target+1} 的值为 {round(values[target])}。{mode?'四角权重之和为1；插值生成更密的采样，不会新增语义证据。':'最近邻只复制一个源位置，会形成阶梯状数值变化。'}</Feedback><Reset onClick={()=>{setSrc([1,0,0,1]);setTarget(5);setMode(1);}}/><Source at="p8 Different resolution">论文将CLIP的v插值到VFM的x网格。此处采用align_corners=true的简化坐标，未声称这是官方实现的插值参数；实际v含多个head与通道。</Source></>;}

export function Cost(){const [k,setK]=useState(0),patch=[16,8,14][k],side=336/patch,L=side*side,mem=4*L*L/1024/1024;return <><Chips labels={['patch 16','patch 8','patch 14']} value={k} onChange={setK}/><div className="lab-columns"><Canvas width={520} height={290} label="随patch尺寸变化的图像网格" draw={c=>{wipe(c,520,290);const a=230/side;for(let y=0;y<side;y++)for(let x=0;x<side;x++){c.fillStyle=x<side/2?'#a6b8cc':'#d5c3dd';c.fillRect(140+x*a,20+y*a,a-.6,a-.6);}stroke(c,138,18,234,234,C.blue);}}/><div><div className="stat-grid"><div><small>token数 L</small><strong>{L.toLocaleString()}</strong></div><div><small>关系数 L²</small><strong>{(L*L).toLocaleString()}</strong></div><div><small>单矩阵 float32</small><strong>{round(mem,2)} MiB</strong></div></div><p>输入336×336、整除patch、去除class token。这里只估算一张L×L矩阵。</p></div></div><Feedback>patch从16减为8：token数变为4倍，关系数变为16倍。更细的空间网格有成本，不能只看mIoU。</Feedback><table className="data-table"><caption>真实效率数据 · CLIP-B/16 + 对应代理</caption><thead><tr><th>VFM</th><th>IPS ↑</th><th>显存 MiB ↓</th><th>GFLOPs ↓</th></tr></thead><tbody><tr className={k===0?'selected-row':''}><td>DINO-B/16</td><td>52.9</td><td>3640</td><td>81.1</td></tr><tr className={k===1?'selected-row':''}><td>DINO-B/8</td><td>26.9</td><td>3926</td><td>253.3</td></tr></tbody></table><Budget/><Source at="p2 §C Table1" supplement>RTX3090、batch1、336×336、fp16。上方float32矩阵估算与下方实测fp16全模型显存是不同量；patch14只显示几何估算，不补造效率数据。</Source></>;}

export function Network(){const [node,setNode]=useState(0),[aligned,setAligned]=useState(true);const labels=['CLIP图像支路','VFM空间支路','空间对齐','PAM聚合','图文投影','类别匹配'];const text=[['n×4×Dv','CLIP最后注意力层的value作为语义底座，保留已预训练的能力。'],['16×Dx','归一化的VFM特征给出S=xxᵀ；不把其特征直接视为文本嵌入。'],[aligned?'n×16×Dv':'n×4×Dv','只调整v的空间位置数，使Lv=Lx；不是把Dx强制改成Dv。'],[aligned?'16×16 · 16×Dv':'16×16 · 4×Dv',aligned?'每个head复用同一P；矩阵乘法的内维相同。':'内维16和4不相等，P×v不合法，必须先对齐。'],['16×d','PAM输出投影继承CLIP，后续映射到与文本匹配的共享空间。'],['16×C','文本编码器处理候选类别提示；局部余弦得分选类别，空间恢复得到分割图。']];return <><div className="network">{labels.map((t,i)=><button key={t} className={node===i?'selected':''} onClick={()=>setNode(i)} aria-pressed={node===i}>{i+1}. {t}<small>{text[i][0]}</small></button>)}</div><Canvas height={200} label="当前选中结构节点及其依赖" draw={c=>{wipe(c,1080,200);const points=[[90,55],[90,145],[330,55],[550,105],[770,105],[990,105]];[[0,2],[1,3],[2,3],[3,4],[4,5]].forEach(([a,b])=>line(c,points[a][0],points[a][1],points[b][0],points[b][1],a===node||b===node?C.blue:C.line,a===node||b===node?5:2));points.forEach(([x,y],i)=>{c.fillStyle=i===node?C.blue:'#b8c9a7';c.beginPath();c.arc(x,y,26,0,7);c.fill();label(c,String(i+1),x-7,y+8,i===node?'white':C.ink);});}}/><label className="check"><input type="checkbox" checked={aligned} onChange={e=>setAligned(e.target.checked)}/>将CLIP网格对齐到VFM网格</label><Feedback kind={!aligned?'bad':''}><strong>{labels[node]}：</strong>{text[node][1]} {!aligned&&node!==3?'当前系统在PAM乘法处阻塞，开启空间对齐后可继续。':''}</Feedback><Details title="架构中的两种投影"><p>Eq5中的Proj合并各head输出，其参数继承最后自注意力层的输出投影；随后§3.2还说明z需投影到图文对齐空间zᵥ。教学图分别标明这两个语义步骤，不把所有投影省略成“DINO直接对文本”。</p><p>PAM的query/key均源于VFM的归一化特征，而value来自CLIP。因此它不同于通常“key与value来自同一编码器”的跨注意力。</p></Details><Source at="p6–8 Fig3 / Eq4–8">上图16/4只是维度示例；两个图像编码器与文本编码器均沿用冻结参数。</Source></>;}

const auditQs=[['ProxyCLIP组合阶段要学习一个新的投影层吗？',0,'不需要；投影沿用CLIP已有参数。'],['输入一张新图像要执行图像编码吗？',1,'需要；CLIP与VFM两条图像支路仍有推理成本。'],['基础模型本身经历过预训练吗？',1,'经历过；无需额外训练不代表模型从未训练。'],['论文标准评测要在目标验证集上微调吗？',0,'不需要；直接评估验证集。'],['Table1结果依赖额外后处理吗？',0,'论文报告未使用后处理步骤。']] as const;
export function Audit(){const [answers,setAnswers]=useState<number[]>(Array(5).fill(-1)),[sent,setSent]=useState(false);return <><div className="quiz-list">{auditQs.map(([q,correct,why],i)=><div key={q}><strong>{i+1}. {q}</strong><Chips labels={['不需要 / 没有','需要 / 有']} value={answers[i]} onChange={v=>{setAnswers(answers.map((x,j)=>j===i?v:x));setSent(false);}}/>{sent&&<p className={answers[i]===correct?'success':'error'}>{answers[i]===correct?'✓':'×'} {why}</p>}</div>)}</div><div className="ctrl"><button className="chip selected" disabled={answers.includes(-1)} onClick={()=>setSent(true)}>提交判断</button><Reset onClick={()=>{setAnswers(Array(5).fill(-1));setSent(false);}}/></div><Feedback>{sent?`答对 ${answers.filter((v,i)=>v===auditQs[i][1]).length}/5。被省掉的是新增训练过程，图像前向计算仍存在。`:`已回答 ${answers.filter(v=>v!==-1).length}/5；逐项区分已有预训练、新增训练与推理成本。`}</Feedback><Source at="§3.2 / §4.1">论文的training-free陈述限定于方法组合和下游评测，不意味着免费、无GPU或零数据历史。</Source></>;}

export function Pipeline(){const [step,setStep]=useState(0),[corrupt,setCorrupt]=useState(false);const q=proxy(corrupt?[0,95,20,120]:[0,20,95,120]);const z=multiply(q.p,vals),text=[[1,0],[0,1],[-1,0]],scores=z.map(v=>text.map(t=>cosine(v,t))),pred=scores.map(r=>r.indexOf(Math.max(...r))),steps=['1 相似度 S','2 筛选后 P','3 聚合语义','4 文本分类','5 恢复网格'];return <><Toy/><Chips labels={steps} value={step} onChange={setStep}/><div className="pipeline-view">{step===0?<Matrix title="单位VFM向量的相似度" values={q.s}/>:step===1?<Matrix title="masked softmax权重" values={q.p} prob/>:step===2?<Matrix title="省略投影的二维P×v" values={z}/>:step===3?<Matrix title="叶子 / 花朵 / 背景余弦" values={scores}/>:<div className="lab-columns"><div><h4>2×2 patch分类</h4><Mosaic values={pred.map(x=>[1,2,0][x])} cols={2}/></div><div><h4>最近邻展开4×4示意</h4><Mosaic values={Array.from({length:16},(_,i)=>[1,2,0][pred[Math.floor(Math.floor(i/4)/2)*2+Math.floor((i%4)/2)]])} cols={4}/></div></div>}</div><div className="ctrl"><button className="chip" disabled={step===0} onClick={()=>setStep(step-1)}>上一步计算</button><button className="chip selected" disabled={step===4} onClick={()=>setStep(step+1)}>执行下一步</button><label className="check"><input type="checkbox" checked={corrupt} onChange={e=>setCorrupt(e.target.checked)}/>错误邻域对照</label><Reset onClick={()=>{setStep(0);setCorrupt(false);}}/></div><Feedback>{['先计算位置之间的关系，这张矩阵还没有类别名称。','负位置被屏蔽，每个合法行权重和为1。','权重与CLIP语义相乘；本例省略多头、投影及真实编码器。','将聚合向量与候选文本比较；这里不是把注意力值直接当类别概率。','空间展开只能恢复输出尺寸，不能修复已经选错的语义标签。'][step]}</Feedback><Details title="真实评测还有哪些条件"><p>主文§3.2举例用“a photo of a {'{label names}'}”；§4.1实际评测使用标准ImageNet提示集合。PASCAL和COCO短边336，Cityscapes和ADE20K短边448。滑窗336×336，步长112。</p><p>本实验四patch单次计算不实现真实大图滑窗融合，不承诺插值方式等价。语义分类与空间恢复分开，是为了让每一步的中间量可检查。</p></Details><Source at="p7–9 Eq4–8 / §4.1">演示每一步使用同一组构造输入重新计算；切换错误关系后，所有后续值同步变化。平局固定取最先出现的候选标签。</Source></>;}

export function Ablation(){const [sel,setSel]=useState(0);const r=abRows[sel];return <><span className="tag verified">论文报告数据 · Table4</span><Chips labels={abRows.map(r=>r.name)} value={sel} onChange={setSel}/><p className="missing">“无归一化 / 有mask”未在主文Table4报告，不能补成第四个消融点。</p><div className="lab-columns"><Bars labels={datasets} values={r.v} max={100}/><div><div className="stat-grid"><div><small>八数据集平均mIoU</small><strong>{round(r.avg,1)}</strong></div><div><small>相对无处理基线</small><strong>+{round(r.avg-25,1)}</strong></div></div><svg viewBox="0 0 400 270" role="img" aria-label="三项已报告消融均值"><line x1="40" y1="240" x2="380" y2="240" stroke="#839992"/>{abRows.map((r,i)=><g key={r.name}><rect x={70+i*105} y={240-r.avg*4.5} width="62" height={r.avg*4.5} fill={i===sel?C.blue:'#b8c9a7'}/><text x={78+i*105} y={225-r.avg*4.5}>{r.avg}</text><text x={85+i*105} y="263">{i+1}</text></g>)}</svg></div></div><Feedback>{sel===0?'直接使用softmax(xxᵀ)的平均仅25.0，说明“拿来VFM关系”本身还不够。':sel===1?'只做平移缩放达到29.5；无mask时全局平移会抵消，因此不能把此提升解释为单独的均值中心化效果。':'加入mask后达到42.3，相比仅归一化提高12.8个百分点；这是该固定配置下的报告结果。'}</Feedback><Source at="p14 Table4">固定CLIP-ViT-B/16 + DINO-ViT-B/8，八个验证集mIoU，越高越好，无后处理。该表评估方法组成，并不证明任意图像上mask都会改善。</Source></>;}

export function Backbone(){const [table,setTable]=useState(0),[sel,setSel]=useState(0);const model=[['MAE B/16',36.7],['SAM B/16',40.8],['SD UNet',41.8],['DINOv2 B/14',41.1],['DINO B/16',41.1]] as const;const patch=[['DINO S/16',40.9],['DINO S/8',41.7],['DINO B/16',41.1],['DINO B/8',42.3]] as const;const rows=table===0?model:patch;const h=hardRows[Math.min(sel,3)];return <><span className="tag verified">论文报告数据 · 条件化比较</span><Chips labels={['不同VFM · Table2','patch与规模 · Table3','固定阈值 · 补充Table2']} value={table} onChange={v=>{setTable(v);setSel(0);}}/>{table<2?<><Chips labels={rows.map(r=>r[0])} value={sel} onChange={setSel}/><div className="lab-columns"><Bars labels={rows.map(r=>r[0])} values={rows.map(r=>r[1])} max={50}/><div className="lab-formula">已选 {rows[sel][0]}<br/>八数据集平均mIoU：{rows[sel][1]}<br/>固定语义主干：CLIP-B/16</div></div></>:<><Chips labels={hardRows.map(r=>r.name)} value={sel} onChange={setSel}/><div className="lab-columns"><svg viewBox="0 0 500 280" role="img" aria-label={`${h.name}固定阈值性能曲线`}><path d="M45 20 V240 H470" stroke="#839992" fill="none"/><polyline points={h.v.map((v,i)=>`${65+i*92},${240-(v-10)*12}`).join(' ')} fill="none" stroke={C.blue} strokeWidth="3"/>{h.v.map((v,i)=><g key={i}><circle cx={65+i*92} cy={240-(v-10)*12} r="5" fill={C.blue}/><text x={52+i*92} y={225-(v-10)*12}>{v}</text><text x={54+i*92} y="264">{i*.2===.6000000000000001?.6:round(i*.2,1)}</text></g>)}<line x1="45" x2="470" y1={240-(h.adaptive-10)*12} y2={240-(h.adaptive-10)*12} stroke={C.green} strokeDasharray="7 5"/><text x="200" y="18">COCOStuff mIoU ↑</text></svg><div><p>横轴：固定阈值α；纵轴范围10–28。</p><div className="lab-formula">自适应（绿虚线）：{h.adaptive}<br/>已报告最佳手调值：{Math.max(...h.v)}</div></div></div></>}<Feedback>{table===0?'这里没有保持全部VFM分辨率与计算成本一致，不能单凭均值断言某模型全面更强。':table===1?'B/16→B/8平均增加1.2点；但S/16→S/8在VOC20为79.8→79.6，并非每列都上升。':`${h.name}：自适应 ${h.adaptive} vs 最佳固定阈值 ${Math.max(...h.v)}。${h.adaptive<Math.max(...h.v)?'自适应并未击败这一行的最佳手调结果；它的优势是跨VFM共用一套规则。':'本行自适应值更高，但不能由这一行推出所有模型均如此。'}`}</Feedback><Source at={table===0?'p12 Table2':table===1?'p13 Table3':'p3 §D Table2'} supplement={table===2}>{table===2?'固定α=0/0.2/0.4/0.6/0.8与自适应归一化+mask比较，数据集是COCOStuff，不是八数据集平均。':'固定CLIP-B/16；同表范围内比较八验证集平均mIoU。SD使用UNet，其他为ViT，实验不等成本。'}</Source></>;}

export function Results(){const [dataset,setDataset]=useState(8),[base,setBase]=useState(0),[method,setMethod]=useState(2),[ext,setExt]=useState(false);const a=dataset===8?mainRows[base].avg:mainRows[base].v[dataset],b=dataset===8?mainRows[method].avg:mainRows[method].v[dataset];return <><span className="tag verified">真实报告结果 · 与教学模拟分开</span><Chips labels={['主表：八个验证集','扩展：847 / 459类']} value={ext?1:0} onChange={v=>setExt(Boolean(v))}/>{!ext?<><div className="ctrl"><label>比较对象 <select aria-label="比较对象" value={base} onChange={e=>setBase(Number(e.target.value))}>{mainRows.map((r,i)=><option value={i} key={r.name}>{r.name}</option>)}</select></label><label>目标配置 <select aria-label="目标配置" value={method} onChange={e=>setMethod(Number(e.target.value))}>{mainRows.map((r,i)=><option value={i} key={r.name}>{r.name}</option>)}</select></label><label>指标列 <select aria-label="指标列" value={dataset} onChange={e=>setDataset(Number(e.target.value))}>{[...datasets,'平均'].map((d,i)=><option value={i} key={d}>{d}</option>)}</select></label></div><Bars labels={[mainRows[base].name,mainRows[method].name]} values={[a,b]} max={100}/><Feedback kind={b<a?'bad':''}>{[...datasets,'平均'][dataset]}：{a.toFixed(1)} → {b.toFixed(1)}；差值 {b-a>=0?'+':''}{round(b-a,1)} 个百分点。{b<a?'目标配置在这一列更低：不要把平均优势写成所有数据集都更好。':'这是当前列和配置的结果；不自动推广到新数据。'}</Feedback><div className="table-scroll"><table className="data-table"><caption>Table1 · mIoU (%) ↑；平均为原表报告值</caption><thead><tr><th>配置</th>{datasets.map(d=><th key={d}>{d}</th>)}<th>平均</th></tr></thead><tbody>{mainRows.map((r,i)=><tr key={r.name} className={i===method?'selected-row':''}><th>{r.name}</th>{r.v.map((v,j)=><td key={j}>{v.toFixed(1)}</td>)}<td>{r.avg.toFixed(1)}</td></tr>)}</tbody></table></div><Source at="p9–10 §4.1 / Table1">VOC、Context、Object含背景类；VOC20、Context59、Stuff、City、ADE不含背景类。Proxy B/L使用CLIP，H使用OpenCLIP；代理均为DINO-B/8。CLIP-DINOiser属于训练方法，不可把40.3→44.4说成同骨干纯消融。</Source></>:<><Bars labels={['Proxy · ADE847','Proxy · PC459','DINOiser · ADE847','DINOiser · PC459','SCLIP · ADE847','SCLIP · PC459']} values={[11.1,9.9,7.1,8.4,4.9,6.3]} max={15}/><Feedback>ProxyCLIP在这两个扩展数据集的平均为10.5；它不是主表八集平均44.4，也不能与ADE20K一列直接相减。</Feedback><Source at="p4 §F Table4" supplement>847类与459类扩大了候选空间。有监督方法通常另用COCOStuff密集标签做域内训练；本页不将其名次解释为控制变量实验。</Source></>}<Details title="哪些结论还需要新实验"><p>训练免费并不成立：只是不需要为本方法新增训练。两图像编码器仍有成本。构造图显示错误对应会传播错误语义，这是机制风险分析，不是论文报告的错误率。</p><p>这篇论文没有证明所有域、任意提示和每个细小边界均可靠。当前网页没有运行权重，所以不能把示意分割当成真实复现，也不提供自称实测的推理时延。</p></Details></>;}

const quizQs=[{q:'A中的负值应如何处理？',choices:['改成0后直接softmax','在softmax前屏蔽成−∞','取绝对值保留'],answer:1,why:'Eq7–8：exp(−∞)=0；exp(0)=1，不等价。'}, {q:'“无需额外训练”可以推出什么？',choices:['基础模型未使用训练数据','每张图不需要图像编码','组合阶段不更新预训练权重'],answer:2,why:'§3.2与§4.1：冻结并直接评测；推理计算仍存在。'}, {q:'八集均值提高，能推出每列都提高吗？',choices:['不能，需要逐列检查','能，均值已经概括全部情况','只要主干更大就能'],answer:0,why:'Table1 VOC20：Proxy-B/16为80.3，SCLIP-B/16为80.4。'}, {q:'补充ADE847的11.1怎样与主表ADE20K比较？',choices:['相减即可估计退化','先区分类别空间与评测协议','合入主表均值即可'],answer:1,why:'补充Table4是847/459类扩展任务；不是主表ADE20K同协议。'}];
export function Quiz(){const [choice,setChoice]=useState(Array(4).fill(-1) as number[]),[submitted,setSubmitted]=useState(false);const score=choice.filter((v,i)=>v===quizQs[i].answer).length;return <><div className="quiz-list">{quizQs.map((q,i)=><div key={q.q}><h4>{i+1}. {q.q}</h4><Chips labels={q.choices} value={choice[i]} onChange={n=>{setChoice(choice.map((v,j)=>i===j?n:v));setSubmitted(false);}}/>{submitted&&<p className={choice[i]===q.answer?'success':'error'}>{choice[i]===q.answer?'✓':'×'} {q.why}</p>}</div>)}</div><div className="ctrl"><button className="chip selected" disabled={choice.includes(-1)} onClick={()=>setSubmitted(true)}>核对证据</button><Reset onClick={()=>{setChoice(Array(4).fill(-1));setSubmitted(false);}}/></div><Feedback kind={submitted&&score===4?'good':''}>{submitted?`证据挑战：${score}/4。结论应该与公式、配置和协议一一对应。`:`已选择 ${choice.filter(x=>x>=0).length}/4；提交后显示出处与理由。`}</Feedback></>;}
