import { Graph, Permutation, Windows } from './extra';
import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { WidgetAblation } from './ablation';
import { WidgetAffinity } from './affinity';
import { WidgetAggregate } from './aggregate';
import { WidgetAnalogy } from './analogy';
import { WidgetAudit } from './audit';
import { WidgetBackbone } from './backbone';
import { WidgetCost } from './cost';
import { WidgetHeroNew } from './hero-new';
import { WidgetHeroOld } from './hero-old';
import { BirdKit } from './kit';
import { LabsRoot } from './labs';
import { MathRoot } from './math';
import { WidgetMetric } from './metric';
import { WidgetNetwork } from './network';
import { WidgetNormal } from './normal';
import { WidgetPaint } from './paint';
import { WidgetPipeline } from './pipeline';
import { WidgetQuiz } from './quiz';
import { WidgetResolution } from './resolution';
import { WidgetResults } from './results';
import { WidgetShift } from './shift';
import { WidgetVector } from './vector';
import { WidgetVocab } from './vocab';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ablation'] = WidgetAblation;
widgetRegistry['affinity'] = WidgetAffinity;
widgetRegistry['aggregate'] = WidgetAggregate;
widgetRegistry['analogy'] = WidgetAnalogy;
widgetRegistry['audit'] = WidgetAudit;
widgetRegistry['backbone'] = WidgetBackbone;
widgetRegistry['cost'] = WidgetCost;
widgetRegistry['hero-new'] = WidgetHeroNew;
widgetRegistry['hero-old'] = WidgetHeroOld;
widgetRegistry['kit'] = BirdKit;
widgetRegistry['labs'] = LabsRoot;
widgetRegistry['math'] = MathRoot;
widgetRegistry['metric'] = WidgetMetric;
widgetRegistry['network'] = WidgetNetwork;
widgetRegistry['normal'] = WidgetNormal;
widgetRegistry['paint'] = WidgetPaint;
widgetRegistry['pipeline'] = WidgetPipeline;
widgetRegistry['quiz'] = WidgetQuiz;
widgetRegistry['resolution'] = WidgetResolution;
widgetRegistry['results'] = WidgetResults;
widgetRegistry['shift'] = WidgetShift;
widgetRegistry['vector'] = WidgetVector;
widgetRegistry['vocab'] = WidgetVocab;

widgetRegistry['graph'] = Graph;
widgetRegistry['permutation'] = Permutation;
widgetRegistry['windows'] = Windows;
