import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ch1Analogy } from './ch1-analogy';
import { Ch1FixedModelStress } from './ch1-fixed-model-stress';
import { Ch1RouteRepair } from './ch1-route-repair';
import { Ch2Analogy } from './ch2-analogy';
import { Ch2HarnessState } from './ch2-harness-state';
import { Ch3Analogy } from './ch3-analogy';
import { Ch3CapabilityMatch } from './ch3-capability-match';
import { Ch4Analogy } from './ch4-analogy';
import { Ch4ParetoConsole } from './ch4-pareto-console';
import { Ch5Analogy } from './ch5-analogy';
import { Ch5EnsembleSelector } from './ch5-ensemble-selector';
import { Ch6AggregationSteps } from './ch6-aggregation-steps';
import { Ch6Analogy } from './ch6-analogy';
import { Ch7Analogy } from './ch7-analogy';
import { Ch7OffpolicyReplay } from './ch7-offpolicy-replay';
import { Ch8Analogy } from './ch8-analogy';
import { Ch8RouterArchitecture } from './ch8-router-architecture';
import { Ch9Analogy } from './ch9-analogy';
import { Ch9BenchmarkRace } from './ch9-benchmark-race';
import { Ch9LimitationsConsole } from './ch9-limitations-console';
import { HeroAgenticMix } from './hero-agentic-mix';
import { HeroFixedTrack } from './hero-fixed-track';
import { StudioKitCarrier } from './studio-kit';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ch1-analogy'] = Ch1Analogy;
widgetRegistry['ch1-fixed-model-stress'] = Ch1FixedModelStress;
widgetRegistry['ch1-route-repair'] = Ch1RouteRepair;
widgetRegistry['ch2-analogy'] = Ch2Analogy;
widgetRegistry['ch2-harness-state'] = Ch2HarnessState;
widgetRegistry['ch3-analogy'] = Ch3Analogy;
widgetRegistry['ch3-capability-match'] = Ch3CapabilityMatch;
widgetRegistry['ch4-analogy'] = Ch4Analogy;
widgetRegistry['ch4-pareto-console'] = Ch4ParetoConsole;
widgetRegistry['ch5-analogy'] = Ch5Analogy;
widgetRegistry['ch5-ensemble-selector'] = Ch5EnsembleSelector;
widgetRegistry['ch6-aggregation-steps'] = Ch6AggregationSteps;
widgetRegistry['ch6-analogy'] = Ch6Analogy;
widgetRegistry['ch7-analogy'] = Ch7Analogy;
widgetRegistry['ch7-offpolicy-replay'] = Ch7OffpolicyReplay;
widgetRegistry['ch8-analogy'] = Ch8Analogy;
widgetRegistry['ch8-router-architecture'] = Ch8RouterArchitecture;
widgetRegistry['ch9-analogy'] = Ch9Analogy;
widgetRegistry['ch9-benchmark-race'] = Ch9BenchmarkRace;
widgetRegistry['ch9-limitations-console'] = Ch9LimitationsConsole;
widgetRegistry['hero-agentic-mix'] = HeroAgenticMix;
widgetRegistry['hero-fixed-track'] = HeroFixedTrack;
widgetRegistry['studio-kit'] = StudioKitCarrier;
