import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Analogy1 } from './analogy-1';
import { Analogy10 } from './analogy-10';
import { Analogy2 } from './analogy-2';
import { Analogy3 } from './analogy-3';
import { Analogy4 } from './analogy-4';
import { Analogy5 } from './analogy-5';
import { Analogy6 } from './analogy-6';
import { Analogy7 } from './analogy-7';
import { Analogy8 } from './analogy-8';
import { Analogy9 } from './analogy-9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { M1_1 } from './m-1-1';
import { M1_2 } from './m-1-2';
import { M10_1 } from './m-10-1';
import { M10_2 } from './m-10-2';
import { M2_1 } from './m-2-1';
import { M2_2 } from './m-2-2';
import { M3_1 } from './m-3-1';
import { M3_2 } from './m-3-2';
import { M4_1 } from './m-4-1';
import { M5_1 } from './m-5-1';
import { M6_1 } from './m-6-1';
import { M7_1 } from './m-7-1';
import { M8_1 } from './m-8-1';
import { M9_1 } from './m-9-1';
import { M9_2 } from './m-9-2';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['analogy-1'] = Analogy1;
widgetRegistry['analogy-10'] = Analogy10;
widgetRegistry['analogy-2'] = Analogy2;
widgetRegistry['analogy-3'] = Analogy3;
widgetRegistry['analogy-4'] = Analogy4;
widgetRegistry['analogy-5'] = Analogy5;
widgetRegistry['analogy-6'] = Analogy6;
widgetRegistry['analogy-7'] = Analogy7;
widgetRegistry['analogy-8'] = Analogy8;
widgetRegistry['analogy-9'] = Analogy9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['m-1-1'] = M1_1;
widgetRegistry['m-1-2'] = M1_2;
widgetRegistry['m-10-1'] = M10_1;
widgetRegistry['m-10-2'] = M10_2;
widgetRegistry['m-2-1'] = M2_1;
widgetRegistry['m-2-2'] = M2_2;
widgetRegistry['m-3-1'] = M3_1;
widgetRegistry['m-3-2'] = M3_2;
widgetRegistry['m-4-1'] = M4_1;
widgetRegistry['m-5-1'] = M5_1;
widgetRegistry['m-6-1'] = M6_1;
widgetRegistry['m-7-1'] = M7_1;
widgetRegistry['m-8-1'] = M8_1;
widgetRegistry['m-9-1'] = M9_1;
widgetRegistry['m-9-2'] = M9_2;
