import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ch1Analogy } from './ch1-analogy';
import { Ch1Ego } from './ch1-ego';
import { Ch10Analogy } from './ch10-analogy';
import { Ch10Demos } from './ch10-demos';
import { Ch10Race } from './ch10-race';
import { Ch2Analogy } from './ch2-analogy';
import { Ch2Pixelray } from './ch2-pixelray';
import { Ch3Analogy } from './ch3-analogy';
import { Ch3Match } from './ch3-match';
import { Ch3Pointmaps } from './ch3-pointmaps';
import { Ch4Analogy } from './ch4-analogy';
import { Ch4Residual } from './ch4-residual';
import { Ch5Analogy } from './ch5-analogy';
import { Ch5Anchordiff } from './ch5-anchordiff';
import { Ch5Ropeswitch } from './ch5-ropeswitch';
import { Ch6Analogy } from './ch6-analogy';
import { Ch6DualLatent } from './ch6-duallatent';
import { Ch7Analogy } from './ch7-analogy';
import { Ch7Lora } from './ch7-lora';
import { Ch8Analogy } from './ch8-analogy';
import { Ch8Arch } from './ch8-arch';
import { Ch8Layers } from './ch8-layers';
import { Ch9Analogy } from './ch9-analogy';
import { Ch9Longvideo } from './ch9-longvideo';
import { Ch9Stride } from './ch9-stride';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ch1-analogy'] = Ch1Analogy;
widgetRegistry['ch1-ego'] = Ch1Ego;
widgetRegistry['ch10-analogy'] = Ch10Analogy;
widgetRegistry['ch10-demos'] = Ch10Demos;
widgetRegistry['ch10-race'] = Ch10Race;
widgetRegistry['ch2-analogy'] = Ch2Analogy;
widgetRegistry['ch2-pixelray'] = Ch2Pixelray;
widgetRegistry['ch3-analogy'] = Ch3Analogy;
widgetRegistry['ch3-match'] = Ch3Match;
widgetRegistry['ch3-pointmaps'] = Ch3Pointmaps;
widgetRegistry['ch4-analogy'] = Ch4Analogy;
widgetRegistry['ch4-residual'] = Ch4Residual;
widgetRegistry['ch5-analogy'] = Ch5Analogy;
widgetRegistry['ch5-anchordiff'] = Ch5Anchordiff;
widgetRegistry['ch5-ropeswitch'] = Ch5Ropeswitch;
widgetRegistry['ch6-analogy'] = Ch6Analogy;
widgetRegistry['ch6-duallatent'] = Ch6DualLatent;
widgetRegistry['ch7-analogy'] = Ch7Analogy;
widgetRegistry['ch7-lora'] = Ch7Lora;
widgetRegistry['ch8-analogy'] = Ch8Analogy;
widgetRegistry['ch8-arch'] = Ch8Arch;
widgetRegistry['ch8-layers'] = Ch8Layers;
widgetRegistry['ch9-analogy'] = Ch9Analogy;
widgetRegistry['ch9-longvideo'] = Ch9Longvideo;
widgetRegistry['ch9-stride'] = Ch9Stride;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
