import {Flow,HeadPhase,Landscape,MaskLab,PairedResults} from './extras';
import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { WidgetAblation } from './ablation';
import { WidgetAnalogy } from './analogy';
import { WidgetBackground } from './background';
import { WidgetCache } from './cache';
import { WidgetClassify } from './classify';
import { WidgetCleanheads } from './cleanheads';
import { WidgetFactorial } from './factorial';
import { WidgetHeads } from './heads';
import { WidgetHeroNew } from './hero-new';
import { WidgetHeroOld } from './hero-old';
import { BirdKit } from './kit';
import { LabsRoot } from './labs';
import { MathRoot } from './math';
import { WidgetNce } from './nce';
import { WidgetNegatives } from './negatives';
import { WidgetNetwork } from './network';
import { WidgetPool } from './pool';
import { WidgetQuiz } from './quiz';
import { WidgetRefine } from './refine';
import { WidgetResults } from './results';
import { WidgetRoutes } from './routes';
import { WidgetShape } from './shape';
import { WidgetSpaces } from './spaces';
import { WidgetTrain } from './train';
import { WidgetUpsample } from './upsample';
import { WidgetWarp } from './warp';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ablation'] = WidgetAblation;
widgetRegistry['analogy'] = WidgetAnalogy;
widgetRegistry['background'] = WidgetBackground;
widgetRegistry['cache'] = WidgetCache;
widgetRegistry['classify'] = WidgetClassify;
widgetRegistry['cleanheads'] = WidgetCleanheads;
widgetRegistry['factorial'] = WidgetFactorial;
widgetRegistry['heads'] = WidgetHeads;
widgetRegistry['hero-new'] = WidgetHeroNew;
widgetRegistry['hero-old'] = WidgetHeroOld;
widgetRegistry['kit'] = BirdKit;
widgetRegistry['labs'] = LabsRoot;
widgetRegistry['math'] = MathRoot;
widgetRegistry['nce'] = WidgetNce;
widgetRegistry['negatives'] = WidgetNegatives;
widgetRegistry['network'] = WidgetNetwork;
widgetRegistry['pool'] = WidgetPool;
widgetRegistry['quiz'] = WidgetQuiz;
widgetRegistry['refine'] = WidgetRefine;
widgetRegistry['results'] = WidgetResults;
widgetRegistry['routes'] = WidgetRoutes;
widgetRegistry['shape'] = WidgetShape;
widgetRegistry['spaces'] = WidgetSpaces;
widgetRegistry['train'] = WidgetTrain;
widgetRegistry['upsample'] = WidgetUpsample;
widgetRegistry['warp'] = WidgetWarp;
widgetRegistry['flow'] = Flow;
widgetRegistry['phase'] = HeadPhase;
widgetRegistry['landscape'] = Landscape;
widgetRegistry['masklab'] = MaskLab;
widgetRegistry['paired'] = PairedResults;
