import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { A1Scene } from './a1-scene';
import { A10Scene } from './a10-scene';
import { A2Scene } from './a2-scene';
import { A3Scene } from './a3-scene';
import { A4Scene } from './a4-scene';
import { A5Scene } from './a5-scene';
import { A6Scene } from './a6-scene';
import { A7Scene } from './a7-scene';
import { A8Scene } from './a8-scene';
import { A9Scene } from './a9-scene';
import { C1CaseStudy } from './c1-case-study';
import { C1MemoryLoop } from './c1-memory-loop';
import { C1ParadigmBars } from './c1-paradigm-bars';
import { C1RetrievalPlateau } from './c1-retrieval-plateau';
import { C10ResultRace } from './c10-result-race';
import { C2DualExtract } from './c2-dual-extract';
import { C2EventBinding } from './c2-event-binding';
import { C2TemporalAnchor } from './c2-temporal-anchor';
import { C3AnchorRecall } from './c3-anchor-recall';
import { C3CrossEvent } from './c3-cross-event';
import { C4DualRecall } from './c4-dual-recall';
import { C5Results } from './c5-results';
import { C6Limits } from './c6-limits';
import { C4SeedK } from './c4-seed-k';
import { C5TriggerWindow } from './c5-trigger-window';
import { C6DualCircuit } from './c6-dual-circuit';
import { C7GroundingSlider } from './c7-grounding-slider';
import { C7LinkAudit } from './c7-link-audit';
import { C8FlowSteps } from './c8-flow-steps';
import { C8SystemMap } from './c8-system-map';
import { C9BatchWindow } from './c9-batch-window';
import { HeroContrast } from './hero-contrast';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['a1-scene'] = A1Scene;
widgetRegistry['a10-scene'] = A10Scene;
widgetRegistry['a2-scene'] = A2Scene;
widgetRegistry['a3-scene'] = A3Scene;
widgetRegistry['a4-scene'] = A4Scene;
widgetRegistry['a5-scene'] = A5Scene;
widgetRegistry['a6-scene'] = A6Scene;
widgetRegistry['a7-scene'] = A7Scene;
widgetRegistry['a8-scene'] = A8Scene;
widgetRegistry['a9-scene'] = A9Scene;
widgetRegistry['c1-case-study'] = C1CaseStudy;
widgetRegistry['c1-memory-loop'] = C1MemoryLoop;
widgetRegistry['c1-paradigm-bars'] = C1ParadigmBars;
widgetRegistry['c1-retrieval-plateau'] = C1RetrievalPlateau;
widgetRegistry['c10-result-race'] = C10ResultRace;
widgetRegistry['c2-dual-extract'] = C2DualExtract;
widgetRegistry['c2-event-binding'] = C2EventBinding;
widgetRegistry['c2-temporal-anchor'] = C2TemporalAnchor;
widgetRegistry['c3-anchor-recall'] = C3AnchorRecall;
widgetRegistry['c3-cross-event'] = C3CrossEvent;
widgetRegistry['c4-dual-recall'] = C4DualRecall;
widgetRegistry['c5-results'] = C5Results;
widgetRegistry['c6-limits'] = C6Limits;
widgetRegistry['c4-seed-k'] = C4SeedK;
widgetRegistry['c5-trigger-window'] = C5TriggerWindow;
widgetRegistry['c6-dual-circuit'] = C6DualCircuit;
widgetRegistry['c7-grounding-slider'] = C7GroundingSlider;
widgetRegistry['c7-link-audit'] = C7LinkAudit;
widgetRegistry['c8-flow-steps'] = C8FlowSteps;
widgetRegistry['c8-system-map'] = C8SystemMap;
widgetRegistry['c9-batch-window'] = C9BatchWindow;
widgetRegistry['hero-contrast'] = HeroContrast;
