import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { HeroNew } from './c0new';
import { HeroOld } from './c0old';
import { Ch10Analogy } from './c10ana';
import { Ch10Cases } from './c10cases';
import { Ch10Race } from './c10race';
import { Ch1Analogy } from './c1ana';
import { Ch1Context } from './c1ctx';
import { Ch2Analogy } from './c2ana';
import { Ch2Loop } from './c2loop';
import { Ch2Roles } from './c2roles';
import { Ch3Analogy } from './c3ana';
import { Ch3Edge } from './c3edge';
import { Ch4Analogy } from './c4ana';
import { Ch4State } from './c4state';
import { Ch5Analogy } from './c5ana';
import { Ch5Grant } from './c5grant';
import { Ch6Analogy } from './c6ana';
import { Ch6Space } from './c6space';
import { Ch7Analogy } from './c7ana';
import { Ch7Trail } from './c7trail';
import { Ch8Analogy } from './c8ana';
import { Ch8Arch } from './c8arch';
import { Ch8Turn } from './c8turn';
import { Ch9Analogy } from './c9ana';
import { Ch9Check } from './c9check';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['c0new'] = HeroNew;
widgetRegistry['c0old'] = HeroOld;
widgetRegistry['c10ana'] = Ch10Analogy;
widgetRegistry['c10cases'] = Ch10Cases;
widgetRegistry['c10race'] = Ch10Race;
widgetRegistry['c1ana'] = Ch1Analogy;
widgetRegistry['c1ctx'] = Ch1Context;
widgetRegistry['c2ana'] = Ch2Analogy;
widgetRegistry['c2loop'] = Ch2Loop;
widgetRegistry['c2roles'] = Ch2Roles;
widgetRegistry['c3ana'] = Ch3Analogy;
widgetRegistry['c3edge'] = Ch3Edge;
widgetRegistry['c4ana'] = Ch4Analogy;
widgetRegistry['c4state'] = Ch4State;
widgetRegistry['c5ana'] = Ch5Analogy;
widgetRegistry['c5grant'] = Ch5Grant;
widgetRegistry['c6ana'] = Ch6Analogy;
widgetRegistry['c6space'] = Ch6Space;
widgetRegistry['c7ana'] = Ch7Analogy;
widgetRegistry['c7trail'] = Ch7Trail;
widgetRegistry['c8ana'] = Ch8Analogy;
widgetRegistry['c8arch'] = Ch8Arch;
widgetRegistry['c8turn'] = Ch8Turn;
widgetRegistry['c9ana'] = Ch9Analogy;
widgetRegistry['c9check'] = Ch9Check;
