import React,{useState,useRef,useEffect} from 'react';
import {Scene,Feedback,C,drawDesk,drawPaper,drawPen,drawLabel,line,bar} from './index-kit';
const names=['Cosine','WSD','Cosine＋精选','WSD＋精选'];const values=[35.63,35.75,34.65,38.10];
const conclusion='本次消融中，WSD＋精选为 38.10，四者最高；精选数据并非在两种调度下都提高分数。这组结果提醒我们：学习率节奏和后期数据选择，需要作为联合设计来检验。';
export const IndexRecipe:React.FC=()=>{
 const [progress,setProgress]=useState(0);const [status,setStatus]=useState<'idle'|'running'|'done'>('idle');const [selected,setSelected]=useState([0,1,2,3]);const [message,setMessage]=useState('准备比较同一消融的四种设置。');const [tone,setTone]=useState<'neutral'|'good'|'bad'>('neutral');const root=useRef<HTMLDivElement>(null);const visible=useRef(true);
 useEffect(()=>{const io=new IntersectionObserver(entries=>{visible.current=entries[0]?.isIntersecting??true;});if(root.current)io.observe(root.current);return()=>io.disconnect();},[]);
 useEffect(()=>{if(status!=='running')return;let frame=0,last:number|null=null,elapsed=0;const tick=(time:number)=>{if(visible.current&&last!==null)elapsed+=Math.min(64,time-last);last=time;const p=Math.min(1,elapsed/1500);setProgress(p);if(p===1){setStatus('done');setMessage(conclusion);setTone('good');}else frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[status]);
 const start=()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setProgress(1);setStatus('done');setMessage(conclusion);setTone('good');return;}setProgress(0);setStatus('running');setMessage('四种配置正在按同一尺度展开；过程只是结果动画。');setTone('neutral');};
 const select=(i:number)=>{if(selected.includes(i)&&selected.length===2){setMessage('至少保留两项，才能继续比较。');setTone('bad');return;}const next=selected.includes(i)?selected.filter(v=>v!==i):[...selected,i];setSelected(next);setTone('neutral');if(status==='idle')setMessage('准备比较同一消融的四种设置。');else if(status==='running')setMessage('四种配置正在按同一尺度展开；过程只是结果动画。');else if(next.length===2&&next.includes(0)&&next.includes(2))setMessage('Cosine 加入精选数据后由 35.63 变为 34.65；适应不够只是作者猜想。');else if(next.length===2&&next.includes(1)&&next.includes(3)){setMessage('WSD 加入精选数据后由 35.75 变为 38.10；结论限于这次消融。');setTone('good');}else setMessage('已强调所选配置；四个原始结果仍保留，比较范围没有改变。');};
 return <div ref={root} onKeyDown={e=>{if(e.key.startsWith('Arrow'))e.stopPropagation();}}><Scene label={`四项配置按 0 到 100 相同尺度比较，${status==='done'?'已完成':'等待或正在展开'}；精确结果见下方表格。`} draw={(ctx,w,h)=>{drawDesk(ctx,w,h);drawPaper(ctx,30,40,430,210);drawLabel(ctx,'墨线',45,25);drawLabel(ctx,'均分',550,25);const colors=[C.muted,C.blue,C.support,C.green];values.forEach((v,i)=>{ctx.globalAlpha=selected.includes(i)?1:.25;const y=66+48*i;line(ctx,60,y,410,y);line(ctx,560,y,1000,y);line(ctx,60,y,60+350*v/100*progress,y,colors[i],5);drawPen(ctx,60+350*v/100*progress,y,-.2,colors[i]);bar(ctx,560,y-14,440*v/100*progress,28,colors[i]);ctx.globalAlpha=1;});line(ctx,560,42,560,239,C.text);ctx.font='18px sans-serif';ctx.fillStyle=C.muted;ctx.fillText('0',554,267);ctx.fillText('100',975,267);}}/>
 <div className="ctrl" style={{flexWrap:'wrap'}}>{names.map((n,i)=><button type="button" key={n} aria-pressed={selected.includes(i)} className={selected.includes(i)?'chip selected':'chip'} onClick={()=>select(i)}>{n}</button>)}<button className="chip" type="button" disabled={status==='running'} onClick={start}>{status==='done'?'重新比较':'开始比较'}</button></div>
 <Feedback tone={tone}>{message}</Feedback>
 <div style={{overflowX:'auto'}}><table style={{width:'100%',fontSize:'1rem'}}><caption>§6.5，Figure 6：六项下游均分，越高越好；最后 10% 训练增加精选数据。本消融不是最终发布模型。</caption><thead><tr><th scope="col">配置</th><th scope="col">均分</th></tr></thead><tbody>{names.map((n,i)=><tr key={n} style={{opacity:selected.includes(i)?1:.6}}><th scope="row">{n}</th><td>{values[i].toFixed(2)}</td></tr>)}</tbody></table></div></div>;
};
