import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { Ch1Lighten } from './ch1-lighten';
import { Ch1Stress } from './ch1-stress';
import { Ch10Race } from './ch10-race';
import { Ch2Strides } from './ch2-strides';
import { Ch3OneToOne } from './ch3-onetoone';
import { Ch4Regression } from './ch4-regression';
import { Ch5DualHead } from './ch5-dualhead';
import { Ch6Pipeline } from './ch6-pipeline';
import { Ch7MuSGD } from './ch7-musgd';
import { Ch7Progressive } from './ch7-progressive';
import { Ch8Arch } from './ch8-arch';
import { Ch9Stal } from './ch9-stal';
import { Ch9Tasks } from './ch9-tasks';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['ch1-lighten'] = Ch1Lighten;
widgetRegistry['ch1-stress'] = Ch1Stress;
widgetRegistry['ch10-race'] = Ch10Race;
widgetRegistry['ch2-strides'] = Ch2Strides;
widgetRegistry['ch3-onetoone'] = Ch3OneToOne;
widgetRegistry['ch4-regression'] = Ch4Regression;
widgetRegistry['ch5-dualhead'] = Ch5DualHead;
widgetRegistry['ch6-pipeline'] = Ch6Pipeline;
widgetRegistry['ch7-musgd'] = Ch7MuSGD;
widgetRegistry['ch7-progressive'] = Ch7Progressive;
widgetRegistry['ch8-arch'] = Ch8Arch;
widgetRegistry['ch9-stal'] = Ch9Stal;
widgetRegistry['ch9-tasks'] = Ch9Tasks;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
