import React, { useEffect, useMemo, useRef, useState } from 'react';
import { setupCanvas, observeCanvas, clamp } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const C={bg:'#f5f8f0',light:'#b8c9a7',dark:'#76906a',brown:'#92400e',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#f07e47',purple:'#7c3aed',text:'#21324a',muted:'#68778f',border:'#d7deea'};
type Draw=(c:CanvasRenderingContext2D,w:number,h:number,t:number)=>void;

function Canvas({draw,w=720,h=280,label='CLIP教学示意',onPointerDown,onPointerMove,onPointerUp,tabIndex,onKeyDown}:{draw:Draw;w?:number;h?:number;label?:string;onPointerDown?:React.PointerEventHandler<HTMLCanvasElement>;onPointerMove?:React.PointerEventHandler<HTMLCanvasElement>;onPointerUp?:React.PointerEventHandler<HTMLCanvasElement>;tabIndex?:number;onKeyDown?:React.KeyboardEventHandler<HTMLCanvasElement>}){
 const ref=useRef<HTMLCanvasElement>(null),latest=useRef(draw);latest.current=draw;
 useEffect(()=>{const el=ref.current;if(!el)return;const c=setupCanvas(el,w,h);el.style.width='100%';el.style.height='auto';let id:number|null=null,active=false;
  const tick=(s:number)=>{latest.current(c,w,h,s/1000);el.classList.add('is-ready');if(active)id=requestAnimationFrame(tick)};
  const start=()=>{active=true;if(id===null)id=requestAnimationFrame(tick)};const stop=()=>{active=false;if(id!==null)cancelAnimationFrame(id);id=null};tick(performance.now());const disconnect=observeCanvas(el,start,stop);return()=>{stop();disconnect()};},[w,h]);
 return <canvas ref={ref} width={w} height={h} role="img" aria-label={label} tabIndex={tabIndex} onKeyDown={onKeyDown} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} style={{width:'100%',height:'auto',display:'block',borderRadius:8,touchAction:onPointerDown?'none':'auto',cursor:onPointerDown?'pointer':'auto'}}/>;
}
function clear(c:CanvasRenderingContext2D,w:number,h:number){c.clearRect(0,0,w,h);c.fillStyle=C.bg;c.fillRect(0,0,w,h)}
function line(c:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number,color=C.border,width=2){c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.strokeStyle=color;c.lineWidth=width;c.stroke()}
function txt(c:CanvasRenderingContext2D,s:string|number,x:number,y:number,color=C.text,size=17,align:CanvasTextAlign='left'){c.fillStyle=color;c.font=`${size}px system-ui`;c.textAlign=align;c.fillText(String(s),x,y)}
type PhotoKind='cat'|'dog'|'bird'|'landscape';
type PhotoEffect='photo'|'sketch';
const photoFiles:Record<PhotoKind,string>={cat:'images/jumping-kitten.jpg',dog:'images/running-puppy.jpg',bird:'images/flying-bird.jpg',landscape:'images/mountain-lake.jpg'};
const photoImages:Partial<Record<PhotoKind,HTMLImageElement>>={};
function getPhotoImage(kind:PhotoKind){
 if(typeof Image==='undefined')return;
 if(!photoImages[kind]){const image=new Image();image.decoding='async';image.src=`${import.meta.env.BASE_URL}${photoFiles[kind]}`;photoImages[kind]=image}
 return photoImages[kind];
}
function drawImageCover(c:CanvasRenderingContext2D,image:HTMLImageElement,x:number,y:number,w:number,h:number){
 const sourceRatio=image.naturalWidth/image.naturalHeight,targetRatio=w/h;
 let sx=0,sy=0,sw=image.naturalWidth,sh=image.naturalHeight;
 if(sourceRatio>targetRatio){sw=image.naturalHeight*targetRatio;sx=(image.naturalWidth-sw)/2}else{sh=image.naturalWidth/targetRatio;sy=(image.naturalHeight-sh)/2}
 c.save();c.beginPath();c.rect(x,y,w,h);c.clip();c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(image,sx,sy,sw,sh,x,y,w,h);c.restore();
}
function photo(c:CanvasRenderingContext2D,x:number,y:number,w=110,h=75,color=C.blue,subject:PhotoKind|boolean=false,effect:PhotoEffect='photo'){
 c.save();c.fillStyle=C.light;c.fillRect(x+4,y+5,w,h);c.fillStyle='#fff';c.fillRect(x,y,w,h);c.strokeStyle=C.border;c.lineWidth=1;c.strokeRect(x,y,w,h);
 const kind=subject===true?'cat':subject===false?'landscape':subject;
 const px=x+8,py=y+8,pw=w-16,ph=h-20,image=getPhotoImage(kind);
 if(image?.complete&&image.naturalWidth>0){c.save();if(effect==='sketch')c.filter='grayscale(1) contrast(1.9) brightness(1.15)';drawImageCover(c,image,px,py,pw,ph);c.restore();if(effect==='sketch'){c.globalAlpha=.12;c.fillStyle='#fff';c.fillRect(px,py,pw,ph);c.globalAlpha=1}}else{const gradient=c.createLinearGradient(px,py,px+pw,py+ph);gradient.addColorStop(0,C.bg);gradient.addColorStop(1,color);c.fillStyle=gradient;c.fillRect(px,py,pw,ph)}
 c.restore();
}
function card(c:CanvasRenderingContext2D,x:number,y:number,w=115,h=42,color=C.blue){c.fillStyle='#fff';c.fillRect(x,y,w,h);c.strokeStyle=color;c.lineWidth=2;c.strokeRect(x,y,w,h);line(c,x+13,y+15,x+w-13,y+15,color,2);line(c,x+13,y+28,x+w-35,y+28,C.border,2)}
function arrow(c:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number,color=C.border){const angle=Math.atan2(y2-y1,x2-x1);line(c,x1,y1,x2,y2,color,3);c.fillStyle=color;c.beginPath();c.moveTo(x2,y2);c.lineTo(x2-9*Math.cos(angle-.45),y2-9*Math.sin(angle-.45));c.lineTo(x2-9*Math.cos(angle+.45),y2-9*Math.sin(angle+.45));c.closePath();c.fill()}
function diagramNode(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,title:string,subtitle:string,active:boolean,accent=C.blue){c.save();c.beginPath();c.roundRect(x,y,w,h,9);c.fillStyle=active?'#e9f7ef':'#fff';c.fill();c.strokeStyle=active?C.orange:accent;c.lineWidth=active?3:2;c.stroke();txt(c,title,x+w/2,y+23,active?C.green:C.text,15,'center');txt(c,subtitle,x+w/2,y+43,C.muted,12,'center');c.restore()}
function Buttons({items,value,set}:{items:[string,string][];value:string;set:(v:string)=>void}){return <div className="chip-row">{items.map(([v,l])=><button key={v} className={`chip ${value===v?'selected':''}`} aria-pressed={value===v} onClick={()=>set(v)}>{l}</button>)}</div>}
function StopArrows({children}:{children:React.ReactNode}){return <div onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.stopPropagation()}}>{children}</div>}

function Life({n}:{n:number}){return <Canvas w={560} h={140} label={`照片册生活类比，第${n}章`} draw={(c,w,h,t)=>{clear(c,w,h);const p=(1-Math.cos(t*Math.PI*2/3))/2;c.fillStyle='#fff';c.fillRect(62,16,436,108);c.strokeStyle=C.brown;c.strokeRect(62,16,436,108);line(c,280,16,280,124,C.light,2);
 if(n===1){card(c,285,54,145,42);photo(c,96+90*p,28,125,85,C.blue,true)}
 if(n===2){card(c,365,52,110,42);c.save();c.translate(250,70);c.rotate((1-p)*.45);photo(c,-62,-42,124,84,C.blue,true);c.restore()}
 if(n===3){photo(c,96,28,124,84);card(c,190+130*p,52,120,42)}
 if(n===4){photo(c,125,28,124,84);card(c,292,52,120,42);line(c,274,32,274,52,C.blue,4+12*(1-p))}
 if(n===5){photo(c,105,28,124,84);card(c,270,48,70+105*p,50)}
 if(n===6){photo(c,105,34,105,72);c.fillStyle=C.brown;c.fillRect(340,20+42*p,24,42);c.fillStyle=C.blue;c.fillRect(322,60+42*p,60,12)}
 if(n===7){c.save();c.translate(310,70);c.rotate(.25*(1-p));photo(c,-62,-42,124,84);c.restore()}
 if(n===8){photo(c,130,28,124,84);c.beginPath();c.arc(270+120*p,66,26,0,Math.PI*2);c.strokeStyle=C.blue;c.lineWidth=5;c.stroke();line(c,289+120*p,85,316+120*p,112,C.brown,7)}
 if(n===9){photo(c,160,22,155,98,C.blue,true);card(c,350-75*p,78,105,38,C.red)}
 if(n===10){c.beginPath();c.arc(280,103,58,Math.PI,Math.PI*2);c.strokeStyle=C.border;c.lineWidth=4;c.stroke();c.save();c.translate(280,103);c.rotate(-.85+1.35*p);line(c,0,0,0,-52,C.orange,5);c.restore()}
 }}/>}
export const Analogy1=()=> <Life n={1}/>;export const Analogy2=()=> <Life n={2}/>;export const Analogy3=()=> <Life n={3}/>;export const Analogy4=()=> <Life n={4}/>;export const Analogy5=()=> <Life n={5}/>;export const Analogy6=()=> <Life n={6}/>;export const Analogy7=()=> <Life n={7}/>;export const Analogy8=()=> <Life n={8}/>;export const Analogy9=()=> <Life n={9}/>;export const Analogy10=()=> <Life n={10}/>;
function Hero({good}:{good:boolean}){return <Canvas w={560} h={220} label={good?'候选描述可以替换':'固定标签分类器'} draw={(c,w,h,t)=>{clear(c,w,h);const p=(1-Math.cos(t*Math.PI*2/3))/2;photo(c,55,45,170,125,C.blue,true);card(c,280+45*p,82,140,52,good?C.green:C.red);line(c,55,190,500,190,C.light,2)}}/>}
export const HeroOld=()=> <Hero good={false}/>;export const HeroNew=()=> <Hero good/>;

const datasetRows=[
 {id:'coco',label:'MS-COCO',amount:'约 10 万',unit:'训练照片',value:0.1,detail:'论文 §2.1：MS-COCO 是高质量众包标注数据集，但按现代预训练规模衡量较小，约有 10 万张训练照片。'},
 {id:'vg',label:'Visual Genome',amount:'约 10 万',unit:'训练照片',value:0.1,detail:'论文 §2.1：Visual Genome 同样是高质量众包标注数据集，约有 10 万张训练照片。'},
 {id:'yfcc',label:'YFCC100M',amount:'1 亿',unit:'照片',value:100,detail:'论文 §2.1：YFCC100M 有 1 亿张照片，但文本元数据稀疏且质量不一；只保留英文自然语言标题或描述后，规模缩小约 6 倍至 1500 万张。'},
 {id:'wit',label:'WIT',amount:'4 亿',unit:'图文对',value:400,detail:'论文 §2.1：WebImageText（WIT）从多种公开互联网来源收集 4 亿图文对，用约 50 万个查询覆盖视觉概念，并为近似平衡而让每个查询最多纳入约 2 万对。'},
] as const;
export const ClipDataMain:React.FC<WidgetProps>=()=>{const[selected,setSelected]=useState('wit');const current=datasetRows.find(row=>row.id===selected)!;return <StopArrows><Canvas label="论文数据规模与 WIT 构建比较" draw={(c,w,h)=>{clear(c,w,h);txt(c,'论文 §2.1 的规模比较（柱高使用对数刻度）',28,28,C.text,16);const base=232;datasetRows.forEach((row,i)=>{const x=38+i*170,height=34+(Math.log10(row.value)+1)*42;c.fillStyle=row.id===selected?C.green:C.blue;c.globalAlpha=row.id===selected?1:.52;c.fillRect(x,base-height,116,height);c.globalAlpha=1;c.strokeStyle=row.id===selected?C.orange:C.border;c.lineWidth=row.id===selected?3:1;c.strokeRect(x,base-height,116,height);txt(c,row.amount,x+58,base-height+28,'#fff',16,'center');txt(c,row.label,x+58,255,row.id===selected?C.green:C.text,14,'center')});line(c,25,232,700,232,C.border,2);txt(c,'注意：照片、训练照片与图文对不是同一种统计口径',360,278,C.muted,13,'center')}}/><Buttons items={datasetRows.map(row=>[row.id,row.label] as [string,string])} value={selected} set={setSelected}/><div className="feedback good" aria-live="polite"><b>{current.label} · {current.amount}{current.unit}</b>：{current.detail}</div><p>规模比较只复述论文给出的数量与筛选条件，不能把不同数据集口径直接当作质量排名。CLIP 的结果来自大规模自然语言监督与可扩展对比目标的共同作用，贡献不应简化为只有对比学习。</p></StopArrows>}

export const Clip1Main:React.FC<WidgetProps>=()=>{const[q,setQ]=useState('animal');const data=q==='animal'?[['猫',.82],['狗',.34],['鸟',.17]]:[['跳跃',.76],['睡觉',.23],['进食',.12]];return <StopArrows><Canvas label="同一照片的两套候选描述" draw={(c,w,h)=>{clear(c,w,h);photo(c,32,70,145,105,C.blue,true);txt(c,'固定类别',275,42,C.text,18,'center');txt(c,'可换描述',545,42,C.text,18,'center');[[.82,.34,.17],data.map(x=>Number(x[1]))].forEach((arr,k)=>arr.forEach((v,i)=>{const x=215+k*270,y=72+i*55;c.fillStyle=C.border;c.fillRect(x,y,200,25);c.fillStyle=i===0?C.green:C.blue;c.fillRect(x,y,v*200,25);txt(c,v.toFixed(2),x+207,y+20,C.text,15)}))}}/><Buttons items={[["animal","问动物"],["action","问动作"]]} value={q} set={setQ}/><div className="feedback good" aria-live="polite">{q==='animal'?'现在都在问动物：固定标签与文本候选都指向猫。':'照片没变，问法变了：文本候选选出正在跳跃；固定动物标签仍只能回答猫。'}</div><p><b>示例候选：</b>{data.map(x=>`${x[0]} ${Number(x[1]).toFixed(2)}`).join('；')}。余弦示例分数不是概率，也不是 CLIP 实测输出。</p></StopArrows>}

export const Clip2Main:React.FC<WidgetProps>=()=>{const[theta,setTheta]=useState(60);const drag=useRef(false);const cos=Math.cos(theta*Math.PI/180);const locate=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)*720/r.width,y=(e.clientY-r.top)*280/r.height;setTheta(Math.round(clamp(Math.atan2(145-y,x-200)*180/Math.PI,0,180)))};const feedback=theta===0?'两个单位方向完全一致，余弦相似度为 1。':theta===90?'两个方向垂直，余弦相似度为 0。':theta===180?'两个方向完全相反，余弦相似度为 −1。':theta<90?'方向较接近，余弦相似度为正；它仍不是概率。':'方向背离，余弦相似度为负。';return <StopArrows><Canvas label="拖动文字向量端点探索余弦" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();setTheta(v=>clamp(v+(e.key==='ArrowLeft'?-1:1),0,180))}}} onPointerDown={e=>{drag.current=true;e.currentTarget.setPointerCapture(e.pointerId);locate(e)}} onPointerMove={e=>{if(drag.current)locate(e)}} onPointerUp={()=>drag.current=false} draw={(c,w,h)=>{clear(c,w,h);photo(c,475,68,125,90,C.blue,true);const cx=200,cy=145,r=100;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.strokeStyle=C.border;c.stroke();line(c,cx,cy,cx+r,cy,C.blue,4);const x=cx+r*Math.cos(theta*Math.PI/180),y=cy-r*Math.sin(theta*Math.PI/180);line(c,cx,cy,x,y,C.green,4);c.fillStyle=C.orange;c.beginPath();c.arc(x,y,9,0,Math.PI*2);c.fill();txt(c,'图像',310,152,C.blue);txt(c,'文字',x,y-13,C.green,15,'center');txt(c,cos.toFixed(3),538,206,C.text,25,'center')}}/><div className="ctrl"><label>文字方向角度 <span className="val">{theta}°</span></label><input aria-label="文字方向角度" type="range" min="0" max="180" value={theta} onChange={e=>setTheta(+e.target.value)}/></div><Buttons items={[["0","对齐 0°"],["90","垂直 90°"],["180","相反 180°"]]} value={String(theta)} set={v=>setTheta(+v)}/><div className={`feedback ${theta>90?'bad':theta<90?'good':''}`} aria-live="polite">{feedback}</div></StopArrows>}

export const Clip3Main:React.FC<WidgetProps>=()=>{const[row,setRow]=useState(0);const vals=[[.8,.3,.1],[.2,.7,.2],[.1,.2,.9]],names=['猫','狗','鸟'],subjects:PhotoKind[]=['cat','dog','bird'];return <StopArrows><Canvas label="三对图文的九格相似度矩阵" draw={(c,w,h)=>{clear(c,w,h);names.forEach((_,i)=>photo(c,20,30+i*80,80,58,C.blue,subjects[i]));vals.forEach((a,i)=>a.forEach((v,j)=>{const x=250+j*93,y=35+i*72;c.globalAlpha=i===row?1:.42;c.fillStyle=i===j?C.green:C.blue;c.fillRect(x,y,75,52);txt(c,v.toFixed(1),x+38,y+33,'#fff',17,'center')}));c.globalAlpha=1;txt(c,'原始配对',570,90,C.green);txt(c,'批内错配',570,148,C.blue)}}/><Buttons items={names.map((n,i)=>[String(i),`第${i+1}对：${n}`] as [string,string])} value={String(row)} set={v=>setRow(+v)}/><div className="chip-row"><button className="chip" disabled={row===2} onClick={()=>setRow(v=>v+1)}>下一行</button><button className="chip" onClick={()=>setRow(0)}>重置</button></div><div className="feedback" aria-live="polite">看{names[row]}这一行：{names[row]}图与{names[row]}描述是原始配对，另两项是这批数据里的错配。</div><p>三对数据形成 3 个原始配对和 6 个批内错配；“错配”不等于语义完全无关。论文图 2 中，BoW 目标比描述生成约快 3 倍，改用对比目标又约快 4 倍；这是达到零样本 ImageNet 表现的学习效率，不是推理速度，也不能把差距全归因于单一因素。</p></StopArrows>}

export const Clip4Main:React.FC<WidgetProps>=()=>{const[tau,setTau]=useState(1);const ps=useMemo(()=>{const a=[.8,.4,.1].map(v=>Math.exp(v/tau)),s=a.reduce((x,y)=>x+y);return a.map(v=>v/s)},[tau]);const loss=-Math.log(ps[0]);return <StopArrows><Canvas label="温度、概率和照片夹联动" draw={(c,w,h)=>{clear(c,w,h);photo(c,25,72,120,92,C.blue,true);card(c,160,92,100,42);line(c,150,64,150,92,C.brown,4+18*tau);ps.forEach((p,i)=>{const y=55+i*65;c.fillStyle=C.border;c.fillRect(310,y,300,28);c.fillStyle=i===0?C.green:C.blue;c.fillRect(310,y,p*300,28);txt(c,(p*100).toFixed(1)+'%',620,y+21,C.text,15)});txt(c,'配对概率',460,32,C.text,18,'center');txt(c,loss.toFixed(3),665,230,C.orange,24,'center')}}/><div className="ctrl"><label>温度 τ <span className="val">{tau.toFixed(2)}</span></label><input type="range" min="0.1" max="1" step="0.05" value={tau} onChange={e=>setTau(+e.target.value)}/></div><div className="feedback good">{tau<=.11?'分布很尖锐；这不表示模型已经训练得更好。':tau>=.99?'温度为 1，概率较平缓；A 仍排第一。':'降低温度让最高分获得更多概率；A、B、C 的排序没有改变。'} 单行交叉熵 {loss.toFixed(3)}。</div></StopArrows>}

export const Clip5Main:React.FC<WidgetProps>=()=>{const[mode,setMode]=useState('bare');const sets:{[k:string]:[string,number][]}={bare:[['猫',.72],['狗',.38],['汽车',.12]],photo:[['一张猫的照片',.76],['一张狗的照片',.42],['一张汽车的照片',.16]],missing:[['一张狗的照片',.42],['一张汽车的照片',.16],['一张鸟的照片',.28]]};const d=sets[mode],winner=d.reduce((a,b)=>a[1]>b[1]?a:b);return <StopArrows><Canvas label="候选描述改变答案范围" draw={(c,w,h)=>{clear(c,w,h);photo(c,25,65,130,95,C.blue,true);d.forEach((v,i)=>{const y=55+i*64;c.fillStyle=C.border;c.fillRect(235,y,390,28);c.fillStyle=v===winner?C.green:C.blue;c.fillRect(235,y,(v[1]+1)/2*390,28);txt(c,String(i+1),210,y+21,C.muted,16,'center');txt(c,v[1].toFixed(2),640,y+21,C.text,15)});txt(c,'候选比较',430,30,C.text,18,'center')}}/><Buttons items={[["bare","裸类名"],["photo","照片模板"],["missing","缺少正确类别"]]} value={mode} set={setMode}/><div className={`feedback ${mode==='missing'?'bad':'good'}`}>{mode==='missing'?`候选中没有“猫”，所以示例选出“${winner[0]}”（${winner[1].toFixed(2)}）。取最大值不会自动发现缺失的正确类别。`:`最高分是“${winner[0]}”（${winner[1].toFixed(2)}）。这里是人为设定的教学分数；换提示不保证真实任务提升。`}</div><p>{d.map(x=>`${x[0]} ${x[1].toFixed(2)}`).join('；')}。分数不是准确率或置信度，本模块没有运行真实编码器。</p></StopArrows>}

const promptTemplates=['“猫”','“一张猫的照片”','“一张宠物猫的照片”'];
const promptVectors=[[.86,.51],[.78,.63],[.90,.38]];
export const ClipPromptEnsemble:React.FC<WidgetProps>=()=>{const[count,setCount]=useState(3);const classVector=useMemo(()=>{const selected=promptVectors.slice(0,count).map(([x,y])=>{const n=Math.hypot(x,y);return [x/n,y/n]});const mx=selected.reduce((sum,v)=>sum+v[0],0)/count,my=selected.reduce((sum,v)=>sum+v[1],0)/count,n=Math.hypot(mx,my);return [mx/n,my/n]},[count]);return <StopArrows><Canvas h={300} label="多个提示模板编码并组合为一个类别表示" draw={(c,w,h)=>{clear(c,w,h);txt(c,'同一个类别：猫',30,28,C.text,16);txt(c,'分别编码',315,28,C.text,16,'center');txt(c,'组合为类别表示',590,28,C.text,16,'center');promptTemplates.forEach((template,i)=>{const y=52+i*72,active=i<count;c.save();c.globalAlpha=active?1:.28;c.beginPath();c.roundRect(28,y,218,48,8);c.fillStyle='#fff';c.fill();c.strokeStyle=active?C.purple:C.border;c.lineWidth=2;c.stroke();txt(c,template,137,y+29,active?C.purple:C.muted,14,'center');arrow(c,250,y+24,314,y+24,active?C.purple:C.border);c.fillStyle=active?C.blue:C.border;c.beginPath();c.arc(345,y+24,16,0,Math.PI*2);c.fill();arrow(c,365,y+24,510,150,active?C.blue:C.border);c.restore()});c.save();c.beginPath();c.arc(578,150,62,0,Math.PI*2);c.fillStyle='#e9f7ef';c.fill();c.strokeStyle=C.green;c.lineWidth=3;c.stroke();txt(c,'类别向量',578,142,C.green,16,'center');txt(c,`(${classVector[0].toFixed(2)}, ${classVector[1].toFixed(2)})`,578,170,C.text,15,'center');c.restore();txt(c,`K = ${count}`,578,244,C.orange,18,'center');txt(c,'归一化后均值（教学实现）',578,270,C.muted,13,'center')}}/><Buttons items={[["1","1 个模板"],["2","2 个模板"],["3","3 个模板"]]} value={String(count)} set={v=>setCount(+v)}/><div className="feedback good" aria-live="polite">当前先编码 {count} 个描述，再用归一化后均值演示怎样得到一个“猫”的类别表示。模板数量改变时，组合后的教学向量会同步变化。</div><p>论文 §2.5 明确实验了文本 prompt，并集成多个模板以提升表现。本交互中的中文模板、二维 embedding、组合方式和显示数值均为教学示例，不是论文逐项给出的模板或 CLIP 实测输出。</p></StopArrows>}

export const Clip6Main:React.FC<WidgetProps>=()=>{const[step,setStep]=useState(0);const f=['三条候选描述对应三个单位文本向量。候选不变时，这组向量可以复用。','照片的示例向量是 (0.80, 0.60)，长度为 1；这里没有运行真实编码器。','点积得到 0.80、0.60、−0.80；单位向量的点积就是余弦相似度。','最高分为 0.80，选择“一张猫的照片”；没有用目标任务标签拟合分类头。'];return <StopArrows><Canvas label="零样本推理四步" draw={(c,w,h)=>{clear(c,w,h);const xs=[28,200,382,570];xs.forEach((x,i)=>{c.fillStyle=i===step?C.green:C.border;c.fillRect(x,85,i===3?120:135,95);txt(c,String(i+1),x+(i===3?60:68),140,i===step?'#fff':C.text,30,'center');if(i<3)line(c,x+140,133,x+168,133,i<step?C.green:C.border,4)});txt(c,'候选缓存',95,55,C.text,16,'center');txt(c,'相似度',630,55,C.text,16,'center')}}/><Buttons items={[["0","候选向量"],["1","图像向量"],["2","计算余弦"],["3","选择答案"]]} value={String(step)} set={v=>setStep(+v)}/><div className="chip-row"><button className="chip" disabled={step===0} onClick={()=>setStep(s=>s-1)}>上一步</button><button className="chip" disabled={step===3} onClick={()=>setStep(s=>s+1)}>下一步</button><button className="chip" onClick={()=>setStep(0)}>重置</button></div><div className="feedback good">{f[step]}</div><p>教学向量：v₁=(1,0)，v₂=(0,1)，v₃=(−1,0)，u=(0.8,0.6)。论文图 5 在 20 个每类至少 16 例的数据集上报告：零样本平均表现约等于同一 CLIP 特征的 4-shot 逻辑回归；后者使用标签，不能称为零样本。</p></StopArrows>}

function softmax(a:number[]){const m=Math.max(...a),e=a.map(v=>Math.exp(v-m)),s=e.reduce((x,y)=>x+y);return e.map(v=>v/s)}
export const Clip7Main:React.FC<WidgetProps>=()=>{const[step,setStep]=useState(0);const a=[[1,.7071,-.7071],[.5,.9659,.2588],[-.5,.2588,.9659]],rows=a.map(softmax),cols=a[0].map((_,j)=>softmax(a.map(r=>r[j])));const lr=-rows.reduce((s,r,i)=>s+Math.log(r[i]),0)/3,lc=-cols.reduce((s,col,i)=>s+Math.log(col[i]),0)/3,avg=(lr+lc)/2;const shown=step===1?rows:step===2?a.map((_,i)=>cols.map(col=>col[i])):a;const feedback=['绿色边框表示原始图文配对；当前是有效单位向量的余弦矩阵。',`按行从文字中选择：平均交叉熵 ${lr.toFixed(3)}。`,`按列从图像中选择：平均交叉熵 ${lc.toFixed(3)}。`,`两方向损失平均为 ${avg.toFixed(3)}；这里没有更新模型参数。`][step];return <StopArrows><Canvas label="双向对比损失矩阵" draw={(c,w,h)=>{clear(c,w,h);shown.forEach((r,i)=>r.forEach((v,j)=>{const x=70+j*100,y=38+i*68;c.fillStyle=i===j?C.green:C.blue;c.globalAlpha=.28+.7*(step===0?(v+1)/2:v);c.fillRect(x,y,78,48);c.globalAlpha=1;txt(c,v.toFixed(3),x+39,y+30,C.text,14,'center')}));txt(c,'原始配对',450,80,C.green);txt(c,step===3?avg.toFixed(3):step===1?lr.toFixed(3):step===2?lc.toFixed(3):'N×N',550,150,C.orange,30,'center');txt(c,'双向平均',550,185,C.text,16,'center')}}/><Buttons items={[["0","余弦矩阵"],["1","按行匹配"],["2","按列匹配"],["3","平均损失"]]} value={String(step)} set={v=>setStep(+v)}/><div className="feedback">{feedback}</div><p>该三组二维单位向量和所有数值均为可复算的教学示例，不是 CLIP 实测输出。非对角项是批内错配，但可能语义相近。</p></StopArrows>}

const archItems=[['image','图像编码器','把一批图像编码为 N×dᵢ 特征；此时不要求与文本特征同宽。'],['text','文本编码器','把一批描述编码为 N×dₜ 特征；基础配置为 12 层、512 宽、8 头。'],['projection','线性投影','图像和文本各用一个线性投影，把特征变为相同的 N×dₑ。'],['norm','L2 归一化','逐行归一化后得到单位向量 uᵢ 与 vⱼ，内积等于余弦相似度。'],['score','相似度矩阵','每个图像向量与每个文本向量比较，形成 N×N 分数矩阵。']];
export const Clip8Main:React.FC<WidgetProps>=()=>{const[sel,setSel]=useState('image');const pick=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)*720/r.width,y=(e.clientY-r.top)*280/r.height;setSel(x<255?(y<140?'image':'text'):x<395?'projection':x<535?'norm':'score')};const item=archItems.find(x=>x[0]===sel)!;return <StopArrows><Canvas label="CLIP 双编码器：图像和文本分别编码、投影、归一化，再形成相似度矩阵" tabIndex={0} onPointerDown={pick} onKeyDown={e=>{const i=archItems.findIndex(x=>x[0]===sel);if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();e.stopPropagation();setSel(archItems[clamp(i+(e.key==='ArrowRight'?1:-1),0,4)][0])}}} draw={(c,w,h)=>{clear(c,w,h);txt(c,'两条独立路径',24,24,C.text,15);txt(c,'投影到共同空间',280,24,C.text,15);txt(c,'两两比较',585,24,C.text,15);
 photo(c,20,48,82,58,C.blue,'cat');txt(c,'图像 Iᵢ',61,122,C.blue,13,'center');
 c.save();c.beginPath();c.roundRect(20,176,82,54,8);c.fillStyle='#fff';c.fill();c.strokeStyle=C.purple;c.lineWidth=2;c.stroke();txt(c,'“一只猫”',61,207,C.purple,14,'center');c.restore();txt(c,'文本 Tⱼ',61,249,C.purple,13,'center');
 diagramNode(c,128,49,112,54,'图像编码器','N×dᵢ',sel==='image',C.blue);diagramNode(c,128,177,112,54,'文本编码器','N×dₜ',sel==='text',C.purple);
 diagramNode(c,276,49,102,54,'线性投影','N×dₑ',sel==='projection',C.blue);diagramNode(c,276,177,102,54,'线性投影','N×dₑ',sel==='projection',C.purple);
 diagramNode(c,414,49,102,54,'L2 归一化','单位向量 uᵢ',sel==='norm',C.blue);diagramNode(c,414,177,102,54,'L2 归一化','单位向量 vⱼ',sel==='norm',C.purple);
 arrow(c,104,76,124,76,C.blue);arrow(c,240,76,272,76,C.blue);arrow(c,378,76,410,76,C.blue);arrow(c,104,204,124,204,C.purple);arrow(c,240,204,272,204,C.purple);arrow(c,378,204,410,204,C.purple);
 arrow(c,516,76,564,111,C.blue);arrow(c,516,204,564,169,C.purple);
 c.save();c.beginPath();c.roundRect(568,64,128,152,11);c.fillStyle=sel==='score'?'#e9f7ef':'#fff';c.fill();c.strokeStyle=sel==='score'?C.orange:C.green;c.lineWidth=sel==='score'?3:2;c.stroke();txt(c,'相似度矩阵',632,88,sel==='score'?C.green:C.text,15,'center');for(let i=0;i<3;i++)for(let j=0;j<3;j++){c.fillStyle=i===j?C.green:'#dce5ef';c.fillRect(600+j*22,105+i*22,18,18)}txt(c,'N×N',632,194,C.text,16,'center');c.restore();
 }}/><Buttons items={archItems.map(x=>[x[0],x[1]] as [string,string])} value={sel} set={setSel}/><div className="feedback good">{item[2]}</div><p>图像路径：Iᵢ → N×dᵢ → N×dₑ → uᵢ；文本路径：Tⱼ → N×dₜ → N×dₑ → vⱼ。最后计算全部 uᵢ·vⱼ，得到 N×N 相似度矩阵。</p></StopArrows>}

export const Clip8Variant:React.FC<WidgetProps>=()=>{const[family,setFamily]=useState('resnet');const active=family==='resnet';return <StopArrows><Canvas h={320} label="图像编码器二选一：改进 ResNet 或 Vision Transformer，二者都输出图像特征" draw={(c,w,h)=>{clear(c,w,h);txt(c,'同一张图片',28,27,C.text,16);txt(c,'图像编码器二选一',215,27,C.text,16);txt(c,'统一输出接口',550,27,C.text,16);
 photo(c,25,111,105,78,C.blue,'cat');txt(c,'输入图像 Iᵢ',77,211,C.blue,14,'center');
 arrow(c,132,150,181,92,C.blue);arrow(c,132,150,181,232,C.purple);
 c.save();c.globalAlpha=active?1:.58;c.beginPath();c.roundRect(184,41,238,105,12);c.fillStyle=active?'#e9f7ef':'#fff';c.fill();c.strokeStyle=active?C.orange:C.blue;c.lineWidth=active?3:2;c.stroke();txt(c,'改进 ResNet',303,66,active?C.green:C.text,17,'center');for(let i=0;i<3;i++){c.strokeStyle=C.blue;c.lineWidth=2;c.strokeRect(205+i*8,82+i*5,54-i*8,42-i*7)}arrow(c,269,105,300,105,C.blue);c.beginPath();c.roundRect(305,83,94,44,7);c.fillStyle='#f3f7fb';c.fill();c.strokeStyle=C.blue;c.stroke();txt(c,'残差卷积',352,101,C.text,12,'center');txt(c,'Attention Pool',352,119,C.blue,11,'center');c.restore();
 c.save();c.globalAlpha=active?.58:1;c.beginPath();c.roundRect(184,174,238,105,12);c.fillStyle=!active?'#f3efff':'#fff';c.fill();c.strokeStyle=!active?C.orange:C.purple;c.lineWidth=!active?3:2;c.stroke();txt(c,'Vision Transformer',303,199,!active?C.purple:C.text,17,'center');for(let i=0;i<6;i++){c.fillStyle=i%2?C.purple:C.blue;c.fillRect(207+(i%3)*18,216+Math.floor(i/3)*18,14,14)}arrow(c,266,234,300,234,C.purple);c.beginPath();c.roundRect(305,212,94,44,7);c.fillStyle='#f7f3ff';c.fill();c.strokeStyle=C.purple;c.stroke();txt(c,'图像分块',352,230,C.text,12,'center');txt(c,'Transformer',352,248,C.purple,11,'center');c.restore();
 arrow(c,423,94,530,130,active?C.blue:C.border);arrow(c,423,226,530,188,!active?C.purple:C.border);
 c.save();c.beginPath();c.roundRect(535,102,160,116,12);c.fillStyle='#fff';c.fill();c.strokeStyle=C.green;c.lineWidth=3;c.stroke();txt(c,'图像特征',615,132,C.green,17,'center');txt(c,'N×dᵢ',615,163,C.text,24,'center');line(c,558,177,672,177,C.border,1);txt(c,'下一步：线性投影',615,201,C.muted,12,'center');c.restore();
 txt(c,'两种家族不会串联；选其中一种作为图像编码器。',360,307,C.muted,14,'center');
 }}/><Buttons items={[["resnet","改进 ResNet"],["vit","Vision Transformer"]]} value={family} set={setFamily}/><div className="feedback good">{active?'当前选择改进 ResNet：残差卷积逐层聚合视觉模式，最后用 attention pooling 汇成一条图像特征。输出 N×dᵢ 后，再进入线性投影。':'当前选择 Vision Transformer：先把图像切成 patch token，再由 Transformer 聚合。输出同样是 N×dᵢ，之后走相同的线性投影。'}</div><p>论文训练 5 个 ResNet 与 3 个 ViT；这是两组备选图像编码器，不是前后串联，也不是速度或准确率测量。ViT-L/14 额外以 336px 训练一轮。</p></StopArrows>}

export const Clip9Main:React.FC<WidgetProps>=()=>{const[task,setTask]=useState('cars'),[done,setDone]=useState(false);const d:{[k:string]:[string,number,string]}={cars:['StanfordCars',28.9,'汽车分类'],food:['Food101',22.5,'食物分类'],eurosat:['EuroSAT',-37.1,'卫星场景'],kitti:['KITTI Distance',-34,'距离判断'],clevr:['CLEVRCounts',-18.2,'物体计数']};const cur=d[task];return <StopArrows><Canvas label="外观示意与任务分数差" draw={(c,w,h,t)=>{clear(c,w,h);photo(c,55,38,190,130,C.blue);photo(c,475,38,190,130,C.blue,'landscape',done?'sketch':'photo');const zero=360,dx=cur[1]/40*230;line(c,130,235,590,235,C.border,3);line(c,zero,215,zero,255,C.text,2);c.fillStyle=cur[1]>=0?C.green:C.red;c.fillRect(Math.min(zero,zero+dx),222,Math.abs(dx),26);txt(c,'照片',150,195,C.blue,17,'center');txt(c,done?'素描':'待转换',570,195,C.muted,17,'center')}}/><div className="chip-row"><button className="chip" onClick={()=>setDone(true)}>开始比较</button><button className="chip" onClick={()=>{setDone(false);setTask('cars')}}>重置</button></div><Buttons items={Object.entries(d).map(([k,v])=>[k,v[0]] as [string,string])} value={task} set={setTask}/><div className={`feedback ${cur[1]>=0?'good':'bad'}`}>{done?'右侧已变为高对比灰度素描示意；页面没有运行识别模型。 ':''}{cur[0]}：零样本 CLIP 比监督 ResNet50 特征线性分类器{cur[1]>=0?'高':'低'} {Math.abs(cur[1]).toFixed(1)} 个百分点，比较的是{cur[2]}任务。</div><p>论文图 4 中 CLIP 在 27 个数据集的 16 个上获胜。各任务指标应分别解释，不能把外观示意、跨任务迁移和开放集能力混为一谈。</p></StopArrows>}

const shift=[['ImageNet',76.2,76.2],['ImageNetV2',64.3,70.1],['ImageNet-R',37.7,88.9],['ObjectNet',32.6,72.3],['Sketch',25.2,60.2],['ImageNet-A',2.7,77.1]] as const;
export const Clip10Main:React.FC<WidgetProps>=()=>{const[shown,setShown]=useState(false);return <StopArrows><Canvas w={1080} label="Figure 7自然分布偏移结果" draw={(c,w,h,t)=>{clear(c,w,h);line(c,55,235,1045,235,C.text,2);shift.forEach((r,i)=>{const x=90+i*160,p=shown?1:0;c.fillStyle=C.blue;c.fillRect(x,235-r[1]*1.9*p,42,r[1]*1.9*p);c.fillStyle=C.green;c.fillRect(x+48,235-r[2]*1.9*p,42,r[2]*1.9*p);txt(c,String(i+1),x+45,260,C.text,15,'center');if(shown){txt(c,r[1].toFixed(1),x+21,225-r[1]*1.9,C.blue,13,'center');txt(c,r[2].toFixed(1),x+69,225-r[2]*1.9,C.green,13,'center')}});txt(c,'准确率',25,35,C.text,17);txt(c,'ResNet101 / CLIP',920,35,C.text,16,'center')}}/><div className="chip-row"><button className="chip" onClick={()=>setShown(true)}>显示结果</button><button className="chip" onClick={()=>{setShown(false);requestAnimationFrame(()=>setShown(true))}}>重播</button></div><div className="feedback good">{shown?'ImageNet 均为 76.2%；其余五组中 CLIP 更高。结论仅适用于图 7 的数据集及类别映射协议。':'表中已列出原文数值；柱形会从共同的 0–100% 纵轴展开。'}</div><table className="paper"><caption>Figure 7：自然分布偏移下的准确率（%）</caption><thead><tr><th>索引</th><th>数据集</th><th>ResNet101</th><th>零样本 CLIP</th><th>差值（百分点）</th></tr></thead><tbody>{shift.map((r,i)=><tr key={r[0]}><td>{i+1}</td><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{(r[2]-r[1]).toFixed(1)}</td></tr>)}</tbody></table><p>两者 ImageNet 起点均为 76.2%，遵循原图类别子集与映射；CLIP 默认为 ViT-L/14@336px。自然分布偏移优势不等于任意扰动鲁棒，也不能与图 4 的 ResNet50 线性探测协议混合平均。</p><p>补充证据边界：表 1 的 ImageNet 零样本准确率为 CLIP 76.2%、Visual N-Grams 11.5%，但多项因素未控制；线性探测在 12/27 数据集平均提高 2.6/5 个百分点。去重分析的重叠中位数为 2.2%，检测到的最大提升为 0.6 个百分点，这不证明绝无数据污染。论文还说明开发过程反复参考验证集，27 项主评估集合也带有选择性。</p></StopArrows>}

const limitationRows=[
 {id:'tasks',label:'复杂任务',title:'文字接口并非万能',body:'论文 §6 指出，许多复杂任务很难只用文字准确规定；零样本 CLIP 往往只是接近 ResNet50 线性分类器，而该基线已低于整体 SOTA。'},
 {id:'evaluation',label:'验证与选集',title:'并非严格的真零样本开发',body:'论文 §6 承认开发中反复查询验证集；主分析使用的 27 个数据集集合较为零散，并与 CLIP 能力存在共同适应。'},
 {id:'overlap',label:'数据重叠',title:'未检出不等于绝无污染',body:'论文第 4 节检查 35 个数据集：9 个未检测到重叠，中位重叠率 2.2%、平均 3.2%，检测到的最大准确率提升为 Birdsnap 的 0.6 个百分点。这只能界定已检测影响，不能证明完全没有 contamination。'},
 {id:'scaling',label:'扩展计算',title:'1000× 是论文估算',body:'论文 §6 估算，要让零样本 CLIP 在其评测集合上达到整体 SOTA，可能需要约 1000 倍计算量；作者同时指出按当时硬件不可行，并呼吁提高计算和数据效率。'},
 {id:'bias',label:'类别与偏差',title:'分类器设计会改变偏差',body:'论文第 5 节强调，类别名称、自然语言描述和候选集合怎样设计，会显著影响模型表现与偏差；因此 prompt 与 candidate design 本身需要审查。'},
 {id:'privacy',label:'隐私与监控',title:'更容易启用小众任务也带来风险',body:'论文第 5 节指出，免去任务专用训练可能让某些小众任务更容易实现，从而带来隐私或 surveillance 风险；名人识别实验用于讨论风险，表现并未达到常见生产系统水平。'},
] as const;
export const ClipLimitations:React.FC<WidgetProps>=()=>{const[selected,setSelected]=useState('tasks');const current=limitationRows.find(row=>row.id===selected)!;return <StopArrows><Canvas h={300} label="CLIP 论文限制与 broader impacts 六项检查" draw={(c,w,h)=>{clear(c,w,h);txt(c,'点击检查论文自己报告的限制与风险',28,28,C.text,16);limitationRows.forEach((row,i)=>{const col=i%3,rowIndex=Math.floor(i/3),x=28+col*228,y=52+rowIndex*100,active=row.id===selected;c.save();c.beginPath();c.roundRect(x,y,204,72,10);c.fillStyle=active?'#e9f7ef':'#fff';c.fill();c.strokeStyle=active?C.orange:C.border;c.lineWidth=active?3:1.5;c.stroke();txt(c,row.label,x+102,y+31,active?C.green:C.text,16,'center');txt(c,active?'正在核对':'点击展开',x+102,y+54,active?C.orange:C.muted,12,'center');c.restore()});txt(c,'能力边界',135,278,C.blue,13,'center');txt(c,'证据边界',360,278,C.purple,13,'center');txt(c,'社会影响',585,278,C.red,13,'center')}}/><Buttons items={limitationRows.map(row=>[row.id,row.label] as [string,string])} value={selected} set={setSelected}/><div className={`feedback ${selected==='privacy'||selected==='bias'?'bad':''}`} aria-live="polite"><b>{current.title}</b>：{current.body}</div><p>以上均限定为论文第 4–6 节作者自己的讨论；页面不把风险扩写为论文没有验证的结论，也不把“未检测到”表述成“绝不存在”。</p></StopArrows>}
