import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ch10A } from './ch10a';
import { Ch10M1 } from './ch10m1';
import { Ch1A } from './ch1a';
import { Ch1M1 } from './ch1m1';
import { Ch1M2 } from './ch1m2';
import { Ch2A } from './ch2a';
import { Ch2M1 } from './ch2m1';
import { Ch2M2 } from './ch2m2';
import { Ch3A } from './ch3a';
import { Ch3M1 } from './ch3m1';
import { Ch4A } from './ch4a';
import { Ch4M1 } from './ch4m1';
import { Ch5A } from './ch5a';
import { Ch5M1 } from './ch5m1';
import { Ch6A } from './ch6a';
import { Ch6M1 } from './ch6m1';
import { Ch7A } from './ch7a';
import { Ch7M1 } from './ch7m1';
import { Ch8A } from './ch8a';
import { Ch8M1 } from './ch8m1';
import { Ch8M2 } from './ch8m2';
import { Ch9A } from './ch9a';
import { Ch9M1 } from './ch9m1';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ch10a'] = Ch10A;
widgetRegistry['ch10m1'] = Ch10M1;
widgetRegistry['ch1a'] = Ch1A;
widgetRegistry['ch1m1'] = Ch1M1;
widgetRegistry['ch1m2'] = Ch1M2;
widgetRegistry['ch2a'] = Ch2A;
widgetRegistry['ch2m1'] = Ch2M1;
widgetRegistry['ch2m2'] = Ch2M2;
widgetRegistry['ch3a'] = Ch3A;
widgetRegistry['ch3m1'] = Ch3M1;
widgetRegistry['ch4a'] = Ch4A;
widgetRegistry['ch4m1'] = Ch4M1;
widgetRegistry['ch5a'] = Ch5A;
widgetRegistry['ch5m1'] = Ch5M1;
widgetRegistry['ch6a'] = Ch6A;
widgetRegistry['ch6m1'] = Ch6M1;
widgetRegistry['ch7a'] = Ch7A;
widgetRegistry['ch7m1'] = Ch7M1;
widgetRegistry['ch8a'] = Ch8A;
widgetRegistry['ch8m1'] = Ch8M1;
widgetRegistry['ch8m2'] = Ch8M2;
widgetRegistry['ch9a'] = Ch9A;
widgetRegistry['ch9m1'] = Ch9M1;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
