import {useEffect,useMemo,useState} from'react'
const nav=[['problem','问题'],['prompt','序列'],['attention','注意力'],['diffusion','扩散'],['training','训练'],['evidence','证据'],['ablation','消融'],['ability','能力'],['limits','边界'],['quiz','验收']]
const Head=({n,k,t,p}:{n:string,k:string,t:string,p:string})=><header><b>{n}</b><div><small>{k}</small><h2>{t}</h2><p>{p}</p></div></header>

function PromptLab(){const[task,setTask]=useState(0);const x=[
 {n:'看图回答',s:['[MMU]','[SOI]','图像×256','[EOI]','问题','回答→'],m:'图像作为条件，文本逐 token 回答',l:'NTP：监督回答文本'},
 {n:'文生图',s:['[T2I]','提示词','[SOI]','MASK×256','[EOI]'],m:'所有图像位置相互可见，并行去噪',l:'MTP：监督被遮住的图像 token'},
 {n:'图文交错',s:['[MMU]','图像','描述','[T2I]','下一帧'],m:'同一序列交替理解、规划与生成',l:'NTP + MTP 按 token 类型组合'}][task];return <div className="lab"><Top n="01" t="同一条序列，切换三种任务" tag="论文 Fig. 3"/><Tabs labels={['理解','生成','混合']} on={task} set={setTask}/><div className="tokens">{x.s.map((v,i)=><i className={/图像|MASK|下一/.test(v)?'vis':''} key={i}>{v}</i>)}</div><div className="cards"><article><span>当前机制</span><h3>{x.n}</h3><p>{x.m}</p></article><article><span>训练目标</span><h3>{x.l}</h3><p>统一的是参数与序列接口，不是强迫所有 token 使用同一种目标。</p></article></div></div>}
function Top({n,t,tag}:{n:string,t:string,tag:string}){return <div className="top"><div><small>交互实验 {n}</small><h3>{t}</h3></div><em>{tag}</em></div>}
function Tabs({labels,on,set}:{labels:string[],on:number,set:(x:number)=>void}){return <div className="tabs">{labels.map((x,i)=><button className={on===i?'on':''} onClick={()=>set(i)} key={x}>{x}</button>)}</div>}

function Attention(){const[mode,setMode]=useState(1),labs=mode===2?['T₁','T₂','T₃','T₄','T₅']:mode===0?['I₁','I₂','I₃','T₁','T₂']:['T₁','T₂','I₁','I₂','I₃'];const ok=(r:number,c:number)=>{if(mode===2)return c<=r;const im=(s:string)=>s[0]==='I';return im(labs[r])?im(labs[c])||c<r:c<=r};return <div className="lab"><Top n="02" t="切换 Omni-Attention 掩码" tag="论文 Fig. 5"/><Tabs labels={['图像→文本','文本→图像','纯文本']} on={mode} set={setMode}/><div className="mask"><div>{labs.map((r,ri)=><p key={r}><b>{r}</b>{labs.map((c,ci)=><i title={`${r}${ok(ri,ci)?'可以':'不能'}关注${c}`} className={ok(ri,ci)?'yes':''} key={c}/>)}</p>)}</div><article><h3>{mode===2?'标准因果注意力':mode===0?'先看完整图像，再逐词回答':'文本保持因果；图像区域全注意力'}</h3><p>深色格表示可见。图像 token 彼此全连接，文本 token 仍遵守从左到右的语言建模顺序。</p><small>悬停方格可查看连接</small></article></div></div>}

function Denoise(){const[step,setStep]=useState(0),cells=useMemo(()=>Array.from({length:16},(_,i)=>i),[]),seen=Math.round(step);return <div className="lab"><Top n="03" t="图像不是从左往右画出来的" tag="教学缩小演示"/><div className="denoise"><div className="pixels">{cells.map(i=><i className={i<seen?'seen':''} key={i}>{i<seen?['●','▲','◆','■'][i%4]:'?'}</i>)}</div><div><label>去噪进度 <b>{step}/16</b><input type="range" min="0" max="16" value={step} onChange={e=>setStep(+e.target.value)}/></label><p>{step===0?'全部位置被 MASK，从文本条件开始。':step<8?'先恢复高置信位置，其余位置继续保持 MASK。':step<16?'更多位置获得全局上下文，结构逐步完整。':'所有离散 token 确定，再由 MAGVIT-v2 解码。'}</p><button onClick={()=>setStep(step===16?0:Math.min(16,step+2))}>{step===16?'重新开始':'推进 2 步'}</button></div></div><p className="note">论文用 16 个采样步骤生成 256 个位置；这里仅解释遮罩比例，不模拟真实图像质量。</p></div>}

function Training(){const[s,setS]=useState(0),x=[['图像词与像素依赖','RefinedWeb + ImageNet-1K + 35M 图文对','保留语言能力，学习图像嵌入、类别生成和描述','500K steps'],['双向图文对齐','35M 图文对替换类别条件生成','同时训练图像描述与文本到图像','额外 1,000K steps'],['高质量微调','高质量图文 + LLaVA 指令 + GenHowTo','提升生成、问答与混合模态能力','未给统一总步数']][s];return <div className="lab"><Top n="04" t="三阶段课程表" tag="§3.3 / §4.1"/><div className="stages">{['① 学图像词','② 双向对齐','③ 高质量微调'].map((v,i)=><button className={s===i?'on':''} onClick={()=>setS(i)} key={v}>{v}</button>)}</div><article className="stage"><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p><b>{x[3]}</b></article><div className="facts">{[['48','A100 80GB'],['1,152','总 batch'],['1e−4','初始学习率'],['0.01','weight decay']].map(v=><div key={v[1]}><b>{v[0]}</b><span>{v[1]}</span></div>)}</div></div>}

type M='POPE'|'MME'|'VQAv2'|'GQA';const scores:{[k in M]:[string,number][]}={POPE:[['LLaVA-Phi',84.1],['Show-o 离散',73.8],['Show-o + CLIP',84.5]],MME:[['LLaVA-Phi',1128],['Show-o 离散',948.4],['Show-o + CLIP',1182.7]],VQAv2:[['LLaVA-Phi',75.3],['Show-o 离散',59.3],['Show-o + CLIP',73.9]],GQA:[['LLaVA-Phi',56.5],['Show-o 离散',48.7],['Show-o + CLIP',57.5]]}
function Evidence(){const[m,setM]=useState<M>('POPE'),rows=scores[m],max=Math.max(...rows.map(x=>x[1]))*1.08;return <div className="lab"><Top n="05" t="切换指标，不隐藏默认模型的代价" tag="论文 Table 1"/><div className="tabs">{(Object.keys(scores)as M[]).map(x=><button className={m===x?'on':''} onClick={()=>setM(x)} key={x}>{x}</button>)}</div><div className="bars">{rows.map(([n,v])=><p className={n.includes('CLIP')?'hi':''} key={n}><span>{n}</span><i><em style={{width:`${v/max*100}%`}}/></i><b>{v}</b></p>)}</div><blockquote>默认离散图像 token 方便统一生成，却削弱理解；换成 CLIP 连续特征后，理解接近或超过同规模 LLaVA。</blockquote></div>}

function Ablation(){const[f,setF]=useState(2),data=[[[84.5,1182.7,64.3,57.5],[84.5,1161.6,68.5,58.7]],[[74.3,947.8,33.9,51],[65.1,800,12.3,43.9]],[[73.8,948.4,36.2,48.7],[63.8,689.1,4.5,40.5]]][f];return <div className="lab"><Top n="06" t="统一预训练到底帮了谁？" tag="论文 Table 4"/><Tabs labels={['CLIP 连续','MAGVIT 连续','MAGVIT 离散']} on={f} set={setF}/><div className="table"><p><span>指标</span><b>无预训练</b><strong>有预训练</strong><em>变化</em></p>{['POPE','MME','Flickr30k','GQA'].map((n,i)=><p key={n}><span>{n}</span><b>{data[1][i]}</b><strong>{data[0][i]}</strong><em className={data[0][i]>=data[1][i]?'up':'down'}>{data[0][i]>=data[1][i]?'+':''}{+(data[0][i]-data[1][i]).toFixed(1)}</em></p>)}</div><blockquote>{f===0?'CLIP 已有强语义空间，统一预训练收益很小，部分指标下降。':'MAGVIT 表征从统一预训练中明显获益，离散 token 尤其需要大规模跨模态对齐。'}</blockquote></div>}

function Quiz(){const q=[['“单一 Transformer”意味着？',['所有模态都自回归','共享主干，按 token 类型切换规则','不需要 tokenizer'],1],['256×256 图像被编码为？',['16','256','8192'],1],['论文证据支持？',['默认离散理解全面领先','CLIP 连续表征明显改善理解','所有指标第一'],1],['图像生成目标是？',['Masked Token Prediction','纯对比学习','只有 NTP'],0],['明确失败类型包括？',['OCR/文字生成与计数','无法生成任何图像','不能输入文字'],0]] as [string,string[],number][];const[a,setA]=useState(q.map(()=>-1)),sum=a.reduce((s,v,i)=>s+(v===q[i][2]?1:0),0);return <div className="quiz">{q.map((x,i)=><fieldset key={x[0]}><legend><b>{i+1}</b>{x[0]}</legend>{x[1].map((v,j)=><button className={a[i]===j?(j===x[2]?'right':'wrong'):''} onClick={()=>setA(z=>z.map((n,k)=>k===i?j:n))} key={v}>{v}</button>)}</fieldset>)}<div className="score"><span>理解得分</span><b>{sum}/5</b><p>{sum===5?'你已经抓住论文主张与证据边界。':'完成五题，并回看答错的章节。'}</p></div></div>}

export default function App(){const[prog,setProg]=useState(0),[active,setActive]=useState('problem');useEffect(()=>{const f=()=>{const max=document.documentElement.scrollHeight-innerHeight;setProg(max?scrollY/max*100:0);let a='problem';nav.forEach(([id])=>{const n=document.getElementById(id);if(n&&n.getBoundingClientRect().top<innerHeight*.4)a=id});setActive(a)};f();addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);return <><div className="progress" style={{width:`${prog}%`}}/><nav><a className="logo" href="#top">S<span>o</span></a>{nav.map(([id,n],i)=><a className={active===id?'active':''} href={'#'+id} key={id}><i>{String(i+1).padStart(2,'0')}</i>{n}</a>)}</nav><main id="top">
<section className="hero"><div><small>UNIFIED MODEL FIELD GUIDE · 03</small><h1><em>Show-o</em><br/>同一舞台，<br/>两种节拍。</h1><p>语言适合从左往右推理，图像适合全局并行去噪。Show-o 让一个 Transformer 根据 token 类型切换规则。</p><aside><a href="#problem">开始拆解 ↓</a><a href="https://arxiv.org/abs/2408.12528" target="_blank">论文 ↗</a></aside><dl>{[['主干','Phi-1.5 · 1.3B'],['图像词表','8,192'],['生成步数','16'],['发表','ICLR 2025']].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl></div><figure><span>T₁ → T₂ → T₃</span><b>ONE<br/><i>TRANSFORMER</i></b><div>{Array.from({length:9},(_,i)=><i key={i}/>)}</div><em>DISCRETE DIFFUSION</em></figure></section>
<section id="problem" className="dark"><Head n="01" k="RESEARCH QUESTION" t="统一，究竟要统一什么？" p="理解与生成常由两套专家拼接。Show-o 追问：能否共享同一组主干参数，同时保留两类任务各自合适的计算规律？"/><div className="compare"><article><span>组装式</span><h3>LLM + 外部扩散</h3><p>两套专家，用接口连接。</p></article><article className="focus"><span>Show-o</span><h3>同一 Transformer</h3><p>文本走 AR，图像走离散扩散。</p></article><article><span>纯自回归</span><h3>一切从左到右</h3><p>接口简单，图像却要逐位置采样。</p></article></div><h4>真正的统一，是一组参数在清楚的边界内切换规则。</h4></section>
<section id="prompt"><Head n="02" k="UNIFIED PROMPT" t="先把任务写成同一种语言" p="任务 token 和模态边界 token 把理解、生成与混合任务组织成结构化序列。"/><PromptLab/><div className="facts light">{[['文本','LLM tokenizer'],['图像','MAGVIT-v2'],['空间','256² → 16×16'],['新增词表','8,192']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section>
<section id="attention" className="pale"><Head n="03" k="OMNI-ATTENTION" t="一张注意力图，两套因果关系" p="文本不能偷看未来词；图像去噪需要所有位置交换信息。Omni-Attention 依序列结构组合因果与全注意力。"/><Attention/></section>
<section id="diffusion"><Head n="04" k="TWO OBJECTIVES" t="文字猜下一个，图像补回遮罩" p="NTP 保留语言推理顺序；MTP 把 MaskGIT 式生成解释为离散扩散。总损失为二者加权和。"/><div className="formula"><article><span>文本</span><b>L<sub>NTP</sub></b><p>p(vᵢ | v&lt;ᵢ, image)</p></article><i>+</i><article><span>图像</span><b>αL<sub>MTP</sub></b><p>p(uⱼ | unmasked, text)</p></article><i>=</i><article className="sum"><span>共享主干</span><b>L</b><p>共同更新</p></article></div><Denoise/></section>
<section id="training" className="dark"><Head n="05" k="CURRICULUM" t="先学图像词，再对齐双向映射" p="新图像嵌入无法直接继承语言知识，训练按像素依赖、图文双向对齐、高质量指令逐级推进。"/><Training/></section>
<section id="evidence"><Head n="06" k="WHAT THE NUMBERS SAY" t="生成有竞争力，理解取决于视觉入口" p="Show-o 用 1.3B 参数与 35M 图文对得到 FID 9.24；默认离散表征的理解却明显落后于 CLIP 连续版本。"/><Evidence/><div className="results"><article><span>Show-o FID↓</span><b>9.24</b><p>1.3B · 35M 数据</p></article><article><span>LWM / SEED-X</span><b>12.68 / 14.99</b><p>统一模型对比</p></article><article><span>边界</span><b>≠ 全面 SOTA</b><p>PixArt 7.32 · Imagen 7.27</p></article></div><p className="note">论文 Table 1–3；FID 受训练分布影响，论文也提醒它不能完整代表生成质量。</p></section>
<section id="ablation" className="pale"><Head n="07" k="CAUSAL EVIDENCE" t="最难的缝：视觉表征" p="Table 4 拆开视觉编码器、连续/离散特征与统一预训练，揭示生成接口与理解语义之间的张力。"/><Ablation/><div className="take"><b>与 Janus 的联系</b><p>离散 token 有利于统一生成，却更难对齐语言语义；Janus 的双视觉编码路径正是在回应这种冲突。</p></div></section>
<section id="ability"><Head n="08" k="EMERGENT USES" t="统一序列带来的能力，不止文生图" p="遮住任意区域即可修补与外扩；文本规划和图像 token 交替输出还能探索混合模态叙事。"/><div className="abilities">{[['VQA / 描述','图像条件下逐词回答','定量评估'],['文生图','文本条件下并行恢复','定量评估'],['修补 / 外扩','只去噪未知区域','无需额外微调'],['混合模态','描述与关键帧交替','定性探索']].map((x,i)=><article key={x[0]}><i>0{i+1}</i><h3>{x[0]}</h3><p>{x[1]}</p><span>{x[2]}</span></article>)}</div></section>
<section id="limits" className="dark"><Head n="09" k="LIMITS & COST" t="能统一，不代表没有代价" p="失败案例、训练规模和指标口径共同划出可信边界。"/><div className="limits">{[['文字识别与生成','漏读 “closing down”，无法正确生成陌生字符串。'],['物体计数','七人滑雪照片回答为三人。'],['训练不轻量','48 张 A100 80GB，1.5M 步后仍需微调。'],['混合模态证据有限','关键帧主要是定性展示，不能等同成熟视频能力。']].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div><div className="audit"><p><s>一个模型 = 一个 tokenizer</s><b>主干统一，tokenizer 分工。</b></p><p><s>统一 = 一种目标</s><b>文本 NTP，图像 MTP。</b></p><p><s>16 倍步数 = 延迟快 16 倍</s><b>论文没有端到端延迟实测。</b></p><p><s>有竞争力 = 所有指标第一</s><b>表格中存在更高结果。</b></p></div></section>
<section id="quiz"><Head n="10" k="UNDERSTANDING CHECK" t="你是否真正读懂 Show-o？" p="五题检查主张、机制与证据边界。"/><Quiz/><div className="summary"><small>一句话带走</small><h2>共享一颗 Transformer 大脑，<br/>让语言与图像保持各自的节拍。</h2><aside><a href="https://arxiv.org/abs/2408.12528" target="_blank">论文 ↗</a><a href="https://github.com/showlab/Show-o" target="_blank">代码 ↗</a><a href="https://grokcv.site/sprouts/umm/" target="_blank">专题 ↗</a></aside></div></section>
</main><footer>SHOW-O · 何熹淳 · XichunHe · 数据与主张以原论文为准</footer></>}
