import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { Mod11 } from './mod-1-1';
import { Mod101 } from './mod-10-1';
import { Mod21 } from './mod-2-1';
import { Mod31 } from './mod-3-1';
import { Mod41 } from './mod-4-1';
import { Mod51 } from './mod-5-1';
import { Mod61 } from './mod-6-1';
import { Mod71 } from './mod-7-1';
import { Mod72 } from './mod-7-2';
import { Mod81 } from './mod-8-1';
import { Mod82 } from './mod-8-2';
import { Mod91 } from './mod-9-1';
import { Mod92 } from './mod-9-2';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['mod-1-1'] = Mod11;
widgetRegistry['mod-10-1'] = Mod101;
widgetRegistry['mod-2-1'] = Mod21;
widgetRegistry['mod-3-1'] = Mod31;
widgetRegistry['mod-4-1'] = Mod41;
widgetRegistry['mod-5-1'] = Mod51;
widgetRegistry['mod-6-1'] = Mod61;
widgetRegistry['mod-7-1'] = Mod71;
widgetRegistry['mod-7-2'] = Mod72;
widgetRegistry['mod-8-1'] = Mod81;
widgetRegistry['mod-8-2'] = Mod82;
widgetRegistry['mod-9-1'] = Mod91;
widgetRegistry['mod-9-2'] = Mod92;
