import React from 'react';
import { TeachingScene } from './Scenes';
import { ChapterIntro } from './ChapterIntros';
export const widgetRegistry: Record<string, React.ComponentType<any>> = {};
widgetRegistry['analogy-1'] = () => <ChapterIntro chapter={1}/>;
widgetRegistry['vadar-1-1'] = () => <TeachingScene chapter={1} variant={1} kind="explore"/>;
widgetRegistry['analogy-2'] = () => <ChapterIntro chapter={2}/>;
widgetRegistry['vadar-2-1'] = () => <TeachingScene chapter={2} variant={1} kind="explore"/>;
widgetRegistry['analogy-3'] = () => <ChapterIntro chapter={3}/>;
widgetRegistry['vadar-3-1'] = () => <TeachingScene chapter={3} variant={1} kind="explore"/>;
widgetRegistry['analogy-4'] = () => <ChapterIntro chapter={4}/>;
widgetRegistry['vadar-4-1'] = () => <TeachingScene chapter={4} variant={1} kind="explore"/>;
widgetRegistry['analogy-5'] = () => <ChapterIntro chapter={5}/>;
widgetRegistry['vadar-5-1'] = () => <TeachingScene chapter={5} variant={1} kind="explore"/>;
widgetRegistry['analogy-6'] = () => <ChapterIntro chapter={6}/>;
widgetRegistry['vadar-6-1'] = () => <TeachingScene chapter={6} variant={1} kind="explore"/>;
widgetRegistry['analogy-7'] = () => <ChapterIntro chapter={7}/>;
widgetRegistry['vadar-7-1'] = () => <TeachingScene chapter={7} variant={1} kind="explore"/>;
widgetRegistry['analogy-8'] = () => <ChapterIntro chapter={8}/>;
widgetRegistry['vadar-8-1'] = () => <TeachingScene chapter={8} variant={1} kind="explore"/>;
widgetRegistry['analogy-9'] = () => <ChapterIntro chapter={9}/>;
widgetRegistry['vadar-9-1'] = () => <TeachingScene chapter={9} variant={1} kind="explore"/>;
widgetRegistry['analogy-10'] = () => <ChapterIntro chapter={10}/>;
widgetRegistry['vadar-10-1'] = () => <TeachingScene chapter={10} variant={1} kind="explore"/>;
widgetRegistry['vadar-10-2'] = () => <TeachingScene chapter={10} variant={2} kind="explore"/>;
widgetRegistry['hero-old'] = () => <TeachingScene chapter={8} variant={1} kind="intro"/>;
widgetRegistry['hero-new'] = () => <TeachingScene chapter={8} variant={1} kind="intro"/>;
