import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana11 } from './ana-11';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { AnaConcl } from './ana-concl';
import { Ch10Mod1 } from './ch10mod1';
import { Ch10Concl } from './ch10concl';
import { Ch1Mod1 } from './ch1mod1';
import { Ch2Mod1 } from './ch2mod1';
import { Ch3Mod1 } from './ch3mod1';
import { Ch4Mod1 } from './ch4mod1';
import { Ch4Mod2 } from './ch4mod2';
import { Ch5Mod1 } from './ch5mod1';
import { Ch6Mod1 } from './ch6mod1';
import { Ch6Depth } from './ch6depth';
import { Ch6Object } from './ch6object';
import { Ch7Mod1 } from './ch7mod1';
import { Ch7Multi } from './ch7multi';
import { Ch8Mod1 } from './ch8mod1';
import { Ch8Radar } from './ch8radar';
import { Ch9Mod1 } from './ch9mod1';
import { Ch9Ref, Ch9Mix, Ch9Size, Ch9Analysis } from './ch9analysis';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-11'] = Ana11;
widgetRegistry['ana-concl'] = AnaConcl;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['ch10mod1'] = Ch10Mod1;
widgetRegistry['ch10concl'] = Ch10Concl;
widgetRegistry['ch1mod1'] = Ch1Mod1;
widgetRegistry['ch2mod1'] = Ch2Mod1;
widgetRegistry['ch3mod1'] = Ch3Mod1;
widgetRegistry['ch4mod1'] = Ch4Mod1;
widgetRegistry['ch4mod2'] = Ch4Mod2;
widgetRegistry['ch5mod1'] = Ch5Mod1;
widgetRegistry['ch6mod1'] = Ch6Mod1;
widgetRegistry['ch6depth'] = Ch6Depth;
widgetRegistry['ch6object'] = Ch6Object;
widgetRegistry['ch7mod1'] = Ch7Mod1;
widgetRegistry['ch7multi'] = Ch7Multi;
widgetRegistry['ch8mod1'] = Ch8Mod1;
widgetRegistry['ch8radar'] = Ch8Radar;
widgetRegistry['ch9mod1'] = Ch9Mod1;
widgetRegistry['ch9analysis'] = Ch9Analysis;
widgetRegistry['ch9ref'] = Ch9Ref;
widgetRegistry['ch9mix'] = Ch9Mix;
widgetRegistry['ch9size'] = Ch9Size;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
