import React, { useEffect, useRef, useState } from 'react';
import { setupCanvas, observeCanvas } from '../lib/canvasKit';

type CT=CanvasRenderingContext2D;
export const C={bg:'#f5f8f0',line:'#cbd8d2',ink:'#233747',blue:'#27446e',green:'#228d5c',red:'#c34555',orange:'#d17c3e',purple:'#7655a5',muted:'#839992'};
export function BirdKit(){return null;}
export function wipe(c:CT,w=1080,h=280){c.clearRect(0,0,w,h);c.fillStyle=C.bg;c.fillRect(0,0,w,h);}
export function stroke(c:CT,x:number,y:number,w:number,h:number,color=C.blue,fill=false){c.beginPath();c.roundRect(x,y,w,h,9);c.lineWidth=3;c.strokeStyle=color;if(fill){c.fillStyle=color;c.fill();}c.stroke();}
export function line(c:CT,x:number,y:number,u:number,v:number,color=C.blue,width=3){c.beginPath();c.moveTo(x,y);c.lineTo(u,v);c.lineWidth=width;c.strokeStyle=color;c.stroke();}
export function label(c:CT,s:string,x:number,y:number,color=C.ink,size=22){c.fillStyle=color;c.font=`${size}px "Microsoft YaHei",sans-serif`;c.fillText(s,x,y);}
export function bird(c:CT,x:number,y:number,size=1,color=C.orange){c.save();c.translate(x,y);c.scale(size,size);c.fillStyle=color;c.beginPath();c.ellipse(0,0,38,26,0,0,7);c.fill();c.beginPath();c.arc(23,-21,19,0,7);c.fill();c.beginPath();c.moveTo(39,-19);c.lineTo(59,-12);c.lineTo(39,-7);c.fillStyle='#ddb15f';c.fill();c.fillStyle=C.ink;c.beginPath();c.arc(27,-25,3,0,7);c.fill();line(c,-14,17,-23,48,C.ink,2);line(c,3,18,6,49,C.ink,2);c.restore();}
export function scene(c:CT,w=1080,h=280){wipe(c,w,h);line(c,30,h-36,w-30,h-36,C.muted,3);[.1,.45,.78].forEach(v=>{const x=w*v;c.fillStyle='#dce9dd';c.beginPath();c.arc(x,h-100,35,0,7);c.fill();});}
type Draw=(c:CT,t:number)=>void;
export function Canvas({draw,label:description,width=1080,height=280,animate=false,onPoint,drag=false,onKey}:{draw:Draw,label:string,width?:number,height?:number,animate?:boolean,onPoint?:(x:number,y:number)=>void,drag?:boolean,onKey?:(key:string)=>void}){const ref=useRef<HTMLCanvasElement>(null),fn=useRef(draw),ctx=useRef<CT|null>(null);fn.current=draw;useEffect(()=>{const el=ref.current!;ctx.current=setupCanvas(el,width,height);el.style.width='100%';el.style.height='auto';let frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const paint=(t:number)=>{fn.current(ctx.current!,t);el.classList.add('is-ready');};paint(0);const tick=(t:number)=>{paint(t);frame=requestAnimationFrame(tick);};const stop=()=>{cancelAnimationFrame(frame);frame=0;};const off=observeCanvas(el,()=>{if(animate&&!reduced&&!frame)frame=requestAnimationFrame(tick);},stop);return()=>{stop();off();};},[width,height,animate]);useEffect(()=>{if(ctx.current)draw(ctx.current,0);},[draw]);const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();onPoint?.((e.clientX-r.left)*width/r.width,(e.clientY-r.top)*height/r.height);};return <canvas ref={ref} width={width} height={height} aria-label={description} role={onPoint?'application':'img'} tabIndex={onPoint||onKey?0:undefined} style={{maxWidth:'100%',cursor:drag?'grab':onPoint?'pointer':'default',touchAction:drag?'none':'auto'}} onPointerDown={e=>{if(drag)e.currentTarget.setPointerCapture(e.pointerId);move(e);}} onPointerMove={e=>{if(drag&&e.currentTarget.hasPointerCapture(e.pointerId))move(e);}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onKeyDown={e=>{if(onKey&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();e.stopPropagation();onKey(e.key);}}}/>;}
export function Chips({labels,value,onChange}:{labels:string[],value:number,onChange:(v:number)=>void}){return <div className="ctrl">{labels.map((x,i)=><button type="button" key={x} className={`chip ${i===value?'selected':''}`} aria-pressed={i===value} onClick={()=>onChange(i)}>{x}</button>)}</div>;}
export function Feedback({children,kind=''}:{children:React.ReactNode,kind?:string}){return <div className={`feedback ${kind}`} aria-live="polite">{children}</div>;}
export function Reset({onClick}:{onClick:()=>void}){return <button type="button" className="tiny" onClick={onClick}>重置</button>;}
