import React, { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import type { WidgetProps } from './registry';
import { paperData, type CapabilityId } from '../data/paperData';
import { unlockSpace } from './spaceSystem';

type Experiment = 'ablation' | 'cost' | 'upgrade';

export const OutputObservatory: React.FC<WidgetProps> = () => {
  const [active, setActive] = useState<Experiment>('ablation');
  const [completed, setCompleted] = useState<Record<Experiment, boolean>>({ ablation: false, cost: false, upgrade: false });
  const [ablationBet, setAblationBet] = useState<string | null>(null);
  const [costGuess, setCostGuess] = useState<string | null>(null);
  const [upgradeType, setUpgradeType] = useState<'vision' | 'language'>('vision');
  const [upgradeGuess, setUpgradeGuess] = useState<string | null>(null);
  const [capability, setCapability] = useState<CapabilityId>('vqa');
  const [dataOpen, setDataOpen] = useState(false);
  const allDone = useMemo(() => Object.values(completed).every(Boolean), [completed]);
  const finish = (id: Experiment) => setCompleted(current => ({ ...current, [id]: true }));
  const upgrade = paperData.upgrades[upgradeType];
  const cap = paperData.capabilities.find(item => item.id === capability)!;

  return <motion.section className="output-observatory" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 1.1 }} aria-label="OutputObservatory 输出观测站">
    <div className="observatory-haze" aria-hidden="true"><span /><span /><span /></div>
    <header className="observatory-header"><span>EXPERIMENTAL VALIDATION CENTER / 06</span><b>{Object.values(completed).filter(Boolean).length} / 3 VERIFIED</b></header>
    <div className="experiment-tabs">{(['ablation','cost','upgrade'] as Experiment[]).map((id, index) => <button key={id} className={`${active === id ? 'active' : ''} ${completed[id] ? 'done' : ''}`} onClick={() => setActive(id)}><i>0{index + 1}</i>{id === 'ablation' ? 'Stage 1 Ablation' : id === 'cost' ? 'Trainable Parameters' : '模块升级'}{completed[id] && <span>✓</span>}</button>)}</div>
    <div className="observatory-console">
      <AnimatePresence mode="wait">
        {active === 'ablation' && <motion.div key="ablation" className="experiment-scene" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><p className="experiment-tag">EXPERIMENT 01 / ABLATION</p><h2>如果最终都要连接 LLM，Stage 1 是否可以跳过？</h2><p>先下注，再打开 zero-shot VQA 测试舱。</p><div className="prediction-options"><button onClick={() => { setAblationBet('two-stage'); finish('ablation'); }}>完整两阶段表现更好</button><button onClick={() => { setAblationBet('stage2-only'); finish('ablation'); }}>直接 Stage 2 同样有效</button></div>{ablationBet && <div className="reveal-panel"><strong>REVEAL / {paperData.stage1Ablation.metric}</strong><div className="metric-bars">{paperData.stage1Ablation.variants.map(item => <div key={item.id}><span>{item.label}</span><i><motion.b initial={{ width: 0 }} animate={{ width: `${item.value}%` }} transition={{ duration: 1 }} /></i><em>{item.approximate ? '约 ' : ''}{item.value.toFixed(1)}</em></div>)}</div><p>{paperData.stage1Ablation.note}</p><small>{paperData.stage1Ablation.source}</small></div>}</motion.div>}
        {active === 'cost' && <motion.div key="cost" className="experiment-scene" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><p className="experiment-tag">EXPERIMENT 02 / EFFICIENCY</p><h2>与大型视觉语言模型相比，BLIP-2 需要更新多少参数？</h2><p>先猜训练成本量级。这里比较的是 trainable parameters，不是模型的总参数量。</p><div className="prediction-options"><button onClick={() => { setCostGuess('less'); finish('cost'); }}>明显更少</button><button onClick={() => { setCostGuess('same'); finish('cost'); }}>大致相同</button><button onClick={() => { setCostGuess('more'); finish('cost'); }}>反而更多</button></div>{costGuess && <div className="reveal-panel efficiency-reveal"><strong>REVEAL / 论文报告的代表性配置</strong><div className="efficiency-grid"><div><span>相对可训练参数</span><div className="param-track"><motion.i initial={{ width: 0 }} animate={{ width: '12%' }}>BLIP-2 · 1×</motion.i></div><div className="param-track"><motion.i className="large" initial={{ width: 0 }} animate={{ width: '100%' }}>Flamingo80B · 54×</motion.i></div></div><div><span>Zero-shot VQAv2</span>{paperData.efficiency.models.map(model => <p key={model.id}><b>{model.vqa.toFixed(1)}</b><small>{model.label}</small></p>)}</div></div><p>{paperData.efficiency.note}</p><small>{paperData.efficiency.source}</small></div>}</motion.div>}
        {active === 'upgrade' && <motion.div key="upgrade" className="experiment-scene" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><p className="experiment-tag">EXPERIMENT 03 / MODULAR UPGRADE</p><h2>如果只更换一个更强的单模态模块，最终效果会怎样？</h2><div className="upgrade-switch"><button className={upgradeType === 'vision' ? 'active' : ''} onClick={() => { setUpgradeType('vision'); setUpgradeGuess(null); }}>升级视觉编码器</button><button className={upgradeType === 'language' ? 'active' : ''} onClick={() => { setUpgradeType('language'); setUpgradeGuess(null); }}>升级 LLM</button></div><div className="module-rig"><span>{upgrade.from}</span><b>⇢</b><span>{upgrade.to}</span></div><p>先预测这次替换对 {upgrade.metric} 的影响。</p><div className="prediction-options"><button onClick={() => { setUpgradeGuess('up'); finish('upgrade'); }}>表现提升</button><button onClick={() => { setUpgradeGuess('flat'); finish('upgrade'); }}>基本不变</button><button onClick={() => { setUpgradeGuess('down'); finish('upgrade'); }}>表现下降</button></div>{upgradeGuess && <div className="reveal-panel"><strong>REVEAL / {upgrade.label}</strong><div className="upgrade-result"><span>{upgrade.before.toFixed(1)}</span><motion.i initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} /><span>{upgrade.after.toFixed(1)}</span></div><p>{paperData.upgrades.note}</p><small>{paperData.upgrades.source}</small></div>}</motion.div>}
      </AnimatePresence>
      {allDone && <motion.div className="capability-deck" initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }}><div className="deck-heading"><span>CAPABILITY OBSERVATION DECK</span><h2>三个实验已完成。现在观察这套接口能支持哪些任务。</h2></div><div className="capability-tabs">{paperData.capabilities.map(item => <button key={item.id} className={capability === item.id ? 'active' : ''} onClick={() => setCapability(item.id)}>{item.label}</button>)}</div><div className="capability-screen"><div><span>任务</span><strong>{cap.question}</strong></div><div><span>论文证据</span><strong>{cap.evidence}</strong></div><div><span>需要的连接能力</span><strong>{cap.signal}</strong></div></div><button className="data-archive-toggle" onClick={() => setDataOpen(!dataOpen)}>{dataOpen ? '收起实验数据档案' : '打开实验数据档案'}</button>{dataOpen && <motion.div className="data-archive" initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }}><strong>TABLE ARCHIVE / PAPER EVIDENCE</strong><div className="benchmark-scroll"><table><thead><tr><th>配置</th><th>VQAv2 val</th><th>VQAv2 test-dev</th><th>OK-VQA</th><th>GQA</th></tr></thead><tbody>{paperData.benchmarkRows.map(row => <tr key={row.model}><td>{row.model}</td><td>{row.vqaVal.toFixed(1)}</td><td>{row.vqaTest.toFixed(1)}</td><td>{row.okVqa.toFixed(1)}</td><td>{row.gqa.toFixed(1)}</td></tr>)}</tbody></table></div><div className="ablation-archive">{paperData.ablationNotes.map(note => <div key={note.title}><b>{note.title}</b><p>{note.finding}</p><small>{note.source}</small></div>)}</div><p className="data-boundary">{paperData.dataBoundary}</p></motion.div>}<button className="observatory-primary" onClick={() => unlockSpace('chap-8')}>完成实验验证，进入回望大厅 →</button></motion.div>}
    </div>
  </motion.section>;
};
