import {useEffect,useState} from 'react';
import {Panel,Hint} from './lab-ui';
const examples=[
 {name:'文字',input:'下雨出门要带什么？',encode:'分词 → 词嵌入',shape:'文本位置 × 768 维',process:'读取出门建议的文字问题，组织回答。',output:'下雨出门记得带伞，注意路滑。'},
 {name:'语音',input:'语音提问：“下雨出门要带什么？”',encode:'SenseVoice → 音频投影器',shape:'512 维 → 768 维',process:'利用声音特征理解提问，组织出门建议。',output:'下雨出门记得带伞，注意路滑。'},
 {name:'图片',input:'雨伞图片 + 文字问题：“下雨出门要带什么？”',encode:'SigLIP2 → 视觉投影器',shape:'64 个视觉位置 × 768 维',process:'结合雨伞图片与文字提问，组织出门建议。',output:'下雨出门可以带上图中的雨伞。'}
];
const stages=['输入就绪','转换为特征序列','Thinker 组织内容','Talker 预测音频码','Mimi 解码完整帧'];
const css=`.omni-lab button[aria-pressed=true]:hover{background:#27446e;color:white}.flow-grid[data-playing=false] .flow-arrow:before{animation-play-state:paused}.flow-grid{display:grid;grid-template-columns:1fr 1.2fr 1.1fr;gap:16px;align-items:stretch}.flow-node{background:#fff;border:1px solid #d9e2ed;border-radius:12px;padding:16px;transition:border-color .3s,background .3s,box-shadow .3s;position:relative}.flow-node.current{border-color:#6384ad;box-shadow:0 0 0 3px #e5edf8;background:#f5f8fc}.flow-node h4{font-size:16px;margin:4px 0 10px;color:#27446e}.flow-node p{font-size:13px;line-height:1.8;margin:8px 0}.flow-arrow{height:30px;position:relative;margin:0 20px;border-left:2px solid #d0dbe8}.flow-arrow:after{content:'↓';position:absolute;bottom:-5px;left:-7px;color:#829ab9}.flow-arrow.lit{border-color:#27446e}.flow-arrow.lit:before{content:'';position:absolute;width:7px;height:7px;left:-4px;background:#27446e;border-radius:50%;animation:flowTravel 1.1s ease-in-out infinite}.flow-output{min-height:80px;padding:12px;background:#eef4fb;border-radius:8px;font-size:16px;line-height:1.8}.flow-wave{display:flex;align-items:center;justify-content:center;gap:4px;height:70px;background:#edf5ef;border-radius:8px;margin:10px 0}.flow-wave i{display:block;width:5px;background:#358260;border-radius:4px}.flow-wave.running i{animation:flowWave .9s ease-in-out 2 alternate}.flow-reveal{animation:flowReveal .4s ease-out}.flow-stage{display:flex;gap:5px;margin:14px 0}.flow-stage span{height:5px;flex:1;background:#e1e7ef;border-radius:5px}.flow-stage span.done{background:#27446e}@keyframes flowTravel{from{top:0;opacity:.3}to{top:22px;opacity:1}}@keyframes flowWave{from{transform:scaleY(.3)}to{transform:scaleY(1)}}@keyframes flowReveal{from{opacity:.1;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){.flow-arrow.lit:before,.flow-wave.running i,.flow-reveal{animation:none}}`;
export function C1Main(){const [mode,setMode]=useState(0),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[run,setRun]=useState(0);const e=examples[mode];
 useEffect(()=>{if(!playing)return;if(step>=4){setPlaying(false);return;}const timer=setTimeout(()=>setStep(s=>Math.min(4,s+1)),1300);return()=>clearTimeout(timer);},[playing,step]);
 const select=(i:number)=>{setMode(i);setStep(0);setPlaying(true);setRun(r=>r+1);};
 const node=(s:number)=>`flow-node ${step===s?'current':''}`;
 return <Panel chapter={1}><style>{css}</style><p>选择一个具体输入，沿图查看它怎样变成回答。中间卡片展示处理内容，右侧展示随输入变化的文字与语音表示。</p>
 <div className="ctrl">{examples.map((v,i)=><Hint key={v.name} text={`切换为${v.name}教学案例并从输入开始播放。编码路径、任务内容和示例回答都会变化。`}><button aria-pressed={mode===i} onClick={()=>select(i)}>{v.name}输入</button></Hint>)}<Hint text="每个阶段停留约 1.3 秒供观察；动画速度不代表模型推理耗时。"><button onClick={()=>{if(step===4){setStep(0);setRun(r=>r+1);}setPlaying(!playing);}}>{playing?'暂停过程':step===4?'重新播放':'播放过程'}</button></Hint><button disabled={step===4} onClick={()=>{setPlaying(false);setStep(s=>s+1);}}>下一阶段</button><button onClick={()=>{setMode(0);setStep(0);setPlaying(false);setRun(r=>r+1);}}>重置</button></div>
 <div className="flow-stage" aria-hidden="true">{stages.map((s,i)=><span key={s} className={step>=i?'done':''}/>)}</div><p className="lab-note" aria-live="polite">阶段 {step+1} / 5 · {stages[step]}{playing?' · 正在播放':''}</p>
 <div className="flow-grid" data-playing={playing} key={`${mode}-${run}`}>
 <div><div className={node(0)}><span className="lab-eyebrow">01 · 具体输入</span><h4>{e.name}提示</h4>{mode===2?<svg role="img" aria-label="教学输入图：撑开的蓝色雨伞" viewBox="0 0 220 130" style={{width:'100%',height:120,background:'#eef4fa',borderRadius:8}}><path d="M30 65 Q110 -30 190 65Z" fill="#476e9f"/><path d="M110 20V108Q110 130 90 112" stroke="#263e5e" strokeWidth="5" fill="none"/><path d="M110 20Q75 30 65 65M110 20Q145 30 155 65" stroke="#adc0d7" fill="none"/></svg>:mode===1?<div className="flow-wave">{Array.from({length:24},(_,i)=><i key={i} style={{height:12+(i*17%43),background:'#476e9f'}}/>)}</div>:null}<p>{e.input}</p>{mode===1&&<p className="lab-note">文字仅为读者说明语音案例，不代表模型先做 ASR 转录。</p>}</div><div className={`flow-arrow ${step>=1?'lit':''}`} style={{animationPlayState:playing?'running':'paused'}}/><div className={node(1)}><span className="lab-eyebrow">02 · 编码与接入</span><h4>{e.encode}</h4>{step>=1?<div className="flow-reveal"><div className="lab-token">{e.shape}</div><p>{mode===0?'文本 token 查嵌入表后进入 Thinker。':'冻结编码器提取特征，可训练投影器将其接入 Thinker。'}</p><strong style={{fontSize:13}}>→ 输入 Thinker 的统一序列</strong></div>:<p className="lab-note">下一阶段将在这里展开特征如何进入序列。</p>}</div></div>
 <div><div className={node(2)}><span className="lab-eyebrow">03 · 理解与文本</span><h4>Thinker</h4>{step>=2?<div className="flow-reveal"><p>{e.process}</p><div className="lab-track"><strong>文字路径 → 右侧回答</strong></div><div className="lab-track" style={{borderColor:'#7c3aed'}}><strong>中间状态 ↓ Talker</strong><p>默认读取第 3 号层后状态，提供内容条件。</p></div></div>:<p className="lab-note">等待特征序列；随后显示当前任务与两条输出路径。</p>}</div><div className={`flow-arrow ${step>=3?'lit':''}`}/><div className={node(3)}><span className="lab-eyebrow">04 · 声音表达</span><h4>Talker</h4>{step>=3?<div className="flow-reveal"><p>中间状态 + 已有音频码 → 预测后续音频码。</p><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:4}}>{Array.from({length:8},(_,q)=><span className="lab-token" key={q}>q{q}</span>)}</div><p>八个码本流按延迟排列；完整帧 → Mimi。</p></div>:<p className="lab-note">等待内容条件，音频码将在这一区域展开。</p>}</div></div>
 <div><div className={`flow-node ${step===2?'current':''}`}><span className="lab-eyebrow">输出 A · 文字</span><h4>本案例的回答</h4><div className="flow-output" data-testid="example-answer">{step>=2?<span className="flow-reveal">{e.output}</span>:<span className="lab-help">等待 Thinker 组织内容…</span>}</div></div><div className={`flow-arrow ${step>=4?'lit':''}`}/><div className={node(4)}><span className="lab-eyebrow">输出 B · 来自 Talker 音频码</span><h4>Mimi：完整帧 → 波形</h4>{step>=4?<div className="flow-reveal"><div className="flow-wave running">{Array.from({length:28},(_,i)=><i key={i} style={{height:10+((i*(13+mode*4))%47),animationDelay:`${i*25}ms`}}/>)}</div><p>表达内容：{e.output}</p><p className="lab-note">波形为动画示意，不是合成音频；这里没有播放声音。</p></div>:<p className="lab-note">等待完整音频帧；音频码尚未齐全时不能解码。</p>}</div></div>
 </div><div className="feedback" aria-live="polite">{step===0?`已选择${e.name}案例：${e.input}`:step===1?`${e.encode}，得到可接入 Thinker 的特征序列。`:step===2?`Thinker 示例文字已显示；中间状态同时为 Talker 提供条件。`:step===3?'Talker 的八层码本流已经展开，继续查看完整帧解码。':`本案例完成：文字与语音表达同一段回答“${e.output}”。`}</div><p className="lab-note">三组案例、组织过程说明和回答均为固定教学示意，不是模型实测或隐藏思维记录。阶段拆分用于讲解；真实生成与解码可以重叠，1.3 秒动画间隔不是推理延迟。依据：论文 p1–3 图 1–2、p5 §3、p6 §4。</p></Panel>
}
