import {useState} from 'react';import {Panel,Term} from './lab-ui';
export function C2Main(){const [mode,setMode]=useState(0),[stage,setStage]=useState(0),[patch,setPatch]=useState(0),[selected,setSelected]=useState(false),[message,setMessage]=useState('先提取并投影特征，再把向量放到序列中。');const names=['语音','图片','文字'];const ready=stage>=1;
 const reset=(m=0)=>{setMode(m);setStage(0);setSelected(false);setPatch(0);setMessage('先提取并投影特征，再把向量放到序列中。');};
 const place=(valid:boolean)=>{if(!selected){setMessage('先点击或拖动左侧的特征块。');return;}if(!valid){setMessage('这里需要离散 token 编号。模态特征是向量，不能直接当作一个文字编号。');return;}if(!ready){setMessage(mode===0?'512 维特征还不能接入 768 维隐空间；先通过音频投影器。':mode===1?'视觉编码器的输出还需要投影到统一隐空间，不能跳过投影器。':'编号不是向量；先查词嵌入表，得到 768 维文本表示。');return;}setStage(2);setMessage(`${mode===1?'64 个视觉向量':mode===0?'音频位置对应的向量':'文本嵌入向量'}已经进入统一序列。统一的是维度，位置数仍由输入决定。`);};
 return <Panel chapter={2} state={JSON.stringify({实验:'输入表示教学',模态:names[mode],阶段:stage,图像位置:patch+1,反馈:message})}><p>把特征块放进 Thinker 的输入序列，亲手检查“维度兼容”和“表示类型”这两道接口条件。<Term name="向量与编号" definition="编号指向离散词表中的一项；向量是一组连续数值。" detail="本图右侧的统一输入每位置需要 768 维向量。文本编号先查词嵌入表，非文字特征先经过投影器。它们到达相同维度的接口，但仍占据各自的位置。"/> 拖动或先选中块、再点目标区都可以。</p>
 <div className="ctrl">{names.map((n,i)=><button key={n} aria-pressed={mode===i} onClick={()=>reset(i)}>{n}</button>)}<button onClick={()=>reset()}>重置</button></div>
 <div className="lab-grid" style={{gridTemplateColumns:'1fr 1.2fr'}}><div className="lab-card"><span className="lab-eyebrow">01 · 输入与表示</span><strong>{mode===0?'SenseVoice · 冻结':mode===1?'SigLIP2 · 冻结':'文字分词'}</strong><button draggable aria-label="选择或拖动特征块" aria-pressed={selected} onDragStart={e=>{setSelected(true);e.dataTransfer.setData('text/plain','tutorial-feature');e.dataTransfer.effectAllowed='move';}} onClick={()=>setSelected(true)} style={{width:'100%',padding:24,margin:'12px 0',cursor:'grab',borderStyle:'dashed'}}>{ready?'768 维向量':mode===0?'512 维声音特征':mode===1?'64 个视觉位置的特征':'离散文本 token 编号'}<small style={{display:'block',marginTop:6}}>点击选中，或拖到右侧</small></button><button onClick={()=>{setStage(1);setSelected(true);setMessage('每个位置现在都有 768 维向量，可以放入右侧统一序列。');}}>{mode===2?'查词嵌入表 →':'经投影器映射到 768 维 →'}</button><p className="lab-note">这里改变接口形状，没有运行编码器或生成随机特征值。</p></div>
 <div className="lab-card"><span className="lab-eyebrow">02 · 放入哪里？</span><strong>Thinker 输入接口</strong><button data-testid="vector-slot" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();place(true);}} onClick={()=>place(true)} style={{width:'100%',padding:22,margin:'12px 0',border:'2px dashed #7eaa95',background:stage===2?'#e2f1e8':'#f5faf7'}}>统一向量序列 · 每位置 768 维<br/><small>{stage===2?'已填入对应向量':'将特征拖放到这里'}</small></button><button data-testid="token-slot" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();place(false);}} onClick={()=>place(false)} style={{width:'100%',padding:15,borderStyle:'dashed'}}>文本 token 编号栏<br/><small>试着比较：编号和向量是一种东西吗？</small></button></div></div>
 {mode===1&&<div className="lab-card"><strong>64 个位置，逐一对应视觉块</strong><div style={{display:'grid',gridTemplateColumns:'repeat(16,1fr)',gap:3}}>{Array.from({length:64},(_,i)=><button key={i} aria-label={`选择图像位置 ${i+1}`} aria-pressed={patch===i} onClick={()=>setPatch(i)} style={{padding:'4px 0',fontSize:11}}>{i+1}</button>)}</div><p>当前位置 {patch+1} → {stage===2?`序列视觉块的第 ${patch+1} 个向量`:'等待填入序列'}。64×768 的 64 是位置数，768 是每个位置的维度。</p></div>}
 <div className="feedback" role="status" aria-live="polite">{message}</div><p className="lab-note">依据：论文 p5 §3、p13 表 6。图像采用 64 个位置；语音位置数随输入变化。投影器改变特征维度，不把全部位置压成一个。</p></Panel>;
}
