import {useRef,useState} from 'react';import {Panel,Hint,Term} from './lab-ui';
export function Ch4Main(){const [layer,setLayer]=useState(3),drag=useRef(false);const x=90+layer*112;const pick=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();setLayer(Math.max(0,Math.min(7,Math.round(((e.clientX-r.left)*1020/r.width-90)/112))));};const explanation=layer<3?'浅层更偏向 token 身份，上下文信息仍在积累。':layer<6?'中部状态给 Talker 提供上下文条件；默认在第 3 号层后连接。':'末层更偏向下一文本 token 分类。作者认为过深的桥接不利于语音内容一致性。';return <Panel chapter={4} state={JSON.stringify({实验:'桥接层教学',零基层:layer,已经过:layer+1,后续:7-layer,说明:explanation})}>
 <p>拖动橙色桥接点，把线接到不同层后面。桥接是一条分支：取出<Term name="中间隐状态" definition="某一层计算后得到的向量表示，包含截至该层整合的信息。" detail="它不是已经写出的句子，也不是可直接阅读的内心推理。图中橙线把它送给 Talker，而蓝色主路径仍经过剩余层继续预测文本。"/>后，Thinker 的剩余层仍继续生成文字。</p>
 <svg viewBox="0 0 1020 265" role="img" aria-label={`可拖动桥接图，当前第 ${layer} 号层后，已过 ${layer+1} 层，余下 ${7-layer} 层`} style={{width:'100%',background:'#f1f6fc',borderRadius:12,touchAction:'none',userSelect:'none',cursor:'grab'}} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();drag.current=true;e.currentTarget.setPointerCapture(e.pointerId);pick(e);}} onPointerMove={e=>{if(drag.current)pick(e);}} onPointerUp={()=>{drag.current=false;}} onPointerCancel={()=>{drag.current=false;}}>
 <path d="M30 80 H978" fill="none" stroke="#b7c9df" strokeWidth="3"/>{Array.from({length:8},(_,i)=><g key={i}><rect x={55+i*112} y={45} width="70" height="70" rx="8" fill={i<=layer?'#d5e5f4':'#f9fbfd'} stroke={i===3?'#258162':'#a6bcd6'} strokeWidth={i===3?3:1}/><text x={90+i*112} y="88" textAnchor="middle" fill="#27446e" fontSize="24">{i}</text><text x={108+i*112} y="138" textAnchor="start" fill="#617992" fontSize="12">{i===3?'论文默认':''}</text></g>)}<text x="34" y="26" fill="#27446e" fontSize="15">输入 → Thinker 8 层 → 最终文字</text>
 <path d={`M${x} 115 V175 H510 V205`} fill="none" stroke="#d58b3d" strokeWidth="4"/><circle cx={x} cy="115" r="11" fill="#fff" stroke="#d58b3d" strokeWidth="4"/><rect x="420" y="205" width="180" height="42" rx="8" fill="#e6f1eb" stroke="#258162"/><text x="510" y="232" textAnchor="middle" fill="#27446e" fontSize="18">Talker 接收状态</text></svg>
 <div className="ctrl">{Array.from({length:8},(_,i)=><Hint key={i} text={`第 ${i} 号层是从 1 开始数的第 ${i+1} 层；之后还有 ${7-i} 层继续计算。`}><button aria-pressed={layer===i} onClick={()=>setLayer(i)}>层 {i}</button></Hint>)}<button onClick={()=>setLayer(3)}>恢复论文默认层 3</button></div>
 <div className="lab-grid"><div className="lab-card"><strong>到桥接点已经过</strong><output className="lab-metric" data-testid="bridge-before">{layer+1} 层</output></div><div className="lab-card"><strong>Thinker 后续继续</strong><output className="lab-metric" data-testid="bridge-after">{7-layer} 层</output></div></div>
 <div className="feedback" aria-live="polite">第 {layer} 号层后 → Talker。{explanation}</div><p className="lab-note">依据：论文 p5 §3.1。默认零基位置 8÷2−1=3，即第 4 层后。浅、中、深为教学分组，论文没有完整逐层 CER 数表，本图不产生性能排名。</p></Panel>}
