import {useState} from 'react';
import {MechanismField} from './mechanism-field';import {useTimeline} from './reading-wheel';import {Panel} from './lab-ui';
export function Ch6Main(){const timeline=useTimeline(12),step=Math.floor(timeline.progress+1e-8);const [strategy,setStrategy]=useState('streaming'),[frame,setFrame]=useState(0);const complete=Math.max(0,step-7),available=strategy==='streaming'||step===12?complete:0;return <Panel chapter={6} state={JSON.stringify({实验:'延迟排列教学',连续进度:timeline.progress.toFixed(3),生成步:step,帧:frame+1,策略:strategy,完整帧:complete,可释放:available})}>
 <p>一条游标同时控制上方汇合图和下方延迟矩阵。沿橙色斜线追踪同一帧；线路可以连续移动，只有跨过生成步边界才增加已收集的码。</p>
 <div className="ctrl"><label>追踪帧<select aria-label="追踪音频帧" value={frame} onChange={e=>setFrame(Number(e.target.value))}>{[0,1,2,3,4].map(f=><option key={f} value={f}>第 {f+1} 帧</option>)}</select></label><label>播放策略<select aria-label="播放策略" value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="streaming">逐帧可用</option><option value="wait">整段等待</option></select></label><button onClick={()=>timeline.seek(Math.max(0,Math.ceil(timeline.progress)-1))}>上一步</button><button onClick={()=>timeline.seek(Math.min(12,Math.floor(timeline.progress)+1))}>下一步</button><button onClick={()=>{timeline.seek(0,true);setStrategy('streaming');setFrame(0);}}>重置</button></div>
 <MechanismField kind="frame" timeline={timeline} frame={frame} strategy={strategy}>
 <div style={{padding:'4px 18px 14px'}}><div className="lab-scroll" tabIndex={0} aria-label="音频码延迟矩阵"><div style={{display:'grid',gridTemplateColumns:'35px repeat(13,minmax(26px,1fr))',gap:3,fontSize:11,textAlign:'center'}}><span>q / 步</span>{Array.from({length:13},(_,s)=><span key={s} style={{fontWeight:s===step?800:400,color:s===step?'#27446e':'#68778f'}}>{s}</span>)}{Array.from({length:8},(_,q)=><Row key={q} q={q} step={step} progress={timeline.progress} frame={frame} complete={complete}/>)}</div></div><div className="feedback" aria-live="polite"><strong>第 {step} 步：完整帧 {complete} 个，可释放 {available} 个。</strong>{complete>available?'帧已完整，当前策略仍等待片段结束。':step<8?'首帧还未集齐八层码。':'完整帧可以增量解码，不必等整句结束。'}</div></div>
 </MechanismField>
 <p className="lab-note">数字为从 1 开始的帧编号；“·”尚未生成，“—”延迟空位。浅蓝游标在整列之间连续移动，橙框表示所选帧的各层位置。依据：论文 p6 §4、公式 1。第 12 步为人为教学终点，不是模型实测结束时间；80 ms 是一帧的覆盖时长。</p></Panel>}
function Row({q,step,progress,frame,complete}:{q:number;step:number;progress:number;frame:number;complete:number}){return <><span style={{padding:4}}>q{q}</span>{Array.from({length:13},(_,s)=>{const f=s-q-1,active=f>=0&&s<=step,glow=Math.max(0,1-Math.abs(s-progress));return <span key={s} style={{padding:'4px 0',borderRadius:3,background:active?f<complete?'#deefe5':'#e1eaf6':`rgba(112,157,204,${.04+glow*.3})`,color:active?'#24394e':'#8997a7',boxShadow:f===frame?'inset 0 0 0 2px #d8924d':undefined,fontWeight:f===frame?700:400}}>{f<0?'—':active?f+1:'·'}</span>})}</>}
