import {useEffect,useRef,useState} from 'react';import {Panel,Term} from './lab-ui';
const costs=[.7,.8,.5,.9,.6,.4,.3,.5,.2,.4,.6];
export function Ch7Main(){const [voice,setVoice]=useState('a'),[brush,setBrush]=useState(true),[mask,setMask]=useState(Array.from({length:11},(_,i)=>i>=6));const dragging=useRef(false),lastPaint=useRef<number|null>(null);useEffect(()=>{const release=()=>{dragging.current=false;lastPaint.current=null;};window.addEventListener('pointerup',release);window.addEventListener('pointercancel',release);return()=>{window.removeEventListener('pointerup',release);window.removeEventListener('pointercancel',release);};},[]);const length=voice==='a'?3:voice==='b'?5:0,valid=(i:number)=>i>=6-length;const active=mask.map((v,i)=>v&&valid(i));const total=active.reduce((s,v,i)=>s+(v?costs[i]:0),0),n=active.filter(Boolean).length,wrongCondition=active.slice(0,6).some(Boolean),missingTarget=active.slice(6).some(v=>!v);const resetMask=()=>setMask(Array.from({length:11},(_,i)=>i>=6));const paint=(i:number)=>{const from=dragging.current&&lastPaint.current!==null?lastPaint.current:i;if(valid(i))setMask(old=>old.map((v,j)=>valid(j)&&j>=Math.min(from,i)&&j<=Math.max(from,i)?brush:v));lastPaint.current=i;};return <Panel chapter={7} state={JSON.stringify({实验:'损失掩码教学',参考:voice,计分掩码:active,人工损失总和:total,实测:false})}>
 <p>参考音频提供条件，回答音频才是监督目标。用画笔修改<Term name="损失掩码" definition="用 0 或 1 指定某个位置是否参与当前目标的损失计算。" detail="mask 为 0 不等于删除输入：条件区仍参与前向计算、影响回答，只是不在这些位置要求模型重建参考。下方数值是人工示例，用来辨认少计位置与真正降低误差的区别。"/>，选择哪些位置计入损失，观察把条件当目标或漏掉目标会发生什么。</p>
 <div className="ctrl"><label>音色条件<select aria-label="音色条件" value={voice} onChange={e=>{setVoice(e.target.value);resetMask();}}><option value="none">无外部参考</option><option value="a">参考 A · 3 个示意位置</option><option value="b">参考 B · 5 个示意位置</option></select></label><button aria-pressed={brush} onClick={()=>setBrush(true)}>画笔：计入损失</button><button aria-pressed={!brush} onClick={()=>setBrush(false)}>画笔：排除损失</button><button onClick={resetMask}>恢复正确掩码</button><button onClick={()=>{setVoice('a');setBrush(true);resetMask();}}>重置</button></div>
 <div className="lab-grid" style={{gridTemplateColumns:'6fr 5fr'}}><div className="lab-card"><strong>条件区 · 正确 mask = 0</strong><p>{length?'CAM++ 192 维说话人向量 + 参考音频码':'无外部参考，仍可使用默认声音'}</p></div><div className="lab-card"><strong>目标区 · 有效位置 mask = 1</strong><p>需要生成的回答音频码</p></div></div>
 <div role="group" aria-label="可刷选损失掩码" style={{display:'grid',gridTemplateColumns:'repeat(11,1fr)',gap:5,userSelect:'none',touchAction:'none'}}>{mask.map((_,i)=><button key={i} aria-label={valid(i)?i<6?'参考位置 R'+(i-(6-length)+1):'目标位置 T'+(i-5):'空位 '+(i+1)} disabled={!valid(i)} aria-pressed={active[i]} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();lastPaint.current=null;dragging.current=true;paint(i);}} onPointerEnter={()=>{if(dragging.current)paint(i);}} onClick={e=>{if(e.detail===0)paint(i);}} style={{padding:'14px 3px',borderColor:i===6?'#d88b3c':undefined,background:active[i]?(i<6?'#f9e1c9':'#dff0e7'):'#edf2f7',color:'#27446e'}}>{valid(i)?i<6?`R${i-(6-length)+1}`:`T${i-5}`:'空'}<small style={{display:'block',marginTop:9}}>mask {active[i]?1:0}</small><small style={{display:'block'}}>L {valid(i)?costs[i].toFixed(1):'—'}</small></button>)}</div>
 <p className="lab-note">按住鼠标划过多个位置可刷选；键盘也可逐个聚焦并操作。参考从右侧对齐，空位不可参与计分。</p>
 <div className="lab-grid"><div className="lab-card"><strong>计分位置</strong><output className="lab-metric" data-testid="mask-count">{n}</output></div><div className="lab-card"><strong>教学损失总和</strong><output className="lab-metric" data-testid="mask-sum">{total.toFixed(1)}</output></div><div className="lab-card"><strong>所选位置的平均值</strong><output className="lab-metric">{n?(total/n).toFixed(3):'无计分位置'}</output></div></div>
 <div className="feedback" aria-live="polite">{wrongCondition?'参考被当成目标计分了：条件可以影响回答，但不应要求模型在这些位置重建参考。 ':''}{missingTarget?'有目标位置被排除，监督信号缺失。 ':''}{!wrongCondition&&!missingTarget?'掩码正确：参考用于提供条件，有效回答位置参与监督。':''}损失数值降低可能只是少计了位置，不一定代表模型变好。</div>
 <p className="lab-note">依据：论文 p5 §3、p6 §4。每个位置的 L 为人为给定的教学数值，求和与平均仅展示掩码作用，不是论文实际训练损失或权重方案。参考长度亦为示意。CAM++ 向量预计算。</p></Panel>}
