import {RankWorkbench} from './rank-workbench';
import {MouseStage} from './mouse-stage';
import {useState} from 'react';import {Panel,Hint} from './lab-ui';
const experiments=[{e:16,h:16,loss:5.453},{e:16,h:256,loss:5.100},{e:256,h:16,loss:5.353},{e:256,h:256,loss:5.002}];
export function Ch8Main(){const [shared,setShared]=useState(true),[pair,setPair]=useState(0),[book,setBook]=useState(0),[side,setSide]=useState<'e'|'h'>('e');const v=experiments[pair];const r=v[side];const change=(i:number)=>{setPair(i);setShared(true);};
return <Panel chapter={8} state={JSON.stringify({实验:'论文图8f',嵌入秩:v.e,输出秩:v.h,audioLoss:v.loss,码本:book,结构:shared?'共享主体加修正':'独立接口'})}><p>八个码本都需要接口。先在小矩阵上看清细节与成本，再对照论文配置。结构总览可以按需展开，选择码本与接口端查看共享方式。</p>

<details className="lab-card" style={{marginTop:14}}><summary style={{cursor:"pointer",fontWeight:650}}>结构对照：八份独立接口与共享主体</summary><div className="ctrl"><button aria-pressed={!shared} onClick={()=>setShared(false)}>八份独立接口</button><button aria-pressed={shared} onClick={()=>setShared(true)}>共享主体＋低秩修正</button><button onClick={()=>{setShared(false);setPair(0);setBook(0);setSide('e');}}>重置</button></div>
<div className="lab-card"><strong>{shared?'一个共享主体，八份专属修正':'八个码本各有一份完整接口'}</strong><div style={{display:'grid',gridTemplateColumns:'repeat(8,1fr)',gap:7}}>{Array.from({length:8},(_,q)=><Hint key={q} text={`追踪 q${q} 的接口。码本编号与秩配置是独立选择。`}><button style={{width:'100%',padding:'14px 3px'}} aria-pressed={book===q} onClick={()=>setBook(q)}>q{q}<small style={{display:'block',fontSize:10}}>{shared?'专属修正':'完整接口'}</small></button></Hint>)}</div></div>
{shared?<div className="shot-enter" key={`${side}-${pair}-${book}`}><div className="ctrl"><button aria-pressed={side==='e'} onClick={()=>setSide('e')}>嵌入端 E：码 → 向量</button><button aria-pressed={side==='h'} onClick={()=>setSide('h')}>输出头 H：状态 → 码分数</button></div><MouseStage book={book} side={side} rank={r}/></div>:<div className="feedback">当前追踪 q{book}：保存一份完整接口。切换到共享结构后，将在图中展开公共矩阵、两个低秩矩阵及它们组合出的接口。</div>}
</details><RankWorkbench/><div className="lab-card" style={{marginTop:18}}><strong>配置 → 实验结果：只使用论文的四个点</strong><p className="lab-note">上方 4×4 矩阵讲解基础原理；这里的 E/H=16 或 256 是论文配置。两组秩不互相换算。</p><div className="ctrl">{experiments.map((x,i)=><Hint key={i} text={`切换为 E${x.e}/H${x.h}，下方真实 loss 更新；展开结构总览可查看对应的接口秩。`}><button aria-pressed={pair===i} onClick={()=>change(i)}>E{x.e} / H{x.h}</button></Hint>)}</div><div className="lab-grid"><div><div className="lab-note">当前配置</div><div className="lab-metric">E{v.e} / H{v.h}</div></div><div><div className="lab-note">论文 audio loss ↓</div><div className="lab-metric" data-testid="rank-loss">{v.loss.toFixed(3)}</div></div><div><div className="lab-note">相对 E16/H16 的 loss 下降</div><div className="lab-metric">{(5.453-v.loss).toFixed(3)}</div></div></div>{experiments.map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'115px 1fr 55px',gap:10,alignItems:'center',margin:'8px 0',fontSize:12}}><span>E{x.e}/H{x.h}</span><div style={{background:'#edf1f6',height:15}}><div style={{width:`${x.loss/6*100}%`,height:'100%',background:pair===i?'#27446e':'#aabccf',transition:'background .4s'}}/></div><strong>{x.loss.toFixed(3)}</strong></div>)}<p className="lab-note">同轴从 0 到 6。差值由论文四个数直接相减；低 loss 不是音质评分。</p></div>
<div className="feedback">固定 E16，提高 H：5.453 → 5.100，下降 0.353。固定 H16，提高 E：5.453 → 5.353，下降 0.100。这组条件下输出头秩更敏感，不能推出所有任务的最优秩。</div><p className="lab-note">来源：论文图 8(f)，冻结 Thinker 的 A2A 子集消融。接口组合图为低秩结构解释，面积不是模型参数比例；独立结构无对应实测 loss。</p></Panel>}
