import {WorkedCase} from './worked-cases';
import {useState} from 'react';
type Note={title:string;body:string};
const notes:Record<number,Note[]>={
1:[{title:'小模型的研究价值在哪里？',body:'这个工作的价值之一是把多模态输入、文字回答和语音生成放进一个较小、可检查的系统。较小的主体让结构与训练取舍更容易研究，但参数少本身不能证明回答质量好，也不能证明包含所有外部组件后仍然轻量。'}, {title:'“语音原生”怎样理解？',body:'在本教程中，重点是音频特征可以作为输入，音频码可以作为输出；理解与表达通过模型内部状态相连。它不是单纯把自动语音识别、语言模型、文字转语音三个服务串起来。这个结构差异也不意味着所有级联系统都更差。'}],
2:[{title:'位置数与特征维度是两条轴',body:'把一段特征写成 L×D：L 是序列中有多少个位置，D 是每个位置携带多少维数值。投影器解决“每个位置的向量怎样接入 Thinker”的问题；它不等于把所有位置压成一个。图像的 64×768 表示 64 个向量，每个向量 768 维。'}, {title:'冻结编码器，为什么投影器还能学习？',body:'冻结是指训练时不更新该模块的参数，不是指其输出永远相同。输入图片或声音变化时，提取的特征也会变化。后面的可训练投影器学习如何把这些特征映射到语言模型可以使用的空间。'}, {title:'占位位置不等于普通文字',body:'序列中的预留位置用于放入模态向量。最终参与计算的是特征嵌入，而不是让模型只看到“这里有一张图片”几个字。因此，统一序列是计算接口的统一，不是把所有输入先转成自然语言。'}],
3:[{title:'为什么不只把最终文字交给 Talker？',body:'最终文字是已经离散化的输出；中间隐状态仍是向量表示，携带模型处理上下文时的内部信息。本文用中间状态给 Talker 提供条件，让声音生成与理解过程联系起来。不能仅凭这个设计就断言模型具备了全部语气、情感或细微声音理解能力。'}, {title:'为什么还需要音频历史？',body:'自回归预测要根据已经生成的序列决定下一项。Thinker 的状态提供内容条件，Talker 的历史音频码提供已经说到哪里的信息。二者承担不同角色；Mimi 随后负责把完整音频帧解码成波形。'}],
4:[{title:'浅层、中间层、末层：比较的是信息角色',body:'论文的解释是，浅层仍较偏向 token 身份，而末层更受下一文本 token 分类目标影响。为 Talker 提供条件时，中间位置可以在这些因素之间取得折中。这是作者针对该模型的设计解释，不是所有 Transformer 的通用最优规律。'}, {title:'为什么默认是第 3 号层？',body:'默认 Thinker 有 8 层，论文使用 N//2−1 这一零基位置：8//2−1=3。从 1 开始数，这就是第 4 层之后。桥接只是从这里读取状态，Thinker 后面的层仍继续计算文字输出。'}, {title:'没有逐层数表，应该怎样展示？',body:'我们可以准确展示桥接位置与默认配置，也可以转述作者对太浅或太深的解释。但不能给每一层编一个“语义完成度”、CER 或音质分数。缺失的实验结果应当保持缺失，而不是用看起来合理的曲线补齐。'}],
5:[{title:'码本里的“码”是什么？',body:'这里的码是离散索引，不是一段文字，也不是直接表示响度的数值。一个音频帧由八层码本的码共同表示。Mimi 解码时使用完整的表示恢复波形；把一个码值改大，不等于把声音调大。'}, {title:'时间轴和码本轴为什么容易混淆？',body:'同一帧的八个码对应同一个时间片段；相邻帧才对应时间向前推进。12.5 帧/秒意味着每帧覆盖 80 毫秒音频，但生成这帧花了多久，是另外一个需要测量的问题。下面的换算不估计推理速度。'}],
6:[{title:'一列不是一帧',body:'延迟排列中，一列代表同一个生成步，各层在这一列预测的码可以属于不同音频帧。想收集同一帧，必须沿对角线寻找；八层齐全后才能交给解码器。把一整列误当成一帧，就会误判何时能够开始播放。'}, {title:'把排列写成索引关系',body:'令第一个文字生成为相对步 s=0，码本层用 q=0…7，帧用零基 f=0…表示。教学图中的对应关系是 s=f+q+1。因此第 f 帧的最后一层在 s=f+8 到达。若改用从 1 开始数的帧编号 F，则完成步为 F+7。'}, {title:'流式输出省掉了什么等待？',body:'流式策略允许完整帧尽早释放，不要求等待整段音频结束。它并不消除编码、模型计算、解码与播放缓冲的时间。图中等待策略只改变释放时机，不改变生成顺序；第 12 步是人为选择的教学终点。'}],
7:[{title:'说话人向量和参考音频码承担不同角色',body:'说话人向量是 CAM++ 预计算的 192 维条件，参考音频还可以提供相应的码序列。这里把二者作为条件路径展示，不把它们当成生成目标。参考长度改变时，右对齐让参考末尾靠近目标起点。'}, {title:'掩码在排除什么？',body:'训练损失只应在相应的有效目标位置计算。参考区属于条件，音频损失掩码为 0；有效目标音频位置参与监督。掩码不是删除条件：参考仍然可以影响预测，只是不要求模型为这部分内容承担目标预测误差。'}],
8:[{title:'共享主体与低秩差异怎样配合？',body:'可以把每个码本接口理解为共享矩阵加上码本专属的小修正。若一个修正矩阵是 m×n，直接存储需要 mn 个数；用 m×r 与 r×n 两个矩阵相乘表达，则需要 r(m+n) 个数。只有 r 足够小时，这部分表示才更省参数。'}, {title:'秩 r 增大意味着什么？',body:'较大的 r 能表达更丰富的线性差异，同时增加参数与计算。本章的矩阵实验只比较修正矩阵的参数数目，不包含共享主体、偏置或其他模块，因此不能代替论文的完整模型参数统计。'}, {title:'E 和 H 为什么分开试？',body:'E 是嵌入端适配的秩，H 是输出头适配的秩。图 8(f) 在冻结 Thinker 的 A2A 子集实验上比较四种配置；报告的是 audio loss，不是 CER。在这组设置里，提高输出头秩带来的 loss 降低更明显，但不能据此推出任何任务都应该采用最大的秩。'}],
9:[{title:'任务与可训练范围是两个独立问题',body:'T2A、I2T、A2A 描述输入与目标；all、audio_proj、vision_proj 描述哪些参数可以更新。某模块被冻结，并不意味着从计算图中删除它。只训练投影器时，固定的后续网络仍可用于计算误差和传递梯度。'}, {title:'联合监督怎样理解？',body:'有回答文字和目标音频的任务可以同时监督文字与各音频码本流。不同目标有不同的有效位置；参考条件、输入位置和无效位置不能不加区分地当作目标。I2T 没有目标音频，不能为它凭空添加音频监督。'}, {title:'为什么不画成唯一固定训练流水线？',body:'论文对训练阶段的概括与实现脚本中的模式需要分别理解。教程展示的是任务、更新范围、监督位置之间的关系，不把它们拼成未经证实的唯一时间顺序。完整论文实验配置也不能与作者 mini 示例的耗时混为一谈。'}],
10:[{title:'CER 到底比较什么？',body:'CER 通常以字符级编辑距离衡量转录与参考的差异：替换数 S、删除数 D、插入数 I 的和，除以参考字符数 N。本文内部一致性评估把生成语音经 ASR 转录后，与 Thinker 文字比较。这会受到发音、ASR 错误和文本格式等因素共同影响。'}, {title:'为什么 WER 可以大于 1？',body:'WER 在词的层面计算，分母是参考词数；大量插入会使错误总数超过分母。因此它是错误率，不能当成准确率或概率。论文表 5 中大于 1 的值并不意味着算错，但也不能被解释成一个直接的视觉理解评分。'}, {title:'实验之间为什么不能直接排总榜？',body:'表 2 比较内部 Talker 宽度，表 3 比较说话人相似度，表 4 使用 20 个简短英文问题比较 T2A 一致性，表 5 是 9 张合成图片上的有限比较。任务、参考构造与指标含义不同，不能把这些数字混成一个“模型能力总分”。'}]
};
const loc:Record<number,string>={1:'p1 摘要、p2 图 1',2:'p5 §3、p13 表 6',3:'p3 图 2、p13 表 6',4:'p5 §3.1',5:'p4 图 3、p6 §4',6:'p6 §4、公式 1',7:'p5 §3、p6 §4',8:'p11 图 8(f)',9:'p6 §5、p7 表 1',10:'p8–10 表 2–5'};
const checks:Record<number,{q:string;options:string[];answer:number;why:string}>={
1:{q:'只看到“约 0.1B”，能确定整套运行系统只有这么多参数吗？',options:['可以，标题已经给出总数','不可以，还要核对冻结外部组件'],answer:1,why:'主模型与整个系统的统计范围不同。SenseVoice、SigLIP2、Mimi 等冻结组件需要另外核对。'},
2:{q:'64×768 的图像特征中，“64”指什么？',options:['图像位置数','每个位置的维度','64 个文字词'],answer:0,why:'64 是位置数，768 是每个位置的向量维度；并不是 64 个文字词。'},
3:{q:'Talker 生成后续音频时，只需要 Thinker 最终文字吗？',options:['是，等价于独立 TTS','否，还使用中间状态与音频历史'],answer:1,why:'中间隐状态与已有音频码是关键条件，不能把该连接简化为最终文字输入。'},
4:{q:'读取第 3 号层的状态，是否让后面的 Thinker 层停止计算？',options:['会，后面层被跳过','不会，文字路径继续计算'],answer:1,why:'桥接是读取中间状态，不是把 Thinker 截断。'},
5:{q:'一个码值由 20 改成 40，能否判断音量翻倍？',options:['能，码值就是振幅','不能，码值是离散索引'],answer:1,why:'索引与音量不存在这种比例关系。教程中的示例码值也不是模型预测。'},
6:{q:'第 7 步已生成不少音频码，第一帧可以解码了吗？',options:['可以，码数量已经很多','还不行，第 8 层尚未到齐'],answer:1,why:'第一帧需要 q=0…7 的全部八层；最后一层在相对第 8 步到达。'},
7:{q:'条件区 mask=0，是否说明模型完全看不到参考音频？',options:['是，mask=0 就是删除输入','否，它仍是条件，只不计目标损失'],answer:1,why:'这里讨论损失掩码。没有目标监督与不参与条件计算是两回事。'},
8:{q:'图 8(f) 的 audio loss 可以直接当作 CER 吗？',options:['不能，它们定义和评估过程不同','可以，都是越低越好'],answer:0,why:'方向相同不代表含义相同。loss 反映训练目标，CER 要比较转录与参考字符。'},
9:{q:'只更新投影器时，冻结的 Thinker 一定不参与前向计算吗？',options:['一定不参与','仍可参与计算并传递梯度'],answer:1,why:'冻结参数与删除模块不同；投影器需要通过后续计算获得学习信号。'},
10:{q:'两个模型 CER 相同，能否断定声音同样自然？',options:['能，CER 就是声音质量','不能，需要听感或其他评估'],answer:1,why:'CER 主要反映该协议下的转录一致性，不评价音色、韵律、自然度的全部方面。'}
};
export function DeepDive({chapter}:{chapter:number}){const [chosen,setChosen]=useState<number|null>(null),[submitted,setSubmitted]=useState(false);const c=checks[chapter];return <section style={{marginTop:28,borderTop:'1px solid #dce3eb',paddingTop:20}}>
 <div className="lab-eyebrow">深入理解 · 从操作走向原理</div><h3 style={{fontSize:20,margin:'8px 0 16px'}}>再往下想一层</h3>
 {notes[chapter].map(n=><details key={n.title} style={{borderBottom:'1px solid #e2e8f0',padding:'12px 0'}}><summary style={{cursor:'pointer',fontWeight:650,color:'#27446e'}}>{n.title}</summary><p style={{margin:'12px 0',lineHeight:1.9}}>{n.body}</p></details>)}
 <p className="lab-note">论文定位：{loc[chapter]}。下列练习中的数字例子为教学推导，不是额外模型实验。</p>
 <WorkedCase chapter={chapter}/>{chapter===3&&<Routing/>}{chapter===5&&<AudioCount/>}{chapter===6&&<FramePredict/>}
 <div className="lab-card" style={{marginTop:18}}><span className="lab-eyebrow">概念辨析 · 先判断，再看解释</span><strong style={{marginTop:8}}>{c.q}</strong><div className="ctrl">{c.options.map((o,i)=><button key={o} aria-pressed={chosen===i} onClick={()=>{setChosen(i);setSubmitted(false);}}>{o}</button>)}</div><button disabled={chosen===null} onClick={()=>setSubmitted(true)}>核对判断</button> <button onClick={()=>{setChosen(null);setSubmitted(false);}}>重新判断</button>{submitted&&<div className="feedback" role="status" style={{marginTop:12}}><strong>{chosen===c.answer?'判断正确。':'这里容易混淆。'}</strong>{c.why}</div>}</div>
 </section>}
function Routing(){const [route,setRoute]=useState(['','','']);const [show,setShow]=useState(false);const sources=['Thinker 中间状态','Talker 的完整音频帧','Thinker 的最终文字'];const right=['Talker','Mimi','阅读界面'];return <div className="lab-card" style={{marginTop:18}}><strong>连接任务：三种信息应该送往哪里？</strong><p className="lab-note">为每条信息选择去向，再检查。此处保留文字输出供人阅读这一路。</p>{sources.map((s,i)=><label key={s} style={{margin:'10px 0'}}>{s} → <select aria-label={s+'的去向'} value={route[i]} onChange={e=>{setRoute(route.map((v,j)=>j===i?e.target.value:v));setShow(false);}}><option value="">选择接收方</option>{['Talker','Mimi','阅读界面'].map(v=><option key={v}>{v}</option>)}</select></label>)}<button disabled={route.some(r=>!r)} onClick={()=>setShow(true)}>检查连接</button> <button onClick={()=>{setRoute(['','','']);setShow(false);}}>清空连接</button>{show&&<div role="status" className="feedback">{route.every((v,i)=>v===right[i])?'三条路径全部连接正确。':'有路径接错：'}中间状态 → Talker；完整音频帧 → Mimi；最终文字 → 阅读界面。Talker 并不是最终文字的独立 TTS 出口。</div>}</div>}
function AudioCount(){const [frames,setFrames]=useState(10);return <div className="lab-card" style={{marginTop:18}}><strong>数量实验：音频帧、码、波形采样点</strong><label>帧数 {frames}<input aria-label="换算音频帧数" type="range" min="1" max="50" value={frames} onChange={e=>setFrames(Number(e.target.value))}/></label><div className="lab-grid">{[['覆盖音频时长',`${(frames/12.5).toFixed(2)} 秒`],['八层码本索引总数',`${frames*8} 个码`],['24 kHz 波形采样点',`${frames*1920} 个`]].map(([a,b])=><div key={a}><div className="lab-note">{a}</div><div className="lab-metric">{b}</div></div>)}</div><p>计算：帧数 ÷ 12.5；帧数 × 8；时长 × 24,000。码的数量不是文件字节数，覆盖音频时长不是模型推理耗时。</p><button onClick={()=>setFrames(10)}>恢复 10 帧</button></div>}
function FramePredict(){const [frame,setFrame]=useState(2),[guess,setGuess]=useState(''),[show,setShow]=useState(false);return <div className="lab-card" style={{marginTop:18}}><strong>预测任务：第几步才能集齐？</strong><label>帧编号（从 1 开始）<select aria-label="预测目标帧" value={frame} onChange={e=>{setFrame(Number(e.target.value));setShow(false);}}>{[1,2,3,4,5].map(f=><option key={f}>{f}</option>)}</select></label><label>你预测的生成步<input aria-label="预测完成步" type="number" min="0" max="20" value={guess} onChange={e=>{setGuess(e.target.value);setShow(false);}}/></label><button disabled={guess===''} onClick={()=>setShow(true)}>验证预测</button>{show&&<div role="status" className="feedback">{Number(guess)===frame+7?'预测正确。':'再沿斜线看一遍。'}第 {frame} 帧在 q=0 层从第 {frame} 步开始，q=7 在第 {frame+7} 步到达，因此第 {frame+7} 步集齐。两端包含八个生成位置。</div>}</div>}
export const DeepDiveWidget=()=>null;
