import {useState,type PointerEvent} from 'react';
const topics=[
 {word:'多模态输入',en:'INPUT',chapter:1,x:15,y:15,depth:14,desc:'文字、语音、图片通过不同路径进入模型，最终产生文字与语音。',prompt:'输入变了，处理过程怎样变？'},
 {word:'统一序列',en:'REPRESENTATION',chapter:2,x:37,y:12,depth:28,desc:'编码器提取特征，投影器接入隐空间，让不同来源的向量进入同一序列。',prompt:'位置数和特征维度有什么区别？'},
 {word:'Thinker × Talker',en:'CORE ARCHITECTURE',chapter:3,x:49,y:47,depth:50,desc:'Thinker 组织内容，Talker 结合中间状态与音频历史生成后续音频码。',prompt:'理解和声音表达，怎样连在一起？'},
 {word:'中间隐状态',en:'SEMANTIC BRIDGE',chapter:4,x:70,y:17,depth:32,desc:'默认读取第 3 号层后的状态，为 Talker 提供条件；这不是最终文字的简单转交。',prompt:'为什么不只读取最后一层？'},
 {word:'八层码本',en:'AUDIO TOKENS',chapter:5,x:87,y:40,depth:18,desc:'一个音频帧由八层码本共同表示。码是离散索引，不是音量或音高。',prompt:'八层码，怎样组成同一帧？'},
 {word:'流式生成',en:'STREAMING',chapter:6,x:73,y:75,depth:36,desc:'音频码按层延迟排列，完整帧可以逐帧解码，减少等待整段生成结束的需要。',prompt:'第一帧什么时候才算完整？'},
 {word:'声音条件',en:'VOICE CONDITION',chapter:7,x:92,y:88,depth:12,desc:'说话人向量与参考音频作为条件参与预测；条件区不计入目标音频损失。',prompt:'参考声音和生成目标有什么不同？'},
 {word:'低秩适配',en:'SHARED + LOW RANK',chapter:8,x:41,y:83,depth:26,desc:'用共享主体加码本专属修正，减少接口重复。秩配置与效果需要结合实验判断。',prompt:'共享之后，怎样保留每个码本的差异？'},
 {word:'训练与冻结',en:'LEARNING',chapter:9,x:16,y:72,depth:20,desc:'输入与监督决定学什么，训练模式决定更新谁。冻结参数不等于跳过计算。',prompt:'哪些模块参与计算，哪些真正更新？'},
 {word:'实验边界',en:'EVIDENCE',chapter:10,x:10,y:44,depth:10,desc:'CER、WER 与说话人相似度回答不同问题；低转录错误率不等于声音自然。',prompt:'这些数字能证明什么，又不能证明什么？'}
];
const css=`
.keyword-intro{min-height:100vh;background:#080e19;color:#e7f0ff;font-family:Inter,'Microsoft YaHei',system-ui,sans-serif;position:relative;isolation:isolate;overflow:hidden;padding:30px 6vw 26px;box-sizing:border-box}
.keyword-intro *{box-sizing:border-box}.keyword-intro:before{content:'';position:absolute;inset:0;z-index:-1;pointer-events:none;background:radial-gradient(550px circle at var(--light-x,60%) var(--light-y,35%),#244d713d,transparent 85%),radial-gradient(ellipse at 15% 90%,#24244a80,transparent 60%)}
.ki-top{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #6f8dac30;padding-bottom:18px;font-size:11px;letter-spacing:2px;color:#8ba3c0}.keyword-intro button{font:inherit;cursor:pointer}.ki-quiet{background:transparent;color:#c7d7ec;border:1px solid #5572936b;padding:9px 15px;border-radius:30px;letter-spacing:0;font-size:13px!important}.ki-header{display:flex;align-items:flex-end;justify-content:space-between;margin:30px 0 12px;gap:30px}.ki-header h1{font-size:clamp(42px,5.5vw,76px);font-weight:550;letter-spacing:-3px;margin:0;line-height:1.05;color:#edf5ff}.ki-header h1 span{color:#82b9e2}.ki-subtitle{margin:10px 0 0;color:#9fb3cd;font-size:16px;letter-spacing:3px}.ki-instruction{max-width:290px;color:#899fb9;font-size:13px;line-height:1.9;margin:0}
.ki-space{height:380px;max-width:1250px;margin:auto;position:relative;perspective:1000px;touch-action:pan-y}.ki-world{position:absolute;inset:0;transform-style:preserve-3d;transform:rotateX(var(--rx,0deg)) rotateY(var(--ry,0deg));transition:transform .18s ease-out}.ki-world svg{position:absolute;inset:0;width:100%;height:100%;overflow:visible;pointer-events:none}.ki-word{position:absolute;transform:translate(-50%,-50%) translateZ(var(--depth));background:transparent;border:0;color:#8199b7;padding:12px 10px;white-space:nowrap;transition:color .2s,text-shadow .2s,background .2s;border-radius:12px;text-align:center}.ki-word strong{display:block;font-size:clamp(16px,1.65vw,24px);font-weight:500;letter-spacing:1px}.ki-word small{display:block;font-size:8px;letter-spacing:2px;margin-top:7px;color:#657f9f}.ki-word:before{content:'';width:4px;height:4px;background:#8ab9df;display:block;margin:0 auto 8px;border-radius:50%;box-shadow:0 0 14px #88c2ff70}.ki-word:hover,.ki-word[aria-pressed=true],.ki-word:focus-visible{color:#f0f8ff;text-shadow:0 0 24px #65b5fb90;background:#709fce0a}.ki-word[aria-pressed=true] small{color:#8ac6f0}.ki-word[aria-pressed=true]:before{box-shadow:0 0 20px 5px #70bdff50;background:#c2e9ff}.ki-word.core strong{font-size:clamp(22px,2.5vw,35px);letter-spacing:-.5px}.keyword-intro button:focus-visible,.keyword-intro a:focus-visible{outline:2px solid #96d4ff;outline-offset:5px}.ki-detail{max-width:1160px;margin:16px auto 0;border-top:1px solid #7495ba42;padding:24px 0 15px;display:grid;grid-template-columns:1fr 1.3fr auto;gap:35px;align-items:center;min-height:137px}.ki-kicker{color:#79acd7;font-size:10px;letter-spacing:2px}.ki-detail h2{font-size:23px;font-weight:500;line-height:1.5;margin:8px 0;color:#e3eeff}.ki-detail p{font-size:14px;line-height:1.9;color:#99aec8;margin:0}.ki-enter{border:1px solid #a5c4e480;border-radius:32px;background:#d9eafd;color:#142740;padding:13px 24px;font-size:13px!important;white-space:nowrap;transition:box-shadow .2s,transform .2s}.ki-enter:hover{box-shadow:0 0 28px #719ac340;transform:translateX(3px)}.ki-bottom{max-width:1160px;margin:8px auto 0;display:flex;justify-content:space-between;align-items:center;gap:20px;color:#667f9c;font-size:11px;line-height:1.7}.ki-bottom a{color:#95b0ce;text-decoration:none}.ki-bottom button{background:transparent;border:0;color:#aec9e5;padding:8px;font-size:12px}.ki-link{transition:stroke .25s,opacity .25s}
@media(min-width:1600px){.ki-space{height:440px}.keyword-intro{padding-top:40px}.ki-header{margin-top:42px}}
@media(max-width:850px){.ki-header{display:block}.ki-instruction{margin-top:20px;max-width:none}.ki-space{height:400px}.ki-word strong{font-size:13px}.ki-word.core strong{font-size:18px}.ki-word small{display:none}.ki-detail{grid-template-columns:1fr;gap:12px}.ki-bottom{flex-wrap:wrap}}
@media(prefers-reduced-motion:reduce){.ki-world{transform:none!important;transition:none}.ki-word{transform:translate(-50%,-50%);transition:none}.ki-enter:hover{transform:none}}
`;
export function KeywordIntro({onEnter,onExperience}:{onEnter:(chapter:number)=>void;onExperience:()=>void}){const [selected,setSelected]=useState(2);const t=topics[selected];const move=(event:PointerEvent<HTMLElement>)=>{if(event.pointerType!=='mouse')return;const box=event.currentTarget.getBoundingClientRect();const x=(event.clientX-box.left)/box.width,y=(event.clientY-box.top)/box.height;event.currentTarget.style.setProperty('--light-x',`${100*x}%`);event.currentTarget.style.setProperty('--light-y',`${100*y}%`);event.currentTarget.style.setProperty('--ry',`${(x-.5)*4}deg`);event.currentTarget.style.setProperty('--rx',`${(.5-y)*3}deg`);};
return <section className="keyword-intro" onPointerMove={move} onPointerLeave={e=>{e.currentTarget.style.setProperty('--rx','0deg');e.currentTarget.style.setProperty('--ry','0deg');}} onKeyDown={e=>e.stopPropagation()}><style>{css}</style><div className="ki-top"><span>MINIMIND-O / INTERACTIVE PAPER</span><div style={{display:"flex",gap:10}}><button className="ki-quiet" onClick={onExperience}>体验真实模型 ↗</button><button className="ki-quiet" onClick={()=>onEnter(0)}>进入教程封面 ↗</button></div></div><header className="ki-header"><div><h1>MiniMind<span>-O</span></h1><p className="ki-subtitle">一个小模型，怎样听、看、说？</p></div><p className="ki-instruction">移动鼠标，探索这篇论文的关键词。<br/>停留或点击一个概念，选择你的阅读起点。</p></header>
<div className="ki-space" aria-label="十个论文关键词"><div className="ki-world"><svg viewBox="0 0 1000 380" preserveAspectRatio="none" aria-hidden="true">{topics.map((v,i)=>i===2?null:<path key={v.word} className="ki-link" d={`M 490 178.6 Q ${(490+v.x*10)/2} ${178.6+(v.y*3.8-178.6)*.2} ${v.x*10} ${v.y*3.8}`} fill="none" stroke={i===selected?'#73b5e9':'#365373'} strokeWidth={i===selected?1.5:.8} opacity={i===selected?.65:.28}/>)}{Array.from({length:32},(_,i)=><circle key={i} cx={(i*173+39)%1000} cy={(i*73+17)%380} r={i%3===0?1.2:.65} fill="#88b5df" opacity={.12+(i%4)*.08}/>)}</svg>{topics.map((v,i)=><button key={v.word} className={`ki-word ${i===2?'core':''}`} style={{left:`${v.x}%`,top:`${v.y}%`,'--depth':`${v.depth}px`} as React.CSSProperties} aria-pressed={selected===i} aria-label={`${v.word}，第 ${v.chapter} 章`} onPointerEnter={()=>setSelected(i)} onFocus={()=>setSelected(i)} onClick={()=>setSelected(i)}><strong>{v.word}</strong><small>{v.en}</small></button>)}</div></div>
<div className="ki-detail"><div><span className="ki-kicker">CHAPTER {String(t.chapter).padStart(2,'0')} / 10</span><h2>{t.prompt}</h2></div><p data-testid="keyword-description" role="status">{t.desc}</p><button className="ki-enter" onClick={()=>onEnter(t.chapter)}>探索第 {t.chapter} 章 →</button></div><footer className="ki-bottom"><span>基于 arXiv:2605.03937v1 · 关键词连线用于导览，不表示完整计算图</span><span><a href="https://arxiv.org/abs/2605.03937v1" target="_blank" rel="noreferrer">论文原文 ↗</a>　<button onClick={()=>onEnter(1)}>从第 1 章顺序开始 →</button></span></footer></section>}
export const KeywordIntroWidget=()=>null;
