import {useState} from 'react';
import {Panel} from './lab-ui';
const official='https://modelscope.cn/studios/gongjy/MiniMind-O';
const tasks=[
{name:'让它说一句话',kind:'文字 → 文字与语音',prompt:'请用一句简短的中文回答：下雨出门要带什么？',steps:['复制下面的提问，在官方演示的文字输入框粘贴并发送。','等回复完成，查看回答文字并播放语音。','对照读一遍：有没有漏字、重复、发音不清或文字与声音不一致？'],observe:['文字和语音内容是否一致？','读起来是否自然？这个判断与内容一致性分开记录。'],chapters:[3,5,10],why:'Thinker 的文字与 Talker 的声音是两条输出路径。一次体验能发现现象，但不能代替论文的系统评估。'},
{name:'用语音问同一个问题',kind:'语音 → 文字与语音',prompt:'下雨出门要带什么？请用一句话回答。',steps:['在官方演示选择录音或上传语音；用自己的声音读出下面的问题。','提交后等待回答，记录这一次是否理解了你的问题。','与文字任务比较：内容是否相关？不要把回答措辞不同直接判定为理解失败。'],observe:['它是否回答了所问的问题？','换成声音后，是否出现明显漏听或误解？'],chapters:[1,2,3],why:'声音由编码器提取特征后进入模型。网页上的问题文字只是录音提示，不代表模型一定先做文字转录。'},
{name:'给它一张简单图片',kind:'图片＋文字 → 文字与语音',prompt:'请描述图片里的两个形状及它们的颜色，简短回答。',steps:['下载下面的测试图片，在官方演示的图片附件入口上传。','输入下面的提问并发送。','检查是否识别出红色圆形和蓝色正方形，再听生成语音。'],observe:['形状和颜色是否说对？是否添加图中没有的物体？','文字描述与最终语音是否一致？'],chapters:[2,9,10],why:'这张图是本站自制的简单体验素材，不是论文表 5 的测试集。一次成功或失败都不能说明全部视觉能力。'}
];
type RecordItem={result:string;note:string};
const initial=()=>{try{const saved=JSON.parse(sessionStorage.getItem('minimind-experience-notes')||'null');if(Array.isArray(saved)&&saved.length===3&&saved.every(v=>typeof v?.result==='string'&&typeof v?.note==='string'))return saved as RecordItem[];}catch{}return tasks.map(()=>({result:'',note:''}));};
export function ModelExperience({onChapter}:{onChapter:(n:number)=>void}){const [task,setTask]=useState(0),[copied,setCopied]=useState(''),[records,setRecords]=useState<RecordItem[]>(initial);const t=tasks[task];const record=records[task];const update=(field:keyof RecordItem,value:string)=>{const next=records.map((v,i)=>i===task?{...v,[field]:value}:v);setRecords(next);try{sessionStorage.setItem('minimind-experience-notes',JSON.stringify(next));}catch{}};
const copy=async()=>{try{await navigator.clipboard.writeText(t.prompt);setCopied('提问已复制，到官方演示粘贴即可。');}catch{setCopied('浏览器未允许复制，请选中下方提问手动复制。');}};
const download=()=>{const canvas=document.createElement('canvas');canvas.width=512;canvas.height=320;const c=canvas.getContext('2d');if(!c)return;c.fillStyle='#fff';c.fillRect(0,0,512,320);c.fillStyle='#df4545';c.beginPath();c.arc(145,160,68,0,Math.PI*2);c.fill();c.fillStyle='#326dcc';c.fillRect(300,94,132,132);const a=document.createElement('a');a.download='minimind-shapes-test.png';a.href=canvas.toDataURL('image/png');a.click();};
return <section className="chap slide-chap"><h2 className="chap-title">亲手试试 MiniMind-O</h2><Panel><style>{`.experience-banner{background:linear-gradient(120deg,#142b45,#294e6c);padding:24px;border-radius:14px;color:#e0edfc;margin:16px 0 24px}.experience-banner h3{color:#fff;margin:0 0 10px;font-size:21px}.omni-lab .experience-banner p{color:#bfd1e7!important;line-height:1.9;font-size:14px}.experience-link{display:inline-block;background:#e6f0fd;color:#163753!important;padding:11px 20px;border-radius:8px;text-decoration:none;font-size:14px}.experience-notes{width:100%;min-height:120px;padding:12px;border:1px solid #bdcde0;border-radius:8px;font:inherit;color:#27446e;resize:vertical}.experience-steps li{margin:10px 0;line-height:1.8}.experience-prompt{padding:18px;background:#eef4fb;border-left:3px solid #7094bf;user-select:text;font-size:17px;line-height:1.9;margin:15px 0}.experience-status{font-size:12px;line-height:1.8;padding:12px 15px;background:#f5f7fa;border-radius:8px;color:#60768f}`}</style>
<div className="experience-banner"><h3>带着一个问题，体验一次真实回答</h3><p>本页帮你准备输入、记录观察；提问、录音和模型生成在作者的 ModelScope 演示页进行。打开新标签后，可以保留本页作为对照。</p><a className="experience-link" href={official} target="_blank" rel="noreferrer">打开作者官方模型演示 ↗</a></div>
<div className="experience-status">2026-09-14 已实测官方演示返回文字与可加载语音。服务状态会变化，加载中、排队或无响应时可稍后重试；本页不会把“打开链接”记为体验成功。作者仓库的 Gradio 演示为非实时模式，不用它判断论文里的首包或流式延迟。</div>
<details style={{margin:'18px 0',padding:16,border:'1px solid #d5e1ee',borderRadius:10}}><summary style={{cursor:'pointer',fontWeight:650,color:'#27446e'}}>先听一条真实模型输出 · 约 2 秒</summary><p>输入：请用一句简短的中文回答：下雨出门要带什么？</p><p><strong>模型文字回复：</strong>如果下雨，需要带雨伞。</p><audio controls preload="none" style={{width:'100%'}} src={new URL('audio/official-rain-test-20260914.wav',document.baseURI).href}>浏览器不支持音频播放。</audio><p className="lab-note">这是 2026-09-14 从作者官方演示生成并保存的原始语音，时长 1.92 秒表示音频长度，不是推理耗时。样例是历史记录；你的实时体验请在官方页面进行。本次未记录具体检查点版本，本条不用于复现论文指标。</p></details>
<div className="ctrl" role="group" aria-label="选择模型体验任务">{tasks.map((v,i)=><button key={v.name} aria-pressed={task===i} onClick={()=>{setTask(i);setCopied('');}}>{i+1}. {v.name}</button>)}</div>
<div className="lab-grid" style={{gridTemplateColumns:'1.3fr 1fr'}}><div className="lab-card"><span className="lab-eyebrow">体验任务 {task+1} / 3</span><strong style={{fontSize:20}}>{t.kind}</strong><ol className="experience-steps">{t.steps.map(s=><li key={s}>{s}</li>)}</ol><div className="experience-prompt">{t.prompt}</div><button onClick={copy}>复制本次提问</button><p className="lab-note" role="status">{copied}</p>{task===2&&<div><svg viewBox="0 0 512 320" role="img" aria-label="体验图片：左边红色圆形，右边蓝色正方形" style={{width:'100%',maxHeight:180,border:'1px solid #d8e3ee',borderRadius:8,background:'#fff'}}><circle cx="145" cy="160" r="68" fill="#df4545"/><rect x="300" y="94" width="132" height="132" fill="#326dcc"/></svg><button onClick={download}>下载测试图片 PNG</button><p className="lab-note">本站绘制的几何图形，仅用于体验；没有预设模型回答。</p></div>}</div>
<div className="lab-card"><span className="lab-eyebrow">观察重点</span>{t.observe.map(s=><p key={s} style={{fontSize:16,lineHeight:1.8}}>{s}</p>)}<div className="feedback">{t.why}</div><h4>回到对应机制</h4><div className="ctrl">{t.chapters.map(n=><button key={n} onClick={()=>onChapter(n)}>回看第 {n} 章 →</button>)}</div><p className="lab-note">录音与上传的文件交给官方平台处理；建议使用这页的简单测试内容。本站不接收音频、图片或模型回答。</p></div></div>
<div className="lab-card" style={{marginTop:20}}><strong>这次你实际观察到了什么？</strong><div className="ctrl">{['得到文字和语音','只得到部分结果','服务未响应／未完成'].map(v=><button key={v} aria-pressed={record.result===v} onClick={()=>update('result',v)}>{v}</button>)}</div><label htmlFor="experience-note">记录现象：例如说错的字、遗漏的物体，或服务加载情况。</label><textarea id="experience-note" className="experience-notes" value={record.note} onChange={e=>update('note',e.target.value)} placeholder="由你记录真实结果；此处不会生成示例回答。"/><p className="lab-note">记录仅保存在当前标签页的浏览器会话中，不上传服务器。切换任务或回看章节后可以继续记录。</p><button onClick={()=>{const next=records.map((v,i)=>i===task?{result:'',note:''}:v);setRecords(next);try{sessionStorage.setItem('minimind-experience-notes',JSON.stringify(next));}catch{}}}>清空本任务记录</button></div>
<details style={{marginTop:20}}><summary style={{cursor:'pointer'}}>官方演示打不开，或者一直在加载？</summary><p>重新打开官方链接，等待页面完成加载；是否需要登录、排队以官方页面提示为准。仍不可用时，可以听本页保存的真实输出样例，继续使用本站机制交互，或者观看作者演示视频。</p><p><a href="https://www.bilibili.com/video/BV1V1RsBcEMX" target="_blank" rel="noreferrer">观看作者视频 ↗</a> · <a href="https://github.com/jingyaogong/minimind-o" target="_blank" rel="noreferrer">查看作者项目说明 ↗</a></p><p className="lab-note">视频和本站样例是已有记录，不等同于你的实时输入得到模型回应。</p></details>
</Panel></section>}
export const ModelExperienceWidget=()=>null;
