import React, { useEffect, useRef } from 'react';
import { setupCanvas, observeCanvas } from '../lib/canvasKit';

export const Palette = { bg:'#f5f8f0', neutral:'#b8c9a7', dark:'#76906a', support:'#92400e', blue:'#27446e', green:'#228d5c', red:'#c43f52', orange:'#f07e47', purple:'#7c3aed', ink:'#21324a', muted:'#68778f', border:'#d7deea' };
export function clearScene(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.clearRect(0,0,w,h);ctx.fillStyle=Palette.bg;ctx.fillRect(0,0,w,h);}
export function box(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string,selected=false){ctx.save();ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,Math.min(12,h/4));ctx.fill();if(selected){ctx.strokeStyle=Palette.ink;ctx.lineWidth=3;ctx.stroke();}ctx.restore();}
export function line(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number,color:string=Palette.border){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore();}
export function label(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,color:string=Palette.ink,size=24){ctx.save();ctx.fillStyle=color;ctx.font=`600 ${size}px system-ui, sans-serif`;ctx.fillText(text,x,y);ctx.restore();}
export function drawDesk(ctx:CanvasRenderingContext2D,w:number,h:number){box(ctx,w*.07,h*.74,w*.86,h*.045,Palette.neutral);line(ctx,w*.14,h*.79,w*.14,h*.98,Palette.dark);line(ctx,w*.86,h*.79,w*.86,h*.98,Palette.dark);}
export function drawMic(ctx:CanvasRenderingContext2D,x:number,y:number,scale=1,color:string=Palette.blue){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);box(ctx,-12,-55,24,48,color);ctx.strokeStyle=Palette.dark;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,-29,19,0,Math.PI);ctx.stroke();line(ctx,0,-10,0,23,Palette.dark);line(ctx,-19,23,19,23,Palette.dark);ctx.restore();}
export function drawCard(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string='#fff'){box(ctx,x,y,w,h,color,true);for(let i=0;i<3;i++)line(ctx,x+w*.16,y+h*(.27+i*.21),x+w*.8,y+h*(.27+i*.21),Palette.neutral);}
export function drawPresenter(ctx:CanvasRenderingContext2D,x:number,y:number,scale=1,pose=0,color:string=Palette.blue){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle='#ead4b9';ctx.beginPath();ctx.arc(0,-49,22,0,Math.PI*2);ctx.fill();ctx.fillStyle=Palette.ink;ctx.beginPath();ctx.arc(-2,-54,23,Math.PI,Math.PI*2);ctx.fill();box(ctx,-30,-20,60,69,color);line(ctx,-24,0,-48,20, color);line(ctx,24,0,52+pose*18,20-pose*28,color);ctx.fillStyle='#ead4b9';ctx.beginPath();ctx.arc(52+pose*18,20-pose*28,7,0,Math.PI*2);ctx.fill();ctx.fillStyle=Palette.ink;ctx.beginPath();ctx.arc(7,-49,2,0,Math.PI*2);ctx.fill();line(ctx,7,-37,14,-37,Palette.support);ctx.restore();}

interface SceneProps {draw:(ctx:CanvasRenderingContext2D,w:number,h:number,time:number)=>void;width?:number;height?:number;animate?:boolean;ariaLabel:string;onPoint?:(x:number,y:number)=>void;draggable?:boolean;}
export const Scene:React.FC<SceneProps>=({draw,width=1080,height=280,animate=false,ariaLabel,onPoint,draggable=false})=>{
 const ref=useRef<HTMLCanvasElement>(null);const drawRef=useRef(draw);drawRef.current=draw;const activePointer=useRef(false);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=setupCanvas(canvas,width,height);canvas.style.width='100%';canvas.style.height='auto';let raf=0;let visible=false;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const paint=(time:number)=>{clearScene(ctx,width,height);drawRef.current(ctx,width,height,reduced?0:time);canvas.classList.add('is-ready');};paint(performance.now());const tick=(t:number)=>{paint(t);raf=animate&&visible&&!reduced?requestAnimationFrame(tick):0;};const start=()=>{visible=true;paint(performance.now());if(animate&&!reduced&&!raf)raf=requestAnimationFrame(tick);};const stop=()=>{visible=false;cancelAnimationFrame(raf);raf=0;};const disconnect=observeCanvas(canvas,start,stop);return()=>{stop();disconnect();};},[width,height,animate]);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;clearScene(ctx,width,height);drawRef.current(ctx,width,height,window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:performance.now());canvas.classList.add('is-ready');},[draw,width,height]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();onPoint?.(Math.max(0,Math.min(width,(e.clientX-r.left)*width/r.width)),Math.max(0,Math.min(height,(e.clientY-r.top)*height/r.height)));};
 return <canvas ref={ref} width={width} height={height} role="img" aria-label={ariaLabel} style={{width:'100%',height:'auto',touchAction:draggable?'none':'auto',cursor:draggable?'grab':onPoint?'pointer':'default'}} onPointerDown={e=>{if(!onPoint)return;activePointer.current=true;if(draggable)e.currentTarget.setPointerCapture(e.pointerId);point(e);}} onPointerMove={e=>{if(draggable&&activePointer.current)point(e);}} onPointerUp={()=>{activePointer.current=false;}} onPointerCancel={()=>{activePointer.current=false;}} />;
};

export const OmniKit:React.FC=()=>null;
