import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AiTutorWidget } from './ai-tutor';
import { Analogy1 } from './analogy-1';
import { Analogy10 } from './analogy-10';
import { Analogy2 } from './analogy-2';
import { Analogy3 } from './analogy-3';
import { Analogy4 } from './analogy-4';
import { Analogy5 } from './analogy-5';
import { Analogy6 } from './analogy-6';
import { Analogy7 } from './analogy-7';
import { Analogy8 } from './analogy-8';
import { Analogy9 } from './analogy-9';
import { C1Main } from './c1-main';
import { Ch10Main } from './c10-main';
import { Ch10Metrics } from './c10-metrics';
import { C2Main } from './c2-main';
import { C3Main } from './c3-main';
import { Ch4Main } from './c4-main';
import { Ch5Main } from './c5-main';
import { Ch6Main } from './c6-main';
import { Ch7Main } from './c7-main';
import { Ch8Main } from './c8-main';
import { Ch9Main } from './c9-main';
import { CerWorkbench } from './cer-workbench';
import { DeepDiveWidget } from './deep-dive';
import { GradientWorkbenchWidget } from './gradient-workbench';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { KeywordIntroWidget } from './keyword-intro';
import { LabUi } from './lab-ui';
import { MechanismFieldWidget } from './mechanism-field';
import { ModelExperienceWidget } from './model-experience';
import { MouseStageWidget } from './mouse-stage';
import { OmniKit } from './omni-kit';
import { RankWorkbench } from './rank-workbench';
import { ReadingWheelWidget } from './reading-wheel';
import { WorkedCasesWidget } from './worked-cases';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ai-tutor'] = AiTutorWidget;
widgetRegistry['analogy-1'] = Analogy1;
widgetRegistry['analogy-10'] = Analogy10;
widgetRegistry['analogy-2'] = Analogy2;
widgetRegistry['analogy-3'] = Analogy3;
widgetRegistry['analogy-4'] = Analogy4;
widgetRegistry['analogy-5'] = Analogy5;
widgetRegistry['analogy-6'] = Analogy6;
widgetRegistry['analogy-7'] = Analogy7;
widgetRegistry['analogy-8'] = Analogy8;
widgetRegistry['analogy-9'] = Analogy9;
widgetRegistry['c1-main'] = C1Main;
widgetRegistry['c10-main'] = Ch10Main;
widgetRegistry['c10-metrics'] = Ch10Metrics;
widgetRegistry['c2-main'] = C2Main;
widgetRegistry['c3-main'] = C3Main;
widgetRegistry['c4-main'] = Ch4Main;
widgetRegistry['c5-main'] = Ch5Main;
widgetRegistry['c6-main'] = Ch6Main;
widgetRegistry['c7-main'] = Ch7Main;
widgetRegistry['c8-main'] = Ch8Main;
widgetRegistry['c9-main'] = Ch9Main;
widgetRegistry['cer-workbench'] = CerWorkbench;
widgetRegistry['deep-dive'] = DeepDiveWidget;
widgetRegistry['gradient-workbench'] = GradientWorkbenchWidget;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['keyword-intro'] = KeywordIntroWidget;
widgetRegistry['lab-ui'] = LabUi;
widgetRegistry['mechanism-field'] = MechanismFieldWidget;
widgetRegistry['model-experience'] = ModelExperienceWidget;
widgetRegistry['mouse-stage'] = MouseStageWidget;
widgetRegistry['omni-kit'] = OmniKit;
widgetRegistry['rank-workbench'] = RankWorkbench;
widgetRegistry['reading-wheel'] = ReadingWheelWidget;
widgetRegistry['worked-cases'] = WorkedCasesWidget;
