import React, { useEffect, useRef, useState } from 'react';
import { setupCanvas, observeCanvas, clamp, easeInOutQuad } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const C={bg:'#f5f8f0',light:'#b8c9a7',dark:'#76906a',support:'#92400e',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#d97706',purple:'#7c3aed',ink:'#21324a',muted:'#68778f',line:'#d7deea',white:'#ffffff'};
type Draw=(ctx:CanvasRenderingContext2D,t:number)=>void;

function clear(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.clearRect(0,0,w,h);ctx.fillStyle=C.bg;ctx.fillRect(0,0,w,h);}
function txt(ctx:CanvasRenderingContext2D,s:string,x:number,y:number,color=C.ink,size=13,align:CanvasTextAlign='left'){ctx.fillStyle=color;ctx.font='600 '+size+'px "Segoe UI",sans-serif';ctx.textAlign=align;ctx.fillText(s,x,y);ctx.textAlign='left';}
function round(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,fill:string,stroke=C.line,lw=1){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke();}
function line(ctx:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number,color=C.line,lw=2,dash:number[]=[]){ctx.beginPath();ctx.setLineDash(dash);ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.stroke();ctx.setLineDash([]);}
function camera(ctx:CanvasRenderingContext2D,x:number,y:number,s=1,color=C.blue){round(ctx,x,y,70*s,42*s,8*s,color,C.ink,2);ctx.beginPath();ctx.arc(x+35*s,y+21*s,14*s,0,Math.PI*2);ctx.fillStyle=C.white;ctx.fill();ctx.strokeStyle=C.ink;ctx.lineWidth=2;ctx.stroke();round(ctx,x+12*s,y-8*s,22*s,10*s,3*s,C.dark,C.ink,1);}
function photo(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,accent=C.blue){round(ctx,x,y,w,h,4,C.white,accent,2);ctx.fillStyle=C.light;ctx.fillRect(x+7,y+7,w-14,h-14);line(ctx,x+8,y+h-12,x+w-8,y+16,C.dark,2);}
function target(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color=C.green){ctx.strokeStyle=color;ctx.lineWidth=3;ctx.strokeRect(x,y,w,h);}

function Canvas({w=560,h=250,draw,animate=false,onPointerDown,onPointerMove,onPointerUp,tabIndex,onKeyDown,label}:{w?:number;h?:number;draw:Draw;animate?:boolean;onPointerDown?:React.PointerEventHandler<HTMLCanvasElement>;onPointerMove?:React.PointerEventHandler<HTMLCanvasElement>;onPointerUp?:React.PointerEventHandler<HTMLCanvasElement>;tabIndex?:number;onKeyDown?:React.KeyboardEventHandler<HTMLCanvasElement>;label?:string}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const cv=ref.current;if(!cv)return;let ctx:CanvasRenderingContext2D;try{ctx=setupCanvas(cv,w,h);}catch{return;}let raf:number|null=null;let start=performance.now();const frame=()=>{draw(ctx,(performance.now()-start)/1000);if(!cv.classList.contains('is-ready'))cv.classList.add('is-ready');if(animate)raf=requestAnimationFrame(frame);};const begin=()=>{if(raf===null){if(animate)raf=requestAnimationFrame(frame);else frame();}};const stop=()=>{if(raf!==null)cancelAnimationFrame(raf);raf=null;};const disconnect=observeCanvas(cv,begin,stop);return()=>{stop();disconnect();};},[w,h,draw,animate]);
 return <canvas ref={ref} width={w} height={h} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp} tabIndex={tabIndex} onKeyDown={onKeyDown} aria-label={label}/>;
}

function Chip({selected,onClick,children,disabled=false}:{selected?:boolean;onClick:()=>void;children:React.ReactNode;disabled?:boolean}){return <button className={'chip '+(selected?'selected':'')} onClick={onClick} disabled={disabled}>{children}</button>}
function Feedback({kind='mid',children}:{kind?:'good'|'bad'|'mid';children:React.ReactNode}){return <div className={'feedback '+(kind==='good'?'good':kind==='bad'?'bad':'')}>{children}</div>}

function Analogy({v}:{v:number}){const draw:Draw=(ctx,t)=>{clear(ctx,244,130);const p=(Math.sin(t*2.1)+1)/2;ctx.fillStyle=C.light;ctx.fillRect(0,104,244,26);if(v===1){photo(ctx,18,20,132,76);target(ctx,75,55,34,22);camera(ctx,164+8*p,60,.72);txt(ctx,'锁定红车',18,16,C.green,12);}if(v===2){camera(ctx,132,55,.9);ctx.beginPath();ctx.arc(65+45*p,74,18,0,Math.PI*2);ctx.fillStyle=C.dark;ctx.fill();txt(ctx,'装接',20,18,C.blue,12);}if(v===3){camera(ctx,130,55,.9);ctx.beginPath();ctx.arc(110-62*p,74,18,0,Math.PI*2);ctx.fillStyle=C.red;ctx.fill();target(ctx,153,67,24,18,C.green);txt(ctx,'保留轻量前端',20,18,C.blue,12);}if(v===4){round(ctx,16,22,212,77,6,C.white);for(let i=0;i<4;i++)photo(ctx,28+i*47*p,38,38,45,i%2?C.orange:C.blue);txt(ctx,'按顺序展开',18,17,C.blue,12);}if(v===5){photo(ctx,24,23,150,76);const y=18+48*p;round(ctx,178,y,44,24,5,C.orange,C.support,2);txt(ctx,'[t,h,w]',121,91,C.blue,12);}if(v===6){photo(ctx,18,24,202,70);ctx.beginPath();ctx.arc(50+136*p,57,23,0,Math.PI*2);ctx.strokeStyle=C.blue;ctx.lineWidth=5;ctx.stroke();line(ctx,65+136*p,75,79+136*p,91,C.support,6);txt(ctx,'检查关系',18,18,C.blue,12);}if(v===7){camera(ctx,78,52,1);ctx.save();ctx.translate(170,69);ctx.rotate(p*Math.PI*1.4);line(ctx,-30,0,28,0,C.support,7);ctx.restore();txt(ctx,'拧紧结构',18,18,C.blue,12);}if(v===8){camera(ctx,24,58,.8);ctx.beginPath();ctx.arc(160,66,32,0,Math.PI*2);ctx.fillStyle=C.white;ctx.fill();ctx.strokeStyle=C.dark;ctx.stroke();const a=-2.3+p*4.6;line(ctx,160,66,160+25*Math.cos(a),66+25*Math.sin(a),C.orange,4);txt(ctx,'三档训练',18,18,C.blue,12);}if(v===9){photo(ctx,18,30,58,58);photo(ctx,93,30,58,58);photo(ctx,168,30,58,58);round(ctx,20+150*p,79,28,18,4,C.orange,C.support,2);txt(ctx,'按条件检查',18,18,C.blue,12);}if(v===10){photo(ctx,22,30,82,58);photo(ctx,140,30,82,58);const x=50+118*p;ctx.beginPath();ctx.moveTo(x,17);ctx.lineTo(x+10,28);ctx.lineTo(x-10,28);ctx.closePath();ctx.fillStyle=C.orange;ctx.fill();txt(ctx,'同协议评选',18,18,C.blue,12);}};return <Canvas w={244} h={130} draw={draw} animate/>}
export const NeoAna1=()=> <Analogy v={1}/>; export const NeoAna2=()=> <Analogy v={2}/>; export const NeoAna3=()=> <Analogy v={3}/>; export const NeoAna4=()=> <Analogy v={4}/>; export const NeoAna5=()=> <Analogy v={5}/>; export const NeoAna6=()=> <Analogy v={6}/>; export const NeoAna7=()=> <Analogy v={7}/>; export const NeoAna8=()=> <Analogy v={8}/>; export const NeoAna9=()=> <Analogy v={9}/>; export const NeoAna10=()=> <Analogy v={10}/>;

function HeroScene({native}:{native:boolean}){const draw:Draw=(ctx,t)=>{clear(ctx,360,190);const p=(Math.sin(t*2)+1)/2;if(!native){camera(ctx,230,65,.9);ctx.beginPath();ctx.arc(80+55*p,84,22,0,Math.PI*2);ctx.fillStyle=C.dark;ctx.fill();round(ctx,148,70,38,28,5,C.orange,C.support,2);txt(ctx,'Vision Encoder',34,35,C.blue,13);txt(ctx,'Adapter',147,60,C.orange,12);txt(ctx,'LLM',259,126,C.blue,12);line(ctx,105,84,148,84,C.blue,4);line(ctx,186,84,230,84,C.blue,4);}else{camera(ctx,144,62,1);for(let r=0;r<3;r++)for(let c=0;c<4;c++){ctx.fillStyle=(r*4+c)/12<p?C.green:C.light;ctx.fillRect(26+c*20,62+r*20,15,15);}line(ctx,104,91,144,82,C.blue,4);txt(ctx,'轻量 patch embedding',24,35,C.blue,13);txt(ctx,'统一 decoder-only 主干',147,133,C.green,13);} };return <Canvas w={360} h={190} draw={draw} animate/>}
export const NeoHeroOld=()=> <HeroScene native={false}/>; export const NeoHeroNew=()=> <HeroScene native/>;

export const NeoCh1Main:React.FC<WidgetProps>=()=>{const labels=['图中有什么','目标在哪里','用户问什么','如何回答'];const feedback=['识别到红色汽车、道路与路口。','红车位于路口右侧，空间关系出现了。','问题锁定“红色汽车”和“哪里”。','四种能力合在一起：红车停在路口右侧。'];const [step,setStep]=useState(0);const [seen,setSeen]=useState<boolean[]>([false,false,false,false]);const draw:Draw=(ctx)=>{clear(ctx,560,250);photo(ctx,24,26,344,188);ctx.fillStyle='#8fa4b8';ctx.fillRect(45,60,85,54);ctx.fillStyle=C.red;ctx.fillRect(230,132,70,32);ctx.fillStyle=C.ink;ctx.fillRect(242,157,12,8);ctx.fillRect(278,157,12,8);if(step>=0){target(ctx,222,124,86,48,step===3?C.green:C.orange);}if(step>=1){line(ctx,265,123,334,83,C.blue,3);txt(ctx,'路口右侧',300,75,C.blue,12,'center');}if(step>=2){round(ctx,390,36,146,58,6,C.white,C.orange,2);txt(ctx,'红色汽车 在哪里？',403,70,C.orange,13);}if(step>=3){line(ctx,310,151,407,157,C.green,4);round(ctx,395,124,140,68,6,'#e8f5ed',C.green,2);txt(ctx,'答案路径',465,148,C.green,13,'center');txt(ctx,'红车→路口右侧',465,174,C.ink,13,'center');}};const pick=(i:number)=>{setStep(i);setSeen(s=>s.map((v,k)=>v||k===i));};return <div><Canvas draw={draw}/><div className="chip-row">{labels.map((x,i)=><Chip key={x} selected={step===i} onClick={()=>pick(i)}>{seen[i]?'✓ ':''}{x}</Chip>)}</div><Feedback kind={seen.every(Boolean)?'good':'mid'}>{feedback[step]}</Feedback></div>}

const modularNodes=[['pixels','Pixels','像素'],['vision','Vision Encoder','提取视觉表示'],['adapter','Adapter / Projector','转换并对齐表示空间'],['llm','LLM','理解问题、推理并生成'],['answer','Answer','最终回答']];
export const NeoCh2Main:React.FC<WidgetProps>=()=>{const [selected,setSelected]=useState('vision');const [removed,setRemoved]=useState(false);const idx=modularNodes.findIndex(n=>n[0]===selected);const draw:Draw=(ctx)=>{clear(ctx,560,250);modularNodes.forEach((n,i)=>{const x=18+i*106;const cut=removed&&i===idx;round(ctx,x,84,92,64,7,cut?'#fdebed':selected===n[0]?'#e8eef7':C.white,cut?C.red:selected===n[0]?C.blue:C.line,cut?3:selected===n[0]?3:1);txt(ctx,n[1],x+46,119,cut?C.red:C.ink,11,'center');if(i<4)line(ctx,x+92,116,x+106,116,removed&&(i===idx||i+1===idx)?C.red:C.blue,3,removed&&(i===idx||i+1===idx)?[5,4]:[]);if(cut){txt(ctx,'×',x+46,75,C.red,24,'center');}});round(ctx,92,177,376,48,6,C.white,C.line);txt(ctx,modularNodes[idx][2],280,207,removed?C.red:C.blue,14,'center');};return <div><Canvas draw={draw}/><div className="chip-row">{modularNodes.map(n=><Chip key={n[0]} selected={selected===n[0]} onClick={()=>{setSelected(n[0]);setRemoved(false)}}>{n[1]}</Chip>)}</div><div className="chip-row"><Chip selected={!removed} onClick={()=>setRemoved(false)}>完整路径</Chip><Chip selected={removed} onClick={()=>setRemoved(true)} disabled={selected==='answer'}>暂时移除所选</Chip></div><Feedback kind={removed?'bad':'good'}>{removed?'教学示意：这条模块化路径失去“'+modularNodes[idx][2]+'”，信息流被中断。':'完整模块链职责清楚，也便于复用成熟视觉与语言模型。'}</Feedback></div>}

export const NeoCh2Boundary:React.FC<WidgetProps>=()=>{const names=['外部视觉编码器','Adapter','轻量 patch embedding','Pre-Buffer','统一主干'];const [parts,setParts]=useState([false,false,true,true,true]);const valid=!parts[0]&&!parts[1]&&parts[2]&&parts[3]&&parts[4];const draw:Draw=(ctx)=>{clear(ctx,560,230);names.forEach((n,i)=>{const x=18+i*106;round(ctx,x,70,92,70,7,parts[i]?'#e8f5ed':'#f4f5f7',parts[i]?C.green:C.line,parts[i]?3:1);txt(ctx,parts[i]?'保留':'去掉',x+46,94,parts[i]?C.green:C.muted,12,'center');txt(ctx,n,x+46,120,C.ink,10,'center');if(i<4)line(ctx,x+92,105,x+106,105,parts[i]&&parts[i+1]?C.blue:C.red,3,parts[i]&&parts[i+1]?[]:[4,4]);});txt(ctx,valid?'论文配置：Encoder-Free':'当前组合不是论文配置',280,190,valid?C.green:C.red,16,'center');};return <div><Canvas h={230} draw={draw}/><div className="chip-row">{names.map((n,i)=><Chip key={n} selected={parts[i]} onClick={()=>setParts(p=>p.map((v,k)=>k===i?!v:v))}>{n}</Chip>)}</div><Feedback kind={valid?'good':'bad'}>{valid?'去掉外部视觉编码器与 Adapter，但保留轻量 patch embedding、Pre-Buffer 与统一主干。':'若移除轻量视觉前端，或保留外部编码器/Adapter，就不再是论文描述的 NEO-ov。'}</Feedback></div>}

export const NeoCh3Main:React.FC<WidgetProps>=()=>{const issues=['二维成序列','视频入框架','二维位置','时间先后','多模态统一'];const [started,setStarted]=useState(false);const [issue,setIssue]=useState(0);const draw:Draw=(ctx)=>{clear(ctx,560,255);[['模块化',22,C.red],['原生统一',292,C.green]].forEach(([label,x,color])=>{round(ctx,x as number,30,246,170,8,C.white,color as string,2);txt(ctx,label as string,(x as number)+123,55,color as string,14,'center');photo(ctx,(x as number)+15,72,62,54);if(x===22){round(ctx,105,82,55,34,5,'#fbe8ec',C.red);round(ctx,178,82,52,34,5,'#fff4dd',C.orange);}else{for(let r=0;r<3;r++)for(let c=0;c<3;c++){ctx.fillStyle=C.light;ctx.fillRect((x as number)+92+c*15,80+r*15,11,11);}round(ctx,(x as number)+154,77,74,48,5,'#e8f5ed',C.green);}line(ctx,(x as number)+78,99,(x as number)+226,99,started?color as string:C.line,started?4:2);});round(ctx,167,211,226,30,15,started?'#fff4dd':C.white,started?C.orange:C.line);txt(ctx,issues[issue],280,231,started?C.orange:C.muted,13,'center');};return <div><Canvas h={255} draw={draw}/><div className="chip-row"><button className="tiny" onClick={()=>setStarted(true)}>同步比较</button>{issues.map((x,i)=><Chip key={x} selected={issue===i} onClick={()=>{setIssue(i);setStarted(true)}}>{x}</Chip>)}</div><Feedback kind={started?'mid':'mid'}>{started?'两条路线都处理视觉；原生路线必须在统一主干内解决“'+issues[issue]+'”。':'两侧从同一照片与问题出发。'}</Feedback></div>}

const serializationModes={single:{name:'Single Image',units:1},multi:{name:'Multi-Image',units:2},video:{name:'Video',units:4}} as const;
export const NeoCh4Main:React.FC<WidgetProps>=()=>{const [mode,setMode]=useState<keyof typeof serializationModes>('single');const [step,setStep]=useState(0);const m=serializationModes[mode];const draw:Draw=(ctx)=>{clear(ctx,560,270);txt(ctx,['原始输入','Patch / Frame 组织','视觉单元','序列化结果','最终输入序列'][step],24,30,C.blue,15);for(let i=0;i<m.units;i++){const x=28+i*(mode==='video'?91:150);photo(ctx,x,55,mode==='video'?76:118,70,i===step%2?C.orange:C.blue);if(step>=1){for(let r=0;r<2;r++)for(let c=0;c<3;c++){ctx.strokeStyle=C.line;ctx.strokeRect(x+8+c*20,65+r*22,18,20);}}if(step>=2){txt(ctx,'<img>',x,142,C.green,11);txt(ctx,'</img>',x+(mode==='video'?35:74),142,C.green,11);}if(mode==='video'&&step>=3)txt(ctx,'τ'+(i+1),x+38,48,C.orange,11,'center');}if(mode==='video'&&step>=3){round(ctx,28,158,210,30,5,'#eee9ff',C.purple);txt(ctx,'p_global：时长 / 帧数 / 采样率',38,179,C.purple,12);}if(step>=3){round(ctx,28,202,504,42,6,C.white,C.line);txt(ctx,mode==='single'?'<img> patch… </img>  q':mode==='multi'?'<img> 图1 </img> … <img> 图2 </img>  q':'p_global  [τ1]:<img>帧1</img> … q',280,228,C.ink,12,'center');}};const switchMode=(x:keyof typeof serializationModes)=>{setMode(x);setStep(0)};return <div><Canvas h={270} draw={draw}/><div className="chip-row">{Object.entries(serializationModes).map(([k,v])=><Chip key={k} selected={mode===k} onClick={()=>switchMode(k as keyof typeof serializationModes)}>{v.name}</Chip>)}</div><div className="step-ctrl"><button className="tiny ghost" disabled={step===0} onClick={()=>setStep(s=>s-1)}>上一步</button><span className="step-label"><b>{step+1}</b> / 5</span><button className="tiny" disabled={step===4} onClick={()=>setStep(s=>s+1)}>下一步</button></div><Feedback kind={step===4?'good':'mid'}>{mode==='video'?'视频保留帧顺序、时间戳，并在可用时带全局时间前缀。':mode==='multi'?'多图按提示顺序形成彼此独立、可用任意分辨率的视觉段。':'单图形成一个带 <img> 边界的视觉单元。'} 这是教学示意，并非论文原始架构图。</Feedback></div>}

export const NeoCh5Main:React.FC<WidgetProps>=()=>{const [mode,setMode]=useState<'single'|'multi'|'video'>('single');const [enabled,setEnabled]=useState(false);const [sel,setSel]=useState(0);const [drag,setDrag]=useState(false);const total=mode==='video'?4:12;const draw:Draw=(ctx)=>{clear(ctx,560,270);round(ctx,24,30,320,210,8,C.white,C.line);const cols=mode==='video'?4:4,rows=mode==='video'?1:3;const cw=68,ch=mode==='video'?120:56;for(let i=0;i<cols*rows;i++){const x=42+(i%cols)*cw,y=58+Math.floor(i/cols)*ch;ctx.fillStyle=i===sel?C.orange:C.light;ctx.fillRect(x,y,cw-8,ch-8);ctx.strokeStyle=i===sel?C.ink:C.line;ctx.lineWidth=i===sel?3:1;ctx.strokeRect(x,y,cw-8,ch-8);if(mode==='video')txt(ctx,'帧 '+(i+1),x+30,y+65,C.ink,11,'center');}round(ctx,365,30,171,88,7,C.white,enabled?C.green:C.red,2);const h=mode==='video'?0:Math.floor(sel/4),w=mode==='video'?0:sel%4,t=mode==='video'?sel+1:mode==='multi'?(sel<6?1:2):1;txt(ctx,enabled?'idx=['+t+','+h+','+w+']':'idx=[ ? , ? , ? ]',451,69,enabled?C.green:C.red,15,'center');txt(ctx,enabled?'Native-RoPE + T/H/W':'仅一维序列',451,96,enabled?C.blue:C.muted,12,'center');round(ctx,365,135,171,105,7,C.white,C.line);txt(ctx,enabled?'空间/时间关系已恢复':'相似内容仍有位置歧义',451,188,enabled?C.green:C.red,13,'center');};const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();const x=(e.clientX-r.left)*560/r.width,y=(e.clientY-r.top)*270/r.height;if(x<42||x>314||y<58||y>(mode==='video'?170:226))return;const col=clamp(Math.floor((x-42)/68),0,3);const row=mode==='video'?0:clamp(Math.floor((y-58)/56),0,2);setSel(clamp(row*4+col,0,total-1));};const key=(e:React.KeyboardEvent<HTMLCanvasElement>)=>{let n=sel;if(e.key==='ArrowRight')n++;if(e.key==='ArrowLeft')n--;if(e.key==='ArrowDown')n+=4;if(e.key==='ArrowUp')n-=4;if(n!==sel){e.preventDefault();setSel(clamp(n,0,total-1));}};return <div><Canvas h={270} draw={draw} onPointerDown={e=>{setDrag(true);e.currentTarget.setPointerCapture(e.pointerId);point(e)}} onPointerMove={e=>drag&&point(e)} onPointerUp={()=>setDrag(false)} tabIndex={0} onKeyDown={key} label="拖动或用方向键选择 patch 或帧"/><div className="chip-row">{(['single','multi','video'] as const).map(x=><Chip key={x} selected={mode===x} onClick={()=>{setMode(x);setSel(0)}}>{x==='single'?'Single Image':x==='multi'?'Multi-Image':'Video'}</Chip>)}<Chip selected={enabled} onClick={()=>setEnabled(v=>!v)}>{enabled?'已启用定位机制':'关闭定位'}</Chip></div><Feedback kind={enabled?'good':'bad'}>{enabled?'当前元素获得 [t,h,w]，模型同时知道“是什么、在哪里、什么时候”。':'教学对照：只有一维顺序时，空间或时间含义仍可能混淆。'}</Feedback></div>}

export const NeoCh6Main:React.FC<WidgetProps>=()=>{const [mode,setMode]=useState<'single'|'multi'|'video'>('multi');const [native,setNative]=useState(true);const [row,setRow]=useState(5);const units=mode==='single'?[1,1,1,1,1,1,1,1]:mode==='multi'?[1,1,1,1,2,2,2,2]:[1,1,2,2,3,3,4,4];const draw:Draw=(ctx)=>{clear(ctx,560,270);const n=8,cell=24,ox=62,oy=48;for(let i=0;i<n;i++)for(let j=0;j<n;j++){const open=j<=i||(native&&units[i]===units[j]);ctx.fillStyle=open?(units[i]===units[j]&&j>i?C.green:C.blue):'#edf0f4';ctx.globalAlpha=i===row?1:.36;ctx.fillRect(ox+j*cell,oy+i*cell,cell-2,cell-2);ctx.globalAlpha=1;}ctx.strokeStyle=C.orange;ctx.lineWidth=3;ctx.strokeRect(ox,oy+row*cell,n*cell-2,cell-2);round(ctx,290,50,238,135,7,C.white,C.line);txt(ctx,'蓝：因果历史',310,84,C.blue,13);txt(ctx,'绿：同视觉单元双向',310,113,C.green,13);txt(ctx,'灰：未来视觉单元关闭',310,142,C.muted,13);txt(ctx,native?'论文混合掩码':'纯因果教学对照',409,170,native?C.green:C.red,13,'center');};return <div><Canvas h={270} draw={draw}/><div className="chip-row">{(['single','multi','video'] as const).map(x=><Chip key={x} selected={mode===x} onClick={()=>{setMode(x);setRow(5)}}>{x==='single'?'单图':x==='multi'?'多图':'视频'}</Chip>)}<Chip selected={native} onClick={()=>setNative(true)}>论文掩码</Chip><Chip selected={!native} onClick={()=>setNative(false)}>全因果对照</Chip></div><div className="ctrl"><label>检查 token 行 <span className="val">{row+1}</span></label><input type="range" min="0" max="7" value={row} onChange={e=>setRow(Number(e.target.value))}/></div><Feedback kind={native?'good':'bad'}>{native?'同一视觉单元内部双向可见，跨视觉单元仍保持因果顺序。':'教学对照：纯因果会限制同图内部后续 patch；这不是论文报告的消融分数。'}</Feedback></div>}

export const NeoCh7Main:React.FC<WidgetProps>=()=>{const [input,setInput]=useState<'image'|'text'>('image');const imagePath=['图像','Patch Embedding','Pre-Buffer','统一主干','答案'];const textPath=['文本','Word Embedding','统一主干','答案'];const pathNow=input==='image'?imagePath:textPath;const [step,setStep]=useState(0);const draw:Draw=(ctx)=>{clear(ctx,560,280);const nodes=[['图像',25,52],['文本',25,172],['Patch Embedding',130,38],['Word Embedding',130,174],['Pre-Buffer',278,38],['统一主干',400,101],['答案',493,111]] as const;nodes.forEach(([name,x,y])=>{const pos=pathNow.indexOf(name);const active=pos>=0&&pos<=step;round(ctx,x,y,name==='Patch Embedding'||name==='Word Embedding'?130:84,54,7,active?'#e8eef7':C.white,active?C.blue:C.line,active?3:1);txt(ctx,name,x+(name.includes('Embedding')?65:42),y+32,active?C.blue:C.ink,11,'center');});const p=input==='image'?[[109,79,130,65],[260,65,278,65],[362,65,400,128],[484,128,493,138]]:[[109,199,130,201],[260,201,400,128],[484,128,493,138]];p.forEach((q,i)=>line(ctx,q[0],q[1],q[2],q[3],i<step?C.green:C.line,i<step?4:2));round(ctx,155,238,250,30,15,C.white,C.line);txt(ctx,input==='image'?'视觉路径：轻量前端→统一主干':'文本路径：原词嵌入→统一主干',280,258,C.blue,12,'center');};const switchInput=(x:'image'|'text')=>{setInput(x);setStep(0)};return <div><Canvas h={280} draw={draw}/><div className="chip-row"><Chip selected={input==='image'} onClick={()=>switchInput('image')}>图像输入</Chip><Chip selected={input==='text'} onClick={()=>switchInput('text')}>文本输入</Chip></div><div className="step-ctrl"><button className="tiny ghost" disabled={step===0} onClick={()=>setStep(s=>s-1)}>上一步</button><span className="step-label"><b>{pathNow[step]}</b></span><button className="tiny" disabled={step===pathNow.length-1} onClick={()=>setStep(s=>s+1)}>下一步</button></div><Feedback kind={step===pathNow.length-1?'good':'mid'}>{input==='image'?'视觉经过两层卷积 patch embedding 与 Pre-Buffer，再进入统一主干。':'文本保留原 LLM tokenizer/word embedding，再与视觉 token 在同一主干中建模。'}</Feedback></div>}

const stages=[{name:'Stage 1 · Pre-Training',data:'约 20M 图文对',objective:'自回归 next-token 对齐',learn:'基础视觉感知与表示对齐',why:'尽量保留预训练语言先验',next:'为混合模态全层训练建立稳定起点',detail:'只更新 patch embedding、Pre-Buffer 与新 QK 参数',color:C.blue},{name:'Stage 2 · Mid-Training',data:'近 60M；text:image:multi:video≈2:4:1:1',objective:'全层联合优化',learn:'多图、视频与空间—时间关系',why:'把上下文 16K 扩展到 36K',next:'为高质量指令跟随准备统一能力',detail:'256²–4096²，视频最多 128 帧',color:C.green},{name:'Stage 3 · SFT',data:'4M 单图 + 1M 多图 + 1M 视频',objective:'端到端 next-token 训练',learn:'指令跟随、细粒度感知与时间推理',why:'用高质量监督强化通用表现',next:'形成最终 NEO-ov 能力',detail:'全模型继续端到端优化',color:C.purple}];
export const NeoCh8Main:React.FC<WidgetProps>=()=>{const [stage,setStage]=useState(0);const s=stages[stage];const draw:Draw=(ctx)=>{clear(ctx,560,290);stages.forEach((x,i)=>{const px=22+i*178;round(ctx,px,24,160,54,7,i===stage?'#e8f5ed':C.white,i===stage?x.color:C.line,i===stage?3:1);txt(ctx,x.name,px+80,57,i===stage?x.color:C.ink,11,'center');if(i<2)line(ctx,px+160,51,px+178,51,i<stage?C.green:C.line,3);});const cards=[['Input',s.data],['Objective',s.objective],['What model learns',s.learn],['Why it matters',s.why],['Connection to next',s.next]];cards.forEach((x,i)=>{const col=i%2,row=Math.floor(i/2);const px=22+col*268,py=103+row*57;round(ctx,px,py,250,46,6,C.white,C.line);txt(ctx,x[0],px+10,py+17,s.color,10);txt(ctx,x[1],px+10,py+36,C.ink,11);});};return <div><Canvas h={290} draw={draw}/><div className="chip-row">{stages.map((x,i)=><Chip key={x.name} selected={stage===i} onClick={()=>setStage(i)}>{x.name}</Chip>)}</div><div className="step-ctrl"><button className="tiny ghost" disabled={stage===0} onClick={()=>setStage(s=>s-1)}>上一步</button><span className="step-label"><b>{stage+1}</b> / 3</span><button className="tiny" disabled={stage===2} onClick={()=>setStage(s=>s+1)}>下一步</button></div><Feedback kind={stage===0?'mid':'good'}>{s.detail}。论文未提供“跳过该阶段”的对应消融分数。</Feedback></div>}

const figs={4:{title:'Figure 4',tag:'随机初始化',models:'Pre-Buffer / Image Encoder / Video Encoder',bars:[.73,.65,.79],facts:['主张：原生 Pre-Buffer 可与两类编码器竞争。','实验：三种架构均随机初始化。','证据：覆盖 VQA、OCR、Video、SI 四类平均表现。','可得：Pre-Buffer 在这些设置下有竞争力。','不可得：不能写成对预训练编码器的普遍胜利。']},5:{title:'Figure 5',tag:'增加 SI 数据',models:'InternVL3.5 / Qwen3-VL / NEO',bars:[.63,.7,.83],facts:['主张：深层原生交互可能更受益于空间监督。','实验：比较增加 SI 数据前后。','证据：NEO 的增益更明显。','可得：该设置支持论文的空间数据分析。','不可得：主体是 NEO，不是 NEO-ov。']},6:{title:'Figure 6',tag:'仅 Stage 1→2',models:'NEO-ov 2B / NEO-ov 9B',bars:[.74,.82],facts:['主张：Mid-Training 强化多模态能力。','实验：2B 与 9B 从 Stage 1 到 Stage 2。','证据：两种规模的平均表现均提升。','可得：Stage 1→2 的进展得到支持。','不可得：原文没有 Stage 3 对照。']}} as const;
export const NeoCh9Main:React.FC<WidgetProps>=()=>{const [fig,setFig]=useState<4|5|6>(4);const [step,setStep]=useState(0);const f=figs[fig];const draw:Draw=(ctx)=>{clear(ctx,560,275);round(ctx,22,25,300,220,7,C.white,C.line);txt(ctx,f.title+' · '+f.tag,172,53,C.blue,14,'center');f.bars.forEach((v,i)=>{const x=55+i*77;ctx.fillStyle=i===f.bars.length-1?C.green:C.light;ctx.fillRect(x,205-v*135,44,v*135);});txt(ctx,'按原图定性重绘，不显示未标注精确值',172,231,C.muted,10,'center');round(ctx,344,25,194,220,7,C.white,C.line);['Claim','Experiment','Evidence','Conclusion','Boundary'].forEach((x,i)=>{round(ctx,360,42+i*38,162,28,5,i===step?'#e8eef7':C.white,i===step?C.blue:C.line,i===step?2:1);txt(ctx,x,441,61+i*38,i===step?C.blue:C.ink,11,'center');});};return <div><Canvas h={275} draw={draw}/><div className="chip-row">{([4,5,6] as const).map(x=><Chip key={x} selected={fig===x} onClick={()=>{setFig(x);setStep(0)}}>Figure {x}</Chip>)}</div><div className="chip-row">{['主张','实验','证据','可得结论','不可得结论'].map((x,i)=><Chip key={x} selected={step===i} onClick={()=>setStep(i)}>{x}</Chip>)}</div><Feedback kind={step===4?'bad':step===3?'good':'mid'}>{f.facts[step]} 模型：{f.models}。</Feedback></div>}

const results={image:{'2B':{metric:'MMMU',vals:[['NEO-ov',54.7],['NEO',48.6],['Qwen3-VL',53.4]]},'8B':{metric:'MMMU',vals:[['NEO-ov',68.1],['NEO',54.6],['Qwen3-VL',69.6]]}},video:{'2B':{metric:'VideoMME',vals:[['NEO-ov',60.4],['InternVL3.5',58.4],['Qwen3-VL',61.9]]},'8B':{metric:'VideoMME',vals:[['NEO-ov',67.4],['InternVL3.5',66.0],['Qwen3-VL',71.4]]}},spatial:{'2B':{metric:'Mindcube',vals:[['NEO-ov',77.2],['InternVL3.5',42.1],['Qwen3-VL',34.2]]},'8B':{metric:'Mindcube',vals:[['NEO-ov',90.0],['InternVL3.5',40.4],['Qwen3-VL',29.6]]}}} as const;
export const NeoCh10Main:React.FC<WidgetProps>=()=>{const [domain,setDomain]=useState<keyof typeof results>('image');const [scale,setScale]=useState<'2B'|'8B'>('2B');const [started,setStarted]=useState(false);const [progress,setProgress]=useState(0);const data=results[domain][scale];useEffect(()=>{if(!started){setProgress(0);return;}let raf=0;const begin=performance.now();const tick=(now:number)=>{const p=clamp((now-begin)/1800,0,1);setProgress(easeInOutQuad(p));if(p<1)raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[started,domain,scale]);const draw:Draw=(ctx)=>{clear(ctx,560,280);txt(ctx,data.metric+' · '+scale+' 规模组 · higher is better',28,32,C.blue,14);const max=Math.max(...data.vals.map(x=>x[1]));data.vals.forEach((v,i)=>{const y=66+i*60;txt(ctx,v[0],28,y+18,C.ink,12);round(ctx,126,y,390,30,6,'#eef1f5',C.line);const w=(v[1]/max)*380*progress;ctx.fillStyle=v[0]==='NEO-ov'?C.green:C.blue;ctx.fillRect(131,y+5,w,20);txt(ctx,progress>.98?v[1].toFixed(1):'—',510,y+21,v[0]==='NEO-ov'?C.green:C.blue,12,'right');});txt(ctx,'同表、同规模组、同数据集比较',280,260,C.muted,12,'center');};const reset=(d:keyof typeof results,s:'2B'|'8B')=>{setDomain(d);setScale(s);setStarted(false)};const neo=data.vals[0][1],best=Math.max(...data.vals.map(x=>x[1]));return <div><Canvas h={280} draw={draw}/><div className="chip-row">{([['image','图像'],['video','视频'],['spatial','空间']] as const).map(x=><Chip key={x[0]} selected={domain===x[0]} onClick={()=>reset(x[0],scale)}>{x[1]}</Chip>)}<Chip selected={scale==='2B'} onClick={()=>reset(domain,'2B')}>2B 组</Chip><Chip selected={scale==='8B'} onClick={()=>reset(domain,'8B')}>8B 组</Chip></div><div className="step-ctrl"><button className="tiny" onClick={()=>{setStarted(false);requestAnimationFrame(()=>setStarted(true))}}>开始比较</button></div><Feedback kind={!started?'mid':neo===best?'good':'bad'}>{!started?'选择条件后开始同协议比较。':neo===best?'该项中 NEO-ov 得分最高；这支持“有竞争力”，不代表所有任务占优。':'该项中 NEO-ov 不是最高分，论文也明确保留与顶级模块化模型的差距。'} 两个规模不足以建立完整 scaling law。</Feedback></div>}
