import React,{useEffect,useRef,useState} from 'react';
import {setupCanvas,observeCanvas} from '../lib/canvasKit';
type G=CanvasRenderingContext2D;
export const P={bg:'#f5f8f0',line:'#d7deea',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#d77e45',muted:'#68778f',soft:'#dce6d4',text:'#21324a'};
export const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
export function rect(c:G,x:number,y:number,w:number,h:number,fill='#fff',stroke=P.line,r=10){c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();c.strokeStyle=stroke;c.lineWidth=2;c.stroke();}
export function line(c:G,x:number,y:number,X:number,Y:number,color=P.blue,width=2){c.beginPath();c.moveTo(x,y);c.lineTo(X,Y);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.stroke();}
export function dot(c:G,x:number,y:number,r:number,color=P.blue){c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=color;c.fill();}
export function label(c:G,t:string,x:number,y:number,color=P.text,size=21){c.font=`600 ${size}px "Microsoft YaHei",sans-serif`;c.textAlign='center';c.textBaseline='middle';c.fillStyle=color;c.fillText(t,x,y);}
export function arrow(c:G,x:number,y:number,X:number,Y:number,color=P.blue){line(c,x,y,X,Y,color,3);const a=Math.atan2(Y-y,X-x);line(c,X,Y,X-10*Math.cos(a-.45),Y-10*Math.sin(a-.45),color,3);line(c,X,Y,X-10*Math.cos(a+.45),Y-10*Math.sin(a+.45),color,3);}
export function field(c:G,w=1000,h=320){c.clearRect(0,0,w,h);c.fillStyle=P.bg;c.fillRect(0,0,w,h);c.fillStyle='#e6ecdf';c.fillRect(0,h-44,w,44);line(c,0,h-44,w,h-44,'#cbd8c2',1);}
export function beaker(c:G,x:number,y:number,s=1,amount=.45,color=P.blue,angle=0){c.save();c.translate(x,y);c.rotate(angle);c.scale(s,s);c.beginPath();c.moveTo(-31,-38);c.lineTo(-27,38);c.quadraticCurveTo(0,49,27,38);c.lineTo(31,-38);c.closePath();c.fillStyle='#ffffffc9';c.fill();c.save();c.clip();c.fillStyle=color+'35';c.fillRect(-35,37-68*amount,70,90);c.beginPath();c.ellipse(0,37-68*amount,30,4,0,0,Math.PI*2);c.strokeStyle=color;c.lineWidth=1.5;c.stroke();c.restore();c.beginPath();c.moveTo(-31,-38);c.lineTo(-27,38);c.quadraticCurveTo(0,49,27,38);c.lineTo(31,-38);c.strokeStyle=P.blue;c.lineWidth=2;c.stroke();c.beginPath();c.ellipse(0,-38,31,6,0,0,Math.PI*2);c.stroke();for(let i=0;i<3;i++)line(c,10,17-i*16,23,17-i*16,P.muted,1.5);line(c,-19,-24,-17,25,'#fff',4);c.restore();}
export function testTube(c:G,x:number,y:number,s=1){c.save();c.translate(x,y);c.scale(s,s);c.beginPath();c.moveTo(-15,-50);c.lineTo(-15,30);c.quadraticCurveTo(-15,54,0,54);c.quadraticCurveTo(15,54,15,30);c.lineTo(15,-50);c.fillStyle='#fff';c.fill();c.strokeStyle=P.blue;c.lineWidth=2;c.stroke();c.fillStyle=P.green+'44';c.beginPath();c.roundRect(-11,9,22,40,[0,0,11,11]);c.fill();rect(c,-19,-55,38,8,'#e4ecf3',P.blue,3);c.restore();}
export function alcoholLamp(c:G,x:number,y:number,s=1){c.save();c.translate(x,y);c.scale(s,s);c.beginPath();c.ellipse(0,23,37,25,0,0,Math.PI*2);c.fillStyle='#edf2f8';c.fill();c.strokeStyle=P.blue;c.lineWidth=2;c.stroke();rect(c,-12,-8,24,14,'#a3b1be',P.blue,3);rect(c,-4,-27,8,19,'#ccb891','#92400e',2);rect(c,22,-35,27,30,'#c9d5de',P.blue,5);c.restore();}
export function arm(c:G,bx:number,by:number,tx:number,ty:number,s=1,color=P.blue){const sx=bx,sy=by-25*s,L1=130*s,L2=121*s;const dx=tx-sx,dy=ty-sy,d=Math.max(12,Math.min(Math.hypot(dx,dy),L1+L2-1));const base=Math.atan2(dy,dx),a=base-Math.acos(clamp((L1*L1+d*d-L2*L2)/(2*L1*d),-1,1));const ex=sx+L1*Math.cos(a),ey=sy+L1*Math.sin(a);const wx=sx+d*Math.cos(base),wy=sy+d*Math.sin(base);c.save();c.fillStyle='#21324a0c';c.beginPath();c.ellipse(bx,by+12*s,65*s,10*s,0,0,Math.PI*2);c.fill();rect(c,bx-43*s,by-8*s,86*s,22*s,'#d2dce4',color,5);for(const [x,y,X,Y] of [[sx,sy,ex,ey],[ex,ey,wx,wy]]){line(c,x,y,X,Y,color,27*s);line(c,x,y,X,Y,'#e9eff2',20*s);line(c,x-3*s,y-2*s,X-3*s,Y-2*s,'#fff',5*s);}for(const [x,y]of[[sx,sy],[ex,ey],[wx,wy]]){dot(c,x,y,17*s,color);dot(c,x,y,10*s,'#eaf0f3');dot(c,x,y,4*s,P.muted);}line(c,wx,wy,wx,wy+18*s,color,8*s);line(c,wx-15*s,wy+19*s,wx+15*s,wy+19*s,color,6*s);line(c,wx-15*s,wy+19*s,wx-15*s,wy+36*s,color,5*s);line(c,wx+15*s,wy+19*s,wx+15*s,wy+36*s,color,5*s);c.restore();return{x:wx,y:wy};}
export function human(c:G,x:number,y:number){dot(c,x,y-77,21,'#c9b9ab');rect(c,x-31,y-50,62,83,'#fff',P.blue,9);line(c,x,y+34,x-22,y+84,P.blue,10);line(c,x,y+34,x+22,y+84,P.blue,10);line(c,x-29,y-33,x-51,y+20,P.blue,9);line(c,x+29,y-33,x+60,y-6,P.blue,9);}
export function Canvas({draw,title,w=1000,h=320,animated=true,drag}:{draw:(c:G,t:number)=>void;title:string;w?:number;h?:number;animated?:boolean;drag?:(x:number,y:number)=>void}){const ref=useRef<HTMLCanvasElement>(null),fn=useRef(draw),held=useRef(false);fn.current=draw;useEffect(()=>{const el=ref.current!,c=setupCanvas(el,w,h);el.style.width='100%';el.style.height='auto';const media=matchMedia('(prefers-reduced-motion: reduce)');let id=0,visible=false;const render=(t:number)=>{fn.current(c,media.matches?1800:t);el.classList.add('is-ready');if(visible&&animated&&!media.matches)id=requestAnimationFrame(render);};const start=()=>{visible=true;cancelAnimationFrame(id);render(performance.now());};const stop=()=>{visible=false;cancelAnimationFrame(id);};render(performance.now());const dispose=observeCanvas(el,start,stop);media.addEventListener('change',start);return()=>{stop();dispose();media.removeEventListener('change',start);};},[w,h,animated]);useEffect(()=>{const el=ref.current;if(el)draw(el.getContext('2d')!,matchMedia('(prefers-reduced-motion: reduce)').matches?1800:performance.now());},[draw]);const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();drag?.(clamp((e.clientX-r.left)/r.width)*w,clamp((e.clientY-r.top)/r.height)*h);};return <div className={"lab-canvas-frame"+(w===1000&&!drag?" lab-canvas-wide":"")}><div className="lab-canvas-window"><canvas ref={ref} role="img" aria-label={title} style={{width:'100%',height:'auto',touchAction:drag?'none':'auto',cursor:drag?'grab':'default'}} onPointerDown={e=>{if(drag){held.current=true;e.currentTarget.setPointerCapture(e.pointerId);move(e);}}} onPointerMove={e=>{if(held.current)move(e);}} onPointerUp={()=>{held.current=false;}} onPointerCancel={()=>{held.current=false;}}/></div>{w===1000&&!drag?<span className="lab-pan-hint">左右滑动查看完整图示</span>:null}</div>;}
export function Choices({items,value,set}:{items:string[];value:number;set:(i:number)=>void}){return <div className="lab-controls">{items.map((t,i)=><button type="button" key={t} className={'lab-choice'+(value===i?' selected':'')} aria-pressed={value===i} onClick={()=>set(i)}>{t}</button>)}</div>;}
export function Feedback({children,tone='blue'}:{children:React.ReactNode;tone?:'blue'|'green'|'red'}){return <div className={'lab-feedback '+tone} role="status">{children}</div>;}
export function Stepper({value,max,set}:{value:number;max:number;set:(v:number)=>void}){return <div className="lab-controls"><button className="lab-choice" onClick={()=>set(0)} disabled={value===0}>重置</button><button className="lab-choice" onClick={()=>set(value-1)} disabled={value===0}>上一步</button><button className="lab-choice" onClick={()=>set(value+1)} disabled={value===max}>{value===max?'已完成':'下一步'}</button><span className="lab-step">{value} / {max}</span></div>;}
export function Route({items,active}:{items:string[];active:number}){return <ol className="lab-route">{items.map((item,i)=><li key={item} className={i===active?'current':''}><span>{i+1}</span>{item}</li>)}</ol>;}

export function HeroProblem(){return <><Canvas w={480} h={245} title="实验室数据与机器人形态造成执行缺口" draw={(c,t)=>{field(c,480,245);rect(c,20,17,200,43,'#fff',P.line);label(c,'通用数据',120,39,P.muted,18);rect(c,267,17,195,43,'#fff',P.line);label(c,'实验室操作',364,39,P.blue,18);const tip=arm(c,98,199,228+Math.sin(t/900)*12,129,.65,P.muted);beaker(c,345,170,.73);testTube(c,425,163,.55);c.setLineDash([6,6]);line(c,248,107,294,151,P.red,3);c.setLineDash([]);line(c,270,108,270,156,P.red,4);}}/><div className="lab-cover-caption">领域示范不足 · 采集成本高 · 机器人形态不同</div></>;}


export function Placement(){const[pos,set]=useState({x:795,y:205});const collision=Math.hypot(pos.x-445,pos.y-195)<80,reachable=((pos.x-210)/390)**2+((pos.y-210)/122)**2<1,good=reachable&&!collision;const move=(x:number,y:number)=>set({x:clamp(x,110,900),y:clamp(y,95,232)});return <><Canvas title="将烧杯拖入机械臂可达范围并避开固定器具" animated={false} drag={move} draw={c=>{field(c);c.beginPath();c.ellipse(210,210,390,122,0,0,Math.PI*2);c.fillStyle=P.green+'0a';c.fill();c.setLineDash([6,6]);c.strokeStyle=P.green;c.stroke();c.setLineDash([]);rect(c,399,133,93,114,'#dfe5e9',P.muted);label(c,'固定器具',445,278,P.muted,18);arm(c,160,263,294,156,.72);beaker(c,pos.x,pos.y,.67,.45,P.orange);c.beginPath();c.ellipse(pos.x,pos.y+34,42,11,0,0,Math.PI*2);c.strokeStyle=good?P.green:P.red;c.lineWidth=3;c.stroke();label(c,'可达范围',139,55,P.green,20);}}/><div className="lab-controls">{[['左移',-30,0],['右移',30,0],['上移',0,-25],['下移',0,25]].map(([v,x,y])=><button className="lab-choice" key={v} onClick={()=>move(pos.x+Number(x),pos.y+Number(y))}>{v}</button>)}<button className="lab-choice" onClick={()=>move(335,210)}>放入可行位置</button></div><Feedback tone={good?'green':'red'}>{!reachable?'超出机械臂可达范围，当前摆放不能直接用于执行。':collision?'与固定器具发生空间冲突，需要重新布置。':'当前摆放满足示意中的可达性与无碰撞条件，实际场景还需通过其他布局和物理检查。'}</Feedback></>;}



export function Fast(){const[step,set]=useState(0);const items=['连续动作示范','有效动作归一化','FAST 离散动作 token','VLM 下一 token 监督'];return <><Route items={items} active={step}/><Canvas animated={false} title={'FAST 预训练：'+items[step]} draw={c=>{field(c);const tip=arm(c,135,260,286,143,.8);beaker(c,tip.x,tip.y+52,.56);label(c,'动作示范',210,38);arrow(c,373,161,449,161);rect(c,481,48,468,220,'#fff',P.line);if(step<2){['手臂运动','夹爪动作','时间顺序'].forEach((v,i)=>{rect(c,506,76+i*60,418,43,step?'#edf4e8':'#f5f8fc',step?P.green:P.line);label(c,v,715,98+i*60,P.blue,21);});}else{['视觉与指令','状态信息','动作 token'].forEach((v,i)=>{rect(c,506+i*144,85,129,69,i===2?P.green+'15':'#f5f8fc',P.line);label(c,v,570+i*144,120,P.blue,18);});rect(c,558,190,318,47,step===3?P.blue:'#f6f8fc',P.line);label(c,step===3?'预测下一动作 token':'形成离散监督序列',716,214,step===3?'#fff':P.blue,20);}}}/><Stepper value={step} max={3} set={set}/><Feedback>{['动作示范保留连续的手臂与夹爪控制信息，首先作为待编码的监督目标。','按数据集统计量处理有效动作维度；为批处理补齐的维度不参与 FAST 编码。','FAST 将有效动作片段编码成离散 token，让动作能够参与视觉语言模型的序列学习。','骨干根据视觉语言前缀和已有 token 预测后续 token；没有动作标注的样本跳过动作 token 块，而不伪造零动作。'][step]}</Feedback></>;}


export function Insulation(){const[mode,set]=useState(0);return <><Choices items={['传递信息：理解支持动作','学习动作：更新动作专家','学习理解：更新视觉语言模型']} value={mode} set={set}/><div className="lab-ki"><div className={'lab-model-block '+(mode===2?'active':'')}><strong>VLM 视觉语言骨干</strong><span>{mode===2?'FAST / 标注监督可更新':'理解画面、指令与状态'}</span></div><div className={'lab-gate '+(mode===1?'blocked':'')}><span>理解结果传给动作专家</span><span>{mode===1?'动作梯度在此停止':'知识隔离位置'}</span></div><div className={'lab-model-block '+(mode===1?'active':'')}><strong>投影层与 DiT</strong><span>{mode===1?'接收流匹配梯度并更新':'读取条件并预测动作更新'}</span></div></div><Canvas title="知识隔离仅控制参数更新范围，不阻断机械臂动作所需的视觉语言信息" draw={(c,t)=>{field(c);const q=(Math.sin(t/650)+1)/2;rect(c,65,84,264,115,mode===2?P.blue+'15':'#fff',mode===2?P.blue:P.line);label(c,'视觉语言先验',197,123);label(c,mode===2?'token 监督继续学习':'作为动作学习的条件',197,166,P.muted,18);rect(c,650,84,280,115,mode===1?P.green+'15':'#fff',mode===1?P.green:P.line);label(c,'独立动作专家',790,123);label(c,mode===1?'流匹配更新':'生成连续动作',790,166,P.muted,18);arrow(c,356,117,623,117,P.blue);if(mode===1){c.setLineDash([12,6]);c.lineDashOffset=-q*18;line(c,623,173,504,173,P.green,4);c.setLineDash([]);line(c,493,145,493,201,P.red,6);label(c,'阻止回传至 VLM',490,233,P.red,19);}else if(mode===2){arrow(c,195,259,195,213,P.blue);label(c,'FAST 与标注损失',195,286,P.blue,18);}else{label(c,'画面与指令信息仍可读取',489,183,P.blue,20);}}}/><Feedback>{['信息仍能传过去：视觉语言模型先理解画面和指令，动作专家通过投影层读取这些条件，再决定怎样行动。','动作学习的反馈只更新投影层和 DiT，在视觉语言模型的接口处停止回传。这种“梯度截断”让动作目标不会直接改写 VLM 已有的理解。','VLM 仍通过 FAST 动作编码和标注任务继续学习。知识隔离限定的是动作反馈的影响范围，没有冻结整个模型。'][mode]}</Feedback></>;}


export function Limitations(){const[mode,set]=useState(0);return <><Choices items={['真实实验室验证有限','自主性限于固定流程','协作与失败解释未展示']} value={mode} set={set}/><Canvas title={['从受控台面到真实实验室存在未覆盖条件','机器人可以尝试执行固定流程但尚不能自主调整实验','尚未展示向科学家报告观察并解释自身失败的协作能力'][mode]} draw={(c,t)=>{field(c);const q=(Math.sin(t/1100)+1)/2;if(mode===0){rect(c,26,57,420,221,'#fff',P.line);arm(c,132,246,285,137,.72);beaker(c,341,232,.55);label(c,'受控仿真 / 单一真机平台',237,28,P.blue,19);arrow(c,477,158,543,158,P.red);rect(c,575,57,398,220,'#fff',P.red);['硬件漂移','试剂差异','安全与污染风险','意外故障'].forEach((v,i)=>{rect(c,608,76+i*46,332,35,i===Math.floor(q*3.9)?P.red+'10':'#f8fafc',P.line,5);label(c,v,774,94+i*46,P.muted,18);});label(c,'真实实验室仍需验证',774,29,P.red,20);}else if(mode===1){['固定步骤','已有指令','尝试执行'].forEach((v,i)=>{rect(c,39,69+i*65,219,44,'#fff',P.line);label(c,v,149,91+i*65,P.blue,19);});arm(c,375,257,532+q*18,146,.76);beaker(c,604,230,.58);arrow(c,645,155,710,155,P.red);line(c,686,127,686,184,P.red,5);rect(c,745,61,225,193,'#fff',P.line);['自主选实验条件','据测量修改流程','替换试剂 / 判断目标'].forEach((v,i)=>label(c,v,857,102+i*53,P.muted,18));}else{arm(c,174,256,329,137,.74);beaker(c,387,229,.55);human(c,837,179);rect(c,487,54,260,54,'#fff',P.line);label(c,'中间观察是什么？',617,81,P.blue,19);rect(c,487,123,260,54,'#fff',P.line);label(c,'失败在哪里、为什么？',617,150,P.blue,18);c.setLineDash([7,6]);c.lineDashOffset=-q*14;line(c,426,211,745,211,P.red,3);c.setLineDash([]);label(c,'自然协作与解释尚未展示',535,282,P.red,20);}}}/><Feedback tone="red">{['验证主要在仿真台面中开展，真机研究仅覆盖单一 Franka 平台的四项台面任务。真实实验室中的硬件漂移、试剂变化、安全约束、污染风险和意外故障仍未被充分覆盖。','展示的自主性是跟随既定流程。系统尚不能自主选择实验条件、根据测量修改步骤、替换试剂，或判断科学目标是否已经实现。','尚未展示策略与科学家的自然协作、中间观察沟通，以及对自身失败模式的识别与解释。这些是进入真实实验闭环前仍需补齐的能力。'][mode]}</Feedback></>;}
