import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { Ch1StressRepair } from './ch1-stress-repair';
import { Ch10ResultRace } from './ch10-result-race';
import { Ch10SlipCorner } from './ch10-slip-corner';
import { Ch10TrajectoryCompare } from './ch10-trajectory-compare';
import { Ch2LearnWhat } from './ch2-learn-what';
import { Ch2LookaheadDrag } from './ch2-lookahead-drag';
import { Ch3DataCost } from './ch3-data-cost';
import { Ch3RolloutCompare } from './ch3-rollout-compare';
import { Ch4ModelPredict } from './ch4-model-predict';
import { Ch4RolloutFlow } from './ch4-rollout-flow';
import { Ch6TrustMap } from './ch6-trust-map';
import { Ch4InfopropPipeline } from './ch4-infoprop-pipeline';
import { Ch4NoiseUncertainty } from './ch4-noise-uncertainty';
import { Ch5HistoryChips } from './ch5-history-chips';
import { Ch6PipelineSteps } from './ch6-pipeline-steps';
import { Ch7RewardSlider } from './ch7-reward-slider';
import { Ch8DynaLoop } from './ch8-dyna-loop';
import { Ch8SystemMap } from './ch8-system-map';
import { Ch9TimelineSteps } from './ch9-timeline-steps';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['ch1-stress-repair'] = Ch1StressRepair;
widgetRegistry['ch10-result-race'] = Ch10ResultRace;
widgetRegistry['ch10-slip-corner'] = Ch10SlipCorner;
widgetRegistry['ch10-trajectory-compare'] = Ch10TrajectoryCompare;
widgetRegistry['ch2-learn-what'] = Ch2LearnWhat;
widgetRegistry['ch2-lookahead-drag'] = Ch2LookaheadDrag;
widgetRegistry['ch3-data-cost'] = Ch3DataCost;
widgetRegistry['ch3-rollout-compare'] = Ch3RolloutCompare;
widgetRegistry['ch4-model-predict'] = Ch4ModelPredict;
widgetRegistry['ch4-rollout-flow'] = Ch4RolloutFlow;
widgetRegistry['ch6-trust-map'] = Ch6TrustMap;
widgetRegistry['ch4-infoprop-pipeline'] = Ch4InfopropPipeline;
widgetRegistry['ch4-noise-uncertainty'] = Ch4NoiseUncertainty;
widgetRegistry['ch5-history-chips'] = Ch5HistoryChips;
widgetRegistry['ch6-pipeline-steps'] = Ch6PipelineSteps;
widgetRegistry['ch7-reward-slider'] = Ch7RewardSlider;
widgetRegistry['ch8-dyna-loop'] = Ch8DynaLoop;
widgetRegistry['ch8-system-map'] = Ch8SystemMap;
widgetRegistry['ch9-timeline-steps'] = Ch9TimelineSteps;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
