import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ch1Analogy } from './ch1-analogy';
import { Ch1Orders } from './ch1-orders';
import { Ch10Analogy } from './ch10-analogy';
import { Ch10Demos } from './ch10-demos';
import { Ch10Evidence } from './ch10-evidence';
import { Ch2Analogy } from './ch2-analogy';
import { Ch2Vqa } from './ch2-vqa';
import { Ch2Execute } from './ch2-execute';
import { Ch3Analogy } from './ch3-analogy';
import { Ch3Twolanguage } from './ch3-twolanguage';
import { Ch4Analogy } from './ch4-analogy';
import { Ch4Tokenize } from './ch4-tokenize';
import { Ch4Detoken } from './ch4-detoken';
import { Ch5Analogy } from './ch5-analogy';
import { Ch5Recipe } from './ch5-recipe';
import { Ch6Analogy } from './ch6-analogy';
import { Ch6Loop } from './ch6-loop';
import { Ch7Analogy } from './ch7-analogy';
import { Ch7Nexttoken } from './ch7-nexttoken';
import { Ch8Analogy } from './ch8-analogy';
import { Ch8Arch } from './ch8-arch';
import { Ch8Vocab } from './ch8-vocab';
import { Ch9Analogy } from './ch9-analogy';
import { Ch9Cot } from './ch9-cot';
import { Ch9Emergent } from './ch9-emergent';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ch1-analogy'] = Ch1Analogy;
widgetRegistry['ch1-orders'] = Ch1Orders;
widgetRegistry['ch10-analogy'] = Ch10Analogy;
widgetRegistry['ch10-demos'] = Ch10Demos;
widgetRegistry['ch10-evidence'] = Ch10Evidence;
widgetRegistry['ch2-analogy'] = Ch2Analogy;
widgetRegistry['ch2-vqa'] = Ch2Vqa;
widgetRegistry['ch2-execute'] = Ch2Execute;
widgetRegistry['ch3-analogy'] = Ch3Analogy;
widgetRegistry['ch3-twolanguage'] = Ch3Twolanguage;
widgetRegistry['ch4-analogy'] = Ch4Analogy;
widgetRegistry['ch4-tokenize'] = Ch4Tokenize;
widgetRegistry['ch4-detoken'] = Ch4Detoken;
widgetRegistry['ch5-analogy'] = Ch5Analogy;
widgetRegistry['ch5-recipe'] = Ch5Recipe;
widgetRegistry['ch6-analogy'] = Ch6Analogy;
widgetRegistry['ch6-loop'] = Ch6Loop;
widgetRegistry['ch7-analogy'] = Ch7Analogy;
widgetRegistry['ch7-nexttoken'] = Ch7Nexttoken;
widgetRegistry['ch8-analogy'] = Ch8Analogy;
widgetRegistry['ch8-arch'] = Ch8Arch;
widgetRegistry['ch8-vocab'] = Ch8Vocab;
widgetRegistry['ch9-analogy'] = Ch9Analogy;
widgetRegistry['ch9-cot'] = Ch9Cot;
widgetRegistry['ch9-emergent'] = Ch9Emergent;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
