import React, { useEffect, useRef } from 'react';
import { setupCanvas, observeCanvas } from '../lib/canvasKit';
export const C={ivory:'#f8f6ef',pink:'#ecd3d4',sage:'#a3b5a5',aqua:'#c6ded6',ink:'#294b40',blue:'#547789',green:'#438268',red:'#ac626b',orange:'#b88a58',purple:'#928099'};
type Ctx=CanvasRenderingContext2D;
export function ellipse(c:Ctx,x:number,y:number,rx:number,ry:number,color:string){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill()}
export function line(c:Ctx,x:number,y:number,ex:number,ey:number,color:string,width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(x,y);c.lineTo(ex,ey);c.stroke()}
export function drawTarget(c:Ctx,x:number,y:number,size=20){c.save();c.translate(x,y);for(let i=0;i<5;i++){c.save();c.rotate(i*Math.PI*2/5);ellipse(c,0,-size*.48,size*.34,size*.52,C.pink);c.restore()}ellipse(c,0,0,size*.17,size*.17,C.orange);c.restore()}
export function drawPrompt(c:Ctx,x:number,y:number,color=C.aqua,size=20){c.save();c.translate(x,y);c.rotate(-.15);c.fillStyle=color;c.strokeStyle=C.blue;c.lineWidth=1.4;c.beginPath();c.roundRect(-size*.65,-size,size*1.3,size*2,size*.45);c.fill();c.stroke();line(c,-size*.3,-size*.25,size*.3,-size*.25,'#ffffff',2);line(c,-size*.3,size*.25,size*.15,size*.25,'#ffffff',2);c.restore()}
function peachBranch(c:Ctx,x:number,y:number,flip=1){c.save();c.translate(x,y);c.scale(flip,1);c.strokeStyle='#a4a895';c.lineWidth=3;c.beginPath();c.moveTo(0,100);c.bezierCurveTo(30,50,115,35,230,-12);c.stroke();for(const [a,b] of [[65,57],[97,41],[135,22],[180,8],[207,1]]){line(c,a,b,a+12,b-28,'#b9b9a6',1.5);drawTarget(c,a+14,b-32,9)}c.restore()}
export function drawGarden(c:Ctx,w:number,h:number){c.clearRect(0,0,w,h);c.fillStyle=C.ivory;c.fillRect(0,0,w,h);const mist=c.createRadialGradient(w*.18,h*.2,10,w*.2,h*.5,w*.6);mist.addColorStop(0,'#f2e0df');mist.addColorStop(1,C.ivory);c.fillStyle=mist;c.fillRect(0,0,w,h);c.globalAlpha=.42;peachBranch(c,0,10);peachBranch(c,w,40,-1);c.globalAlpha=1;ellipse(c,w*.22,h*.87,w*.16,h*.07,'#dce5d9');c.strokeStyle='#c0d0c1';c.lineWidth=1;c.beginPath();c.ellipse(w*.22,h*.85,w*.16,h*.055,0,0,Math.PI*2);c.stroke();line(c,w*.02,h*.92,w*.95,h*.92,'#d9ded0',1)}
export function drawRobot(c:Ctx,x:number,y:number,scale=1,mood:'neutral'|'happy'|'uncertain'='neutral',pose=0){c.save();c.translate(x,y);c.scale(scale,scale);ellipse(c,0,92,68,12,'#bccbbc55');const coat=c.createLinearGradient(-55,0,55,60);coat.addColorStop(0,'#dce5d9');coat.addColorStop(1,'#bdcdc0');c.fillStyle=coat;c.strokeStyle='#95a99b';c.lineWidth=1.8;
// legs, translucent joints, sleeves
for(const side of [-1,1]){c.beginPath();c.roundRect(side*20-10,44,21,41,10);c.fill();c.stroke();ellipse(c,side*20,57,5,5,C.aqua);c.beginPath();c.roundRect(side*22-14,80,29,13,6);c.fill();c.stroke();c.save();c.translate(side*45,0);c.rotate(side*(.22+pose*.25));c.beginPath();c.roundRect(-10,-2,20,54,10);c.fill();c.stroke();ellipse(c,0,31,5,5,C.aqua);c.beginPath();c.roundRect(-9,46,18,17,8);c.fill();c.stroke();c.restore()}
c.beginPath();c.roundRect(-37,-9,74,70,24);c.fill();c.stroke();c.fillStyle='#c4dcd788';c.beginPath();c.roundRect(-20,4,40,37,15);c.fill();ellipse(c,0,23,11,11,'#a8c9b9');ellipse(c,0,23,5,5,mood==='happy'?C.green:C.blue);line(c,0,6,0,13,'#f8f6ef',2);c.fillStyle=coat;c.beginPath();c.roundRect(-8,-27,16,20,6);c.fill();c.stroke();
// porcelain head and glass face
c.fillStyle='#cbd8cc';c.beginPath();c.roundRect(-47,-99,94,77,29);c.fill();c.stroke();c.fillStyle='#e3eae0';c.beginPath();c.roundRect(-36,-86,72,44,18);c.fill();c.strokeStyle='#b3c4b5';c.stroke();for(const side of [-1,1]){if(mood==='happy'){c.strokeStyle=C.ink;c.lineWidth=3;c.beginPath();c.arc(side*17,-66,6,Math.PI,0);c.stroke()}else ellipse(c,side*17,-67,mood==='uncertain'?3:4,6,C.ink)}c.strokeStyle=C.ink;c.lineWidth=1.5;c.beginPath();c.arc(0,-54,5,0,Math.PI);c.stroke(); c.restore()}
type Props={draw:(c:Ctx,w:number,h:number,time:number)=>void;height?:number;label?:string;onPointerDown?:React.PointerEventHandler<HTMLCanvasElement>;onPointerMove?:React.PointerEventHandler<HTMLCanvasElement>;onPointerUp?:React.PointerEventHandler<HTMLCanvasElement>};
export function SceneCanvas({draw,height=280,label='机器人与提示交互场景',...pointer}:Props){const ref=useRef<HTMLCanvasElement>(null);const render=useRef(draw);render.current=draw;useEffect(()=>{const el=ref.current!;const c=setupCanvas(el,1080,height);el.style.width='100%';el.style.height='auto';let id=0,visible=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const frame=(t:number)=>{render.current(c,1080,height,reduced?0:t/1000);el.classList.add('is-ready');if(visible)id=requestAnimationFrame(frame)};frame(0);const stop=()=>{visible=false;cancelAnimationFrame(id)};const cleanup=observeCanvas(el,()=>{if(!visible){visible=true;id=requestAnimationFrame(frame)}},stop);return()=>{stop();cleanup()}},[height]);return <canvas ref={ref} role="img" aria-label={label} style={{width:'100%',height:'auto',aspectRatio:`1080 / ${height}`,touchAction:pointer.onPointerDown?'none':'auto'}} {...pointer}/>}
export function RobotStory({chapter=1,hero=false}:{chapter?:number;hero?:boolean}){return <SceneCanvas height={hero?520:270} label={hero?'桃花与未来实验空间中的浅灰绿色机器人':'机器人在桃源中练习一项任务'} draw={(c,w,h,t)=>{drawGarden(c,w,h);const pulse=Math.sin(t*Math.PI*2/3);const x=hero?w*.55: w*.28;const y=hero?h*.65:h*.58;const scale=hero?1.65: .9;const motion=chapter===9?pulse*15:0;drawRobot(c,x+motion,y,scale,chapter>=5?'happy':'neutral',pulse*.2+chapter*.035);if(hero){c.save();c.globalAlpha=.65;c.strokeStyle='#a7c3ba';c.lineWidth=1;for(let i=0;i<3;i++){c.beginPath();c.ellipse(x,y+110,130+i*32,31+i*12,0,0,Math.PI*2);c.stroke()}c.restore();for(let i=0;i<5;i++)drawPrompt(c,x-200+i*65,y-170+Math.sin(i)*20,C.aqua,15);drawTarget(c,x+220,y-15,28);c.strokeStyle='#cad9d0';c.beginPath();c.roundRect(740,90,175,86,7);c.stroke();line(c,760,120,890,120,'#b1c7bd');line(c,760,141,840,141,'#c6d4c9');}
else {const tx=w*.68,ty=h*.49; const hand=x+65, hy=y+15-pulse*7;
if(chapter===1){drawTarget(c,hand+20,hy-10,16);line(c,hand,hy,hand+25,hy,C.sage,3)}
else if(chapter===2){c.save();c.translate(hand+24,hy-20);c.rotate(.1);drawPrompt(c,0,0,C.pink,31);c.restore()}
else if(chapter===3){drawPrompt(c,hand+20,hy-50,C.ivory,33);line(c,hand-3,hy,hand+16,hy-30,C.sage,3)}
else if(chapter===4){c.save();c.translate(hand+34,hy-8);c.rotate(pulse*.2);drawPrompt(c,0,0,C.aqua,22);c.restore();ellipse(c,hand+34,hy+24,26,7,'#c8d7c4')}
else if(chapter===5){c.save();c.translate(hand+30,hy-25);c.rotate(pulse*.32);drawPrompt(c,0,0,C.aqua,22);c.restore()}
else if(chapter===6){c.strokeStyle=C.blue;c.lineWidth=3;c.beginPath();c.arc(hand+23,hy-48,24,0,Math.PI*2);c.stroke();line(c,hand+12,hy-28,hand-8,hy,C.sage,5)}
else if(chapter===7){c.fillStyle='#e4ece0';c.fillRect(hand+15,hy-20,125+pulse*12,34);c.strokeStyle=C.sage;c.strokeRect(hand+15,hy-20,125+pulse*12,34);for(let i=0;i<5;i++)drawPrompt(c,hand+29+i*23,hy-3,C.aqua,8)}
else if(chapter===8){drawPrompt(c,hand+80,hy-45,C.ivory,38);c.fillStyle='#b9d6c766';c.beginPath();c.moveTo(hand,hy-10);c.lineTo(hand+72,hy-74);c.lineTo(hand+75,hy-15);c.fill();line(c,hand-10,hy,hand+4,hy-12,C.sage,6)}
else if(chapter===9){c.strokeStyle='#a9ba9f';c.lineWidth=3;c.beginPath();c.moveTo(x-60,y+86);c.quadraticCurveTo(x+30,y+35,x+125,y+86);c.stroke();drawTarget(c,tx,ty,20)}
else{drawTarget(c,hand+25,hy-58,24);line(c,hand+22,hy-39,hand+13,hy,C.sage,3)}
if(chapter!==9)drawTarget(c,tx,ty,20)}
}}/>}
