import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AblationWidget } from './ablation';
import { Analogy1 } from './analogy-1';
import { Analogy10 } from './analogy-10';
import { Analogy2 } from './analogy-2';
import { Analogy3 } from './analogy-3';
import { Analogy4 } from './analogy-4';
import { Analogy5 } from './analogy-5';
import { Analogy6 } from './analogy-6';
import { Analogy7 } from './analogy-7';
import { Analogy8 } from './analogy-8';
import { Analogy9 } from './analogy-9';
import { CostWidget } from './cost';
import { DomainWidget } from './domain';
import { EmbedWidget } from './embed';
import { EnsembleWidget } from './ensemble';
import { HardWidget } from './hard';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { LengthWidget } from './length';
import { ObjectiveWidget } from './objective';
import { ScaleWidget } from './scale';
import { TaskWidget } from './task';
import { TrainWidget } from './train';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ablation'] = AblationWidget;
widgetRegistry['analogy-1'] = Analogy1;
widgetRegistry['analogy-10'] = Analogy10;
widgetRegistry['analogy-2'] = Analogy2;
widgetRegistry['analogy-3'] = Analogy3;
widgetRegistry['analogy-4'] = Analogy4;
widgetRegistry['analogy-5'] = Analogy5;
widgetRegistry['analogy-6'] = Analogy6;
widgetRegistry['analogy-7'] = Analogy7;
widgetRegistry['analogy-8'] = Analogy8;
widgetRegistry['analogy-9'] = Analogy9;
widgetRegistry['cost'] = CostWidget;
widgetRegistry['domain'] = DomainWidget;
widgetRegistry['embed'] = EmbedWidget;
widgetRegistry['ensemble'] = EnsembleWidget;
widgetRegistry['hard'] = HardWidget;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['length'] = LengthWidget;
widgetRegistry['objective'] = ObjectiveWidget;
widgetRegistry['scale'] = ScaleWidget;
widgetRegistry['task'] = TaskWidget;
widgetRegistry['train'] = TrainWidget;
