import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { Wla11 } from './wla-1-1';
import { Wla101 } from './wla-10-1';
import { Wla102 } from './wla-10-2';
import { Wla21 } from './wla-2-1';
import { Wla31 } from './wla-3-1';
import { Wla32 } from './wla-3-2';
import { Wla41 } from './wla-4-1';
import { Wla42 } from './wla-4-2';
import { Wla51 } from './wla-5-1';
import { Wla61 } from './wla-6-1';
import { Wla71 } from './wla-7-1';
import { Wla81 } from './wla-8-1';
import { Wla91 } from './wla-9-1';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['wla-1-1'] = Wla11;
widgetRegistry['wla-10-1'] = Wla101;
widgetRegistry['wla-10-2'] = Wla102;
widgetRegistry['wla-2-1'] = Wla21;
widgetRegistry['wla-3-1'] = Wla31;
widgetRegistry['wla-3-2'] = Wla32;
widgetRegistry['wla-4-1'] = Wla41;
widgetRegistry['wla-4-2'] = Wla42;
widgetRegistry['wla-5-1'] = Wla51;
widgetRegistry['wla-6-1'] = Wla61;
widgetRegistry['wla-7-1'] = Wla71;
widgetRegistry['wla-8-1'] = Wla81;
widgetRegistry['wla-9-1'] = Wla91;
