import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AnaCh1Tiles } from './ana-ch1-tiles';
import { AnaCh10Tiles } from './ana-ch10-tiles';
import { AnaCh2Tiles } from './ana-ch2-tiles';
import { AnaCh3Tiles } from './ana-ch3-tiles';
import { AnaCh4Tiles } from './ana-ch4-tiles';
import { AnaCh5Tiles } from './ana-ch5-tiles';
import { AnaCh6Tiles } from './ana-ch6-tiles';
import { AnaCh7Tiles } from './ana-ch7-tiles';
import { AnaCh8Tiles } from './ana-ch8-tiles';
import { AnaCh9Tiles } from './ana-ch9-tiles';
import { DitronThemeKit } from './ditron-theme-kit';
import { HeroNewTiles } from './hero-new-tiles';
import { HeroOldTiles } from './hero-old-tiles';
import { M11CommShare } from './m1-1-comm-share';
import { M101ResultRace } from './m10-1-result-race';
import { M21LevelSpot } from './m2-1-level-spot';
import { M31SwizzleCompare } from './m3-1-swizzle-compare';
import { M32GatherScatter } from './m3-2-gather-scatter';
import { M41TileSplit } from './m4-1-tile-split';
import { M51CommChoice } from './m5-1-comm-choice';
import { M52FlipCurve } from './m5-2-flip-curve';
import { M61PipelineSteps } from './m6-1-pipeline-steps';
import { M71LowLevelOpts } from './m7-1-lowlevel-opts';
import { M81ArchMap } from './m8-1-arch-map';
import { M82ArchFlow } from './m8-2-arch-flow';
import { M91PlatformChips } from './m9-1-platform-chips';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-ch1-tiles'] = AnaCh1Tiles;
widgetRegistry['ana-ch10-tiles'] = AnaCh10Tiles;
widgetRegistry['ana-ch2-tiles'] = AnaCh2Tiles;
widgetRegistry['ana-ch3-tiles'] = AnaCh3Tiles;
widgetRegistry['ana-ch4-tiles'] = AnaCh4Tiles;
widgetRegistry['ana-ch5-tiles'] = AnaCh5Tiles;
widgetRegistry['ana-ch6-tiles'] = AnaCh6Tiles;
widgetRegistry['ana-ch7-tiles'] = AnaCh7Tiles;
widgetRegistry['ana-ch8-tiles'] = AnaCh8Tiles;
widgetRegistry['ana-ch9-tiles'] = AnaCh9Tiles;
widgetRegistry['ditron-theme-kit'] = DitronThemeKit;
widgetRegistry['hero-new-tiles'] = HeroNewTiles;
widgetRegistry['hero-old-tiles'] = HeroOldTiles;
widgetRegistry['m1-1-comm-share'] = M11CommShare;
widgetRegistry['m10-1-result-race'] = M101ResultRace;
widgetRegistry['m2-1-level-spot'] = M21LevelSpot;
widgetRegistry['m3-1-swizzle-compare'] = M31SwizzleCompare;
widgetRegistry['m3-2-gather-scatter'] = M32GatherScatter;
widgetRegistry['m4-1-tile-split'] = M41TileSplit;
widgetRegistry['m5-1-comm-choice'] = M51CommChoice;
widgetRegistry['m5-2-flip-curve'] = M52FlipCurve;
widgetRegistry['m6-1-pipeline-steps'] = M61PipelineSteps;
widgetRegistry['m7-1-lowlevel-opts'] = M71LowLevelOpts;
widgetRegistry['m8-1-arch-map'] = M81ArchMap;
widgetRegistry['m8-2-arch-flow'] = M82ArchFlow;
widgetRegistry['m9-1-platform-chips'] = M91PlatformChips;
