import React, { useState } from 'react';
import type { WidgetProps } from './registry';

type Design = { name: string; hypothesis: string; ablation: string; supports: string; cannot: string; data: string };
const DESIGNS: Design[] = [
  { name:'M3W', hypothesis:'自然交错的网页图文会为 few-shot 学习提供任务上下文。', ablation:'论文的训练数据是混合配方；核验时必须同时记录 M3W、配对数据、视频数据与目标权重，不能把它们简化成单一因果对照。', supports:'M3W 为模型提供自然交错的网页图文结构，与论文报告的跨任务 few-shot 能力相容。', cannot:'不能单独证明 M3W 是唯一原因，也不能把跨任务结果直接归因于某一个数据源。', data:'M3W 约含 4300 万网页；依据 DOM 位置保留图文顺序，插入 <image> 与 <EOC> 标记，并随机采样 L=256 tokens、最多 N=5 张图片。' },
  { name:'Perceiver Resampler', hypothesis:'固定数量视觉 token 能在可变媒体输入下保持可控上下文。', ablation:'改变视觉连接器或移除压缩桥，比较下游任务表现与计算负担。', supports:'不同分辨率和视频帧数共享同一视觉接口。', cannot:'不能推出 64 一定是全任务最优，只能说明论文设置下有效。', data:'固定输出 64 visual tokens；Figure 2 不是它的单独消融。' },
  { name:'tanh gating', hypothesis:'从零附近打开新通路可以保护冻结语言先验。', ablation:'比较带门控与无门控或不同初始化的训练稳定性和表现。', supports:'新增视觉路径以较小扰动接入 Frozen LM。', cannot:'没有独立初始化对照时，不能把所有提升都归因于 tanh。', data:'x′ = x + tanh(α)·XAttn(x,Z)，α 初始接近 0。' },
  { name:'GATED XATTN-DENSE', hypothesis:'在语言层间插入轻量跨注意力足以传递视觉证据。', ablation:'移除跨注意力或替换连接位置，比较视觉任务性能。', supports:'单一连接器覆盖问答、描述和选择题。', cannot:'不能证明每个插入层都同等重要，除非有频率消融。', data:'训练集中在新插入模块，语言与视觉大骨干保持冻结。' },
  { name:'cross-attention frequency', hypothesis:'跨注意力插入频率决定视觉证据与计算成本的折中。', ablation:'改变层间插入频率，观察精度和效率变化。', supports:'频率是可调的架构超参数。', cannot:'单个最佳频率不等于所有规模、任务都最佳。', data:'应结合架构配置与消融表阅读，不能只看一个 benchmark。' },
  { name:'strong vision encoder', hypothesis:'冻结且强大的视觉骨干能提供可迁移的视觉语义。', ablation:'替换视觉编码器或比较不同预训练强度。', supports:'视觉骨干越强，少样本迁移上限通常越高。', cannot:'相关性不等于视觉编码器单独造成全部提升。', data:'论文使用预训练视觉模型，再通过 Flamingo 连接语言模型。' },
  { name:'freezing LM', hypothesis:'保留语言先验比端到端更新更节省数据与计算，并减少遗忘。', ablation:'比较冻结语言骨干与微调语言骨干的成本和性能。', supports:'少量示例即可通过上下文适配。', cannot:'冻结不保证没有幻觉，也不代表微调在所有任务都更差。', data:'Frozen LM 是论文设计边界，输出依赖语言模型已有生成能力。' },
];

export const ReviewerEvidence: React.FC<WidgetProps> = () => {
  const [entered, setEntered] = useState(false); const [index, setIndex] = useState(0); const [scores, setScores] = useState(DESIGNS.map(() => 5)); const [details, setDetails] = useState(false); const [results, setResults] = useState(false); const [strong, setStrong] = useState<string[]>([]); const [weak, setWeak] = useState<string[]>([]);
  const design = DESIGNS[index]; const total = scores.reduce((a,b) => a+b, 0);
  const finishScore = () => index < DESIGNS.length - 1 ? setIndex(index + 1) : setResults(true);
  const toggle = (setter: React.Dispatch<React.SetStateAction<string[]>>, name: string) => setter(v => v.includes(name) ? v.filter(x => x !== name) : v.length < 3 ? [...v, name] : v);
  const enterNext = () => { const b = document.querySelector('button.slide-nav-btn-primary:not(:disabled)') as HTMLButtonElement | null; if (b) { b.focus(); b.click(); } };
  const architecture = ['image / video','      │','      ▼','[ Strong Vision Encoder ]','      │','[ Perceiver Resampler ]','      │  64 visual tokens','      ▼','╔══════════════════════════════╗','║ Frozen LM  ⇄  GATED XATTN-DENSE ║','║ cross-attention every k layers ║','╚══════════════════════════════╝','      │','      ▼','   Text Output'].join('\n');
  return <div className="reviewer-scene">{!entered ? <div className="architecture-overview"><div className="reviewer-kicker">REVIEW DESK · FULL ARCHITECTURE</div><pre>{architecture}</pre><p>先看完整架构，再进入评审桌，逐项审查作者的假设与证据。</p><button type="button" className="review-enter" onClick={() => setEntered(true)}>进入架构评审 →</button></div> : !results ? <div className="review-panel"><div className="reviewer-kicker">DESIGN {index + 1} / {DESIGNS.length} · {design.name}</div><div className="review-grid"><div><h4>作者假设</h4><p>{design.hypothesis}</p></div><div><h4>消融怎么测</h4><p>{design.ablation}</p></div><div><h4>数据支持什么</h4><p>{design.supports}</p></div><div><h4>不能推出什么</h4><p>{design.cannot}</p></div></div><div className="review-score"><label>你的证据可信度：<strong>{scores[index]} / 10</strong><input type="range" min="0" max="10" value={scores[index]} onChange={e => setScores(v => v.map((s,i) => i === index ? Number(e.target.value) : s))}/></label><span>{design.data}</span></div><button type="button" className="review-detail-toggle" onClick={() => setDetails(v => !v)}>{details ? '收起实验细节' : '打开技术细节抽屉'}</button>{details && <div className="review-drawer"><strong>审稿备注：</strong>{design.data}<br/>评分应同时考虑对照是否隔离、协议是否一致、指标是否可比。</div>}<button type="button" className="review-next" onClick={finishScore}>{index < DESIGNS.length - 1 ? '保存评分，审查下一项 →' : '完成评分，查看总分 →'}</button></div> : <div className="review-results"><div className="reviewer-kicker">EVIDENCE SUMMARY · 总分 {total} / 70</div><p>分数不是“真理”，而是你对证据强度、对照质量和结论边界的审稿判断。</p><div className="figure2"><h4>Figure 2 趋势：model scale × number of shots（定性示意，非原始数值）</h4>{[['0',22],['4',36],['8',49],['16',61],['32',72]].map(([s,w]) => <div className="trend-row" key={s as string}><span>shots: {s}</span><i style={{width:`${w}%`}}/></div>)}<p>论文右图比较 Flamingo-3B、Flamingo-9B 与 Flamingo-80B：模型规模增大、shots 从 0 增至 4、8、16、32 时，聚合性能总体提高。这里仅保留趋势，不把示意条当作论文原始百分比。</p></div><button type="button" className="review-detail-toggle" onClick={() => setDetails(v => !v)}>{details ? '收起实验数据抽屉' : '打开实验数据抽屉'}</button>{details && <div className="review-drawer">Figure 2 是趋势证据；跨任务 few-shot 表格是广度证据；消融表才更接近部件因果证据。三类证据不能互相替代。</div>}<div className="evidence-choice"><h4>最强的三个证据：</h4>{DESIGNS.map(d => <button key={d.name} type="button" className={strong.includes(d.name) ? 'chosen' : ''} onClick={() => toggle(setStrong,d.name)}>{d.name}</button>)}</div><div className="evidence-choice"><h4>相对薄弱的证据：</h4>{DESIGNS.map(d => <button key={d.name} type="button" className={weak.includes(d.name) ? 'chosen weak' : ''} onClick={() => toggle(setWeak,d.name)}>{d.name}</button>)}</div><p className="review-conclusion">你现在不只是知道 Flamingo 怎么做，也开始判断为什么、在什么边界内相信它有效。</p><button type="button" className="review-next" onClick={enterNext}>完成审稿，进入下一章 →</button></div>}</div>;
};
