import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ch1Analogy } from './ch1-analogy';
import { Ch10Analogy } from './ch10-analogy';
import { Ch10Mod1 } from './ch10mod1';
import { Ch10Mod2 } from './ch10mod2';
import { Ch1Mod1 } from './ch1mod1';
import { Ch1Mod2 } from './ch1mod2';
import { Ch2Analogy } from './ch2-analogy';
import { Ch2Mod1 } from './ch2mod1';
import { Ch3Analogy } from './ch3-analogy';
import { Ch3Mod1 } from './ch3mod1';
import { Ch3Mod2 } from './ch3mod2';
import { Ch4Analogy } from './ch4-analogy';
import { Ch4Mod1 } from './ch4mod1';
import { Ch5Analogy } from './ch5-analogy';
import { Ch5Mod1 } from './ch5mod1';
import { Ch6Analogy } from './ch6-analogy';
import { Ch6Mod1 } from './ch6mod1';
import { Ch7Analogy } from './ch7-analogy';
import { Ch7Mod1 } from './ch7mod1';
import { Ch8Analogy } from './ch8-analogy';
import { Ch8Mod1 } from './ch8mod1';
import { Ch8Mod2 } from './ch8mod2';
import { Ch9Analogy } from './ch9-analogy';
import { Ch9Mod1 } from './ch9mod1';
import { Ch9Mod2 } from './ch9mod2';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ch1-analogy'] = Ch1Analogy;
widgetRegistry['ch10-analogy'] = Ch10Analogy;
widgetRegistry['ch10mod1'] = Ch10Mod1;
widgetRegistry['ch10mod2'] = Ch10Mod2;
widgetRegistry['ch1mod1'] = Ch1Mod1;
widgetRegistry['ch1mod2'] = Ch1Mod2;
widgetRegistry['ch2-analogy'] = Ch2Analogy;
widgetRegistry['ch2mod1'] = Ch2Mod1;
widgetRegistry['ch3-analogy'] = Ch3Analogy;
widgetRegistry['ch3mod1'] = Ch3Mod1;
widgetRegistry['ch3mod2'] = Ch3Mod2;
widgetRegistry['ch4-analogy'] = Ch4Analogy;
widgetRegistry['ch4mod1'] = Ch4Mod1;
widgetRegistry['ch5-analogy'] = Ch5Analogy;
widgetRegistry['ch5mod1'] = Ch5Mod1;
widgetRegistry['ch6-analogy'] = Ch6Analogy;
widgetRegistry['ch6mod1'] = Ch6Mod1;
widgetRegistry['ch7-analogy'] = Ch7Analogy;
widgetRegistry['ch7mod1'] = Ch7Mod1;
widgetRegistry['ch8-analogy'] = Ch8Analogy;
widgetRegistry['ch8mod1'] = Ch8Mod1;
widgetRegistry['ch8mod2'] = Ch8Mod2;
widgetRegistry['ch9-analogy'] = Ch9Analogy;
widgetRegistry['ch9mod1'] = Ch9Mod1;
widgetRegistry['ch9mod2'] = Ch9Mod2;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
