import React, { useEffect, useRef, useState } from 'react';
import { setupCanvas, clamp, easeOutCubic } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const C={bg:'#f5f8f0',env:'#b8c9a7',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#d97706',purple:'#7c3aed',ink:'#21324a',muted:'#68778f',line:'#d7deea',white:'#fff'};
function base(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.clearRect(0,0,w,h);ctx.fillStyle=C.bg;ctx.fillRect(0,0,w,h);ctx.strokeStyle=C.line;ctx.strokeRect(.5,.5,w-1,h-1);}
function text(ctx:CanvasRenderingContext2D,s:string,x:number,y:number,color=C.ink,bold=false){ctx.fillStyle=color;ctx.font=`${bold?'700':'400'} 14px "Segoe UI",sans-serif`;ctx.fillText(s,x,y);}
function useCanvas(draw:(ctx:CanvasRenderingContext2D)=>void,deps:React.DependencyList,w=780,h=320){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(!ref.current)return;const ctx=setupCanvas(ref.current,w,h);draw(ctx);ref.current.classList.add('is-ready');},deps);return ref;}

const abl={
  full:{name:'Mirage 完整方法',vals:[70.36,92.21,93.95],color:C.green},
  rgb:{name:'显式 RGB 点云',vals:[67.71,90.75,91.10],color:C.red},
  pixel:{name:'特征上采样后像素提升',vals:[60.85,84.90,79.81],color:C.orange},
  filter:{name:'关闭动态物体过滤',vals:[61.20,80.88,76.10],color:C.red},
  single:{name:'单阶段训练',vals:[63.18,87.11,84.47],color:C.purple}
};
type AblKey=keyof typeof abl;
export const LsmC9Main:React.FC<WidgetProps>=()=>{
  const [kind,setKind]=useState<AblKey>('full');const d=abl[kind];const labels=['Average','3D Cons.','Photo Cons.'];const ref=useCanvas(ctx=>{base(ctx,780,320);text(ctx,'Table 3 · 同一 WorldScore split，单因素改变',26,28,C.ink,true);labels.forEach((l,i)=>{const x=80+i*225;ctx.strokeStyle=C.line;ctx.beginPath();ctx.moveTo(x,250);ctx.lineTo(x+120,250);ctx.stroke();const full=abl.full.vals[i],v=d.vals[i];ctx.fillStyle='#dfe9e2';ctx.fillRect(x,250-full*1.75,46,full*1.75);ctx.fillStyle=d.color;ctx.fillRect(x+60,250-v*1.75,46,v*1.75);text(ctx,l,x,280,C.ink,true);text(ctx,full.toFixed(2),x,250-full*1.75-8,C.green,true);text(ctx,v.toFixed(2),x+58,250-v*1.75-8,d.color,true);text(ctx,'完整',x,302,C.muted);text(ctx,'当前',x+61,302,C.muted);});},[kind,d]);const drop=(70.36-d.vals[0]).toFixed(2);
  return <div><div className="chip-row">{(Object.keys(abl) as AblKey[]).map(k=><button key={k} className={`chip ${kind===k?'selected':''}`} onClick={()=>setKind(k)}>{abl[k].name}</button>)}</div><canvas ref={ref} width={780} height={320}/><div className={`feedback ${kind==='full'?'good':'bad'}`}>{kind==='full'?'完整方法是同一消融表的参照：Average 70.36，3D 92.21，Photo 93.95。':`${d.name} 的 Average 比完整方法低 ${drop} 分；这里只能归因于该受控消融设置。`}</div></div>;
};

type MaskMode='mask'|'depth'|'down';
export const LsmC9Mask:React.FC<WidgetProps>=()=>{
  const [mode,setMode]=useState<MaskMode>('mask');const [maskX,setMaskX]=useState(55);const dragging=useRef(false);const [choice,setChoice]=useState(0);
  const ref=useCanvas(ctx=>{base(ctx,780,330);if(mode==='mask'){text(ctx,'把遮罩拖过场景：长期缓存只收可靠静态表面',25,28,C.ink,true);ctx.fillStyle=C.env;ctx.fillRect(30,80,720,195);ctx.fillStyle=C.white;ctx.strokeStyle=C.green;ctx.lineWidth=3;ctx.fillRect(80,125,230,150);ctx.strokeRect(80,125,230,150);text(ctx,'刚性建筑',145,202,C.green,true);ctx.fillStyle='#dbe8f2';ctx.fillRect(330,80,180,195);text(ctx,'天空',395,108,C.blue,true);const personX=585;ctx.fillStyle=C.red;ctx.beginPath();ctx.arc(personX,150,18,0,Math.PI*2);ctx.fill();ctx.fillRect(personX-13,168,26,62);text(ctx,'动态人物',548,252,C.red,true);const mx=30+maskX*7;ctx.fillStyle='rgba(39,68,110,.24)';ctx.fillRect(mx-70,72,140,210);ctx.strokeStyle=C.blue;ctx.lineWidth=4;ctx.strokeRect(mx-70,72,140,210);const zone=maskX<45?'static':maskX<72?'sky':'person';text(ctx,zone==='static'?'✓ 写入 Λₜ':zone==='sky'?'× 天空不写入':'× 动态人物不写入',560,307,zone==='static'?C.green:C.red,true);}else{const data=mode==='depth'?[{n:'DepthAnything 3',v:70.36},{n:'MapAnything',v:69.66},{n:'UniDepth',v:69.13}]:[{n:'双线性',v:42.53},{n:'最近邻',v:47.78},{n:'面积池化',v:53.72},{n:'中值池化',v:52.22}];text(ctx,mode==='depth'?'Table 4 · 更高更好':'Table 5 · 投影 hole rate，更低更好',25,28,C.ink,true);data.forEach((d,i)=>{const y=75+i*58;const max=mode==='depth'?72:56;ctx.fillStyle=i===choice?C.orange:C.blue;ctx.fillRect(170,y,Math.max(20,d.v/max*520),28);text(ctx,d.n,25,y+20,i===choice?C.orange:C.ink,true);text(ctx,String(d.v),680,y+20,i===choice?C.orange:C.ink,true);});}},[mode,maskX,choice]);
  const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!dragging.current||mode!=='mask')return;const r=e.currentTarget.getBoundingClientRect();setMaskX(Math.round(clamp((e.clientX-r.left)/r.width*100,10,90)));};const zone=maskX<45?'建筑静态单元：深度有效时可以写入缓存。':maskX<72?'天空：几何不可靠，被掩码排除。':'动态人物：状态会变化，被排除以免污染持久缓存。';
  return <div><div className="chip-row"><button className={`chip ${mode==='mask'?'selected':''}`} onClick={()=>setMode('mask')}>动态过滤</button><button className={`chip ${mode==='depth'?'selected':''}`} onClick={()=>{setMode('depth');setChoice(0);}}>深度源</button><button className={`chip ${mode==='down'?'selected':''}`} onClick={()=>{setMode('down');setChoice(0);}}>下采样</button></div>{mode!=='mask'?<div className="chip-row">{(mode==='depth'?['DepthAnything 3','MapAnything','UniDepth']:['双线性','最近邻','面积池化','中值池化']).map((n,i)=><button key={n} className={`chip ${choice===i?'selected':''}`} onClick={()=>setChoice(i)}>{n}</button>)}</div>:null}<canvas ref={ref} width={780} height={330} onPointerDown={e=>{dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId);move(e);}} onPointerMove={move} onPointerUp={()=>dragging.current=false}/><div className={`feedback ${mode==='mask'&&maskX>=45?'bad':'good'}`}>{mode==='mask'?zone:mode==='depth'?'三种深度源结果接近，但默认 DepthAnything 3 的 Average 70.36 最高；这说明有弹性，不等于不依赖深度。':'双线性 hole rate 42.53% 最低，因此成为经验默认；论文同时指出它会在轮廓处平滑深度。'}</div></div>;
};

type Metric='world'|'loop'|'speed'|'memory';
const metricData={
  world:{title:'WorldScore Average ↑',names:['Mirage','Spatia'],vals:[70.36,69.73],unit:'分',higher:true,note:'同一 WorldScore 表内比较'},
  loop:{title:'RE10K Closed-loop SSIM_C ↑',names:['Mirage','Spatia'],vals:[0.825,0.579],unit:'',higher:true,note:'Mirage 的 LPIPS_C 0.228 不及 Spatia 0.213（越低越好）'},
  speed:{title:'端到端最高加速倍数 ↑',names:['Mirage','RGB pipeline'],vals:[10.57,1],unit:'×',higher:true,note:'单 H100 论文设置；“最高”随 rollout 长度变化'},
  memory:{title:'Chunk 5 缓存显存 ↓',names:['Mirage','Spatia'],vals:[2.25,124],unit:' MiB',higher:false,note:'Figure 5 原始值，低者更好，约 55× 差距'}
};
export const LsmC10Main:React.FC<WidgetProps>=()=>{
  const [metric,setMetric]=useState<Metric>('world');const [progress,setProgress]=useState(0);const [run,setRun]=useState(false);const d=metricData[metric];useEffect(()=>{if(!run)return;let raf=0;const s=performance.now();const tick=()=>{const p=clamp((performance.now()-s)/1700,0,1);setProgress(easeOutCubic(p));if(p<1)raf=requestAnimationFrame(tick);else setRun(false);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[run]);const ref=useCanvas(ctx=>{base(ctx,800,350);text(ctx,d.title,25,30,C.ink,true);const max=Math.max(...d.vals)*1.08;d.vals.forEach((v,i)=>{const y=95+i*105;const len=v/max*590*progress;const wins=d.higher?v===Math.max(...d.vals):v===Math.min(...d.vals);ctx.fillStyle=wins?C.green:C.red;ctx.fillRect(150,y,len,42);text(ctx,d.names[i],28,y+27,wins?C.green:C.ink,true);text(ctx,progress>.98?`${v}${d.unit}`:'—',165+len,y+27,wins?C.green:C.red,true);});ctx.strokeStyle=C.line;ctx.beginPath();ctx.moveTo(150,265);ctx.lineTo(740,265);ctx.stroke();text(ctx,d.higher?'方向：越高越好':'方向：越低越好',25,300,C.orange,true);text(ctx,d.note,25,330,C.muted);},[metric,progress,d],800,350);
  const choose=(m:Metric)=>{setMetric(m);setProgress(0);setRun(false);};
  return <div><div className="chip-row"><button className={`chip ${metric==='world'?'selected':''}`} onClick={()=>choose('world')}>WorldScore</button><button className={`chip ${metric==='loop'?'selected':''}`} onClick={()=>choose('loop')}>闭环重访</button><button className={`chip ${metric==='speed'?'selected':''}`} onClick={()=>choose('speed')}>端到端速度</button><button className={`chip ${metric==='memory'?'selected':''}`} onClick={()=>choose('memory')}>缓存显存</button></div><canvas ref={ref} width={800} height={350}/><div className="step-ctrl"><button className="tiny" disabled={run} onClick={()=>{setProgress(0);setRun(true);}}>{run?'比较中…':progress===1?'重新比较':'启动证据赛道'}</button></div><div className={`feedback ${progress===1?'good':''}`}>{progress===1?`${d.note}。Mirage 的优势必须连同协议和指标方向一起陈述。`:'先选一个协议，再启动；页面不会把不同数据集或相反指标方向混成一个总排名。'}</div><div className="feedback bad">明确限制：动态物体和天空被过滤，Mirage 不会跨 chunk 维持动态人物状态；运动主导场景受益更少。</div></div>;
};
