import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AnaCh1 } from './ana-ch1';
import { AnaCh10 } from './ana-ch10';
import { AnaCh2 } from './ana-ch2';
import { AnaCh3 } from './ana-ch3';
import { AnaCh4 } from './ana-ch4';
import { AnaCh5 } from './ana-ch5';
import { AnaCh6 } from './ana-ch6';
import { AnaCh7 } from './ana-ch7';
import { AnaCh8 } from './ana-ch8';
import { AnaCh9 } from './ana-ch9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { ModArch } from './mod-arch';
import { ModBudget } from './mod-budget';
import { ModCompare } from './mod-compare';
import { ModEvolve } from './mod-evolve';
import { ModIndex } from './mod-index';
import { ModLoop } from './mod-loop';
import { ModMemory } from './mod-memory';
import { ModRace } from './mod-race';
import { ModStuffing } from './mod-stuffing';
import { ModTradeoff } from './mod-tradeoff';
import { ModTrim } from './mod-trim';
import { ModTools } from './mod-tools';
import { ModCapabilities } from './mod-capabilities';
import { ModExplore } from './mod-explore';
import { ModMemoryCommit } from './mod-memory-commit';
import { ModThresholds } from './mod-thresholds';
import { ModEvalMap } from './mod-eval-map';
import { ModFailureModes } from './mod-failure-modes';
import { ModToolOverhead } from './mod-tool-overhead';
import { ModEvolutionArchitecture } from './mod-evolution-architecture';
import { ModPrinciple } from './mod-principle';
import { ModContextDensity } from './mod-context-density';
import { ModStagnation } from './mod-stagnation';
import { ModExplorationLoop } from './mod-exploration-loop';
import { ModConclusion } from './mod-conclusion';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-ch1'] = AnaCh1;
widgetRegistry['ana-ch10'] = AnaCh10;
widgetRegistry['ana-ch2'] = AnaCh2;
widgetRegistry['ana-ch3'] = AnaCh3;
widgetRegistry['ana-ch4'] = AnaCh4;
widgetRegistry['ana-ch5'] = AnaCh5;
widgetRegistry['ana-ch6'] = AnaCh6;
widgetRegistry['ana-ch7'] = AnaCh7;
widgetRegistry['ana-ch8'] = AnaCh8;
widgetRegistry['ana-ch9'] = AnaCh9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['mod-arch'] = ModArch;
widgetRegistry['mod-budget'] = ModBudget;
widgetRegistry['mod-compare'] = ModCompare;
widgetRegistry['mod-evolve'] = ModEvolve;
widgetRegistry['mod-index'] = ModIndex;
widgetRegistry['mod-loop'] = ModLoop;
widgetRegistry['mod-memory'] = ModMemory;
widgetRegistry['mod-race'] = ModRace;
widgetRegistry['mod-stuffing'] = ModStuffing;
widgetRegistry['mod-tradeoff'] = ModTradeoff;
widgetRegistry['mod-trim'] = ModTrim;
widgetRegistry['mod-tools'] = ModTools;
widgetRegistry['mod-capabilities'] = ModCapabilities;
widgetRegistry['mod-explore'] = ModExplore;
widgetRegistry['mod-memory-commit'] = ModMemoryCommit;
widgetRegistry['mod-thresholds'] = ModThresholds;
widgetRegistry['mod-eval-map'] = ModEvalMap;
widgetRegistry['mod-failure-modes'] = ModFailureModes;
widgetRegistry['mod-tool-overhead'] = ModToolOverhead;
widgetRegistry['mod-evolution-architecture'] = ModEvolutionArchitecture;
widgetRegistry['mod-principle'] = ModPrinciple;
widgetRegistry['mod-context-density'] = ModContextDensity;
widgetRegistry['mod-stagnation'] = ModStagnation;
widgetRegistry['mod-exploration-loop'] = ModExplorationLoop;
widgetRegistry['mod-conclusion'] = ModConclusion;
