import React,{useEffect,useRef,useState} from 'react';
import {setupCanvas,observeCanvas} from '../lib/canvasKit';
import type {WidgetProps} from './registry';
const W=560,H=240,BLUE='#176b92',GREEN='#20936f',RED='#d75d72',ORANGE='#f08b66',INK='#12233b',MUTED='#5d7189';
export const DcvcLab:React.FC<WidgetProps>=({chapterId,moduleId})=>{
 const ref=useRef<HTMLCanvasElement>(null);const [v,setV]=useState(1);const [mode,setMode]=useState(0);const key=moduleId==='hero'?chapterId:moduleId;const n=Math.max(1,Math.min(8,Math.round(1+v*7)));
 useEffect(()=>{const c=ref.current;if(!c)return;let ctx:CanvasRenderingContext2D;try{ctx=setupCanvas(c,W,H)}catch{return}
 const draw=()=>{ctx.clearRect(0,0,W,H);ctx.fillStyle='#f4fafc';ctx.fillRect(0,0,W,H);ctx.fillStyle=INK;ctx.font='600 16px Segoe UI';ctx.fillText(label(key),22,28);const old=mode===0,color=old?RED:GREEN;ctx.lineWidth=3;ctx.strokeStyle=color;const count=key.startsWith('6.')?4:n;for(let i=0;i<count;i++){const x=38+i*(480/Math.max(count,1));ctx.fillStyle=old&&i>0?'#fff':color;ctx.strokeRect(x,72,42,42);ctx.fillRect(x+5,77,32,32);ctx.fillStyle=MUTED;ctx.font='12px Segoe UI';ctx.fillText(String(i+1),x+17,132)}ctx.strokeStyle=old?RED:BLUE;ctx.beginPath();ctx.moveTo(42,166);ctx.lineTo(old?60+Math.min(count,7)*55:500,166);ctx.stroke();ctx.fillStyle=ORANGE;ctx.beginPath();ctx.arc(old?60+((Date.now()/25)%Math.max(60,count*45)):500,166,9,0,Math.PI*2);ctx.fill();ctx.fillStyle=INK;ctx.font='14px Segoe UI';ctx.fillText(old?'串行：依赖逐项完成':'并行：共享状态、同时完成',22,212);c.classList.add('is-ready')};let raf=0;const tick=()=>{draw();raf=requestAnimationFrame(tick)},start=()=>{if(!raf)raf=requestAnimationFrame(tick)},stop=()=>{cancelAnimationFrame(raf);raf=0};const off=observeCanvas(c,start,stop);return()=>{stop();off()}},[key,mode,n]);
 return <div><canvas ref={ref} width={W} height={H}/><div className="ctrl"><button type="button" className={mode===0?'active':''} onClick={()=>setMode(0)}>旧方法 / 基线</button><button type="button" className={mode===1?'active':''} onClick={()=>setMode(1)}>DCVC-UF</button><label>块大小 <span className="val">{n}</span></label><input aria-label="块大小" type="range" min="0" max="100" value={v*100} onChange={e=>setV(Number(e.target.value)/100)}/></div><div className={`feedback ${mode===1?'good':'bad'}`}>{mode===0?oldText(key):newText(key,n)}</div></div>
};
function label(k:string){const m:Record<string,string>={'1.1':'等待队列','2.1':'块潜变量','3.1':'相关性路径','4.1':'帧特定解码','5.1':'长时序训练','6.1':'σ / μ 分工','6.2':'比特流交互','7.1':'解码路径','8.1':'DCVC-UF 架构','9.1':'配置取舍','10.1':'结果比较'};return m[k]||'视频剪辑台：逐帧与块并行'}
function oldText(k:string){if(k.startsWith('6.'))return '四个分区交替估计参数并读比特流，产生四次同步。';if(k==='4.1')return '统一解码器兼顾所有时间位置，消融中BD-Rate退至 -10.1%。';return '基线保留串行依赖；红色表示等待、退化或额外同步。'}
function newText(k:string,n:number){if(k.startsWith('6.'))return 'σ一次预测并完成一次算术解码；μ仍逐步估计后加回。';if(k==='9.1'||k==='10.1')return '4090/1080p：HT-S 655.9 编码、453.3 解码 FPS，平均BD-Rate -31.6%。';return `块大小 N=${n}：共享潜变量与上下文，绿色表示并行完成；最大块等待为 ${n-1} 帧。`}
export default DcvcLab;
