import React from 'react';
import { DcvcLab } from './DcvcLab';
import {NeuralLearning,DcvcUfBlocks,NvcRouteAnalogy,NvcRouteCompare} from './ChapterOneWidgets';
import {PainpointMap} from './FlowOverviewWidgets';
import {FrameSpecificDecoders} from './FrameSpecificDecoders';
import {LongTermCorrelation} from './LongTermCorrelation';
import {EntropyFigure,EntropyLab} from './StreamlinedEntropy';
import {OverallResults,AblationResults,CombinedExperiments,TradeoffResults,PaperConclusion,Limitations} from './ResultsWidgets';
import {PaperExperiments} from './PaperExperiments';
import {FigureTwoExplorer,FigureThreeExplorer} from './PaperFrameworkFigures';
export interface WidgetProps { chapterId:string; moduleId:string; }
export const widgetRegistry:Record<string,React.FC<WidgetProps>>={};
widgetRegistry['dcvc-lab']=DcvcLab;
widgetRegistry['neural-learning']=NeuralLearning;
widgetRegistry['dcvc-uf-blocks']=DcvcUfBlocks;
widgetRegistry['nvc-route-analogy']=NvcRouteAnalogy;
widgetRegistry['nvc-route-compare']=NvcRouteCompare;
widgetRegistry['painpoint-map']=PainpointMap;
widgetRegistry['frame-specific-decoders']=FrameSpecificDecoders;
widgetRegistry['long-term-correlation']=LongTermCorrelation;
widgetRegistry['entropy-figure']=EntropyFigure;
widgetRegistry['entropy-lab']=EntropyLab;
widgetRegistry['overall-results']=OverallResults;
widgetRegistry['ablation-results']=AblationResults;
widgetRegistry['tradeoff-results']=TradeoffResults;
widgetRegistry['limitations']=Limitations;
widgetRegistry['combined-experiments']=CombinedExperiments;
widgetRegistry['paper-experiments']=PaperExperiments;
widgetRegistry['paper-conclusion']=PaperConclusion;
widgetRegistry['figure-two-explorer']=FigureTwoExplorer;
widgetRegistry['figure-three-explorer']=FigureThreeExplorer;
