import React,{useEffect,useRef,useState} from 'react';
import {observeCanvas,setupCanvas} from '../lib/canvasKit';
import type {WidgetProps} from './registry';
const W=900,H=330,C={bg:'#f4fafc',ink:'#12233b',muted:'#5d7189',blue:'#176b92',green:'#20936f',red:'#d75d72',orange:'#f08b66',purple:'#7868d8',line:'#cbdce6'};
const models=[{n:'DCVC-RT',bd:-21,enc:118.8,dec:105.3,p:20.7,mac:385},{n:'UF (LD)',bd:-9.5,enc:313.6,dec:353.8,p:9.7,mac:170},{n:'UF (HT-S)',bd:-31.6,enc:655.9,dec:453.3,p:81.2,mac:211},{n:'UF (HT-L)',bd:-42.2,enc:371.1,dec:273.6,p:120.5,mac:343}];
const txt=(c:CanvasRenderingContext2D,s:string,x:number,y:number,size=13,color=C.ink,w=400,a:CanvasTextAlign='center')=>{c.fillStyle=color;c.font=`${w} ${size}px "Segoe UI",sans-serif`;c.textAlign=a;c.fillText(s,x,y)};
export const OverallResults:React.FC<WidgetProps>=()=>{const [metric,setMetric]=useState<'enc'|'dec'|'bd'>('dec');const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const cv=ref.current;if(!cv)return;let c:CanvasRenderingContext2D;try{c=setupCanvas(cv,W,H)}catch{return}const draw=()=>{c.fillStyle=C.bg;c.fillRect(0,0,W,H);txt(c,'论文 Figure 1 / Table 1：4090、1080p、实际码流读写',450,26,15,C.blue,700);const vals=models.map(x=>metric==='bd'?-x.bd:x[metric]),max=Math.max(...vals)*1.12;models.forEach((m,i)=>{const x=65+i*205,v=vals[i],h=220*v/max,color=i<2?C.blue:i===2?C.green:C.purple;c.fillStyle=color;c.fillRect(x,280-h,110,h);txt(c,m.n,x+55,305,12,C.ink,700);txt(c,metric==='bd'?`${m.bd}%`:`${m[metric]} FPS`,x+55,268-h,13,color,700)});cv.classList.add('is-ready')};draw();return observeCanvas(cv,draw,()=>{})},[metric]);return <div><div className="ctrl"><button className={metric==='enc'?'active':''} onClick={()=>setMetric('enc')}>编码 FPS</button><button className={metric==='dec'?'active':''} onClick={()=>setMetric('dec')}>解码 FPS</button><button className={metric==='bd'?'active':''} onClick={()=>setMetric('bd')}>BD-Rate</button></div><canvas ref={ref}/><div className="feedback good">{metric==='bd'?'BD-Rate 越低越好：HT-L 压缩率最佳，HT-S 在压缩率和吞吐之间更均衡。':'FPS 越高越好：HT-S 在 4090 上达到 655.9 编码 / 453.3 解码 FPS。'}</div><p className="result-condition">条件：YUV420；VTM-17.0（LD）为 BD-Rate 锚点；1920×1080；单张 RTX 4090；包含真实码流写入和读取。</p></div>};

const ab=[{id:'A',s:'DCVC-RT 基线',bd:-21,dec:105.3},{id:'B',s:'+ 块编码，无帧专属解码器',bd:-10.1,dec:349.1},{id:'C',s:'+ 帧专属解码器',bd:-25.3,dec:343.2},{id:'D',s:'+ 精简熵模型',bd:-23.4,dec:453.3},{id:'E',s:'+ 128 帧训练（HT-S）',bd:-31.6,dec:453.3}];
export const AblationResults:React.FC<WidgetProps>=()=>{const [i,setI]=useState(0);const x=ab[i];return <div><div className="ctrl">{ab.map((r,j)=><button className={i===j?'active':''} onClick={()=>setI(j)}>{r.id}</button>)}</div><table className="results-table"><thead><tr><th>ID</th><th>设置</th><th>BD-Rate ↓</th><th>解码 FPS ↑</th></tr></thead><tbody>{ab.map((r,j)=><tr className={i===j?'selected':''} onClick={()=>setI(j)}><th>{r.id}</th><td>{r.s}</td><td>{r.bd}%</td><td>{r.dec}</td></tr>)}</tbody></table><div className={`feedback ${i===1||i===3?'bad':'good'}`}><strong>{x.id}：</strong>{i===0?'速度与压缩率基线。':i===1?'块编码把速度推高，但通用解码器使压缩率明显退化。':i===2?'帧专属解码器几乎不损失速度，却修复并超过基线压缩率。':i===3?'精简熵模型把解码提升到 453.3 FPS，代价是小幅 BD-Rate 变化。':'长序列训练不改变解码速度，把 BD-Rate 进一步推到 −31.6%。'}</div></div>};

const comparison=[{n:'VTM-17.0 (LD)',bd:0,enc:0.01,dec:23.6},{n:'VTM-17.0 (Hierarchical-B)',bd:-33.8,enc:0.01,dec:23.1},{n:'DCVC-RT',bd:-21,enc:118.8,dec:105.3},{n:'DCVC-UF (LD)',bd:-9.5,enc:313.6,dec:353.8},{n:'DCVC-UF (HT-S)',bd:-31.6,enc:655.9,dec:453.3},{n:'DCVC-UF (HT-L)',bd:-42.2,enc:371.1,dec:273.6}];
export const CombinedExperiments:React.FC<WidgetProps>=()=>{const [tab,setTab]=useState<'rate'|'speed'|'ablation'>('rate');const [row,setRow]=useState(0);const x=ab[row];return <div><div className="experiment-tabs"><button className={tab==='rate'?'active':''} onClick={()=>setTab('rate')}><span>方向 1</span><b>压缩效率</b><small>Table 1 · BD-Rate</small></button><button className={tab==='speed'?'active':''} onClick={()=>setTab('speed')}><span>方向 2</span><b>实际速度</b><small>Figure 1 / Table 1 · FPS</small></button><button className={tab==='ablation'?'active':''} onClick={()=>setTab('ablation')}><span>方向 3</span><b>机制消融</b><small>Table 2 · A–E</small></button></div>{tab!=='ablation'?<><div className="metric-explain"><strong>{tab==='rate'?'BD-Rate 是什么？':'FPS 是什么？'}</strong><p>{tab==='rate'?'BD-Rate 衡量在相同画质下相对锚点的平均码率变化。本文以 VTM-17.0（LD）为锚点：负数表示节省码率，数值越低越好；例如 −31.6% 表示平均节省 31.6% 码率。':'FPS 是每秒完成编码或解码的帧数，数值越高越快。论文速度包含实际码流写入和读取；此表条件为 1920×1080、单张 RTX 4090。'}</p></div><table className="results-table source-table"><caption>原文 Table 1 摘录：YUV420，所有帧参与测试</caption><thead><tr><th>方法</th>{tab==='rate'?<th>平均 BD-Rate ↓</th>:<><th>编码 FPS ↑</th><th>解码 FPS ↑</th></>}</tr></thead><tbody>{comparison.map(r=><tr><th>{r.n}</th>{tab==='rate'?<td>{r.bd.toFixed(1)}%</td>:<><td>{r.enc}</td><td>{r.dec}</td></>}</tr>)}</tbody></table><div className="feedback good">{tab==='rate'?'原文结论：HT-L 的平均码率节省最高（42.2%）；HT-S 为 31.6%，与 VTM Hierarchical-B 的 33.8% 接近，但最大块等待为 7 帧，而后者默认 GOP 32 的最大等待为 31 帧。':'原文结论：HT-S 在 4090、1080p 上达到 655.9 编码 FPS 和 453.3 解码 FPS；HT-L 达到 371.1/273.6 FPS；LD 解码速度相对 DCVC-RT 超过 3 倍。'}</div></>:<><div className="metric-explain"><strong>消融实验是什么？</strong><p>保持测试协议不变，从同一基线逐项加入一个设计，观察 BD-Rate 与解码 FPS 的增量变化，从而判断每个模块主要贡献压缩效率还是速度。BD-Rate 越低越好，FPS 越高越好。</p></div><div className="ctrl">{ab.map((r,j)=><button className={row===j?'active':''} onClick={()=>setRow(j)}>{r.id}</button>)}</div><table className="results-table source-table"><caption>原文 Table 2：VTM-17.0（LD）为 BD-Rate 锚点，4090 测试解码 FPS</caption><thead><tr><th>ID</th><th>设置</th><th>BD-Rate ↓</th><th>解码 FPS ↑</th></tr></thead><tbody>{ab.map((r,j)=><tr className={row===j?'selected':''} onClick={()=>setRow(j)}><th>{r.id}</th><td>{r.s}</td><td>{r.bd}%</td><td>{r.dec}</td></tr>)}</tbody></table><div className={`feedback ${row===1||row===3?'bad':'good'}`}><strong>{x.id}：</strong>{row===0?'DCVC-RT 基线。':row===1?'块编码把解码速度从 105.3 提高到 349.1 FPS，但缺少帧专属解码器使 BD-Rate 从 −21.0% 退化到 −10.1%。':row===2?'加入帧专属解码器后，速度保持在 343.2 FPS，BD-Rate 改善到 −25.3%。':row===3?'精简熵模型把解码速度提高到 453.3 FPS，BD-Rate 由 −25.3% 变为 −23.4%。':'128 帧训练不改变 453.3 FPS，将 BD-Rate 从 −23.4% 改善到 −31.6%。'}</div></>}</div>};

export const TradeoffResults:React.FC<WidgetProps>=()=>{const [i,setI]=useState(2),m=models[i];return <div><div className="ctrl">{models.map((x,j)=><button className={i===j?'active':''} onClick={()=>setI(j)}>{x.n}</button>)}</div><div className="metric-grid"><div><b>{m.bd}%</b><span>平均 BD-Rate ↓</span></div><div><b>{m.enc}/{m.dec}</b><span>编码/解码 FPS</span></div><div><b>{m.mac}G</b><span>MACs / 帧</span></div><div><b>{m.p}M</b><span>参数量</span></div></div><div className="figure5-note"><strong>Figure 5 的正确读法：</strong>在 UVG 较低质量区间，HT-S 与 HT-L 持续优于此前方法；高质量区间超过约 40 dB 后，VTM（Hierarchical-B）更好。论文认为该差距主要出现在肉眼较难分辨的高 PSNR 区间，但这仍是模型的客观性能边界。</div></div>};

export const PaperConclusion:React.FC<WidgetProps>=()=> <div><div className="conclusion-lead">原文的 Conclusion 主要有五层结论：</div><ol className="conclusion-list"><li><span>01</span><p>DCVC-UF 在保持较高压缩效率的同时，实现了前所未有的编解码速度。</p></li><li><span>02</span><p>块编码让多帧同时处理，显著提高吞吐量，也便于学习长时序相关性。</p></li><li><span>03</span><p>帧专属解码器分别适配块内不同时间位置，提高重建能力。</p></li><li><span>04</span><p>精简熵模型解耦 μ 与 σ，把码流交互合并为一步，降低实际运行开销。</p></li><li><span>05</span><p>作者认为 DCVC-UF 将常用但复杂的 Hierarchical-B 编码范式，推进为更高效的 chunk coding 范式。</p></li></ol><div className="conclusion-summary"><strong>一句话总结：</strong>DCVC-UF 通过块编码同时处理多帧，并结合帧专属解码器、长时序相关性学习和单步码流交互，在保持高压缩效率的同时获得了前所未有的编解码速度，为替代复杂的逐帧 Hierarchical-B 编码提供了一条更高效的方向。</div></div>;

const limits=[{t:'固定块大小',kind:'论文明确局限',d:'当前 DCVC-UF 使用固定 N，无法随视频运动强弱和内容复杂度自适应；论文将内容自适应块大小列为未来工作。'},{t:'时延不是零',kind:'结构边界',d:'HT 配置 N=8，最大引入 7 帧等待；LD 需退回 N=1，并牺牲部分压缩效率。'},{t:'长训练数据不足',kind:'实验边界',d:'结构容量示例可达 1024 帧（512×512、batch=1、24GB），但论文实际只用 128 帧微调，原因是高质量长视频数据难以构建。'},{t:'尚未跨块流水',kind:'实验边界',d:'速度测试按块顺序执行，未重叠不同块的网络推理与熵编码；这意味着仍有加速空间，也意味着当前结果不等于完整流水系统。'},{t:'高质量区间',kind:'结果边界',d:'UVG 超过约 40 dB 时，VTM Hierarchical-B 的率失真表现更好；轻量网络并非所有质量区间都占优。'},{t:'模型规模',kind:'部署取舍',d:'HT-S / HT-L 分别为 81.2M / 120.5M 参数；吞吐优势不应被误读为模型体积最小。'}];
export const Limitations:React.FC<WidgetProps>=()=>{const [i,setI]=useState(0),x=limits[i];return <div><div className="limit-grid">{limits.map((x,j)=><button className={i===j?'active':''} onClick={()=>setI(j)}><span>{x.kind}</span><b>{x.t}</b></button>)}</div><div className="limitation-detail"><strong>{x.t}</strong><p>{x.d}</p></div><div className="feedback bad">结论应写成“在论文测试条件下取得先进的率失真—复杂度折中”，而不是“在所有视频、硬件和质量区间全面最好”。</div></div>};
