import { useMemo, useState } from 'react';

type Phase = 'problem' | 'method' | 'evidence';
type Chapter = { title: string; kicker: string; phase: Phase; body: string; takeaway: [string, string, string] };
type MetricRow = { group: '固定帧数基线' | 'FreeMEF'; name: string; frames: string; psnr: string; ssim: string; lpips: string };

const chapters: Chapter[] = [
  { title: '一张照片为何不够', kicker: '问题', phase: 'problem', body: '亮窗会过曝、阴影会欠曝；单张 LDR 图像中已裁剪掉的细节无法可靠复原。多曝光融合（MEF）直接在 LDR 域融合互补曝光，因而省去 CRF 标定和 tone mapping。', takeaway: ['MEF 的目标是保留互补细节。', '动态物体会使不同曝光之间出现重影。', 'Free 指“灵活帧数”，并非“免费”。'] },
  { title: '固定帧数的枷锁', kicker: '问题', phase: 'problem', body: '传统网络常把 2、3 或 5 帧编码进输入通道或并行融合层；帧数改变就需改结构、重训。FreeMEF 将参考信息递推成全局状态，目标是让同一模型适应不同输入长度。', takeaway: ['灵活性不等于帧越多一定越好。', '基准帧与参考帧承担不同角色。', '帧数变化不应迫使重训模型。'] },
  { title: '先去后回：技术路线', kicker: '方法总览', phase: 'method', body: 'FreeMEF 先“去”：把基准帧和辅助帧逐步汇入一个全局状态；再“回”：以基准帧为几何锚点，选择性从全局状态取回信息。聚合与复原被拆成两步。', takeaway: ['先递推融合，再受引导地复原。', '基准帧始终保留几何锚点。', '这条路线旨在降低动态场景中的重影。'] },
  { title: 'RSSM：T+1 次的可变记忆', kicker: '方法 / RSSM', phase: 'method', body: '基准帧也参与 RSSM 初始化：共享 FEM 先提取每一帧的 Fₜ，随后对总计 T+1 帧递推。每一轮先在特征空间对齐，再由 ASE 提供上下文，最后通过 Sigmoid 选通更新 Hₜ。', takeaway: ['循环次数是总帧数 T+1。', '共享单元重复使用，所以帧数可变。', '门控是 Sigmoid 选通更新，而非直接相加。'] },
  { title: '对齐后，谨慎写入', kicker: '方法 / RSSM', phase: 'method', body: '动态物体令当前 Fₜ 与历史 Hₜ₋₁ 错位。RSSM 预测偏移 ΔPₜ，并用可变形卷积 DCN 在特征空间对齐；这不是显式光流。随后 Gₜ 决定候选信息写入历史状态的程度。', takeaway: ['对齐发生在特征空间。', 'DCN 不等同于显式光流估计。', 'Sigmoid 门控减少把错位细节写成重影的风险。'] },
  { title: '相似性悖论', kicker: '方法 / 难点', phase: 'method', body: '传统交叉注意力偏好相似位置，但过曝或欠曝的基准特征最不可靠，恰会得到较低权重。于是最需要修复的区域反而难以取到健康参考帧中的信息。', takeaway: ['低相似度并不表示没有可用证据。', '饱和会使 Qbase 失真。', 'EAHA 用连续门在两种查询间切换。'] },
  { title: 'EAHA：让查询适应极端曝光', kicker: '方法 / EAHA', phase: 'method', body: '极端图 E=Sigmoid(·) 是表示曝光极端严重程度的连续门，不是硬二值掩码。正常处依赖基准查询 Qbase；极端处更多依赖全局历史查询 Qref，同时基准帧仍保留几何锚点。', takeaway: ['Qhybrid=(1−E)⊙Qbase+E⊙Qref。', 'E 越大，Qref 权重越高。', '这是空间自适应混合，不是抛弃基准帧。'] },
  { title: 'AFFN：把全局光照统计带回来', kicker: '方法 / AFFN', phase: 'method', body: 'AFFN 从全局 Hᵀ 预测逐通道向量 γ、β，先执行仿射调制 X̂=X⊙(1+γ)+β，再送入门控前馈网络。γ 缩放、β 平移局部特征，用于亮度和对比度校正。', takeaway: ['先仿射、后门控前馈。', 'γ、β 来自全局历史，不是手工曝光规则。', '它不保证消除所有色偏。'] },
  { title: '训练与融合顺序', kicker: '验证 / 条件', phase: 'evidence', body: '默认结构是四阶段编码器—解码器加瓶颈（dim=32、[2,2,2,2] blocks、2 refinement blocks）。训练使用 256×256 patch、每 GPU batch 2、Adam 与 L1；两阶段调度约为 300k iterations（最低学习率 2.85×10⁻⁴）再约 92k iterations（最低学习率 1×10⁻⁶）。', takeaway: ['训练样本默认是三帧。', '顺序结论来自 5 帧 SICE 推理。', '暗帧放前端、亮帧（长曝光）放末端。'] },
  { title: '结果、边界与结论', kicker: '验证 / 实验', phase: 'evidence', body: 'SICE 跨数据集的 2/3/5 帧 PSNR 分别为 17.087 / 19.326 / 22.269。表中结果必须与数据集、帧数、指标方向一起阅读；当基准帧过暗且长曝光帧过饱和时，最易出现轻微颜色偏移。', takeaway: ['PSNR、SSIM 越高越好；LPIPS 越低越好。', '数值绑定论文的评测协议。', '任意帧数不等于任意曝光间隔都无误差。'] }
];

const resultRows: MetricRow[] = [
  { group: '固定帧数基线', name: 'SCTNet', frames: 'SICE / 5 帧', psnr: '21.153', ssim: '0.842', lpips: '0.177' }, { group: '固定帧数基线', name: 'AFUNet', frames: 'SICE / 5 帧', psnr: '21.121', ssim: '0.838', lpips: '0.164' },
  { group: 'FreeMEF', name: 'FreeMEF', frames: 'SICE / 2 帧', psnr: '17.087', ssim: '0.731', lpips: '0.225' }, { group: 'FreeMEF', name: 'FreeMEF', frames: 'SICE / 3 帧', psnr: '19.326', ssim: '0.774', lpips: '0.199' }, { group: 'FreeMEF', name: 'FreeMEF', frames: 'SICE / 5 帧', psnr: '22.269', ssim: '0.851', lpips: '0.149' },
  { group: 'FreeMEF', name: 'FreeMEF', frames: 'Kalantari / 3 帧（原文表 1 已核对）', psnr: '28.418', ssim: '0.948', lpips: '0.081' }, { group: 'FreeMEF', name: 'FreeMEF', frames: 'Real-HDRV / 3 帧（原文表 1 已核对）', psnr: '26.077', ssim: '0.940', lpips: '0.074' }
];

function KnowledgeCard({ term, children }: { term: string; children: React.ReactNode }) { return <details className="knowledge"><summary>知识卡片：{term}</summary><p>{children}</p></details>; }

function App() {
  const [chapter, setChapter] = useState(0); const [frames, setFrames] = useState(3); const [step, setStep] = useState(0); const [extreme, setExtreme] = useState(35); const [gamma, setGamma] = useState(0); const [beta, setBeta] = useState(0); const [order, setOrder] = useState('I'); const [compareEaha, setCompareEaha] = useState(false); const [filter, setFilter] = useState<'全部' | 'SICE' | '原文表 1'>('全部');
  const c = chapters[chapter]; const hidden = useMemo(() => Math.min(100, 22 + frames * 17 + step * 8), [frames, step]); const rows = resultRows.filter(row => filter === '全部' || (filter === 'SICE' ? row.frames.includes('SICE') : row.frames.includes('原文表 1')));
  const stats: Record<string, [string, string, string, string]> = { I: ['暗→亮', '22.269', '0.851', '0.149'], II: ['亮→暗', '21.463', '0.836', '0.163'], III: ['相近→跨度大', '22.152', '0.848', '0.152'], IV: ['跨度大→相近', '22.181', '0.849', '0.151'] }; const [label, psnr, ssim, lpips] = stats[order];
  return <div className="app"><aside><div className="brand">FreeMEF <span>交互研读</span></div><p className="paper">There and Back Again<br />Flexible-Frame Transformer</p><nav>{chapters.map((item, index) => <button key={item.title} className={`${index === chapter ? 'active ' : ''}nav-${item.phase}`} onClick={() => setChapter(index)}><b>{String(index + 1).padStart(2, '0')}</b>{item.title}</button>)}</nav><a href="https://arxiv.org/abs/2606.27905" target="_blank">论文 arXiv ↗</a></aside>
    <main className={`phase-${c.phase}`}><header><span>{c.kicker} / 第 {chapter + 1} 章</span><div><button onClick={() => setChapter(Math.max(0, chapter - 1))}>←</button><button onClick={() => setChapter(Math.min(9, chapter + 1))}>→</button></div></header><section className="hero"><div><p className="eyebrow">问题 → 方法 → 验证</p><h1>{c.title}</h1><p>{c.body}</p></div><div className="scene"><div className="sun" /><div className="mountain" /><div className="frame f1">短曝光 / 暗</div><div className="frame f2">基准锚点</div><div className="frame f3">长曝光 / 亮</div><div className="fused">先去后回</div></div></section><section className="module"><h2>动手理解</h2>
      {chapter <= 2 && <><p>切换总输入帧数，基准帧也进入 RSSM；随后以基准特征为锚完成“回”的复原。</p><div className="controls"><label>总帧数 <input type="range" min="2" max="5" value={frames} onChange={e => { setFrames(+e.target.value); setStep(0); }} /><strong>{frames} 帧</strong></label><button className="primary" onClick={() => setStep((step + 1) % frames)}>推进 RSSM</button></div><div className="pipeline">{Array.from({ length: frames }, (_, index) => <span className={index <= step ? 'lit' : ''} key={index}>{index === 0 ? '基准 F₀' : `辅助 F${index}`} →</span>)}<em style={{ width: `${hidden}%` }}>Hₜ 全局状态</em></div><p className="feedback">{step === 0 ? '第 0 轮：基准帧 F₀ 初始化 H₀。' : `第 ${step} 轮：对齐、ASE 上下文、Sigmoid 选通更新。`}</p></>}
      {chapter === 3 && <><p>RSSM 的每次写入是“对齐 → ASE → Sigmoid 选通”。ASE 提示池通过路由机制，为各像素选择实例相关的语义提示。</p><div className="controls"><label>总帧数 <input type="range" min="0" max="2" step="1" value={[2, 3, 5].indexOf(frames)} onChange={e => { setFrames([2, 3, 5][+e.target.value]); setStep(0); }} /><strong>{frames} 帧 / {frames} 次循环</strong></label><button className="primary" onClick={() => setStep(1)}>① 对齐 F̄ₜ</button><button className="primary" onClick={() => setStep(2)}>② 路由提示池</button><button className="primary" onClick={() => setStep(3)}>③ Sigmoid 选通</button></div><div className={`rssm-map s${step}`}><i>F̄ₜ</i><b>提示池 P</b><strong>路由 R</strong><em>Hₜ</em></div><p className="feedback">{step < 2 ? '先让当前特征与历史位置对齐。' : step === 2 ? '每个位置经 R 选择相关提示，形成实例相关的 ASE 输出。' : 'Gₜ=Sigmoid(·) 选通更新：Hₜ=Hₜ₋₁+Gₜ⊙(候选−Hₜ₋₁)。'}</p><KnowledgeCard term="SSM / ASE">状态空间模型以递推状态承载历史。论文的 ASE 通过提示池 P=M×N 与可微路由 R，为各像素选择实例相关提示，补充全局语义。</KnowledgeCard></>}
      {chapter === 4 && <><p>先点“对齐”，再点“写入”。DCN 解决特征空间对齐，不是显式光流。</p><div className="controls"><button className="primary" onClick={() => setStep(1)}>① 预测 ΔP</button><button className="primary" onClick={() => setStep(2)}>② DCN 对齐</button><button className="primary" onClick={() => setStep(3)}>③ Sigmoid 门控写入</button></div><div className={`align s${step}`}><i>当前特征 Fₜ</i><b>历史 Hₜ₋₁</b><em>{step < 2 ? '错位亮点' : '✓ 对齐亮点'}</em></div><p className="feedback">{step < 2 ? '直接叠加会把移动边缘写成重影。' : step === 2 ? 'DCN 已将特征对齐；下一步仍需决定写入量。' : 'Sigmoid 门 Gₜ 控制候选信息的更新比例。'}</p><KnowledgeCard term="DCN">可变形卷积会学习采样偏移 ΔP，从不规则邻域取特征；这里用于把当前特征与历史状态对齐。</KnowledgeCard></>}
      {chapter === 5 && <><p>打开对比，查看传统交叉注意力与 EAHA 在过曝区域的权重差异。</p><label className="switch"><input type="checkbox" checked={compareEaha} onChange={e => setCompareEaha(e.target.checked)} /> <span>启用 EAHA 对比</span></label><div className="attention-compare"><div><h3>传统 Cross-Attention</h3><div className="weight low" style={{ height: compareEaha ? '26%' : '44%' }}>过曝区：低权重</div><div className="weight high">正常区：高权重</div></div><div className={compareEaha ? 'enabled' : 'muted'}><h3>EAHA</h3><div className="weight rescue" style={{ height: compareEaha ? '76%' : '26%' }}>过曝区：Qref 补充</div><div className="weight high">正常区：Qbase</div></div></div><p className="feedback">{compareEaha ? 'EAHA 在 E 较大时切入 Qref，让全局历史参与检索。' : '传统查询依赖失真的 Qbase，过曝区域难以匹配健康参考。'}</p></>}
      {chapter === 6 && <><p>拖动连续极端门 E。它由 Sigmoid 生成，表达曝光极端严重程度；基准帧仍保留几何锚点。</p><label className="wide">极端图 E <input type="range" value={extreme} onChange={e => setExtreme(+e.target.value)} /><strong>{(extreme / 100).toFixed(2)}</strong></label><div className="query"><div style={{ opacity: 1 - extreme / 100 }}>Q<sub>base</sub><small>基准查询 / 几何锚点</small></div><div className="mix">Q<sub>hybrid</sub><small>Qhybrid=(1−E)⊙Qbase+E⊙Qref</small></div><div style={{ opacity: extreme / 100 }}>Q<sub>ref</sub><small>全局历史查询</small></div></div><p className="feedback">{extreme < 45 ? 'E 较低：以 Qbase 为主，保留可信局部结构。' : 'E 较高：以 Qref 补充失真的极端曝光区域。'}</p></>}
      {chapter === 7 && <><p>Hᵀ 预测逐通道 γ、β。先仿射调制，再进入门控前馈网络。</p><div className="controls"><label>γ（缩放）<input type="range" min="-50" max="50" value={gamma} onChange={e => setGamma(+e.target.value)} /><strong>{(gamma / 100).toFixed(2)}</strong></label><label>β（平移）<input type="range" min="-50" max="50" value={beta} onChange={e => setBeta(+e.target.value)} /><strong>{(beta / 100).toFixed(2)}</strong></label></div><div className="affine"><span style={{ filter: `brightness(${1 + gamma / 100})`, transform: `translateY(${-beta / 3}px)` }}>X</span><b>仿射 X̂ → Gating FFN</b></div><p className="feedback">X̂=X⊙(1+γ)+β；当前演示为 X×{(1 + gamma / 100).toFixed(2)}+{(beta / 100).toFixed(2)}。γ、β 均为逐通道向量，来自全局 Hᵀ，不保证消除色偏。</p></>}
      {chapter === 8 && <><p>选择 5 帧 SICE 的融合顺序。方案 I（暗→亮）最好：暗帧 / 短曝光放前端，亮帧 / 长曝光放末端。</p><div className="chips">{(['I', 'II', 'III', 'IV'] as const).map(item => <button className={order === item ? 'chosen' : ''} onClick={() => setOrder(item)} key={item}>方案 {item}</button>)}</div><div className="metric"><b>{label}</b><span className={order === 'I' ? 'highlight' : ''}>PSNR {psnr}</span><span>SSIM {ssim}</span><span>LPIPS {lpips}</span></div><p className="feedback">{order === 'I' ? '最佳：PSNR 22.269。这是论文的 SICE 5 帧实验结论。' : `方案 ${order} 的 PSNR 为 ${psnr}，低于暗→亮方案的 22.269。`}</p></>}
      {chapter === 9 && <><p>先筛选数据，再比较指标。绿色大字标出 SICE 5 帧的 <strong>22.269</strong>，对照 SCTNet 的 <strong>21.153</strong>。</p><div className="chips filter">{(['全部', 'SICE', '原文表 1'] as const).map(item => <button className={filter === item ? 'chosen' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><div className="table-wrap"><table><thead><tr><th>方法</th><th>数据 / 帧数</th><th>PSNR ↑</th><th>SSIM ↑</th><th>LPIPS ↓</th></tr></thead><tbody>{rows.map(row => <tr key={`${row.name}-${row.frames}`} className={row.psnr === '22.269' ? 'best-row' : ''}><td>{row.name}</td><td>{row.frames}</td><td><strong>{row.psnr}</strong></td><td>{row.ssim}</td><td>{row.lpips}</td></tr>)}</tbody></table></div><p className="feedback danger">边界：基准帧过暗且长曝光帧过饱和时，最易出现轻微颜色偏移。不要把结果泛化为所有相机、场景或曝光间隔。</p></>}
      </section><section className="take"><h2>带走三件事</h2>{c.takeaway.map(item => <p key={item}>✓ {item}</p>)}</section><footer>证据来源：Qu 等，《There and Back Again》，arXiv:2606.27905v2，2026。表 1 与 SICE 数值按论文表格及相应评测协议呈现。</footer></main></div>;
}
export default App;
