import React from 'react';
import {tutorial} from '../data/tutorial';
import {ChapterOverview} from '../modules/VisualLessons';
import {Module} from './Module';
import {Formula} from './Formula';
import {ThinkingQuestion} from './ThinkingQuestion';
import {TrainingNote} from './TrainingArchive';
import {PaperKnowledge,knowledgeSections} from './PaperKnowledge';
type Chapter=typeof tutorial.chapters[number];
export function SceneIcon({kind}:{kind:'opening'|'experiment'|'formula'|'question'|'note'}){return <svg className="scene-icon" viewBox="0 0 64 64" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{kind==='opening'?<><path d="M12 53Q21 25 52 13M24 34Q17 18 24 13M35 24Q46 31 53 27"/><path d="M25 12Q14 3 17 17Q7 20 21 24Q26 35 30 22Q41 19 28 16Z" fill="#ead3d4"/><circle cx="25" cy="19" r="2"/></>:kind==='experiment'?<><path d="M22 8H42M26 8V26L12 49Q8 56 17 56H47Q56 56 52 49L38 26V8M18 39H46"/><path d="M22 44Q30 40 42 47" stroke="#b9949c"/><circle cx="30" cy="30" r="2"/><circle cx="37" cy="48" r="2"/></>:kind==='formula'?<><path d="M10 51V12M10 51H55M16 43Q27 21 49 17"/><circle cx="33" cy="25" r="4" fill="#ead3d4"/><path d="M33 29V51" strokeDasharray="3 5"/></>:kind==='question'?<><path d="M13 11H51V42H31L19 53V42H13Z"/><path d="M25 22Q25 15 33 17Q43 21 34 27L32 31"/><circle cx="32" cy="36" r="1"/></>:<><path d="M10 14Q23 10 32 16Q42 10 54 14V50Q42 46 32 52Q22 46 10 50ZM32 16V52M17 23H25M17 30H25M39 23H47M39 30H47"/><path d="M39 40L43 43L50 36" stroke="#a17e87"/></>}</svg>}
function chapterKnowledge(ch:Chapter){return knowledgeSections.filter(s=>s.chapter===tutorial.chapters.indexOf(ch)+1)}
export function chapterStages(ch:Chapter){const extra=chapterKnowledge(ch);const next=extra.length?'补齐论文中的证据':'带着理解，做一道判断';return [{kind:'opening' as const,label:'先读懂这次任务',next:'进入交互实验',guide:'先理解这一章要回答的问题，再亲手改变一个条件，观察机器人的表现。'},...ch.modules.map((m,i)=>({kind:'experiment' as const,label:m.title,next:i<ch.modules.length-1?'继续下一项实验':ch.formula?'看看背后的公式':next,guide:i<ch.modules.length-1?'保留刚才的观察，再检验另一项设计选择。':ch.formula?'把实验中的变化与数学表达对应起来。':extra.length?'带着刚才的观察，读清论文的实验依据与方法边界。':'用一道思考题检验你对原因与边界的理解。'})),...(ch.formula?[{kind:'formula' as const,label:'读懂背后的关系',next,guide:extra.length?'把公式与论文的真实方法、实验配置对应起来。':'理解了符号关系后，判断哪些说法真正符合方法。'}]:[]),...extra.map((s,i)=>({kind:'knowledge' as const,label:s.title,next:i<extra.length-1?'继续查看实验结果':'带着证据，做一道判断',guide:i<extra.length-1?'读清提示的解释边界，再查看各任务的完整实验成绩。':'区分论文的观察、作者的解释和教学比喻，再做出你的判断。'})),{kind:'question' as const,label:'暂停一下，做出你的判断',next:'整理本章训练笔记',guide:'比较选项的解释，把最值得保留的结论浓缩进训练笔记。'},{kind:'note' as const,label:'把发现记入档案',next:'进入下一章',guide:'点击记录至档案，把这张笔记留给最后的论文逻辑复盘。'}]}
export function ChapterJourney({ch,id,step,saved,onSave}:{ch:Chapter;id:number;step:number;saved:boolean;onSave:()=>void}){const stages=chapterStages(ch);let cursor=0;const intro=cursor++;const experiments=ch.modules.map(m=>({m,index:cursor++}));const formula=ch.formula?cursor++:-1;const extra=chapterKnowledge(ch).map(s=>({s,index:cursor++}));const question=cursor++;const note=cursor++;return <section className="story-chapter chapter-journey" aria-label={ch.title}><div className="chapter-eyebrow">桃源训练日志 / {String(id+1).padStart(2,'0')}<span>{stages[step].label} · {step+1}/{stages.length}</span></div><div className="scene-progress" aria-label="本章学习进度">{stages.map((s,i)=><span key={i} className={step===i?'is-current':i<step?'is-past':''}><i/>{s.kind==='opening'?'引入':s.kind==='experiment'?'实验':s.kind==='formula'?'公式':s.kind==='question'?'思考':s.kind==='knowledge'?'证据':'笔记'}</span>)}</div>
<div hidden={step!==intro} className="journey-scene"><div className="scene-heading"><SceneIcon kind="opening"/><div><span>故事开场</span><h1>{ch.title}</h1></div></div><p className="story-bridge" dangerouslySetInnerHTML={{__html:ch.bridge}}/><ChapterOverview chapter={id+1}/><p className="overview-explanation" dangerouslySetInnerHTML={{__html:ch.analogy.text}}/></div>
{experiments.map(({m,index})=><div hidden={step!==index} className="journey-scene experiment-scene" key={m.id}><div className="scene-heading compact"><SceneIcon kind="experiment"/><div><span>亲手探索 · {ch.title}</span><h1>{m.title}</h1></div></div><Module module={m} chapterId={ch.id}/></div>)}
{ch.formula&&<div hidden={step!==formula} className="journey-scene"><div className="scene-heading"><SceneIcon kind="formula"/><div><span>把观察写成关系</span><h1>读懂背后的公式</h1></div></div><Formula formula={ch.formula}/></div>}
{extra.map(({s,index})=><div hidden={step!==index} className="journey-scene" key={s.key}><div className="scene-heading"><SceneIcon kind="note"/><div><span>论文证据与边界</span><h1>{s.title}</h1></div></div><PaperKnowledge section={s.key}/></div>)}
<div hidden={step!==question} className="journey-scene"><div className="scene-heading"><SceneIcon kind="question"/><div><span>训练师的判断</span><h1>让观察变成理解</h1></div></div><ThinkingQuestion chapter={id+1}/></div>
<div hidden={step!==note} className="journey-scene"><div className="scene-heading"><SceneIcon kind="note"/><div><span>留下本章的发现</span><h1>一页训练笔记</h1></div></div><TrainingNote id={id} saved={saved} onSave={onSave}/></div>
<div className="scene-transition"><span className="transition-symbol">⌁</span><p>{step===note&&saved?'这张笔记已收录。带着本章的发现，继续下一段训练旅程。':stages[step].guide}</p></div></section>}
