import React,{useState} from 'react';

const methods=[
 ['Model Tuning','改写整颗大脑','完整权重随任务更新。',0],
 ['Hard Prompt / AutoPrompt','选择文字任务签','人工设计或自动搜索离散 token，词表嵌入固定。',1],
 ['Prompt Tuning','学习输入前的提示','仅编码器输入前的连续 Pₑ 可训练；模型权重冻结。',2],
 ['Prefix Tuning','每层都放一组前缀','本文比较的 BART 方案涉及编码器、解码器；训练重参数化网络在推理时可移除。',3],
 ['WARP','提示 + 输出分类接口','除输入提示，还学习输出层，利用 masked LM 的 [MASK] 分类。',4],
 ['P-tuning','把提示穿插进人工模式','本文讨论的版本将提示交错在输入中，强结果还结合底座调优。',5],
 ['Qin / Eisner','提示 + 逐层偏移','手工原型中的 soft words 还配有层相关参数。',6],
 ['Adapters','在层间安装小模块','训练瓶颈模块，改变内部函数；原模型权重保持固定。',7]
] as const;
function MethodPicture(){const [selected,setSelected]=useState(2);const m=methods[selected];return <><div className="trainer-controls" aria-label="选择适配方法">{methods.map((x,i)=><button key={x[0]} className="trainer-button" aria-pressed={i===selected} onClick={()=>setSelected(i)}>{x[0]}</button>)}</div><svg className="evidence-svg" viewBox="0 0 720 350" role="img" aria-label={`${m[0]}：${m[1]}。${m[2]}`}><defs><marker id="evidence-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#688777"/></marker></defs><text x="360" y="28" textAnchor="middle">{m[1]}</text><path d="M360 95V122M360 268V299" stroke="#688777" markerEnd="url(#evidence-arrow)"/><rect x="210" y="53" width="300" height="42" rx="12" fill={selected===1?'#ead0d3':'#edf2e9'}/><text x="360" y="80" textAnchor="middle">{selected===1?'离散文字任务签 + 输入文本':selected===5?'输入 · 提示 · 人工模式 · 提示':'输入文本 Xₑ'}</text>{selected===2&&<><rect x="70" y="53" width="115" height="42" rx="12" fill="#ead0d3"/><text x="127" y="80" textAnchor="middle">软提示 Pₑ</text><path d="M185 74H210" stroke="#a67f8b"/></>}<rect x="200" y="122" width="320" height="146" rx="28" fill={selected===0||selected===5?'#ead0d3':'#e3ece1'} stroke="#77917c"/><text x="360" y="151" textAnchor="middle">{selected===0||selected===5?'底座参与更新':'冻结底座 θ'}</text>{[0,1,2].map(i=><g key={i}><rect x="275" y={163+i*29} width="170" height="22" rx="6" fill="#f8f6ef"/><text x="360" y={179+i*29} textAnchor="middle" fontSize="12">Transformer 层 {i+1}</text>{(selected===3||selected===6||selected===7)&&<><rect x="215" y={163+i*29} width="53" height="22" rx="5" fill="#ddb9c2"/><text x="241" y={178+i*29} textAnchor="middle" fontSize="10">{selected===7?'Adapter':selected===6?'偏移':'前缀'}</text></>}</g>)}<rect x="255" y="300" width="210" height="36" rx="10" fill={selected===4?'#ead0d3':'#edf2e9'}/><text x="360" y="324" textAnchor="middle">{selected===4?'可学习分类输出层':'输出任务答案'}</text>{selected===4&&<text x="540" y="85" fontSize="13">输入提示也学习</text>}</svg><p className="visual-caption" role="status">{m[2]}</p><p className="diagram-legend"><span>● 灰绿：冻结或共享</span><span>● 灰粉：任务学习或选择</span> · 结构示意，不表示层数或参数比例</p></>}

type Step=[string,string,string];
const routes:Record<string,{intro:string;steps:Step[];closing:string}>={
 serving:{intro:'换任务时，换任务签；交付时，同一颗大脑接收整批任务。',steps:[['准备提示','任务 A → Pₐ；任务 B → Pᵦ；任务 C → P𝒸','每项任务独立学习提示，不是用一份提示覆盖所有任务。'],['组成批次','[Pₐ; Xₐ]   [Pᵦ; Xᵦ]   [P𝒸; X𝒸]','不同任务输入配上自己的提示，可组成混合任务推理批次。'],['共享底座','三条输入 → 同一冻结 θ → 各自答案','共享权重省去完整模型副本；底座的实际计算仍存在。']],closing:'Figure 2 的 5-token 是存储示例；默认实验为 100-token。'},
 training:{intro:'一次任务训练，是沿着误差线调提示，封印中的大脑只负责传递信息。',steps:[['准备底座','T5.1.1 → 上游 LM adaptation 100K → 冻结','交付前准备底座，交付后只学提示；T5.1.1 去掉监督预训练混入、采用 GeGLU 并调整维度。'],['预测与比较','100-token 提示 + 文本 → 标签序列 → 交叉熵','标签被当成文字生成，没有另装分类头。'],['更新提示','Adafactor · 学习率 0.3 · batch 32','30,000 步训练；以开发集指标选择检查点。权重衰减 10⁻⁵、β₂ decay 0.8、parameter scaling 关闭。'],['重复与核验','3 次运行 → 均值 ± 标准差','77 次搜索（40 提示 / 37 单任务调优）、195 次主要与消融运行，另有迁移和集成。参数少不等于同比加速。']],closing:'真实实验配置，区别于网页一维教学模拟。'},
 evaluation:{intro:'沿尺度走廊比较三条路线；越靠右，大底座越能被小提示引导。',steps:[['同一系列','Small → Base → Large → XL → XXL','比较 T5.1.1 五个尺度；不把不同模型的结果当成适配方法的因果证明。'],['三条路线','单任务全调优 / 多任务全调优 / 单任务提示','完整调优学习率 0.001；单任务每批 2¹⁶ token，多任务 2²⁰ token 并加入 DPR。'],['测量窗口','八项英文任务 → SuperGLUE 开发集','沿用各任务官方指标；WSC 转为生成指代，只用 259 个正确指代训练例。'],['尺度结论','XXL：提示调优 ≈ 更强的多任务模型调优','这是该实验设置的观测，不是所有任务上放弃全微调的保证。']],closing:'八任务：BoolQ · CB · COPA · MultiRC · ReCoRD · RTE · WiC · WSC。'},
 initialization:{intro:'相同的提示槽位，可以从三种起点出发。起点决定怎么启程，不限制终点必须是文字。',steps:[['随机起点','每个元素 ← Uniform[−0.5, 0.5]','直接在连续空间采样。'],['词表起点','最常见 5,000 个 token → 抽取嵌入','从 T5 SentencePiece 常见词的嵌入出发，后续仍学习连续向量。'],['标签起点','标签 → 多 token 取平均 → 多余槽位补词表','一个类别标签初始化一个提示位置，不足部分由常见词表采样补齐。'],['任务例外','ReCoRD / WSC → 任务相关词','ReCoRD 用常识、推理、阅读、理解相关词；WSC 用常识、代词、指代消解相关词。']],closing:'XXL 上初始化差距消失；1、5、20、100、150 的长度消融不支持“越长越好”。'},
 objective:{intro:'三种读写习惯不是三次下游重训：先看交付前是否改变底座。',steps:[['原出厂目标','遮挡文本 + sentinel → 缺失片段 + sentinel','Span corruption 的输出以 sentinel 开头；有些中间尺度会复制输入或输出空串。'],['目标加标记','下游答案前加 sentinel → 底座保持原样','只改变下游目标格式，论文发现帮助有限。'],['上游适配','自然文本前缀 → 自然续写 → 冻结交付','LM adaptation 是一次真实底座训练，可以被各任务共享。'],['投入与收益','0K → 10K → 50K → 100K 步','较长适配通常获益；100K 是原预训练步数的 10%。XXL 更稳健、增益较温和。']],closing:'尺度趋势也受预训练目标影响：非理想目标下，小模型可能优于部分中间尺度。'},
 transfer:{intro:'先在熟悉的花园学习，再带着原提示到新环境；目标域不参与重新训练。',steps:[['出发','SQuAD v1.1 训练 → 按 SQuAD 验证 F1 选检查点','目标域开发集只用于评估。'],['换环境','书籍 / 生物医学 / 考试 / 电影 / Wikipedia','TextbookQA、BioASQ、RACE、DuoRC 分别来自前四种来源；SQuAD、RE、DROP 同为 Wikipedia。'],['保留反例','TextbookQA +12.5   ↔   DuoRC −1.2 / DROP −1.8','提升和下降都必须展示；DROP 同来源但不同数据集，论文视作较小域转移。'],['双向检验','QQP ↔ MRPC：方向和指标都影响结论','反向 Accuracy 略升，但 F1 下降。误差条是 3 次运行的标准差，不是显著性证明。']],closing:'冻结减少伪相关过拟合是作者解释性假设，不是本文已证明的普遍因果规律。'},
 interpretation:{intro:'词表近邻像提示石上的投影：能看到局部轮廓，不能读成完整任务说明。',steps:[['投影','提示向量 → 余弦距离 → top-5 词表近邻','比较的是冻结词表嵌入，不是将整个提示译成自然语言。'],['观察簇','语义相关近邻 / 保留的标签近邻','随机向量没有同样的模式；其他初始化也可能学出分散的标签近邻。'],['观察重复','多个提示位置 → 相同近邻','可能是容量冗余，也可能是缺少顺序结构。作者未确定哪种解释成立。'],['观察领域','BoolQ：科学词近邻 ↔ 约 20% 自然/科学问题','作者推测提示可能准备领域语境；相关性不证明某个词导致某个答案。']],closing:'近邻提供分析线索；可解释性仍需研究。'}
};
function RouteDiagram({section,selected}:{section:string;selected:number}){const green='#95b59c',pink='#d5afb9';return <svg className="evidence-svg" viewBox="0 0 720 290" role="img" aria-label={section==='transfer'?'七个问答数据集的F1变化：提示调优减模型调优，含正负结果。':'当前证据的概括图；形状、位置与向量颜色仅为教学示意。'}>
{section==='transfer'?<>{[['SQuAD',-.1],['TextbookQA',12.5],['BioASQ',1.2],['RACE',.9],['RE',.4],['DuoRC',-1.2],['DROP',-1.8]].map(([name,value],i)=>{const v=Number(value);return <g key={name}><text x="142" y={35+i*33} textAnchor="end" fontSize="14">{name}</text><rect x={v<0?225+v*26:225} y={19+i*33} width={Math.abs(v)*26} height="22" rx="3" fill={v<0?pink:green}/><text x={v<0?160:235+v*26} y={35+i*33} fontSize="14">{v>0?'+':''}{v.toFixed(1)}</text></g>})}<path d="M225 10V245" stroke="#678476"/><text x="225" y="271" textAnchor="middle" fontSize="13">0</text><text x="500" y="271" textAnchor="middle" fontSize="13">ΔF1：提示 − 模型 · Table 1</text></>:
section==='evaluation'?<><path d="M90 225H650M90 225V45" stroke="#718777"/><text x="30" y="45" fontSize="13">表现</text><path d="M95 80Q350 50 625 45" stroke={green} strokeWidth="4" fill="none"/><path d="M95 108Q350 67 625 47" stroke="#bac7b0" strokeWidth="4" fill="none"/><path d="M95 200Q340 115 625 49" stroke={pink} strokeWidth="4" fill="none"/>{['Small','Base','Large','XL','XXL'].map((x,i)=><text key={x} x={95+i*130} y="246" textAnchor="middle" fontSize="13">{x}</text>)}<text x="205" y="34" fontSize="13" fill="#6b8d72">多任务模型调优</text><text x="110" y="132" fontSize="13">单任务模型调优</text><text x="315" y="174" fontSize="13" fill="#a67f8b">单任务提示调优 → 差距缩小</text><text x="360" y="278" textAnchor="middle" fontSize="12">定性结构图，无实测坐标或虚构分数</text></>:
section==='initialization'?<>{['随机向量','常见词嵌入','类别标签嵌入'].map((x,k)=><g key={x}><text x={120+k*235} y="35" textAnchor="middle">{x}</text>{Array.from({length:20},(_,i)=><rect key={i} x={55+k*235+(i%5)*26} y={60+Math.floor(i/5)*30} width="22" height="24" rx="4" fill={(i+k)%3===0?pink:green} opacity={.3+((i*3+k)%7)*.1}/>)}<text x={120+k*235} y="209" textAnchor="middle" fontSize="13">{['[−0.5, 0.5]','top 5,000 token','多token取平均'][k]}</text></g>)}<text x="360" y="268" textAnchor="middle">三种起点 → 学习同一类连续提示 Pₑ</text></>:
section==='objective'?<><text x="360" y="35" textAnchor="middle">一次上游准备 → 多个下游任务复用</text><path d="M90 120H620" stroke="#a4bda8" strokeWidth="5"/>{[0,10,50,100].map((v,i)=><g key={v}><circle cx={90+v*5.3} cy="120" r={selected===3?13:9} fill={i===3?pink:green}/><text x={90+v*5.3} y={i===1?173:153} textAnchor="middle" fontSize="14">{v}K步</text></g>)}<path d="M620 138V197H420M620 197H680" stroke="#a4bda8" fill="none"/><text x="420" y="227" textAnchor="middle">冻结 → 任务 A</text><text x="660" y="227" textAnchor="middle">冻结 → 任务 B</text><text x="360" y="277" textAnchor="middle" fontSize="12">时间投入示意；不表示任务成绩的线性增长</text></>:
section==='interpretation'?<><circle cx="150" cy="138" r="44" fill={pink}/><text x="150" y="145" textAnchor="middle">提示向量</text>{['相关词 A','相关词 B','标签近邻','相关词 D','相关词 E'].map((x,i)=><g key={x}><path d={`M200 138L${330+i*70} ${i%2?200:85}`} stroke="#c1cec0" strokeDasharray="5 4"/><circle cx={330+i*70} cy={i%2?200:85} r="32" fill={green} opacity=".7"/><text x={330+i*70} y={i%2?204:89} textAnchor="middle" fontSize="11">{x}</text></g>)}<text x="360" y="267" textAnchor="middle" fontSize="13">五个局部近邻 ≠ 一封可读指令 · 非论文实际词例</text></>:
<><rect x="285" y="70" width="160" height="130" rx="38" fill="#dbe5d9" stroke="#829b85"/><circle cx="333" cy="115" r="8" fill="#527060"/><circle cx="397" cy="115" r="8" fill="#527060"/><path d="M337 158Q365 177 393 158" fill="none" stroke="#829b85" strokeWidth="3"/><text x="365" y="227" textAnchor="middle">只读核心 θ</text>{(section==='serving'?['A + Pₐ','B + Pᵦ','C + P𝒸']:['软提示 Pₑ','文本 Xₑ','真实标签 Y']).map((x,i)=><g key={x}><rect x="25" y={48+i*65} width="130" height="40" rx="12" fill={i===0?pink:'#e5ece1'}/><text x="90" y={74+i*65} textAnchor="middle" fontSize="14">{x}</text><path d={section==='training'&&i===2?`M155 ${68+i*65}L530 155`:`M155 ${68+i*65}L280 132`} stroke="#b4c7b8" fill="none"/></g>)}<path d="M450 132H525" stroke="#a0b59f" strokeWidth="3"/><rect x="530" y="105" width="165" height="55" rx="12" fill="#e9eee4"/><text x="612" y="138" textAnchor="middle">{section==='serving'?'各任务目标输出':'计算损失 L'}</text>{section==='training'&&<><path d="M605 168V249H90V218" stroke={pink} strokeWidth="3" fill="none" strokeDasharray="7 5"/><text x="360" y="278" textAnchor="middle" fontSize="13">误差回传 → 只更新提示；核心权重不更新</text></>}</>}
</svg>}
function RoutePicture({section}:{section:string}){const r=routes[section];const [selected,setSelected]=useState(0);return <><p className="visual-intro">{r.intro}</p><RouteDiagram section={section} selected={selected}/><div className="evidence-path" aria-label="点击流程步骤查看含义">{r.steps.map((s,i)=><React.Fragment key={s[0]}><button aria-pressed={i===selected} onClick={()=>setSelected(i)}><small>0{i+1}</small><span>{s[0]}</span></button>{i<r.steps.length-1&&<span className="path-arrow" aria-hidden="true">→</span>}</React.Fragment>)}</div><div className="route-focus" role="status"><span className="route-line">{r.steps[selected][1]}</span><p>{r.steps[selected][2]}</p></div><p className="visual-caption">{r.closing}</p></>}

const tasks=[['BoolQ','Accuracy',91.1,91.3,91.7],['CB','Accuracy',99.3,100,100],['CB','F1',99,100,100],['COPA','Accuracy',98.8,100,100],['MultiRC','EM',65.7,66.3,67.1],['MultiRC','F1a',88.7,89,89.4],['ReCoRD','EM',92.7,92.9,93.2],['ReCoRD','F1',93.4,93.5,93.9],['RTE','Accuracy',92.6,93.5,93.5],['WiC','Accuracy',76.2,76.6,77.4],['WSC','Accuracy',95.8,96.2,96.2],['SuperGLUE','开发集聚合分',90.5,91,91.3]] as const;
function ResultsPicture(){const [selected,setSelected]=useState(0);const t=tasks[selected];return <><p>给同一个任务配五份独立提示，然后比较平均、最好与投票集成。选择任务与指标，查看 Table 3 的精确成绩。</p><label className="result-selector">选择任务与指标 <select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{tasks.map((x,i)=><option key={x[0]+x[1]} value={i}>{x[0]} · {x[1]}</option>)}</select></label><svg className="evidence-svg results-picture" viewBox="0 0 720 290" role="img" aria-label={`${t[0]} ${t[1]}：平均${t[2]}，最好${t[3]}，集成${t[4]}。横轴0至100。`}>{[0,25,50,75,100].map(v=><g key={v}><path d={`M${160+v*4.8} 45V242`} stroke="#dce2d8"/><text x={160+v*4.8} y="263" textAnchor="middle" fontSize="13">{v}</text></g>)}{['五提示平均','单提示最好','五提示集成'].map((label,i)=><g key={label}><text x="140" y={85+i*66} textAnchor="end" fontSize="16">{label}</text><rect x="160" y={64+i*66} height="30" width={Number(t[i+2])*4.8} rx="8" fill={['#b9cac4','#d6b8c1','#93b49a'][i]}/><text x="655" y={85+i*66} fontSize="16">{Number(t[i+2]).toFixed(1)}</text></g>)}</svg><p className="visual-caption" role="status">{t[0]} · {t[1]} ↑；集成比最好提示高 {(t[4]-t[3]).toFixed(1)} 点。共用 0–100 坐标，不把不同任务分数混排为排行榜。</p><div className="evidence-path ensemble-route"><span>同一输入 × 5份提示</span><span className="path-arrow">→</span><span>共享 θ · batch 5</span><span className="path-arrow">→</span><span>多数投票</span></div><p>一次批量前向仍处理五个条件实例；该表未报告标准差或显著性检验。全部为开发集成绩。</p></>}
export function EvidenceVisuals({section}:{section:string}){return section==='comparison'?<MethodPicture/>:section==='results'?<ResultsPicture/>:<RoutePicture section={section}/>}
