import React from 'react';
import {EvidenceVisuals} from './EvidenceVisuals';
export const knowledgeSections=[
 {chapter:2,key:'serving',title:'同一个机器人，怎样同时接多项任务？'},
 {chapter:4,key:'comparison',title:'不同的轻量适配，究竟改了哪里？'},
 {chapter:5,key:'training',title:'把教学演示与真实训练分开'},
 {chapter:6,key:'evaluation',title:'尺度结论是怎样被测出来的？'},
 {chapter:7,key:'initialization',title:'初始化的细节与例外'},
 {chapter:8,key:'objective',title:'为什么读写习惯会影响提示？'},
 {chapter:9,key:'transfer',title:'跨域实验的边界与评价协议'},
 {chapter:10,key:'interpretation',title:'提示学会了任务，我们能读懂它吗？'},
 {chapter:10,key:'results',title:'查看完整的八项任务成绩'}
];
const results=[['BoolQ','Accuracy','91.1','91.3','91.7'],['CB','Accuracy / F1','99.3 / 99.0','100.0 / 100.0','100.0 / 100.0'],['COPA','Accuracy','98.8','100.0','100.0'],['MultiRC','EM / F1a','65.7 / 88.7','66.3 / 89.0','67.1 / 89.4'],['ReCoRD','EM / F1','92.7 / 93.4','92.9 / 93.5','93.2 / 93.9'],['RTE','Accuracy','92.6','93.5','93.5'],['WiC','Accuracy','76.2','76.6','77.4'],['WSC','Accuracy','95.8','96.2','96.2'],['SuperGLUE','开发集聚合分','90.5','91.0','91.3']];
function Source({children}:{children:React.ReactNode}){return <p className="evidence-note">论文依据 · {children}</p>}
function EvidenceDetails({section}:{section:string}){return <div className="paper-knowledge">
{section==='serving'&&<><p>你可以为情绪任务和阅读任务分别保存提示，交付时换上相应提示，仍然调用同一个冻结底座。</p><div className="knowledge-route"><span>任务 A + Pₐ</span><span>任务 B + Pᵦ</span><span>任务 C + P𝒸</span><strong>↓ 混合任务批次</strong><b>同一冻结模型 → 各自的目标输出</b></div><p>Figure 2 不只讨论存储：共享权重还允许混合任务推理。完整微调方案通常需要切换任务专用模型、分别组成批次；这里比较的是论文的每任务完整副本方案，并非所有多任务方法。</p><p>图中的 5-token 提示是存储示例：5 × 4,096 = 20,480 参数。论文默认训练用 100 token，在 XXL 上是 409,600 参数。共享底座仍需保存与运行。</p><Source>Figure 2（p2）、§2.1（p3）、Table 4（p14）。</Source></>}
{section==='comparison'&&<><p>Figure 4 在 T5.1.1、提示/前缀长度 1–100 的口径下，Prefix Tuning 推理任务参数约 0.1–1%，训练时更多；WARP 小于 0.1%；Prompt Tuning 在十亿参数以上模型中小于 0.01%。这是本文比较范围，不是所有方法的固定比例。</p><p>Logeswaran 等侧重从头联合训练的小模型与合成任务；本文研究冻结的大型预训练模型。</p><Source>§1、§4、Figure 4（pp.6–7）。</Source></>}
{section==='training'&&<><p>你刚才运行的是一维教学模型。真实机器人使用序列生成：给定文本 X 和标签序列 Y，学习 Pₑ 来最大化 Pr(Y | [Pₑ; Xₑ])。类别标签也被当成文本生成，而不是另外安装一个分类头。</p><dl className="knowledge-facts"><div><dt>冻结交付</dt><dd>T5.1.1 底座，先做 100K 步 LM adaptation；下游只更新提示。</dd></div><div><dt>默认任务配置</dt><dd>100-token 提示、类别标签初始化、交叉熵、常数学习率 0.3、batch 32、30,000 个训练步骤，以开发集指标选择检查点。</dd></div><div><dt>优化器</dt><dd>Adafactor；weight decay 10⁻⁵，β₂ decay 0.8，关闭 parameter scaling。实现使用 JAX / Flax。</dd></div><div><dt>监督与复现</dt><dd>每个提示单独训练一个任务；不混合不同任务的训练数据。省去任务权重副本，不省去标注数据和底座反向计算。</dd></div></dl><p>底座采用 T5.1.1，而非原版 T5：预训练去掉混入的监督数据，调整 d_model / d_ff，并以 GeGLU 替换 ReLU。这些属于预训练底座设置，不是训练师额外修改核心的步骤。</p><p>论文进行了 77 次超参数搜索试验（提示调优 40、单任务模型调优 37），主要结果与消融共 195 次运行，另有跨域与集成运行。设置经 SuperGLUE 分数选择；图中展示 3 次运行的均值与标准差，不能把一次演示当成实验可靠性证据。</p><p>附录 Table 5 的速度是特定 TPU 与 BoolQ 设置的测量，收敛定义为达到该配置均值表现的 1% 范围内。它不支持把“任务参数少”直接换算成同倍数的训练加速；部分受抢占影响的运行被排除。</p><Source>§2–3（pp.2–4）、Appendix A.1–A.2（p13）、Table 5–6（pp.14–15）。Small / Base 提示在 4 个 TPU v2 芯片上训练，较大模型在 16 个 TPU v3 芯片上训练。</Source></>}
{section==='evaluation'&&<><p>观测室比较的是五个 T5.1.1 尺度：Small、Base、Large、XL、XXL。每个任务都转成 text-to-text，去掉输入里的任务名称前缀；提示分别训练，冻结底座可以在服务时复用。</p><p>SuperGLUE 包含八项英文任务：BoolQ、CB、COPA、MultiRC、ReCoRD、RTE、WiC、WSC。本文报告开发集结果，沿用各任务的官方评价指标；聚合分数不能当成一个共同的 Accuracy。</p><div className="knowledge-route"><span>单任务完整模型调优</span><span>多任务完整模型调优</span><span>单任务提示调优</span><strong>↓ 同一 T5.1.1 系列比较</strong><b>XXL：提示调优也匹配更强的多任务模型调优基线</b></div><p>完整模型调优基线用学习率 0.001 和 Adafactor，恢复预训练优化器参数状态。单任务基线搜索 batch size 后使用每批 2¹⁶ token；多任务基线每批 2²⁰ token，包含 DPR 数据以帮助 WSC，任务名文字前缀标明任务。这些基线配置与提示的 batch 32 不同。</p><p>Figure 1 还比较 GPT-3 few-shot prompt design。模型、架构、预训练数据和上下文长度不同，因此这个对比不能隔离适配方法的因果效果。摘要中的“缩小差距”是本文设置中的经验结论。</p><Source>§3–3.1及脚注（p4）、Figure 1（p1）、Appendix A（pp.13–15）。所有数据集为英文，没有收集新数据；WSC按T5改为生成正确指代，只用正确指代的训练例，训练集为259例。</Source></>}
{section==='initialization'&&<><p>“用类别标签初始化”是一种起点选择，不是在每次训练中把提示限制为这些离散词。</p><ol><li>随机初始化：各元素从均匀分布 [−0.5, 0.5] 采样。</li><li>词表初始化：从 T5 SentencePiece 中最常见的 5,000 个 token 的嵌入中采样。</li><li>类别标签初始化：每个标签初始化一个提示位置；多 token 标签取嵌入平均。提示位置多于标签数时，用常见词表采样补齐。</li></ol><p>自由生成任务没有普通的类别清单：ReCoRD 使用与常识、推理、阅读、理解有关的词，WSC 使用与常识、代词、指代消解有关的词初始化。这是默认配置的任务例外。</p><p>标签词常常仍是训练后提示的近邻，但这不说明整段软提示成为可读的自然语言指令。类别标签初始化在小模型上更有优势，XXL 上差距消失；更长的提示也不保证更好。</p><Source>§3.2（pp.5–6）、p5脚注7、Figure 3(a,b)。长度消融：1、5、20、100、150。Table 4 中部分印刷数字有疑点，教程参数计数依据 p×e 精确计算，例如 Small、20 token 为10,240，而不是表中印出的10,420。</Source></>}
{section==='objective'&&<><p>Span corruption 要求读取带 sentinel 的遮挡文本，并输出缺失片段与 sentinel；每个预训练目标都以 sentinel 开头。这种既有习惯是底座出厂目标的结果，不能只凭一个复制或空输出就断定底座缺少语言能力。</p><p>“目标加 Sentinel”只调整下游目标格式，未重新训练底座。论文发现它帮助有限。LM adaptation 则把自然文本前缀作为输入、自然续写作为输出，先在上游做一次，然后冻结给各任务复用。</p><p>Figure 3(d) 比较 0K、10K、50K、100K 步适配：更长通常带来收益；100K 相当于原 T5 预训练步骤的 10%，是一次真实的训练投入。XXL 对较短或非理想适配仍较稳健，收益相对温和。</p><p>原始 span corruption 设置下，Small 可能优于 Base / Large / XL；部分中间尺度模型在多项任务中不能生成合法标签，出现复制输入片段或空字符串。三次运行的低方差提示这不是简单的偶然失败。不要把默认配置下的尺度趋势误套到所有预训练目标。</p><Source>§2.2（pp.3–4）、§3.2（p6）、Figure 3(c,d)。</Source></>}
{section==='transfer'&&<><p>你观察到的是在相同训练与检查点选择协议下的迁移，目标域开发集只用于评估，不再训练提示。问答实验在 SQuAD v1.1 训练、按 SQuAD 验证 F1 选检查点，再评估 MRQA 目标域。</p><p>域的差别也要读清楚：TextbookQA 是书籍，BioASQ 是生物医学，RACE 是考试，DuoRC 是电影；SQuAD、RE、DROP 都来自 Wikipedia。DROP仍是不同数据集，但和训练域共享来源，论文将它视作较小的域转移。</p><p>QQP 是 Quora 问题重复检测，MRPC 是新闻句子同义检测；二者双向迁移收益并不对称。反向 Accuracy 略升而 F1 下降，说明结论不仅取决于方向，也取决于指标。</p><p>误差条是 3 次运行的标准差，不是置信区间或显著性检验。论文提出冻结可能减少对词汇线索与伪相关的过拟合，这是解释性假设；这里没有做出“冻结导致任何域上都更好”的因果证明。</p><Source>§5（pp.7–8）、Table 1–2、Appendix A.1–A.3（p13）。F1允许部分答案跨度匹配；不同任务指标不混合排名。</Source></>}
{section==='interpretation'&&<><p>训练师拿到学好的提示石，想把它翻译成一封任务说明。论文没有直接读取向量，而是用余弦距离查找每个提示向量在冻结词表中的最近邻。</p><div className="knowledge-route"><span>一个学习后的提示向量</span><strong>↓ 余弦距离 · 查找 top-5 近邻</strong><span>词形相近或语义相关的词簇</span><strong>≠</strong><b>整段提示的可读指令或因果解释</b></div><p>观察一：top-5 近邻经常组成语义簇，随机向量没有同样的模式，提示可能学到了“像词”的表示。观察二：类别标签初始化的标签经常保留为近邻；其他初始化也可能学出标签近邻，但分散在多个提示位置。</p><p>观察三：较长提示中多个位置可能有相同近邻。作者提出两种可能解释——容量冗余，或缺少顺序结构使信息难以局部化；没有将任何一种确定为原因。</p><p>BoolQ 提示近邻里常出现科学、技术、工程相关词；约20%的问题属于自然/科学类别。作者推测提示可能为领域或语境作准备，但强调还需研究。近邻描述不能保证把软提示逆向翻译成人类句子，更不能证明哪个词导致某个输出。</p><Source>§7、§8（p9）。最终贡献是将任务定义参数与通用语言参数分开，不是宣称提示已获得完全可解释性。</Source></>}
{section==='results'&&<><p>一位冻结 T5-XXL 机器人，每个任务独立训练五份提示。下表保留 Table 3 的全部任务与指标；“最好”取自各任务五份提示，不是一份提示能同时负责八项任务。</p><p className="table-scroll-hint">↔ 小屏可左右滑动表格，查看完整列。</p><div className="knowledge-table" tabIndex={0} role="region" aria-label="论文Table3完整结果"><table><thead><tr><th>任务</th><th>指标 ↑</th><th>五提示平均</th><th>单提示最好</th><th>五提示集成</th></tr></thead><tbody>{results.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><p>Accuracy 是正确比例；EM 是完全匹配；F1 是相应任务规定的 F1，MultiRC 使用 F1a。CB、MultiRC、ReCoRD各报告两种指标；SuperGLUE开发集聚合分是另一行，不能把所有列都称为准确率。</p><p>五份提示对同一个输入形成五个条件实例，可组成 batch size=5 的一次批量前向，再多数投票。存储只需一份底座，服务比切换五份模型更方便，但仍处理五个条件实例。Table 3 中集成优于平均、优于或匹配最好提示，没有给出该表的标准差或显著性检验；不要给它补造误差条。</p><Source>§6、Table 3（p8）。全部为开发集结果；不是测试集排行榜或本网页在线测量。</Source></>}
</div>}

const sources:Record<string,string>={serving:'Figure 2、§2.1、Table 4',comparison:'§4、Figure 4',training:'§2–3、Appendix A、Table 5–6',evaluation:'§3.1、Figure 1、Appendix A',initialization:'§3.2、Figure 3(a,b)、脚注7',objective:'§2.2、Figure 3(c,d)',transfer:'§5、Table 1–2',interpretation:'§7–8',results:'§6、Table 3'};
export function PaperKnowledge({section}:{section:string}){return <div className="visual-evidence"><EvidenceVisuals section={section}/><p className="evidence-note">论文依据 · {sources[section]}。图示为结构与流程概括；结果条形图使用原表数值。</p><details className="evidence-details"><summary>展开原始配置、完整数据与核验说明</summary><EvidenceDetails section={section}/></details></div>}
