import React,{useEffect,useState} from 'react';
import {notes} from '../data/notes';
const archiveKey='prompt-garden-training-archive-v1';
const orderKey='prompt-garden-review-order-v1';
function readIds(key:string):(number|null)[]{try{const data=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(data)?data.filter((n:unknown)=>n===null||(Number.isInteger(n)&&Number(n)>=0&&Number(n)<notes.length)):[]}catch{return []}}
function persist(key:string,data:unknown){try{localStorage.setItem(key,JSON.stringify(data))}catch{/* The current session remains usable if storage is unavailable. */}}
export function useTrainingArchive(){const [saved,setSaved]=useState<number[]>(()=>Array.from(new Set(readIds(archiveKey).filter((n):n is number=>n!==null))));useEffect(()=>persist(archiveKey,saved),[saved]);return {saved,save:(id:number)=>setSaved(s=>s.includes(id)?s:[...s,id])}}
export function TrainingNote({id,saved,onSave}:{id:number;saved:boolean;onSave:()=>void}){const note=notes[id];return <div className="training-note"><span className="note-stamp">训练师笔记 · {String(id+1).padStart(2,'0')}</span><h3>{note.title}</h3><p>{note.text}</p><button className="trainer-button" onClick={onSave} disabled={saved}>{saved?'✓ 已记录至档案':'记录至档案 ＋'}</button><span className="note-save-status" role="status">{saved?'复盘页中已可使用这张笔记。':'保存后，这张卡片会进入你的复盘素材。'}</span></div>}
const shuffled=[7,2,9,0,6,4,8,1,5,3];
export function ArchiveReview({saved,onVisit}:{saved:number[];onVisit:(chapter:number)=>void}){const [order,setOrder]=useState<(number|null)[]>(()=>{const old=readIds(orderKey);const seen=new Set<number>();return Array.from({length:10},(_,i)=>{const v=old[i];if(v==null||seen.has(v))return null;seen.add(v);return v})});const [target,setTarget]=useState(0),[checked,setChecked]=useState(false),[dragged,setDragged]=useState<number|null>(null);useEffect(()=>persist(orderKey,order),[order]);const actual=order.map(id=>id!==null&&saved.includes(id)?id:null);const complete=actual.every((v,i)=>v===i);const filled=actual.filter(v=>v!==null).length;
function place(id:number,index:number){if(!saved.includes(id))return;setOrder(prev=>{const next=prev.map(v=>v===id?null:v);next[index]=id;const empty=next.findIndex(v=>v===null);setTarget(empty<0?index:empty);return next});setChecked(false)}
function remove(index:number){setOrder(prev=>prev.map((v,i)=>i===index?null:v));setTarget(index);setChecked(false)}
return <section className="archive-review" aria-label="训练档案复盘"><div className="chapter-eyebrow">离园之前 / 训练档案复盘<span>{saved.length} / 10 已归档</span></div><h1>把一路的发现，连成一份笔记</h1><p className="story-bridge">你已经学会了如何引导机器人。现在依据每一步的提示，把档案中的笔记排列成论文的论证流程：从问题出发，建立方法，再用实验检验边界。</p><p className="review-instructions">先点击流程中的位置，再点击下方笔记放入；也可以拖动笔记到指定位置。点击“取回”可重新排列。这里的位置顺序是论证顺序，不是卡片收集顺序。</p>
{saved.length<10&&<div className="archive-missing"><p>档案还缺 {10-saved.length} 张笔记。回到相应章节，读完浓缩笔记并点击“记录至档案”。</p><div className="trainer-controls">{notes.map((_,i)=>!saved.includes(i)&&<button className="trainer-button" key={i} onClick={()=>onVisit(i+1)}>返回第 {i+1} 章</button>)}</div></div>}
<ol className="review-flow" aria-label="论文论证流程">{actual.map((id,i)=><li key={i} className={`review-step ${target===i?'is-target':''} ${checked&&id!==i?'needs-reorder':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragged!==null)place(dragged,i);setDragged(null)}}><button className="step-target" aria-pressed={target===i} onClick={()=>setTarget(i)}><span>步骤 {i+1}</span><p>{notes[i].hint}</p><small>{target===i?'当前放置位置':'点击选择这个位置'}</small></button>{id===null?<div className="empty-note">等待一张训练笔记</div>:<div className="placed-note" draggable onDragStart={()=>setDragged(id)} onDragEnd={()=>setDragged(null)}><h3>{notes[id].title}</h3><p>{notes[id].text}</p><button onClick={()=>remove(i)} aria-label={`取回步骤${i+1}的笔记`}>取回 ↗</button></div>}{checked&&id!==i&&<p className="step-feedback">{id===null?'此处还没有笔记。':'这张笔记与这一阶段的提问还不对应，请沿提示重新思考。'}</p>}</li>)}</ol>
<div className="archive-bank"><h2>档案中的笔记</h2><p>已放入 {filled} / 10 张 · 当前选择：步骤 {target+1}。选错可以取回，再放入其他位置。</p><p className="bank-current-hint"><strong>步骤 {target+1} 的引导</strong> · {notes[target].hint}</p><div className="note-bank">{shuffled.filter(id=>saved.includes(id)&&!actual.includes(id)).map(id=><button className="bank-note" key={id} draggable onDragStart={()=>setDragged(id)} onDragEnd={()=>setDragged(null)} onClick={()=>place(id,target)}><h3>{notes[id].title}</h3><p>{notes[id].text}</p><span>放入步骤 {target+1} →</span></button>)}</div>{filled===10&&<p>所有笔记已放入流程。检查前，仍可以取回任意一张进行调整。</p>}</div>
<button className="trainer-button review-check" onClick={()=>setChecked(true)}>检查论文逻辑</button>{checked&&<div className="review-result" role="status">{complete?<><h2>训练档案完成</h2><p>你把“为什么需要适配” → “如何学习引导” → “尺度与设计实验” → “泛化与集成”连成了完整的论证。</p><h3>最后的训练师结论</h3><p>在本文的实验设置中，模型越强，任务适配越可能从改写整套权重，转向学习一段有效的引导。Soft Prompt 让同一颗冻结大脑服务不同任务，也让同任务的多份提示能够集成。</p><p>这并不意味着所有任务都可以放弃完整微调。任务监督、底座的出厂目标、计算成本与领域差异仍然重要；很少的可训练参数，也不意味着免去庞大底座的计算。提示的词表近邻呈现语义模式，但不是完整可读指令，也不是输出原因的证明。</p><p className="final-reflection">再问自己一次：机器人缺少的是能力，还是理解当前任务的方式？你现在会先寻找哪些证据，再决定是否重写它的大脑？</p></>:<><h2>沿着提示再整理一次</h2><p>有 {actual.filter((id,i)=>id===i).length} / 10 个位置符合论文逻辑。流程中已标出需要调整的位置；先区分问题、方法和实验，再考虑它们的先后关系。</p></>}</div>}
</section>}
