import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { ArchitectureMapLab } from './architecture-map-lab';
import { CodesignRepairLab } from './codesign-repair-lab';
import { ConditioningLab } from './conditioning-lab';
import { EfficiencyDistillLab } from './efficiency-distill-lab';
import { FlowMatchingLab } from './flow-matching-lab';
import { HeroStackContrast } from './hero-stack-contrast';
import { InferenceFamilyLab } from './inference-family-lab';
import { NativePackLab } from './native-pack-lab';
import { NftAlignmentLab } from './nft-alignment-lab';
import { ResultFrontierLab } from './result-frontier-lab';
import { StackBottleneckLab } from './stack-bottleneck-lab';
import { StudioAnalogy } from './studio-analogy';
import { VaeTokenizerLab } from './vae-tokenizer-lab';
import { GenerativeArchitecturePrimer } from './generative-architecture-primer';
import { PackedCfgLab } from './packed-cfg-lab';
import { CudaFusionLab } from './cuda-fusion-lab';
import { DataCurriculumLab } from './data-curriculum-lab';
import { VaeAnchorLab, VaeArchitectureLab, VaeBottleneckLab, VaeTrainingLab } from './mage-vae-explainer';
import { BucketMismatchLab, PackingBoundaryLab, SpatialPositionLab } from './nr-packing-explainer';
import { FusionStackDetailLab, KernelTrafficLab } from './cuda-fusion-explainer';
import { DecoupledDmdLab, LargeStepDistillationLab, PerceptualGuidanceLab, TurboTrainingDataLab } from './distillation-explainer';
import { NftCandidateLab, NftPositiveNegativeLab } from './nft-explainer';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['static-figure'] = () => null;
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['architecture-map-lab'] = ArchitectureMapLab;
widgetRegistry['codesign-repair-lab'] = CodesignRepairLab;
widgetRegistry['conditioning-lab'] = ConditioningLab;
widgetRegistry['efficiency-distill-lab'] = EfficiencyDistillLab;
widgetRegistry['flow-matching-lab'] = FlowMatchingLab;
widgetRegistry['hero-stack-contrast'] = HeroStackContrast;
widgetRegistry['inference-family-lab'] = InferenceFamilyLab;
widgetRegistry['native-pack-lab'] = NativePackLab;
widgetRegistry['nft-alignment-lab'] = NftAlignmentLab;
widgetRegistry['result-frontier-lab'] = ResultFrontierLab;
widgetRegistry['stack-bottleneck-lab'] = StackBottleneckLab;
widgetRegistry['studio-analogy'] = StudioAnalogy;
widgetRegistry['vae-tokenizer-lab'] = VaeTokenizerLab;
widgetRegistry['generative-architecture-primer'] = GenerativeArchitecturePrimer;
widgetRegistry['packed-cfg-lab'] = PackedCfgLab;
widgetRegistry['cuda-fusion-lab'] = CudaFusionLab;
widgetRegistry['data-curriculum-lab'] = DataCurriculumLab;
widgetRegistry['vae-bottleneck-lab'] = VaeBottleneckLab;
widgetRegistry['vae-architecture-lab'] = VaeArchitectureLab;
widgetRegistry['vae-anchor-lab'] = VaeAnchorLab;
widgetRegistry['vae-training-lab'] = VaeTrainingLab;
widgetRegistry['bucket-mismatch-lab'] = BucketMismatchLab;
widgetRegistry['packing-boundary-lab'] = PackingBoundaryLab;
widgetRegistry['spatial-position-lab'] = SpatialPositionLab;
widgetRegistry['kernel-traffic-lab'] = KernelTrafficLab;
widgetRegistry['fusion-stack-detail-lab'] = FusionStackDetailLab;
widgetRegistry['large-step-distillation-lab'] = LargeStepDistillationLab;
widgetRegistry['decoupled-dmd-lab'] = DecoupledDmdLab;
widgetRegistry['perceptual-guidance-lab'] = PerceptualGuidanceLab;
widgetRegistry['turbo-training-data-lab'] = TurboTrainingDataLab;
widgetRegistry['nft-candidate-lab'] = NftCandidateLab;
widgetRegistry['nft-positive-negative-lab'] = NftPositiveNegativeLab;
