import React, { useEffect, useRef, useState } from 'react';
import { observeCanvas, setupCanvas } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const C={bg:'#f5f8f0',env:'#b8c9a7',dark:'#76906a',road:'#92400e',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#d97706',purple:'#7c3aed',text:'#21324a',muted:'#68778f',border:'#d7deea'};
const W=560,H=230;
function useCanvas(draw:(ctx:CanvasRenderingContext2D)=>void,deps:unknown[]=[]){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const cv=ref.current;if(!cv)return;let ctx:CanvasRenderingContext2D;try{ctx=setupCanvas(cv,W,H)}catch{return}
    const render=()=>{draw(ctx);cv.classList.add('is-ready')}; const disconnect=observeCanvas(cv,render,()=>{});render();return disconnect;
  },deps); return ref;
}
function road(ctx:CanvasRenderingContext2D, loop=false){
  ctx.clearRect(0,0,W,H);ctx.fillStyle=C.bg;ctx.fillRect(0,0,W,H);
  ctx.strokeStyle=C.road;ctx.lineWidth=18;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(45,175);ctx.bezierCurveTo(160,80,330,210,510,70);ctx.stroke();
  ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.setLineDash([10,10]);ctx.stroke();ctx.setLineDash([]);
  ctx.fillStyle=C.orange;ctx.fillRect(105,135,34,20);ctx.fillStyle=C.text;ctx.fillText('人类',94,128);
  ctx.fillStyle=C.blue;ctx.beginPath();ctx.arc(445,92,18,0,Math.PI*2);ctx.fill();ctx.fillStyle=C.text;ctx.fillText('AI',435,65);
  if(loop){ctx.strokeStyle=C.green;ctx.lineWidth=4;ctx.beginPath();ctx.arc(280,115,55,0.25,5.8);ctx.stroke();ctx.fillStyle=C.green;ctx.fillText('持续反馈',250,118);}
}
const Canvas=({refEl}:{refEl:React.RefObject<HTMLCanvasElement>})=><canvas ref={refEl} width={W} height={H}/>;
const Feedback=({children,cls=''}:{children:React.ReactNode,cls?:string})=><div className={'feedback '+cls}>{children}</div>;
const Btns=({items,active,onClick}:{items:string[],active:number,onClick:(i:number)=>void})=><div className="widget-controls">{items.map((x,i)=><button key={x} className={i===active?'active':''} onClick={()=>onClick(i)}>{x}</button>)}</div>;

export const HeroModeling:React.FC<WidgetProps>=()=>{const r=useCanvas(c=>road(c,false));return <Canvas refEl={r}/>};
export const HeroConstituting:React.FC<WidgetProps>=()=>{const r=useCanvas(c=>road(c,true));return <Canvas refEl={r}/>};
export const RoadAnalogy:React.FC<WidgetProps>=()=>{const r=useCanvas(c=>{road(c,true);c.fillStyle=C.muted;c.fillText('长期共同驾驶 / 个性化智能导航',155,215)});return <Canvas refEl={r}/>};

export const SystemModes:React.FC<WidgetProps>=()=>{const names=['笔记本','自动补全','长期个性化 AI','耦合式 AI'];const states=[[0,0,0],[0,0,0],[1,0,0],[1,1,1]];const [i,setI]=useState(0);const s=states[i];const r=useCanvas(c=>{road(c,!!s[2]);c.fillStyle=s[0]?C.blue:C.muted;c.fillText(s[0]?'学习此用户':'仅存储/通用响应',180,35);},[i]);return <><Canvas refEl={r}/><Btns items={names} active={i} onClick={setI}/><div className="widget-grid">{['AI 学习特定用户','用户反向适应','进入真实决策回路'].map((x,j)=><div className={'state-card '+(s[j]?'good':'bad')} key={x}><b>{x}</b><br/>{s[j]?'是':'否'}</div>)}</div><Feedback cls={i===3?'good':''}>{i===3?'三个状态同时出现：这是认知整合的候选，不是仅“更像你”。':'该系统仍不足以跨过“模型 → 组件”的边界。'}</Feedback></>};

export const ManifoldExplorer:React.FC<WidgetProps>=()=>{const [x,setX]=useState(22);const t=x/100*Math.PI*5;const probe={x:280+185*Math.cos(t)*(.55+.45*Math.cos(t*.37)),y:122+72*Math.sin(t),z:Math.sin(t*.63)};const d=Math.round(Math.abs(Math.sin(t*1.31))*24);const inside=d<13;const r=useCanvas(c=>{c.clearRect(0,0,W,H);const g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,'#edf3f7');g.addColorStop(1,'#f7efe8');c.fillStyle=g;c.fillRect(0,0,W,H);c.strokeStyle='#c7d4df';c.lineWidth=1;for(let k=0;k<9;k++){c.beginPath();c.moveTo(40+k*60,30);c.lineTo(15+k*60,205);c.stroke()}for(let k=0;k<6;k++){c.beginPath();c.moveTo(25,40+k*32);c.lineTo(530,25+k*35);c.stroke()}for(let band=0;band<7;band++){c.beginPath();for(let j=0;j<=120;j++){const q=j/120*Math.PI*5;const depth=Math.sin(q*.63);const px=280+185*Math.cos(q)*(.55+.45*Math.cos(q*.37));const py=122+72*Math.sin(q)+depth*18;const width=13+8*(depth+1);if(j===0)c.moveTo(px,py);else c.lineTo(px,py)}c.strokeStyle=`rgba(39,68,110,${.08+band*.025})`;c.lineWidth=34-band*4;c.stroke()}for(let j=0;j<85;j++){const q=j/85*Math.PI*5;const depth=Math.sin(q*.63);const px=280+185*Math.cos(q)*(.55+.45*Math.cos(q*.37));const py=122+72*Math.sin(q)+depth*18;c.fillStyle=depth>.1?'#3e709e':'#7795b2';c.globalAlpha=.38+.45*(depth+1)/2;c.beginPath();c.arc(px,py,2.2+2*(depth+1),0,7);c.fill()}c.globalAlpha=1;c.setLineDash([5,5]);c.strokeStyle=inside?C.green:C.red;c.beginPath();c.moveTo(probe.x,probe.y);c.lineTo(280+160*Math.cos(t),122+60*Math.sin(t));c.stroke();c.setLineDash([]);c.fillStyle=inside?C.green:C.orange;c.beginPath();c.arc(probe.x,probe.y,10,0,7);c.fill();c.fillStyle=C.text;c.font='12px Segoe UI';c.fillText('投影维度：时间 · 场景 · 风险 · 偏好 · 社交语境',22,20);c.fillText('反复行为形成的低维曲面',350,214)},[x]);return <div className="manifold-lab"><Canvas refEl={r}/><div className="manifold-dimensions"><span>时间偏好</span><span>风险容忍</span><span>沟通风格</span><span>情境压力</span><span>社会语境</span></div><div className="widget-controls manifold-control"><label>沿高维行为轨迹探索 <b>{x}%</b></label><input type="range" min="0" max="100" value={x} onChange={e=>setX(+e.target.value)}/></div><Feedback cls={inside?'good':'bad'}>探针到行为曲面的距离（示意）：{d} · {inside?'这个行为落在个人反复使用的结构附近。':'这个行为偏离已观察结构，不能仅凭现有数据判定。'}</Feedback></div>};

export const NbirDomains:React.FC<WidgetProps>=()=>{const names=['时间规划','偏好表达','沟通风格','问题解决','现象体验 / 感质','自我意识 / 元认知'];const levels=['行为签名较清晰','行为签名较清晰','行为签名较清晰','中间地带','行为不可见的残余更可能','行为不可见的残余更可能'];const [i,setI]=useState(0);const r=useCanvas(c=>{c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);const n=i<3?3:i===3?2:1;for(let k=0;k<3;k++){c.fillStyle=k<n?(n===1?C.red:n===2?C.orange:C.green):C.border;c.fillRect(110+k*115,85,80,70)}c.fillStyle=C.text;c.fillText(names[i],205,50);c.fillText(levels[i],190,190)},[i]);return <><Canvas refEl={r}/><Btns items={names} active={i} onClick={setI}/>{i>=4&&<div className="big-no" style={{fontSize:36}}>意识边界：不主张转移</div>}<Feedback cls={i>=4?'bad':i===3?'':'good'}>{levels[i]}。这是论文的定性范围判断，不是百分比测量。</Feedback></>};

export const FoundationSteps:React.FC<WidgetProps>=()=>{const s=[['细胞','单个单元响应局部信号'],['组织','许多细胞协调完成共同功能'],['器官','组织被整合为可持续工作的器官'],['个体','器官进入整个生物体的闭环调节'],['人类 + 外部工具','工具提供信息，但仍可在回路之外'],['人类—AI 耦合系统','若满足三个判据，AI 可成为功能组件']];const [i,setI]=useState(0);return <div className={'foundation-lab foundation-'+i}><div className="foundation-scene"><div className="cell-cluster">{Array.from({length:12},(_,k)=><i key={k}/>)}</div><div className="organ-shape"><span>协调功能</span><i/><i/><i/></div><div className="human-system"><div className="mini-person"><i/><b/></div><div className="body-loop">感知 → 判断 → 行动 → 反馈</div></div><div className="external-ai"><div className="device-screen">AI<br/><small>外部系统</small></div><div className="coupling-pulse">双向影响</div></div><div className="foundation-boundary">系统边界</div></div><div className="foundation-progress">{s.map((item,k)=><button key={item[0]} className={k===i?'active':k<i?'done':''} onClick={()=>setI(k)}><span>{k+1}</span><b>{item[0]}</b></button>)}</div><div className="foundation-explain"><strong>{s[i][0]}</strong><p>{s[i][1]}</p><small>{i<4?'重点：高层级不是把低层级排成一排，而是把它纳入新的协调闭环。':i===4?'外部存在不等于成为组件；还必须检验它有没有进入系统的实际因果组织。':'这是理论上的可能性条件，不是已经完成的实验证明。'}</small></div></div>};

export const AdaptationDecouple:React.FC<WidgetProps>=()=>{const [m,setM]=useState(0);const [coupled,setCoupled]=useState(true);const [removed,setRemoved]=useState(false);const strength=coupled?m/12:m/30;const ok=m>=6&&coupled;return <div className={'adaptation-lab '+(removed?'ai-removed':'')}><div className="adaptation-scene"><div className="driver-cockpit"><div className="mini-person large"><i/><b/></div><strong>驾驶者</strong><div className="habit-list"><span style={{opacity:.25+strength*.75}}>开始提前查看建议</span><span style={{opacity:.15+strength*.85}}>把路线比较交给 AI</span><span style={{opacity:.1+strength*.9}}>围绕 AI 重组出行习惯</span></div></div><div className="adaptation-channel"><i style={{opacity:.2+strength*.8,transform:`scaleX(${.25+strength*.75})`}}/><b>{coupled?'双方都在改变':'只有 AI 在学习'}</b><i className="return" style={{opacity:coupled?.2+strength*.8:.08,transform:`scaleX(${coupled?.25+strength*.75:.15})`}}/></div><div className="personal-nav"><div className="device-screen"><b>{removed?'设备已移除':m<3?'通用路线':m<6?'开始记住偏好':'已形成个性化策略'}</b><small>{removed?'无法读取长期模型':`已积累 ${m} 个月互动记录`}</small></div><div className="learned-profile" style={{width:`${Math.max(8,strength*100)}%`}}>偏好模型</div></div><div className="calendar-strip">{Array.from({length:12},(_,k)=><i key={k} className={k<m?'filled':''}>{k+1}</i>)}</div>{removed?<div className="removal-impact"><strong>{ok?'原工作流程出现缺口':'工具帮助消失'}</strong><span>{ok?'驾驶者已经把部分比较与提醒工作稳定交给 AI。':'尚无证据表明人的工作方式已围绕 AI 重组。'}</span></div>:null}</div><div className="widget-controls adaptation-controls"><label>互动时长 <b>{m} 个月</b></label><input type="range" min="0" max="12" value={m} onChange={e=>{setM(+e.target.value);setRemoved(false)}}/><button className={coupled?'active':''} onClick={()=>{setCoupled(!coupled);setRemoved(false)}}>{coupled?'双向适应':'单向学习'}</button><button className={removed?'active danger':''} onClick={()=>setRemoved(!removed)}>{removed?'恢复 AI':'移除 AI'}</button></div><Feedback cls={removed?'bad':ok?'good':''}>{removed?(ok?'移除后，已经形成的工作流程出现可观察缺口；还需对照“技能退化”等解释。':'移除只显示工具帮助消失，尚不能证明认知功能已经外化。'):ok?'画面中的偏好模型、用户习惯和双向通道都随时间增强：达到作者提出的六个月操作性建议。':'继续推进时间，观察 AI 学习与用户反向适应是否同时累积。'}</Feedback></div>};

export const EquivalenceGates:React.FC<WidgetProps>=()=>{const names=['Output Fidelity','Generalization','Structural Correspondence'];const [on,setOn]=useState([true,false,false]);const pass=on.every(Boolean);const r=useCanvas(c=>{c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);on.forEach((v,i)=>{c.fillStyle=v?C.green:C.red;c.fillRect(75+i*155,75,110,80);c.fillStyle=C.text;c.fillText(names[i].split(' ')[0],80+i*155,180)});},[on]);return <><Canvas refEl={r}/><div className="widget-controls">{names.map((x,i)=><button className={on[i]?'active':''} onClick={()=>setOn(a=>a.map((v,k)=>k===i?!v:v))} key={x}>{x}</button>)}</div><Feedback cls={pass?'good':'bad'}>{pass?'三道门同时通过：才是 GCE 所需的 functional equivalence。':'查表式系统可能只通过 Output Fidelity；memorization ≠ cognitive extension。'}</Feedback></>};

export const NovelInput:React.FC<WidgetProps>=()=>{const [rel,setRel]=useState(false);const r=useCanvas(c=>{road(c,false);c.fillStyle=C.red;c.fillRect(270,85,80,18);c.fillText('封路',288,78);c.strokeStyle=rel?C.green:C.red;c.lineWidth=5;c.beginPath();c.moveTo(130,150);rel?c.quadraticCurveTo(300,30,470,105):c.lineTo(310,95);c.stroke()},[rel]);return <><Canvas refEl={r}/><Btns items={['Surface memorization','Relational preference structure']} active={rel?1:0} onClick={i=>setRel(!!i)}/><Feedback cls={rel?'good':'bad'}>{rel?'新路况中仍保持“避开高风险、接受稍长路线”的关系性偏好。':'只会复现旧路线，遇到封路即系统失败。'} 教学示意，不是论文实验结果。</Feedback></>};

export const CausalIntervention:React.FC<WidgetProps>=()=>{const [done,setDone]=useState(false);const [personal,setPersonal]=useState(true);const r=useCanvas(c=>{c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);c.fillStyle=C.text;c.fillText('仅有相关性',70,30);c.fillText('因果干预',350,30);[60,330].forEach((x,j)=>{c.strokeStyle=j&&done&&personal?C.green:C.blue;c.lineWidth=6;c.beginPath();c.moveTo(x,170);c.lineTo(x+150,j&&done&&personal?65:100);c.stroke();c.fillStyle=C.orange;c.beginPath();c.arc(x,170,10,0,7);c.fill()});},[done,personal]);return <><Canvas refEl={r}/><div className="widget-controls"><button onClick={()=>setDone(!done)}>改变 AI 状态 / 建议</button><button className={personal?'active':''} onClick={()=>setPersonal(!personal)}>{personal?'个性化影响':'通用效应'}</button></div><Feedback cls={done&&personal?'good':'bad'}>{done&&personal?'do(Aₜ := a′) 后，这个用户的 Hₜ₊₁ 改变：满足候选干预证据。':'相关性或通用搜索引擎效应不足以满足个性化因果耦合。'}</Feedback>{done&&personal&&<div className="model-component"><span>模型</span><span className="arrow">→</span><span style={{color:C.green}}>组件</span></div>}</>};

export const ExternalizationRatio:React.FC<WidgetProps>=()=>{const [v,setV]=useState([30,45,20]);const w=[.4,.35,.25];const e=v.reduce((s,x,i)=>s+x*w[i],0)/100;const r=useCanvas(c=>{c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);v.forEach((x,i)=>{c.fillStyle=[C.blue,C.green,C.orange][i];c.fillRect(90+i*145,175-x,80,x);c.fillStyle=C.text;c.fillText(['规划','偏好','沟通'][i],105+i*145,205)});c.font='24px Segoe UI';c.fillText(`E(t) = ${e.toFixed(2)}`,210,40)},[v]);return <><Canvas refEl={r}/>{v.map((x,i)=><div className="widget-controls" key={i}><label>{['规划','偏好','沟通'][i]} {x}%</label><input type="range" value={x} onChange={q=>setV(a=>a.map((z,k)=>k===i?+q.target.value:z))}/></div>)}<Feedback>教学示意 E(t)={e.toFixed(2)}。wᵢ 需来自引入 AI 前的频率与 consequentiality 日志，并做 sensitivity analysis。</Feedback></>};

export const IntegrationLevels:React.FC<WidgetProps>=()=>{const names=['0 静态','1 响应式','2 耦合式','3 替代式','4 整合式'];const [i,setI]=useState(0);const r=useCanvas(c=>{c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);names.forEach((x,k)=>{c.fillStyle=k===i?(k>=2?C.green:C.blue):C.border;c.fillRect(30+k*103,75,90,75);c.fillStyle=C.text;c.fillText(String(k),70+k*103,118)});c.strokeStyle=C.orange;c.lineWidth=5;c.beginPath();c.moveTo(225,55);c.lineTo(225,175);c.stroke();c.fillText('模型 → 组件',170,205)},[i]);return <><Canvas refEl={r}/><Btns items={names} active={i} onClick={setI}/><Feedback cls={i>=2?'good':''}>{i<2?'层级 0–1：仍是工具使用，E < 0.2。':i===2?'层级 2（耦合式）：0.2 ≤ E < 0.5；双向适应开始且进入因果回路。':'层级 3–4：E ≥ 0.5；论文没有给出二者各自的数值分界。'}</Feedback></>};

export const ChallengeCards:React.FC<WidgetProps>=()=>{const names=['天气模型','恒温器','意识上传？'];const [i,setI]=useState(0);const r=useCanvas(c=>{c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);c.fillStyle=i===2?C.red:C.blue;c.font='bold 50px Segoe UI';c.fillText(i===2?'不主张':i===1?'三道门':'因果',145,130)},[i]);const t=i===0?'天气模型位于真实大气的因果过程之外；耦合 AI 的差异是进入了因果回路。':i===1?'反馈回路不够：恒温器缺少新输入泛化、结构对应与丰富关系结构。':'GCE 主张认知功能外化，不主张意识或感质转移。';return <><Canvas refEl={r}/><Btns items={names} active={i} onClick={setI}/>{i===2&&<div className="big-no">不主张</div>}<Feedback cls={i===2?'bad':''}>{t}</Feedback></>};

export const PredictionThreshold:React.FC<WidgetProps>=()=>{const names=['1 决策预测','2 沟通不可区分','3 长期人类适应','4 人机相关变化','5 生理状态'];const [i,setI]=useState(0);const [acc,setAcc]=useState(55);const r=useCanvas(c=>{c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);c.fillStyle=C.border;c.fillRect(60,95,440,35);c.fillStyle=acc>=69?C.green:C.orange;c.fillRect(60,95,440*acc/100,35);c.strokeStyle=C.red;c.beginPath();c.moveTo(60+440*.69,75);c.lineTo(60+440*.69,150);c.stroke();c.fillStyle=C.text;c.fillText(`AI ${acc}%   示例阈值 69%`,165,50)},[acc]);return <><Canvas refEl={r}/><Btns items={names} active={i} onClick={setI}/><div className="widget-controls"><label>AI 预测准确率 {acc}%</label><input type="range" min="40" max="80" value={acc} onChange={e=>setAcc(+e.target.value)}/></div><Feedback cls={acc>=69?'good':''}>{i===4?'预测 5 是论文明确标注的最具推测性的预测。':acc<65?'低于阈值':acc<69?'正在接近判据':'达到示意阈值'}；75% 自我预测准确率、±8% 波动 → 69% 是论文具体示例。</Feedback></>};

export const FalsifyGce:React.FC<WidgetProps>=()=>{const names=['1 数据增十倍仍停滞','2 无人类适应','3 始终可区分','4 变化不相关','5 相关任务迁移失败'];const [i,setI]=useState(-1);const r=useCanvas(c=>{c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);const chain=['BMH','NBIR','功能主义','三个判据','GCE'];chain.forEach((x,k)=>{c.fillStyle=i===4&&k===1?C.red:(i>=0?C.orange:C.blue);c.fillRect(22+k*107,85,92,55);c.fillStyle='#fff';c.fillText(x,27+k*107,118)});},[i]);return <><Canvas refEl={r}/><div className="widget-controls">{names.map((x,k)=><button className={i===k?'active':''} onClick={()=>setI(k)} key={x}>{x}</button>)}</div><Feedback cls={i>=0?'bad':''}>{i<0?'选择一个条件，尝试证伪 GCE。':i===4?'NBIR 受到挑战：训练任务中 AI ≈ 人类，但在结构相关新任务中人类成功、AI 系统失败。证伪条件 5 的理论后果最强。':'该观察若稳定成立，将反驳相应的收敛或耦合预测。'}</Feedback></>};
