import React, { useEffect, useState } from 'react';
import type { WidgetProps } from './registry';

function useAutoSteps(length:number,delay:number){const[step,setStep]=useState(0);const[playing,setPlaying]=useState(true);useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setStep(v=>(v+1)%length),delay);return()=>window.clearInterval(timer)},[length,delay,playing]);return{step,setStep,playing,setPlaying}}
const modes=[
  {name:'笔记本',q:'系统只保存了什么？',caption:'用户把路线写进笔记；笔记不会学习、建议或改变现实行动。',checks:[false,false,false]},
  {name:'自动补全',q:'建议来自谁的长期结构？',caption:'用户输入目的地，通用 AI 补全建议；信息流仍然是单向的。',checks:[false,false,false]},
  {name:'长期个性化 AI',q:'个性化是否已经等于进入认知回路？',caption:'AI 读取长期路线历史，输出更像这个用户的建议，但用户尚未围绕它改变。',checks:[true,false,false]},
  {name:'耦合式 AI',q:'双方是否共同改变下一次真实决策？',caption:'AI 学习历史并建议路线；用户接受或修正；真实结果再反馈给 AI。',checks:[true,true,true]},
];
export const ToolBoundaryLab:React.FC<WidgetProps>=()=>{const[mode,setMode]=useState(0);const auto=useAutoSteps(4,2100);useEffect(()=>setMode(auto.step),[auto.step]);const data=modes[mode];return <div className="tool-boundary-lab"><div className="auto-scene-guide"><span>自动演示</span><strong>{data.q}</strong><button onClick={()=>auto.setPlaying(!auto.playing)}>{auto.playing?'暂停':'播放'}</button></div><div className={'topology-stage mode-'+mode}><div className="person-figure"><div className="person-head"/><div className="person-body"/><span>驾驶者</span></div><div className="topology-object storage-object"><b>路线笔记</b><small>静态记录</small></div><div className="topology-object ai-object"><b>个性化 AI</b><small>{mode<2?'通用响应':'读取长期历史'}</small></div><div className="topology-object action-object"><b>真实出行</b><small>{mode===3?'路线结果回到系统':'不在闭环中'}</small></div><svg viewBox="0 0 1000 320"><path className="edge human-storage" d="M180 165 C260 130 300 130 365 155"/><path className="edge human-ai" d="M180 165 C315 55 520 55 625 145"/><path className="edge ai-human" d="M625 180 C500 260 300 250 180 190"/><path className="edge ai-action" d="M690 170 C770 170 800 170 855 170"/><path className="edge action-ai" d="M855 205 C790 285 690 270 650 210"/></svg><div className="message-token token-one">{mode===0?'写入':mode===1?'输入目的地':'路线历史'}</div>{mode>0?<div className="message-token token-two">{mode===3?'个性化建议':'建议'}</div>:null}{mode===3?<><div className="message-token token-three">接受 / 修正</div><div className="message-token token-four">实际结果反馈</div></>:null}</div><div className="mode-timeline">{modes.map((item,index)=><button key={item.name} className={index===mode?'active':''} onClick={()=>{auto.setPlaying(false);auto.setStep(index);setMode(index)}}><span>{index+1}</span>{item.name}</button>)}</div><p className="scene-caption">{data.caption}</p><div className="boundary-questions">{['AI 学习特定用户','用户反过来适应','进入真实行为循环'].map((label,index)=><div className={data.checks[index]?'yes':'no'} key={label}><span>{data.checks[index]?'是':'否'}</span>{label}</div>)}</div><div className={'boundary-conclusion '+(mode===3?'crossed':'')}>{mode===3?'关系结构发生改变：这是跨越工具边界的候选。':'个性化程度还不够；关键是双方是否形成真实持续闭环。'}</div></div>};

export const CoDrivingLoop:React.FC<WidgetProps>=()=>{const auto=useAutoSteps(4,1500);const labels=['AI 读取长期偏好','AI 建议避开拥堵','驾驶者接受或修正','真实路况反馈给 AI'];return <div className="co-driving-loop"><div className="windshield"><div className="road-perspective"><i/><i/><i/></div><div className="driver-view"><div className="steering-wheel"/><span>驾驶者正在真实驾驶</span></div><div className="nav-device"><header>个性化导航</header><div className="nav-route"/><strong>{auto.step===0?'读取：安全优先':auto.step===1?'建议：走高架主路':auto.step===2?'用户修正：避开收费站':'更新：记住此次选择'}</strong></div></div><div className="loop-sequence">{labels.map((label,index)=><div className={index===auto.step?'active':''} key={label}><span>{index+1}</span>{label}</div>)}</div><div className="real-feedback"><div>AI 内部状态</div><b>→</b><div>导航建议</div><b>→</b><div>驾驶者实际行动</div><b>→</b><div>新的行为记录</div><b>↺</b></div><div className="auto-scene-guide compact"><strong>持续反馈：建议进入真实行动，行动结果又改变下一次建议。</strong><button onClick={()=>auto.setPlaying(!auto.playing)}>{auto.playing?'暂停':'继续播放'}</button></div></div>};

const challenges=[['天气模型','准确模型 ≠ 被建模对象'],['恒温器','反馈回路 ≠ 丰富认知功能'],['意识上传？','GCE 的主张范围到哪里？']];
export const ObjectionArena:React.FC<WidgetProps>=()=>{const[round,setRound]=useState(0);const auto=useAutoSteps(3,4200);useEffect(()=>setRound(auto.step),[auto.step]);return <div className={'objection-arena round-'+round}><div className="auto-scene-guide"><span>自动演示 · 第 {round+1} 回合</span><strong>{challenges[round][1]}</strong><button onClick={()=>auto.setPlaying(!auto.playing)}>{auto.playing?'暂停':'播放'}</button></div><div className="objection-question">{round===0?'实验：把模型中的“降雨概率”从 90% 改为 0%，真实云层会消失吗？':round===1?'实验：给系统一个从未见过的复杂舒适度任务，它能迁移结构吗？':'边界检查：论文究竟主张了什么，又明确没有主张什么？'}</div><div className="debate-stage"><div className="critic-side"><header>质疑者</header><div className="speaker"><div className="critic-avatar"><i/><b/></div><div className="speech-bubble">{round===0?'天气模型再准，也不是天气。':round===1?'恒温器也有反馈回路，难道也是认知？':'所以 GCE 证明意识可以上传？'}</div></div></div><div className="evidence-side">{round===0?<Weather/>:round===1?<Thermostat/>:<Scope/>}</div></div><div className="challenge-tabs">{challenges.map((item,index)=><button key={item[0]} className={index===round?'active':''} onClick={()=>{auto.setPlaying(false);auto.setStep(index);setRound(index)}}>{item[0]}</button>)}</div></div>};
function Weather(){const[forecast,setForecast]=useState(90);return <div className="weather-mechanism"><div className="atmosphere"><span className="cloud one"/><span className="cloud two"/><i className="rain r1"/><i className="rain r2"/><i className="wind">真实云雨继续演化</i></div><div className="sensor-stream"><i/>传感器只把大气状态送进模型</div><div className="weather-model"><b>天气模型</b><strong>{forecast}%</strong><span>明日降雨概率</span><input aria-label="修改模型预测" type="range" min="0" max="100" value={forecast} onChange={e=>setForecast(+e.target.value)}/></div><div className="blocked-causal"><b>修改模型：{forecast}%</b><span>真实大气没有随之改变</span><strong>模型没有进入被建模对象的因果回路</strong></div></div>}
function Thermostat(){const[novel,setNovel]=useState(false);return <div className={'thermostat-mechanism '+(novel?'novel-on':'')}><div className="house-room"><span>客厅 19°C</span><div className="heater">加热器正在工作</div><i className="heat-wave"/></div><div className="thermostat"><b>22°C</b><span>规则：低于目标就加热</span></div><div className="thermo-loop">测温 → 开关 → 再测温</div><button className="novel-trigger" onClick={()=>setNovel(!novel)}>{novel?'返回简单控温':'加入陌生复杂任务'}</button><div className="novel-needs"><span>陌生任务进入</span><p>同时兼顾老人舒适、节能、分时电价与不同房间偏好</p><strong>{novel?'恒温器仍只会执行单一温度规则：迁移失败':'等待测试新任务'}</strong></div></div>}
function Scope(){return <div className="scope-mechanism"><div className="scope-claimed"><span>GCE 主张</span><b>规划 · 偏好 · 沟通等认知功能外化</b></div><div className="scope-line"/><div className="scope-not"><strong>不</strong><span>GCE 不主张</span><b>意识 / 感质转移</b></div><div className="uncertain-zone">感质 · 现象体验 · 自我意识：高度不确定的边界</div></div>}
