import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AlayaAna1 } from './alaya-ana-1';
import { AlayaAna10 } from './alaya-ana-10';
import { AlayaAna2 } from './alaya-ana-2';
import { AlayaAna3 } from './alaya-ana-3';
import { AlayaAna4 } from './alaya-ana-4';
import { AlayaAna5 } from './alaya-ana-5';
import { AlayaAna6 } from './alaya-ana-6';
import { AlayaAna7 } from './alaya-ana-7';
import { AlayaAna8 } from './alaya-ana-8';
import { AlayaAna9 } from './alaya-ana-9';
import { AlayaHeroNew } from './alaya-hero-new';
import { AlayaHeroOld } from './alaya-hero-old';
import { AlayaMod101 } from './alaya-mod-10';
import { AlayaMod11 } from './alaya-mod-1a';
import { AlayaMod12 } from './alaya-mod-1b';
import { AlayaMod21 } from './alaya-mod-2';
import { AlayaMod31 } from './alaya-mod-3';
import { AlayaMod41 } from './alaya-mod-4';
import { AlayaMod51 } from './alaya-mod-5';
import { AlayaMod61 } from './alaya-mod-6';
import { AlayaMod71 } from './alaya-mod-7';
import { AlayaMod81 } from './alaya-mod-8a';
import { AlayaMod82 } from './alaya-mod-8b';
import { AlayaMod91 } from './alaya-mod-9';
import { AlayaShared } from './alaya-shared';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['alaya-ana-1'] = AlayaAna1;
widgetRegistry['alaya-ana-10'] = AlayaAna10;
widgetRegistry['alaya-ana-2'] = AlayaAna2;
widgetRegistry['alaya-ana-3'] = AlayaAna3;
widgetRegistry['alaya-ana-4'] = AlayaAna4;
widgetRegistry['alaya-ana-5'] = AlayaAna5;
widgetRegistry['alaya-ana-6'] = AlayaAna6;
widgetRegistry['alaya-ana-7'] = AlayaAna7;
widgetRegistry['alaya-ana-8'] = AlayaAna8;
widgetRegistry['alaya-ana-9'] = AlayaAna9;
widgetRegistry['alaya-hero-new'] = AlayaHeroNew;
widgetRegistry['alaya-hero-old'] = AlayaHeroOld;
widgetRegistry['alaya-mod-10'] = AlayaMod101;
widgetRegistry['alaya-mod-1a'] = AlayaMod11;
widgetRegistry['alaya-mod-1b'] = AlayaMod12;
widgetRegistry['alaya-mod-2'] = AlayaMod21;
widgetRegistry['alaya-mod-3'] = AlayaMod31;
widgetRegistry['alaya-mod-4'] = AlayaMod41;
widgetRegistry['alaya-mod-5'] = AlayaMod51;
widgetRegistry['alaya-mod-6'] = AlayaMod61;
widgetRegistry['alaya-mod-7'] = AlayaMod71;
widgetRegistry['alaya-mod-8a'] = AlayaMod81;
widgetRegistry['alaya-mod-8b'] = AlayaMod82;
widgetRegistry['alaya-mod-9'] = AlayaMod91;
widgetRegistry['alaya-shared'] = AlayaShared;
