import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { C1Analogy } from './c1-analogy';
import { CameraKit } from './c1-camera-kit';
import { C1HeroNew } from './c1-hero-new';
import { C1HeroOld } from './c1-hero-old';
import { C1Ownership } from './c1-ownership';
import { C1StorageCompare } from './c1-storage-compare';
import { C10Analogy } from './c10-analogy';
import { C10Boundaries } from './c10-boundaries';
import { C10ResultRace } from './c10-result-race';
import { C2Analogy } from './c2-analogy';
import { C2TransferModes } from './c2-transfer-modes';
import { C3Analogy } from './c3-analogy';
import { C3SequentialTasks } from './c3-sequential-tasks';
import { C4Analogy } from './c4-analogy';
import { C4Bottleneck } from './c4-bottleneck';
import { C5Analogy } from './c5-analogy';
import { C5IdentityInit } from './c5-identity-init';
import { C6Analogy } from './c6-analogy';
import { C6TaskSwitch } from './c6-task-switch';
import { C7Analogy } from './c7-analogy';
import { C7LearningRate } from './c7-learning-rate';
import { C7UpdateMask } from './c7-update-mask';
import { C8Analogy } from './c8-analogy';
import { C8ArchitectureMap } from './c8-architecture-map';
import { C8Propagation } from './c8-propagation';
import { C9AblationSpan } from './c9-ablation-span';
import { C9Analogy } from './c9-analogy';
import { C9WidthRobustness } from './c9-width-robustness';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['c1-analogy'] = C1Analogy;
widgetRegistry['c1-camera-kit'] = CameraKit;
widgetRegistry['c1-hero-new'] = C1HeroNew;
widgetRegistry['c1-hero-old'] = C1HeroOld;
widgetRegistry['c1-ownership'] = C1Ownership;
widgetRegistry['c1-storage-compare'] = C1StorageCompare;
widgetRegistry['c10-analogy'] = C10Analogy;
widgetRegistry['c10-boundaries'] = C10Boundaries;
widgetRegistry['c10-result-race'] = C10ResultRace;
widgetRegistry['c2-analogy'] = C2Analogy;
widgetRegistry['c2-transfer-modes'] = C2TransferModes;
widgetRegistry['c3-analogy'] = C3Analogy;
widgetRegistry['c3-sequential-tasks'] = C3SequentialTasks;
widgetRegistry['c4-analogy'] = C4Analogy;
widgetRegistry['c4-bottleneck'] = C4Bottleneck;
widgetRegistry['c5-analogy'] = C5Analogy;
widgetRegistry['c5-identity-init'] = C5IdentityInit;
widgetRegistry['c6-analogy'] = C6Analogy;
widgetRegistry['c6-task-switch'] = C6TaskSwitch;
widgetRegistry['c7-analogy'] = C7Analogy;
widgetRegistry['c7-learning-rate'] = C7LearningRate;
widgetRegistry['c7-update-mask'] = C7UpdateMask;
widgetRegistry['c8-analogy'] = C8Analogy;
widgetRegistry['c8-architecture-map'] = C8ArchitectureMap;
widgetRegistry['c8-propagation'] = C8Propagation;
widgetRegistry['c9-ablation-span'] = C9AblationSpan;
widgetRegistry['c9-analogy'] = C9Analogy;
widgetRegistry['c9-width-robustness'] = C9WidthRobustness;
