import React, { useEffect, useRef, useState } from 'react';
import { clamp, setupCanvas, observeCanvas } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const C = { bg:'#f5f8f0', desk:'#b8c9a7', dark:'#76906a', wood:'#92400e', blue:'#27446e', green:'#228d5c', red:'#c43f52', orange:'#d97706', purple:'#7c3aed', ink:'#21324a', muted:'#68778f', line:'#d7deea' };
function useCanvas(w:number,h:number,draw:(ctx:CanvasRenderingContext2D,t:number)=>void,deps:React.DependencyList){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;let ctx:CanvasRenderingContext2D;try{ctx=setupCanvas(canvas,w,h)}catch{return}canvas.style.width='100%';canvas.style.height='auto';let raf=0;const tick=(ms:number)=>{draw(ctx,ms/1000);canvas.classList.add('is-ready');raf=requestAnimationFrame(tick)};const start=()=>{if(!raf)raf=requestAnimationFrame(tick)};const stop=()=>{if(raf)cancelAnimationFrame(raf);raf=0};const disconnect=observeCanvas(canvas,start,stop);return()=>{stop();disconnect()}},deps);return ref}
function clear(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.clearRect(0,0,w,h);ctx.fillStyle=C.bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=C.desk;ctx.fillRect(0,h-20,w,20)}
function label(ctx:CanvasRenderingContext2D,s:string,x:number,y:number,color=C.ink,align:CanvasTextAlign='left'){ctx.fillStyle=color;ctx.font='600 12px Segoe UI, sans-serif';ctx.textAlign=align;ctx.fillText(s,x,y);ctx.textAlign='left'}
function receipt(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number){ctx.fillStyle='#fff';ctx.strokeStyle=C.line;ctx.lineWidth=1.5;ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.strokeStyle='#dfe5ec';for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(x+12,y+18+i*15);ctx.lineTo(x+w-12,y+18+i*15);ctx.stroke()}ctx.fillStyle=C.ink;ctx.font='700 12px Segoe UI, sans-serif';ctx.fillText('ARCHIVE  2026',x+16,y+34)}
function magnifier(ctx:CanvasRenderingContext2D,x:number,y:number,r:number,color:string){ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=color;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x+r*.7,y+r*.7);ctx.lineTo(x+r+20,y+r+20);ctx.stroke();ctx.lineCap='butt'}
function Scene({n}:{n:number}){const ref=useCanvas(244,130,(ctx,t)=>{clear(ctx,244,130);const p=(Math.sin(t*2)+1)/2;receipt(ctx,18,20,144,78);if(n===4){[30,22,15].forEach((r,i)=>{ctx.strokeStyle=i===0?C.green:C.purple;ctx.lineWidth=2;ctx.beginPath();ctx.arc(88,58,r*(1-p*.35),0,Math.PI*2);ctx.stroke()});label(ctx,'多分支 → 单卷积',122,112,C.green,'center')}else if(n===5){magnifier(ctx,54+p*82,55,22,p>.55?C.green:C.blue);ctx.strokeStyle=C.orange;ctx.lineWidth=3;ctx.beginPath();ctx.arc(90,61,52,.1,2.8);ctx.stroke();label(ctx,'覆盖长文字',122,112,C.green,'center')}else{const x=44+p*94;ctx.fillStyle=C.blue;ctx.fillRect(x,46,5,38);label(ctx,'沿一行读取',122,112,C.green,'center')}} ,[n]);return <canvas ref={ref} width={244} height={130} aria-label="档案核验动画"/>}
export const Analogy4:React.FC<WidgetProps>=()=> <Scene n={4}/>;
export const Analogy5:React.FC<WidgetProps>=()=> (
  <div className="d6-hook" role="img" aria-label="P4、P3、P2、P1 四层特征通过 top-down FPN 汇合，并把 per-level refinement 从 3×3 扩展到 7×7">
    <div className="d6-hook-pyramid">
      <span><b>P4</b>1/32</span>
      <i>↓</i>
      <span><b>P3</b>1/16</span>
      <i>↓</i>
      <span className="active"><b>P2</b>1/8</span>
      <i>↓</i>
      <span><b>P1</b>1/4</span>
    </div>
    <div className="d6-hook-refine">
      <span>Per-level refinement</span>
      <div><i className="small">3×3</i><b>→</b><i className="large">7×7</i></div>
      <strong>更大的局部上下文</strong>
    </div>
    <p>feature-level local receptive field，不是输入图像上的像素放大镜。</p>
  </div>
);
export const Analogy6:React.FC<WidgetProps>=()=> <Scene n={6}/>;

export const Ch4Fusion:React.FC<WidgetProps>=()=>{const [step,setStep]=useState(0);const steps=['三条训练分支','补零对齐','权重求和','单个推理卷积'];const ref=useCanvas(560,250,(ctx)=>{clear(ctx,560,250);label(ctx,steps[step],280,30,step===3?C.green:C.blue,'center');const ys=[70,120,170];['3×3 DW','1×1 DW','Identity'].forEach((s,i)=>{const visible=step<3;ctx.fillStyle=visible?(i===0?C.blue:C.purple):C.line;ctx.globalAlpha=visible?1:.2;ctx.fillRect(42,ys[i],105,30);ctx.globalAlpha=1;label(ctx,s,94,ys[i]+20,'#fff','center');if(step>=1){ctx.strokeStyle=C.orange;ctx.strokeRect(184,ys[i]-5,55,40)}});ctx.strokeStyle=step===2?C.orange:C.line;ctx.lineWidth=3;ys.forEach(y=>{ctx.beginPath();ctx.moveTo(147,y+15);ctx.lineTo(300,125);ctx.stroke()});ctx.fillStyle=step===3?C.green:step===2?C.orange:C.line;ctx.fillRect(320,88,184,74);label(ctx,step===3?'Deploy 3×3 DWConv':step===2?'K3 + pad(K1) + Kid':'等待融合',412,130,step>=2?'#fff':C.muted,'center');label(ctx,step===3?'额外推理分支：0':'训练结构',412,188,step===3?C.green:C.purple,'center')},[step]);return <div><canvas ref={ref} width={560} height={250}/><div className="step-ctrl"><button disabled={step===0} onClick={()=>setStep(s=>s-1)}>上一步</button><span className="val">{step+1} / 4</span><button disabled={step===3} onClick={()=>setStep(s=>s+1)}>下一步</button></div><div className={`feedback ${step===3?'good':''}`}>{step===3?'代数等价，部署图只剩一条空间分支。':steps[step]+'：训练分支仍可见。'}</div></div>};

type Neck='rse'|'rep';
export const Ch5Detection:React.FC<WidgetProps>=()=>{const [x,setX]=useState(.32);const [method,setMethod]=useState<Neck>('rse');const dragging=useRef(false);const ref=useCanvas(560,260,(ctx)=>{clear(ctx,560,260);receipt(ctx,26,28,310,178);ctx.strokeStyle=C.orange;ctx.lineWidth=4;ctx.beginPath();ctx.arc(172,111,88,.15,2.9);ctx.stroke();const cx=78+x*210;const radius=method==='rep'?46:25;magnifier(ctx,cx,104,radius,method==='rep'?C.green:C.red);label(ctx,method==='rep'?'7×7 refinement':'3×3 refinement',cx,190,method==='rep'?C.green:C.red,'center');label(ctx,'Neck 参数',382,55);const val=method==='rep'?118:172;ctx.fillStyle=C.line;ctx.fillRect(382,72,132,18);ctx.fillStyle=method==='rep'?C.green:C.red;ctx.fillRect(382,72,132*(val/172),18);label(ctx,`${val}K`,514,108,method==='rep'?C.green:C.red,'right');ctx.strokeStyle=C.purple;ctx.setLineDash([5,4]);if(method==='rep')ctx.strokeRect(374,133,148,50);ctx.setLineDash([]);label(ctx,method==='rep'?'训练期多尺度分支':'单一局部精修',448,163,method==='rep'?C.purple:C.muted,'center')},[x,method]);const setFromPointer=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();setX(clamp(((e.clientX-r.left)/r.width*560-78)/210,0,1))};const feedback=method==='rep'?(x>.22&&x<.78?['7×7 上下文覆盖更完整，推理 neck 仍为 118K。','good']:['移动到文字中心，观察大窗口覆盖。','']):['3×3 精修窗口难以覆盖完整弯曲笔画。','bad'];return <div><canvas ref={ref} width={560} height={260} tabIndex={0} aria-label="拖动放大镜比较检测 neck" onPointerDown={e=>{dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId);setFromPointer(e)}} onPointerMove={e=>{if(dragging.current)setFromPointer(e)}} onPointerUp={()=>{dragging.current=false}} onKeyDown={e=>{if(e.key==='ArrowLeft')setX(v=>clamp(v-.05,0,1));if(e.key==='ArrowRight')setX(v=>clamp(v+.05,0,1))}}/><div className="chip-row"><button className={`chip ${method==='rse'?'selected':''}`} onClick={()=>setMethod('rse')}>RSEFPN</button><button className={`chip ${method==='rep'?'selected':''}`} onClick={()=>setMethod('rep')}>RepLKFPN</button></div><div className={`feedback ${feedback[1]}`}>{feedback[0]}</div></div>};

type RecView='infer'|'train';
export const Ch6Recognition:React.FC<WidgetProps>=()=>{const [step,setStep]=useState(0);const [view,setView]=useState<RecView>('infer');const names=['LCNetV4 序列','1×7 局部卷积','全局注意力','加法跳连','CTC 输出'];const ref=useCanvas(560,270,(ctx,t)=>{clear(ctx,560,270);const xs=[38,142,246,350,454];xs.forEach((x,i)=>{const active=i<=step;ctx.fillStyle=active?(i===4?C.green:C.blue):'#fff';ctx.strokeStyle=active?(i===4?C.green:C.blue):C.line;ctx.lineWidth=active?3:1.5;ctx.fillRect(x,86,78,54);ctx.strokeRect(x,86,78,54);label(ctx,names[i],x+39,116,active?'#fff':C.muted,'center');if(i<4){ctx.strokeStyle=i<step?C.blue:C.line;ctx.lineWidth=i<step?4:2;ctx.beginPath();ctx.moveTo(x+78,113);ctx.lineTo(xs[i+1],113);ctx.stroke()}});if(view==='train'){ctx.strokeStyle=C.purple;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(389,140);ctx.lineTo(389,205);ctx.lineTo(480,205);ctx.stroke();ctx.fillStyle='rgba(124,58,237,.12)';ctx.fillRect(480,180,54,48);ctx.strokeRect(480,180,54,48);label(ctx,'NRTR',507,209,C.purple,'center')}label(ctx,'B×C×1×W',77,64,C.orange,'center');label(ctx,view==='infer'?'推理视图：NRTR 已禁用':'训练视图：紫色支路仅作辅助',280,245,view==='infer'?C.green:C.purple,'center');const pulse=.6+.4*Math.sin(t*3);ctx.fillStyle=`rgba(217,119,6,${.08+pulse*.12})`;ctx.fillRect(xs[step],78,78,8)},[step,view]);const msg=step===4?'推理只保留 CTC，NRTR 的作用已在训练中完成。':names[step]+'：'+(['保留横向字符顺序','先聚合相邻字符','再连接全行依赖','同维度逐元素融合','并行解码'][step]);return <div><canvas ref={ref} width={560} height={270}/><div className="chip-row"><button className={`chip ${view==='infer'?'selected':''}`} onClick={()=>setView('infer')}>推理视图</button><button className={`chip ${view==='train'?'selected':''}`} onClick={()=>setView('train')}>训练视图</button></div><div className="step-ctrl"><button disabled={step===0} onClick={()=>setStep(s=>s-1)}>上一步</button><span className="val">{step+1} / 5</span><button disabled={step===4} onClick={()=>setStep(s=>s+1)}>下一步</button></div><div className={`feedback ${step===4?'good':''}`}>{msg}</div></div>};
