import React, { useEffect, useRef, useState } from 'react';
import { clamp, easeOutCubic, setupCanvas, observeCanvas } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const C={bg:'#f5f8f0',desk:'#b8c9a7',wood:'#92400e',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#d97706',purple:'#7c3aed',ink:'#21324a',muted:'#68778f',line:'#d7deea'};
function useCanvas(w:number,h:number,draw:(c:CanvasRenderingContext2D,t:number)=>void,deps:React.DependencyList){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;let c:CanvasRenderingContext2D;try{c=setupCanvas(el,w,h)}catch{return}el.style.width='100%';el.style.height='auto';let raf=0;const tick=(ms:number)=>{draw(c,ms/1000);el.classList.add('is-ready');raf=requestAnimationFrame(tick)};const start=()=>{if(!raf)raf=requestAnimationFrame(tick)};const stop=()=>{if(raf)cancelAnimationFrame(raf);raf=0};const off=observeCanvas(el,start,stop);return()=>{stop();off()}},deps);return ref}
function clear(c:CanvasRenderingContext2D,w:number,h:number){c.clearRect(0,0,w,h);c.fillStyle=C.bg;c.fillRect(0,0,w,h);c.fillStyle=C.desk;c.fillRect(0,h-20,w,20)}
function label(c:CanvasRenderingContext2D,s:string,x:number,y:number,color=C.ink,align:CanvasTextAlign='left'){c.fillStyle=color;c.font='600 12px Segoe UI, sans-serif';c.textAlign=align;c.fillText(s,x,y);c.textAlign='left'}
function receipt(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,text='TEH  A@@A'){c.fillStyle='#fff';c.strokeStyle=C.line;c.lineWidth=1.5;c.fillRect(x,y,w,h);c.strokeRect(x,y,w,h);c.fillStyle=C.ink;c.font='700 13px Segoe UI, sans-serif';c.fillText(text,x+16,y+37);c.strokeStyle='#dfe5ec';c.beginPath();c.moveTo(x+14,y+52);c.lineTo(x+w-14,y+52);c.stroke()}
function Scene({n}:{n:number}){const ref=useCanvas(244,130,(c,t)=>{clear(c,244,130);const p=(Math.sin(t*2.1)+1)/2;receipt(c,18,20,144,78);if(n===9){c.strokeStyle=C.wood;c.lineWidth=5;c.lineCap='round';c.beginPath();c.moveTo(54+p*72,30);c.lineTo(66+p*72,72);c.stroke();c.lineCap='butt';label(c,'原样誊录',122,112,C.green,'center')}else{c.save();c.translate(94,28+p*34);c.fillStyle=C.wood;c.fillRect(-18,-12,36,34);c.fillStyle=C.green;c.fillRect(-28,22,56,9);c.restore();label(c,'核验通过',122,112,C.green,'center')}},[n]);return <canvas ref={ref} width={244} height={130} aria-label="档案核验动画"/>}
export const Analogy9:React.FC<WidgetProps>=()=> <Scene n={9}/>;
export const Analogy10:React.FC<WidgetProps>=()=> <Scene n={10}/>;

export const Ch9Margin:React.FC<WidgetProps>=()=>{const [margin,setMargin]=useState(.45);const dragging=useRef(false);const ref=useCanvas(560,260,(c)=>{clear(c,560,260);receipt(c,42,42,300,110,'C0DE  TEH');const expand=margin*62;c.strokeStyle=C.orange;c.lineWidth=3;c.strokeRect(90-expand,66-expand*.25,172+expand*2,42+expand*.5);label(c,'裁剪边界',90-expand,56-expand*.25,C.orange);const stableV6=margin>.1&&margin<.92;const stableV5=margin>.34&&margin<.67;const rows=[['PP-OCRv5_server','C0DE  TEH',stableV5,'54.82%'],['PP-OCRv6_medium','C0DE  TEH',stableV6,'75.32%']] as const;rows.forEach((r,i)=>{const y=165+i*38;c.fillStyle=r[2]?'rgba(34,141,92,.10)':'rgba(196,63,82,.10)';c.strokeStyle=r[2]?C.green:C.red;c.fillRect(42,y,472,28);c.strokeRect(42,y,472,28);label(c,r[0],54,y+19,r[2]?C.green:C.red);label(c,r[2]?r[1]:'C0D  TEH',290,y+19,r[2]?C.green:C.red,'center');label(c,r[3],500,y+19,C.ink,'right')});label(c,'聚合一致性（越高越好）',514,245,C.muted,'right')},[margin]);const fromPointer=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();setMargin(clamp((e.clientX-r.left)/r.width,0,1))};return <div><canvas ref={ref} width={560} height={260} tabIndex={0} aria-label="拖动裁剪边界" onPointerDown={e=>{dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId);fromPointer(e)}} onPointerMove={e=>{if(dragging.current)fromPointer(e)}} onPointerUp={()=>dragging.current=false} onKeyDown={e=>{if(e.key==='ArrowLeft')setMargin(v=>clamp(v-.05,0,1));if(e.key==='ArrowRight')setMargin(v=>clamp(v+.05,0,1))}}/><div className="ctrl"><label>裁剪松紧 <span className="val">{Math.round(margin*100)}%</span></label><input aria-label="裁剪松紧" type="range" min="0" max="100" value={Math.round(margin*100)} onChange={e=>setMargin(Number(e.target.value)/100)}/></div><div className="feedback good">一致性不是识别准确率：它只衡量不同 margin 下预测是否保持不变。</div></div>};

type FaithMode='prior'|'visual';
const samples=[['TEH','THE'],['goood','good'],['A@@A','A@A']];
export const Ch9Faithfulness:React.FC<WidgetProps>=()=>{const [mode,setMode]=useState<FaithMode>('prior');const [sample,setSample]=useState(0);const ref=useCanvas(560,260,(c)=>{clear(c,560,260);label(c,'图像文字',42,38,C.ink);label(c,'模型输出',322,38,C.ink);receipt(c,36,55,218,98,samples[sample][0]);receipt(c,306,55,218,98,mode==='visual'?samples[sample][0]:samples[sample][1]);c.strokeStyle=mode==='visual'?C.green:C.red;c.lineWidth=3;c.strokeRect(326,73,100,38);label(c,mode==='visual'?'逐字符一致':'语言更顺，但改字',415,175,mode==='visual'?C.green:C.red,'center');label(c,'论文幻觉集准确率（越高越好）',280,207,C.muted,'center');c.fillStyle=C.line;c.fillRect(82,220,396,14);c.fillStyle=C.red;c.fillRect(82,220,396*.8056,14);c.fillStyle=C.green;c.fillRect(82,238,396*.932,14);label(c,'Qwen3-VL 80.56',78,231,C.red,'right');label(c,'PP-OCRv6 93.20',78,249,C.green,'right')},[mode,sample]);const msg=mode==='visual'?'输出保留了图像中的非标准写法。':'句子更顺，但已经不是原图文字。';return <div><canvas ref={ref} width={560} height={260}/><div className="chip-row"><button className={`chip ${mode==='prior'?'selected':''}`} onClick={()=>setMode('prior')}>语言先验改写</button><button className={`chip ${mode==='visual'?'selected':''}`} onClick={()=>setMode('visual')}>视觉证据优先</button></div><div className="chip-row">{['故意拼错','重复字符','特殊字符'].map((s,i)=><button key={s} className={`chip ${sample===i?'selected':''}`} onClick={()=>setSample(i)}>{s}</button>)}</div><div className={`feedback ${mode==='visual'?'good':'bad'}`}>{msg}</div></div>};

type Metric='det'|'rec'|'hall'|'latency';
const metrics:Record<Metric,{label:string,a:string,b:string,av:number,bv:number,max:number,direction:string,protocol:string,feedback:string}>={det:{label:'检测 Hmean',a:'PP-OCRv5_server',b:'PP-OCRv6_medium',av:81.6,bv:86.2,max:100,direction:'越高越好',protocol:'自建16类检测基准 · Table 4 · %',feedback:'同一检测协议下，medium 高 4.6 个百分点。'},rec:{label:'识别准确率',a:'PP-OCRv5_server',b:'PP-OCRv6_medium',av:78.1,bv:83.2,max:100,direction:'越高越好',protocol:'自建15类识别基准 · Table 6 · %',feedback:'同一识别协议下，medium 高 5.1 个百分点。'},hall:{label:'幻觉集准确率',a:'Qwen3-VL-235B',b:'PP-OCRv6_medium',av:80.56,bv:93.2,max:100,direction:'越高表示幻觉越少',protocol:'论文自建OCR幻觉集 · Table 7 · %',feedback:'该幻觉集上，medium 更忠实地保留原图文本。'},latency:{label:'Xeon 延迟',a:'PP-OCRv5_mobile',b:'PP-OCRv6_tiny',av:.78,bv:.20,max:1,direction:'越低越好',protocol:'Xeon 8350C + OpenVINO · Table 9 · 秒/图',feedback:'在指定硬件与后端下，tiny 为 0.20 秒/图。'}};
export const Ch10Results:React.FC<WidgetProps>=()=>{const [metric,setMetric]=useState<Metric>('det');const [run,setRun]=useState(0);const started=useRef(0);useEffect(()=>{if(run)started.current=performance.now()},[run,metric]);const m=metrics[metric];const ref=useCanvas(620,290,(c,t)=>{clear(c,620,290);const p=run?easeOutCubic(clamp((t*1000-started.current)/1700,0,1)):0;label(c,m.label,32,34,C.ink);label(c,m.direction,588,34,C.orange,'right');const rows=[[m.a,m.av,C.red],[m.b,m.bv,C.green]] as const;rows.forEach((r,i)=>{const y=78+i*78;label(c,r[0],32,y,C.ink);c.fillStyle=C.line;c.fillRect(32,y+14,500,28);const normalized=metric==='latency'?1-r[1]/m.max:r[1]/m.max;c.fillStyle=r[2];c.fillRect(32,y+14,500*normalized*p,28);label(c,metric==='latency'?`${r[1].toFixed(2)} s/图`:`${r[1].toFixed(r[1]%1?2:0)}%`,576,y+34,r[2],'right')});label(c,m.protocol,310,241,C.muted,'center');label(c,'主要精度结论来自论文自建基准',310,270,C.orange,'center')},[metric,run]);return <div><canvas ref={ref} width={620} height={290}/><div className="chip-row">{(Object.keys(metrics) as Metric[]).map(k=><button key={k} className={`chip ${metric===k?'selected':''}`} onClick={()=>{setMetric(k);setRun(0)}}>{metrics[k].label}</button>)}</div><div className="step-ctrl"><button onClick={()=>setRun(v=>v+1)}>开始比较</button></div><div className={`feedback ${run?'good':''}`}>{run?m.feedback:'选择一个协议，结果会保留单位与方向。'}</div></div>};
