import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { M11 } from './m1-1';
import { M12 } from './m1-2';
import { M101 } from './m10-1';
import { M21 } from './m2-1';
import { M31 } from './m3-1';
import { M41 } from './m4-1';
import { M51 } from './m5-1';
import { M61 } from './m6-1';
import { M71 } from './m7-1';
import { M81 } from './m8-1';
import { M82 } from './m8-2';
import { M91 } from './m9-1';
import { M92 } from './m9-2';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['m1-1'] = M11;
widgetRegistry['m1-2'] = M12;
widgetRegistry['m10-1'] = M101;
widgetRegistry['m2-1'] = M21;
widgetRegistry['m3-1'] = M31;
widgetRegistry['m4-1'] = M41;
widgetRegistry['m5-1'] = M51;
widgetRegistry['m6-1'] = M61;
widgetRegistry['m7-1'] = M71;
widgetRegistry['m8-1'] = M81;
widgetRegistry['m8-2'] = M82;
widgetRegistry['m9-1'] = M91;
widgetRegistry['m9-2'] = M92;
