import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { AnaCh1Blind } from './ana-ch1-blind';
import { AnaCh10Seal } from './ana-ch10-seal';
import { AnaCh2Read } from './ana-ch2-read';
import { AnaCh3Trace } from './ana-ch3-trace';
import { AnaCh4Cursive } from './ana-ch4-cursive';
import { AnaCh5Pressure } from './ana-ch5-pressure';
import { AnaCh6Hover } from './ana-ch6-hover';
import { AnaCh7Air } from './ana-ch7-air';
import { AnaCh8Dip } from './ana-ch8-dip';
import { AnaCh9Compose } from './ana-ch9-compose';
import { HeroPredictive } from './hero-predictive';
import { HeroReactive } from './hero-reactive';
import { M11BlindVsCorrect } from './m1-1-blind-vs-correct';
import { M12LoopStep } from './m1-2-loop-step';
import { M101LiberoRace } from './m10-1-libero-race';
import { M102Challenges } from './m10-2-challenges';
import { M21LatentDim } from './m2-1-latent-dim';
import { M31LearningCurves } from './m3-1-learning-curves';
import { M41RolloutSteps } from './m4-1-rollout-steps';
import { M51CondStrength } from './m5-1-cond-strength';
import { M52CondType } from './m5-2-cond-type';
import { M61MpcRollout } from './m6-1-mpc-rollout';
import { M62DropPoint } from './m6-2-drop-point';
import { M71ImaginedRatio } from './m7-1-imagined-ratio';
import { M81ParadigmMap } from './m8-1-paradigm-map';
import { M82CouplingSpectrum } from './m8-2-coupling-spectrum';
import { M91ThreeLenses } from './m9-1-three-lenses';
import { ThemeKit } from './theme-kit';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-ch1-blind'] = AnaCh1Blind;
widgetRegistry['ana-ch10-seal'] = AnaCh10Seal;
widgetRegistry['ana-ch2-read'] = AnaCh2Read;
widgetRegistry['ana-ch3-trace'] = AnaCh3Trace;
widgetRegistry['ana-ch4-cursive'] = AnaCh4Cursive;
widgetRegistry['ana-ch5-pressure'] = AnaCh5Pressure;
widgetRegistry['ana-ch6-hover'] = AnaCh6Hover;
widgetRegistry['ana-ch7-air'] = AnaCh7Air;
widgetRegistry['ana-ch8-dip'] = AnaCh8Dip;
widgetRegistry['ana-ch9-compose'] = AnaCh9Compose;
widgetRegistry['hero-predictive'] = HeroPredictive;
widgetRegistry['hero-reactive'] = HeroReactive;
widgetRegistry['m1-1-blind-vs-correct'] = M11BlindVsCorrect;
widgetRegistry['m1-2-loop-step'] = M12LoopStep;
widgetRegistry['m10-1-libero-race'] = M101LiberoRace;
widgetRegistry['m10-2-challenges'] = M102Challenges;
widgetRegistry['m2-1-latent-dim'] = M21LatentDim;
widgetRegistry['m3-1-learning-curves'] = M31LearningCurves;
widgetRegistry['m4-1-rollout-steps'] = M41RolloutSteps;
widgetRegistry['m5-1-cond-strength'] = M51CondStrength;
widgetRegistry['m5-2-cond-type'] = M52CondType;
widgetRegistry['m6-1-mpc-rollout'] = M61MpcRollout;
widgetRegistry['m6-2-drop-point'] = M62DropPoint;
widgetRegistry['m7-1-imagined-ratio'] = M71ImaginedRatio;
widgetRegistry['m8-1-paradigm-map'] = M81ParadigmMap;
widgetRegistry['m8-2-coupling-spectrum'] = M82CouplingSpectrum;
widgetRegistry['m9-1-three-lenses'] = M91ThreeLenses;
widgetRegistry['theme-kit'] = ThemeKit;
