import React, { useEffect, useRef, useState } from 'react';
import { setupCanvas, observeCanvas } from '../lib/canvasKit';

type CT=CanvasRenderingContext2D;
export const C={bg:'#f3f7f4',line:'#cbd8d2',ink:'#233747',blue:'#28527b',green:'#268467',red:'#c34555',orange:'#d17c3e',purple:'#7655a5',muted:'#839992'};
export function BirdKit(){return null;}
export function wipe(c:CT,w=1080,h=280){c.clearRect(0,0,w,h);c.fillStyle=C.bg;c.fillRect(0,0,w,h);}
export function stroke(c:CT,x:number,y:number,w:number,h:number,color=C.blue,fill=false){c.beginPath();c.roundRect(x,y,w,h,9);c.lineWidth=3;c.strokeStyle=color;if(fill){c.fillStyle=color;c.fill();}c.stroke();}
export function line(c:CT,x:number,y:number,u:number,v:number,color=C.blue,width=3){c.beginPath();c.moveTo(x,y);c.lineTo(u,v);c.lineWidth=width;c.strokeStyle=color;c.stroke();}
export function label(c:CT,s:string,x:number,y:number,color=C.ink,size=22){c.fillStyle=color;c.font=`${size}px "Microsoft YaHei",sans-serif`;c.fillText(s,x,y);}
export function bird(c:CT,x:number,y:number,size=1,color=C.orange){c.save();c.translate(x,y);c.scale(size,size);c.fillStyle=color;c.beginPath();c.ellipse(0,0,38,26,0,0,7);c.fill();c.beginPath();c.arc(23,-21,19,0,7);c.fill();c.beginPath();c.moveTo(39,-19);c.lineTo(59,-12);c.lineTo(39,-7);c.fillStyle='#ddb15f';c.fill();c.fillStyle=C.ink;c.beginPath();c.arc(27,-25,3,0,7);c.fill();line(c,-14,17,-23,48,C.ink,2);line(c,3,18,6,49,C.ink,2);c.restore();}
export function scene(c:CT,w=1080,h=280){wipe(c,w,h);line(c,30,h-36,w-30,h-36,C.muted,3);[.1,.45,.78].forEach(v=>{const x=w*v;c.fillStyle='#dce9dd';c.beginPath();c.arc(x,h-100,35,0,7);c.fill();});}
type Draw=(c:CT,t:number)=>void;
export function Canvas({draw,label:description,width=1080,height=280,animate=false,onPoint,drag=false,onKey}:{draw:Draw,label:string,width?:number,height?:number,animate?:boolean,onPoint?:(x:number,y:number)=>void,drag?:boolean,onKey?:(key:string)=>void}){const ref=useRef<HTMLCanvasElement>(null),fn=useRef(draw),ctx=useRef<CT|null>(null);fn.current=draw;useEffect(()=>{const el=ref.current!;ctx.current=setupCanvas(el,width,height);el.style.width='100%';el.style.height='auto';let frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const paint=(t:number)=>{fn.current(ctx.current!,t);el.classList.add('is-ready');};paint(0);const tick=(t:number)=>{paint(t);frame=requestAnimationFrame(tick);};const stop=()=>{cancelAnimationFrame(frame);frame=0;};const off=observeCanvas(el,()=>{if(animate&&!reduced&&!frame)frame=requestAnimationFrame(tick);},stop);return()=>{stop();off();};},[width,height,animate]);useEffect(()=>{if(ctx.current)draw(ctx.current,0);},[draw]);const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();onPoint?.((e.clientX-r.left)*width/r.width,(e.clientY-r.top)*height/r.height);};return <canvas ref={ref} width={width} height={height} aria-label={description} role={onPoint?'application':'img'} tabIndex={onPoint||onKey?0:undefined} style={{maxWidth:'100%',cursor:drag?'grab':onPoint?'pointer':'default',touchAction:drag?'none':'auto'}} onPointerDown={e=>{if(drag)e.currentTarget.setPointerCapture(e.pointerId);move(e);}} onPointerMove={e=>{if(drag&&e.currentTarget.hasPointerCapture(e.pointerId))move(e);}} onPointerUp={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}} onKeyDown={e=>{if(onKey&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();e.stopPropagation();onKey(e.key);}}}/>;}
export function Chips({labels,value,onChange}:{labels:string[],value:number,onChange:(v:number)=>void}){return <div className="ctrl">{labels.map((x,i)=><button type="button" key={x} className={`chip ${i===value?'selected':''}`} aria-pressed={i===value} onClick={()=>onChange(i)}>{x}</button>)}</div>;}
export function Feedback({children,kind=''}:{children:React.ReactNode,kind?:string}){return <div className={`feedback ${kind}`} aria-live="polite">{children}</div>;}
export function Reset({onClick}:{onClick:()=>void}){return <button type="button" className="tiny" onClick={onClick}>重置</button>;}

export function BirdScene({chapterId='chap-1'}:{chapterId?:string}){const n=Number(chapterId.split('-')[1])||1;return <Canvas width={560} height={140} animate label={`第${n}章机制类比示意，非实测数据`} draw={(c,t)=>{wipe(c,560,140);const p=(Math.sin(t/1800)+1)/2;if(n===1||n===2){[150,300,450].forEach((x,i)=>{bird(c,x,70,.55,i===1?C.purple:C.orange);if(n===1?i===Math.floor(p*2.99):i===2)stroke(c,x-40,20,90,100,C.green)});}else if(n===3){stroke(c,70,40,100,60,C.blue);stroke(c,390,40,100,60,C.purple);line(c,170,70,390,70,C.line);c.fillStyle=C.green;c.beginPath();c.arc(170+220*p,70,12,0,7);c.fill();}else if(n===4){[.9,.5,.7,.2].forEach((v,i)=>{stroke(c,80+i*120,110-v*80,60,v*80,i===0||i===2?C.green:C.line,true)});}else if(n===5){bird(c,280,65,.7);stroke(c,150+70*p,15+8*p,260-120*p,115-20*p,C.blue);}else if(n===6){[100,200,360,460].forEach((x,i)=>{stroke(c,x-24,45,48,48,i<2?C.blue:C.purple,true)});line(c,124,70,176,70,C.green,4);line(c,384,70,436,70,C.green,4);line(c,280,25,280,115,C.red,3);}else if(n===7){[0,1,2].forEach(i=>{stroke(c,95,15+i*40,45,25,C.blue);stroke(c,420,15+i*40,45,25,C.green);line(c,140,28+i*40,420,28+[1,0,2][i]*40,C.purple,2)});}else if(n===8){[0,1,2].forEach(i=>{stroke(c,55+i*175,40,110,60,i===Math.floor(p*2.99)?C.green:C.line);label(c,['A','B','C'][i],95+i*175,80,C.ink,24);if(i<2)line(c,165+i*175,70,230+i*175,70,C.blue)});}else if(n===9){line(c,90,90,250,40,C.green,5);line(c,310,40,470,100,C.red,5);}else{[0,1,2].forEach(i=>{stroke(c,65+i*170,20,130,100,C.line);line(c,85+i*170,90,175+i*170,90,C.muted);stroke(c,110+i*170,40+i*10,30,50-i*10,C.blue,true)});}}}/>;}
export function BirdHeroOld(){return <Canvas width={500} height={220} animate label="固定名单无法表达新的寻鸟描述" draw={(c,t)=>{scene(c,500,220);bird(c,210+10*Math.sin(t/900),100,.8);stroke(c,340,55,120,90,C.line);label(c,'固定名单',345,108,C.ink,18);}}/>;}
export function BirdHeroNew(){return <Canvas width={500} height={220} animate label="文字指引望远镜定位鸟" draw={(c,t)=>{scene(c,500,220);const x=210+10*Math.sin(t/900);bird(c,x,100,.8);stroke(c,x-56,41,124,113,C.green);line(c,340,95,x+60,88,C.blue,4);}}/>;}

export function Task(){const [target,setTarget]=useState(0),[mode,setMode]=useState(0);const found=target===0||mode===1;return <><Canvas label="目标文字与两只鸟的定位结果" draw={c=>{scene(c);bird(c,265,127,1.3);bird(c,715,127,1.1,C.purple);if(found)stroke(c,(target?715:265)-90,35,180,190,C.green);else stroke(c,625,35,180,190,C.red);stroke(c,920,63,100,75,found?C.green:C.red);}}/><Chips labels={['常见橙鸟','紫色新鸟']} value={target} onChange={setTarget}/><Chips labels={['固定名单','文字提示']} value={mode} onChange={setMode}/><Feedback kind={found?'good':'bad'}>{found?`目标“${target?'紫色新鸟':'常见橙鸟'}”可被当前提示表达；框是教学示意，真实检测仍取决于数据和图像。`:'固定名单里没有紫色新鸟；改变请求并不能给封闭类别头自动新增类别。'} 论文 p1 Fig.1 区分固定类别与开放集描述。</Feedback></>;}
export function Prompt(){const [mode,set]=useState(0);return <><Canvas label="类别名与指代表达对应到不同定位目标" draw={c=>{scene(c);bird(c,300,135,1.1);bird(c,700,135,.9);stroke(c,(mode?700:300)-82,55,165,170,C.green);line(c,475,95,mode?630:375,115,C.purple,4);}}/><Chips labels={['类别名：鸟','指代：右侧较小的鸟']} value={mode} onChange={set}/><Feedback>当前文字：{mode?'“右侧较小的鸟”包含相对位置与属性，因此应指向右侧个体。':'“鸟”仅给类别，两只鸟都满足；图中选择左侧仅为展示一个候选。'} 论文 §3 说明模型输出框与短语；REC 按最高分框作为结果，不能保证描述一定定位正确。</Feedback></>;}
export function Enhancer(){const [phase,set]=useState(0);return <><Canvas label="图像特征与文字特征的双向增强路径" draw={c=>{wipe(c);stroke(c,115,65,260,150,C.blue);stroke(c,705,65,260,150,C.purple);label(c,'图像特征',175,148,C.blue);label(c,'文字特征',770,148,C.purple);if(phase>0){line(c,375,110,705,110,C.green,5);if(phase>1)line(c,705,170,375,170,C.purple,5);}else line(c,375,140,705,140,C.line,2);}}/><Chips labels={['尚未跨模态','图像→文字','再加文字→图像']} value={phase} onChange={set}/><Feedback kind={phase===2?'good':''}>{phase===0?'各自骨干先提取特征；此处还未跨模态交换。':phase===1?'图像信息进入文字特征，但还没完成相反方向。':'两种跨注意力方向均存在；论文增强器还分别包含图像可变形自注意和文字自注意。'} 图中连线是机制示意，不是实测注意力权重。</Feedback></>;}
const matrices=[[[.9,.2],[.2,.8],[.7,.1],[.1,.6]],[[.1,.5],[.2,.4],[.05,.8],[.9,.1]]];
export function Query(){const [prompt,setPrompt]=useState(0),[n,setN]=useState(2);const mat=matrices[prompt],scores=mat.map(row=>Math.max(...row)),order=[0,1,2,3].sort((a,b)=>scores[b]-scores[a]),selected=order.slice(0,n);return <><Canvas label="四个图像位置与两个文字词的点积、逐行最大值与选中位置" draw={c=>{wipe(c);scores.forEach((s,i)=>{const x=95+i*230;stroke(c,x,58,170,150,selected.includes(i)?C.green:C.line);bird(c,x+85,122,.42,i%2?C.purple:C.orange);stroke(c,x+20,178,Math.max(1,130*s),14,selected.includes(i)?C.green:C.blue,true);label(c,String(i+1),x+75,40,C.ink,19);});}}/><Chips labels={['文本 A','文本 B']} value={prompt} onChange={setPrompt}/><div className="ctrl"><label htmlFor="query-count">教学用 Nq：{n}</label><input id="query-count" type="range" min="1" max="4" step="1" value={n} onKeyDown={e=>e.stopPropagation()} onChange={e=>setN(Number(e.target.value))}/><Reset onClick={()=>{setPrompt(0);setN(2);}}/></div><Feedback>逐行 max={scores.map(x=>x.toFixed(2)).join('，')}；Top-{n} 图像位置={selected.map(x=>x+1).join('、')}。{prompt===0?'文本 A 对前两个位置得分较高。':'文本 B 把焦点移向后两个位置。'} 本例是人工点积矩阵；论文 Eq.1 默认选 900 个索引，演示缩为四选 Nq。</Feedback></>;}
export function Mixed(){const [side,set]=useState(0);return <><Canvas label="混合查询的位置部分与内容部分" draw={c=>{wipe(c);stroke(c,120,70,290,140,side===0?C.green:C.line);stroke(c,665,70,290,140,side===1?C.green:C.line);label(c,'位置锚框',185,148,C.blue);label(c,'可学习内容',720,148,C.purple);line(c,410,140,665,140,C.line,3);}}/><Chips labels={['查看位置部分','查看内容部分']} value={side} onChange={set}/><Feedback kind="good">{side===0?'选中的图像编码器输出用于初始化动态锚框，即查询的位置部分。':'内容查询是训练时可学习的参数，不是把选中图像 token 直接当内容复制进去。'} 这是论文 §3.2 所述混合查询的关键区分。</Feedback></>;}
export function Decoder(){const [step,setStep]=useState(0);const names=['查询自注意','图像跨注意','文本跨注意','前馈更新'];return <><Canvas label="查询依次经过四个解码环节，边框随教学步骤收敛" draw={c=>{scene(c);bird(c,650,126,1.15);stroke(c,500+step*22,45+step*12,265-step*45,190-step*25,step===3?C.green:C.blue);for(let i=0;i<4;i++)stroke(c,65+i*95,198,67,18,i<=step?C.green:C.line,true);}}/><Chips labels={names} value={step} onChange={setStep}/><Feedback>{`当前：${names[step]}（第${step+1}/4步）。`}{step===2?'这是相对 DINO 解码器新增的文本跨注意，使查询再次读取文本线索。':step===3?'完成示意更新后仍需输出框和词分数；这里的缩框轨迹不是实际推理记录。':'继续选择下一个环节，观察查询的可用信息。'} 论文 §3.3 Fig.3。</Feedback></>;}
export function Mask(){const [on,set]=useState(0);return <><Canvas label="类别词之间的自注意连接有无子句级掩码" draw={c=>{wipe(c);const xs=[165,365,690,890];for(let i=0;i<xs.length;i++)for(let j=i+1;j<xs.length;j++){const same=(i<2)===(j<2);if(!on||same)line(c,xs[i],125,xs[j],125,same?C.green:C.red,2);}xs.forEach((x,i)=>{stroke(c,x-32,89,64,72,i<2?C.blue:C.purple,true);label(c,String(i+1),x-7,135,'white');});}}/><Chips labels={['不加掩码','子句级掩码']} value={on} onChange={set}/><Feedback kind={on?'good':'bad'}>{on?'两组无关类别之间的连接被挡住，组内词仍可相互注意；这不是逐词完全隔离。':'无关类别词也可能在同一次文本自注意中彼此影响，尤其类别名被任意拼接时。'} 红线代表本示意中的跨类别连接。论文 §3.4 Fig.4。</Feedback></>;}
export function Matching(){const [mode,set]=useState(0);const matrix=[[1,5],[4,1]],cost=mode===0?2:9;return <><Canvas label="二乘二预测目标匹配成本表与连线" draw={c=>{wipe(c);[0,1].forEach(i=>{stroke(c,130,50+i*135,140,72,C.blue);stroke(c,790,50+i*135,140,72,C.green);});line(c,270,85,790,mode?220:85,mode?C.red:C.green,5);line(c,270,220,790,mode?85:220,mode?C.red:C.green,5);label(c,String(cost),520,147,mode?C.red:C.green,38);}}/><Chips labels={['预测1→目标1，预测2→目标2','交叉配对']} value={mode} onChange={set}/><Feedback kind={mode?'bad':'good'}>教学成本矩阵=[[{matrix[0].join(',')}],[{matrix[1].join(',')}]]；当前一对一总成本={cost}。{mode?'交叉方案=5+4=9，高于另一方案。':'同序方案=1+1=2，是此例的最小总成本。'} 真实训练先做匹配，再用 token 分类 focal、框 L1 和 GIoU 计算匹配后损失；矩阵并非论文实测值。</Feedback></>;}
export function Architecture(){const [node,set]=useState(0);const names=['特征增强 A','查询选择 B','解码器 C'];const copy=['A：图像和文字各自编码后，在增强器里双向交换特征。','B：图像与文本逐位置匹配，按逐行最大值选图像索引，初始化位置锚框。','C：查询在解码器里读取图像和文本，更新表示并预测框与词。'];return <><Canvas label="点击三个结构阶段查看信息路径" onPoint={(x,y)=>{if(y>70&&y<205)set(Math.max(0,Math.min(2,Math.floor(x/360))));}} draw={c=>{wipe(c);names.forEach((_,i)=>{stroke(c,52+i*355,72,250,130,node===i?C.blue:C.line,node===i);label(c,String.fromCharCode(65+i),160+i*355,151,node===i?'white':C.ink,34);if(i<2)line(c,302+i*355,137,406+i*355,137,C.green,4);});}}/><Chips labels={names} value={node} onChange={set}/><Feedback>{copy[node]} 这是论文 Fig.2–3 的概念阶段，不表示三个模块参数或时长相等。</Feedback></>;}
const trans=[[48.1,25.6,20],[48.5,21.9,17.7]];
export function Transfer(){const [v,set]=useState(0);return <><Canvas label="加入 RefC 前后三个数据集的指标变化" draw={c=>{wipe(c);trans[v].forEach((value,i)=>{const y=38+i*76;stroke(c,150,y,Math.max(1,value*15),45,[C.blue,C.purple,C.orange][i],true);label(c,value.toFixed(1),170+value*15,y+31,C.ink,22);});}}/><Chips labels={['O365+GoldG','再加 RefC']} value={v} onChange={set}/><div className="ctrl"><span>从上到下：COCO 2017val AP / LVIS MiniVal AP / ODinW mean AP</span></div><Feedback kind={v?'bad':''}>论文表6，Grounding DINO T：COCO {trans[v][0].toFixed(1)}，LVIS {trans[v][1].toFixed(1)}，ODinW {trans[v][2].toFixed(1)}。{v?'相对基线分别 +0.4、−3.7、−2.3；添加指代表达数据并非所有任务都受益。':'切换到加入 RefC 的训练配置，比较每个数据集自身的变化。'} 不把不同数据集的 AP 大小互相排名。</Feedback></>;}
const groups=[{name:'COCO 2017val · 零样本',names:['T：O365','T：O365+GoldG','T：再加Cap4M','L：O365+OI+GoldG'],values:[46.7,48.1,48.4,52.5],note:'表2：L 的骨干和预训练数据同时变化；52.5 是未用 COCO 训练划分的 box AP。'},{name:'LVIS MiniVal · 零样本',names:['GLIP-T(C)：AP','Grounding DINO T：AP','GLIP-T(C)：APr','Grounding DINO T：APr'],values:[24.9,25.6,17.7,14.4],note:'表3：两者为 Swin-T、O365+GoldG；总体 AP 略升，稀有类 APr 下降。'},{name:'ODinW · 零样本',names:['T：O365+GoldG','T：再加Cap4M','L：更多数据与骨干'],values:[20,22.3,26.1],note:'表4：这里是跨数据集的 APaverage，不能与 COCO AP 直接互比。'}];
export function Results(){const [which,set]=useState(0),[show,setShow]=useState(false);const data=groups[which];return <><Canvas label="按照当前选定的实验协议绘制真实论文表格数值" draw={c=>{wipe(c);data.values.forEach((value,i)=>{const y=30+i*56;stroke(c,210,y,Math.max(1,value*12*(show?1:.08)),32,i===data.values.length-1?C.green:C.blue,true);if(show)label(c,value.toFixed(1),220+value*12,y+24,C.ink,19);});}}/><Chips labels={groups.map(x=>x.name)} value={which} onChange={v=>{set(v);setShow(false);}}/><div className="ctrl"><button className="tiny" onClick={()=>setShow(true)}>显示比较</button><Reset onClick={()=>setShow(false)}/></div><table className="evidence-table"><caption>{data.name} · 论文原始数值</caption><thead><tr><th scope="col">配置/指标</th><th scope="col">AP ↑</th></tr></thead><tbody>{data.values.map((v,i)=><tr key={i}><th scope="row">{data.names[i]}</th><td>{v.toFixed(1)}</td></tr>)}</tbody></table><Feedback>{data.note} {show?'图形已经按本组数值展开。':'选择显示比较；表格始终保留精确值。'} 图形刻度从 0 开始。</Feedback></>;}
const questions=[{q:'52.5 是什么？',options:['COCO 2017val 零样本 box AP','LVIS 稀有类 APr','COCO 逐图准确率'],answer:0,note:'表2：L 配置在 COCO 2017val 上，训练未使用 COCO 训练划分，box AP 52.5。'},{q:'60.7‡ 能算零样本吗？',options:['能，因为模型名字没变','不能：训练包含 COCO','能，因为使用新骨干'],answer:1,note:'表2脚注‡：该配置加入了 COCO 数据，论文明确写明不是真实零样本。'},{q:'LVIS 总 AP 高就一定 APr 高吗？',options:['一定','不一定：25.6>24.9，但14.4<17.7','只有微调后才成立'],answer:1,note:'表3：同骨干与 O365+GoldG 配置下，Grounding DINO T 总 AP 高于 GLIP-T(C)，APr 反而较低。'},{q:'添加 RefC 的影响？',options:['所有数据集都提升','COCO 略升，LVIS 和 ODinW 下降','不改变任何指标'],answer:1,note:'表6：COCO 48.1→48.5，LVIS 25.6→21.9，ODinW 20.0→17.7。'}];
export function Quiz(){const [q,setQ]=useState(0),[choice,setChoice]=useState<number|null>(null),[done,setDone]=useState(false);const item=questions[q];return <><Canvas width={1080} height={145} label="四道论文结论题的当前位置" draw={c=>{wipe(c,1080,145);questions.forEach((_,i)=>{stroke(c,100+i*230,28,150,80,q===i?C.blue:C.line,q===i);label(c,String(i+1),170+i*230,82,q===i?'white':C.ink,26);});}}/><Chips labels={questions.map((_,i)=>`第${i+1}题`)} value={q} onChange={v=>{setQ(v);setChoice(null);setDone(false);}}/><p><strong>{item.q}</strong></p><div className="quiz-options">{item.options.map((x,i)=><button key={x} className={`chip ${choice===i?'selected':''}`} disabled={done} onClick={()=>setChoice(i)}>{String.fromCharCode(65+i)}. {x}</button>)}</div><div className="ctrl"><button className="tiny" disabled={choice===null||done} onClick={()=>setDone(true)}>核对证据</button><button className="tiny" onClick={()=>{setChoice(null);setDone(false);}}>重答</button><button className="tiny" onClick={()=>{setQ((q+1)%4);setChoice(null);setDone(false);}}>下一题</button></div><Feedback kind={done?choice===item.answer?'good':'bad':''}>{done?`${choice===item.answer?'正确。':'这项表述不成立。'} ${item.note}`:'选一项后核对论文表格证据；每题可以重答。'}</Feedback></>;}
