import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana1';
import { Ana10 } from './ana10';
import { Ana2 } from './ana2';
import { Ana3 } from './ana3';
import { Ana4 } from './ana4';
import { Ana5 } from './ana5';
import { Ana6 } from './ana6';
import { Ana7 } from './ana7';
import { Ana8 } from './ana8';
import { Ana9 } from './ana9';
import { Ch10Mod1 } from './ch10mod1';
import { Ch10Mod2 } from './ch10mod2';
import { Ch1Mod1 } from './ch1mod1';
import { Ch1Mod2 } from './ch1mod2';
import { Ch2Mod1 } from './ch2mod1';
import { Ch3Mod1 } from './ch3mod1';
import { Ch4Mod1 } from './ch4mod1';
import { Ch4Mod2 } from './ch4mod2';
import { Ch5Mod1 } from './ch5mod1';
import { Ch6Mod1 } from './ch6mod1';
import { Ch7Mod1 } from './ch7mod1';
import { Ch8Mod1 } from './ch8mod1';
import { Ch9Mod1 } from './ch9mod1';
import { Ch9Mod2 } from './ch9mod2';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana1'] = Ana1;
widgetRegistry['ana10'] = Ana10;
widgetRegistry['ana2'] = Ana2;
widgetRegistry['ana3'] = Ana3;
widgetRegistry['ana4'] = Ana4;
widgetRegistry['ana5'] = Ana5;
widgetRegistry['ana6'] = Ana6;
widgetRegistry['ana7'] = Ana7;
widgetRegistry['ana8'] = Ana8;
widgetRegistry['ana9'] = Ana9;
widgetRegistry['ch10mod1'] = Ch10Mod1;
widgetRegistry['ch10mod2'] = Ch10Mod2;
widgetRegistry['ch1mod1'] = Ch1Mod1;
widgetRegistry['ch1mod2'] = Ch1Mod2;
widgetRegistry['ch2mod1'] = Ch2Mod1;
widgetRegistry['ch3mod1'] = Ch3Mod1;
widgetRegistry['ch4mod1'] = Ch4Mod1;
widgetRegistry['ch4mod2'] = Ch4Mod2;
widgetRegistry['ch5mod1'] = Ch5Mod1;
widgetRegistry['ch6mod1'] = Ch6Mod1;
widgetRegistry['ch7mod1'] = Ch7Mod1;
widgetRegistry['ch8mod1'] = Ch8Mod1;
widgetRegistry['ch9mod1'] = Ch9Mod1;
widgetRegistry['ch9mod2'] = Ch9Mod2;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
