import React, { useState, useEffect, useCallback } from 'react';
import { tutorial } from './data/tutorial';
import { Hero } from './components/Hero';
import { ChapterBridge } from './components/ChapterBridge';
import { AnalogyCard } from './components/AnalogyCard';
import { Module } from './components/Module';
import { Formula } from './components/Formula';
import { InsightBar } from './components/InsightBar';
import { Takeaway } from './components/Takeaway';
import { BiliVideos } from './components/BiliVideos';
const shortTitles=['统一脑编码','三种模态对齐','长上下文为何重要','刺激与 BOLD 对时','缺失模态怎么办','适配不同大脑','训练与验证','完整模型之旅','在计算机里做实验','证据与能力边界'];
const groups=[{label:'01 / 理解任务',from:1,to:3},{label:'02 / 建立机制',from:4,to:6},{label:'03 / 串起全貌',from:7,to:8},{label:'04 / 阅读证据',from:9,to:10}];
export default function App(){
 const chapters=tutorial.chapters,total=chapters.length,bili=tutorial.bilibili||[],lastSlide=total+(bili.length?1:0);
 const readHash=()=>Math.max(0,Math.min(lastSlide,Number(location.hash.match(/(?:chapter-|page-)(\d+)/)?.[1]||0)));
 const [active,setActive]=useState(readHash),[sidebarOpen,setSidebarOpen]=useState(false),[sidebarCollapsed,setSidebarCollapsed]=useState(false);
 const [visited,setVisited]=useState<Set<number>>(()=>new Set([readHash()]));
 const goTo=useCallback((i:number)=>{const next=Math.max(0,Math.min(i,lastSlide));setActive(next);setSidebarOpen(false);history.pushState(null,'',next?'#chapter-'+next:location.pathname);},[lastSlide]);
 useEffect(()=>{const onHash=()=>{setActive(readHash());setSidebarOpen(false)};window.addEventListener('hashchange',onHash);window.addEventListener('popstate',onHash);return()=>{window.removeEventListener('hashchange',onHash);window.removeEventListener('popstate',onHash)}},[lastSlide]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});setVisited(prev=>new Set([...prev,active]));document.title=(active===0?'TRIBE v2':active<=total?shortTitles[active-1]:'延伸阅读')+' · 交互式论文笔记';},[active,total]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,select,button,a,[contenteditable="true"],[role="slider"]'))return;if(e.key==='ArrowRight'){e.preventDefault();goTo(active+1)}else if(e.key==='ArrowLeft'){e.preventDefault();goTo(active-1)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[active,goTo]);
 const chapter=active>=1&&active<=total?chapters[active-1]:null;
 const item=(i:number,label:string)=><button type="button" key={i} className={'slide-sidebar-item '+(active===i?'active':'')} aria-current={active===i?'page':undefined} onClick={()=>goTo(i)}><span className="slide-sidebar-num">{i?String(i).padStart(2,'0'):'↗'}</span><span className="slide-sidebar-text">{label}</span>{visited.has(i)&&i!==active&&<span className="visited-dot" aria-label="已浏览"/>}</button>;
 return <div className={'slide-layout '+(sidebarOpen?'sidebar-open ':'')+(sidebarCollapsed?'sidebar-collapsed':'')}><a className="skip-to-content" href="#lesson-content">跳到正文</a><button type="button" className="slide-sidebar-toggle" aria-expanded={sidebarOpen} aria-controls="lesson-sidebar" onClick={()=>setSidebarOpen(v=>!v)}>{sidebarOpen?'✕':'☰'} 目录</button>{sidebarOpen&&<div className="slide-sidebar-overlay" onClick={()=>setSidebarOpen(false)}/>}
 <aside className="slide-sidebar" id="lesson-sidebar"><button className="lesson-brand" type="button" onClick={()=>goTo(0)}><span className="brand-symbol">t.</span><span><strong>TRIBE <em>v2</em></strong><small>交互式论文笔记</small></span></button><div className="sidebar-caption">感官刺激 → 脑响应</div><nav className="slide-sidebar-nav" aria-label="教程章节">{item(0,'从这里开始')}{groups.map(group=><div className="sidebar-group" key={group.label}><div className="sidebar-group-label">{group.label}</div>{chapters.slice(group.from-1,group.to).map((_,idx)=>item(group.from+idx,shortTitles[group.from+idx-1]))}</div>)}{bili.length>0&&item(total+1,'延伸视频')}</nav><div className="sidebar-bottom"><span>已浏览 {visited.size} / {lastSlide+1}</span><div className="sidebar-progress"><i style={{width:visited.size/(lastSlide+1)*100+'%'}}/></div><a href="https://arxiv.org/abs/2605.04326" target="_blank" rel="noreferrer">阅读原论文 ↗</a></div></aside>
 <button type="button" className="slide-sidebar-collapse" aria-label={sidebarCollapsed?'展开目录':'折叠目录'} onClick={()=>setSidebarCollapsed(v=>!v)}>{sidebarCollapsed?'☰':'‹'}</button>
 <main className="slide-main" id="lesson-content"><div className="lesson-topline"><span>TRIBE v2 <b>/</b> {active===0?'导读':active<=total?shortTitles[active-1]:'延伸视频'}</span><span>交互探索 · {String(active+1).padStart(2,'0')} / {lastSlide+1}</span></div><div className="slide-content" key={active}>{active===0?<Hero meta={tutorial.meta} hero={tutorial.hero}/>:chapter?<section className="chap slide-chap" aria-labelledby="chapter-title"><div className="chapter-kicker">CHAPTER {String(active).padStart(2,'0')}<span>{chapter.badgeLabel}</span></div><h2 className="chap-title" id="chapter-title">{chapter.title}</h2><ChapterBridge text={chapter.bridge}/><AnalogyCard analogy={chapter.analogy} chapterId={chapter.id}/>{chapter.modules.map(m=><Module key={m.id} module={m} chapterId={chapter.id}/>)}{chapter.insight&&<InsightBar text={chapter.insight}/ >}{chapter.formula&&<Formula formula={chapter.formula}/>}<Takeaway items={chapter.takeaways}/></section>:<BiliVideos items={bili}/>}</div><div className="slide-nav"><button type="button" className="slide-nav-btn" onClick={()=>goTo(active-1)} disabled={active===0}>← 上一章</button><span className="slide-nav-counter">{active===0?'从问题开始':active===lastSlide?'回顾与延伸':shortTitles[active-1]}</span><button type="button" className="slide-nav-btn slide-nav-btn-primary" onClick={()=>goTo(active+1)} disabled={active===lastSlide}>{active===0?'开始探索':'下一章'} →</button></div></main></div>;
}
