import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { M1Demo } from './m1-demo';
import { M1Problems } from './m1-problems';
import { M1Repair } from './m1-repair';
import { M10Race } from './m10-race';
import { M2Album } from './m2-album';
import { M2Extract } from './m2-extract';
import { M3Cache } from './m3-cache';
import { M4Blocks } from './m4-blocks';
import { M5Steer } from './m5-steer';
import { M6Rope } from './m6-rope';
import { M7Lambda } from './m7-lambda';
import { M7Teachers } from './m7-teachers';
import { M8Arch } from './m8-arch';
import { M9Backprop } from './m9-backprop';
import { SceneKitBadge } from './scene-kit';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['m1-demo'] = M1Demo;
widgetRegistry['m1-problems'] = M1Problems;
widgetRegistry['m1-repair'] = M1Repair;
widgetRegistry['m10-race'] = M10Race;
widgetRegistry['m2-album'] = M2Album;
widgetRegistry['m2-extract'] = M2Extract;
widgetRegistry['m3-cache'] = M3Cache;
widgetRegistry['m4-blocks'] = M4Blocks;
widgetRegistry['m5-steer'] = M5Steer;
widgetRegistry['m6-rope'] = M6Rope;
widgetRegistry['m7-lambda'] = M7Lambda;
widgetRegistry['m7-teachers'] = M7Teachers;
widgetRegistry['m8-arch'] = M8Arch;
widgetRegistry['m9-backprop'] = M9Backprop;
widgetRegistry['scene-kit'] = SceneKitBadge;
