import React,{useEffect,useRef,useState}from'react';
import{setupCanvas}from'../lib/canvasKit';
import type{WidgetProps}from'./registry';
const W=560,H=260,C={bg:'#f5f8f0',paper:'#fff',ink:'#21324a',muted:'#68778f',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#d97706',purple:'#7c3aed',line:'#d7deea'};
const S:React.CSSProperties={display:'flex',gap:8,flexWrap:'wrap',alignItems:'center',margin:'10px 0'};
const chip=(on:boolean):React.CSSProperties=>({padding:'7px 11px',borderRadius:18,border:`1px solid ${on?C.blue:C.line}`,background:on?C.blue:'#fff',color:on?'#fff':C.ink,fontWeight:700,cursor:'pointer'});
function txt(c:CanvasRenderingContext2D,s:string,x:number,y:number,col=C.ink,size=11,w=600){c.fillStyle=col;c.font=`${w} ${size}px "Microsoft YaHei",sans-serif`;c.fillText(s,x,y)}
function box(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,col=C.line,fill=C.paper){c.fillStyle=fill;c.strokeStyle=col;c.lineWidth=1.4;c.beginPath();c.roundRect(x,y,w,h,7);c.fill();c.stroke()}
function bar(c:CanvasRenderingContext2D,label:string,v:number,max:number,y:number,col:string,note=''){txt(c,label,24,y+14,C.ink,10,650);c.fillStyle='#e9eee8';c.fillRect(135,y,330,18);c.fillStyle=col;c.fillRect(135,y,330*Math.max(0,v/max),18);txt(c,String(v),475,y+14,col,11,800);if(note)txt(c,note,135,y+34,C.muted,9,550)}
function draw(c:CanvasRenderingContext2D,id:string,mode:string,value:number,toggle:boolean,step:number,started:boolean,counts:{s:number,f:number},expanded:boolean){
 c.clearRect(0,0,W,H);c.fillStyle=C.bg;c.fillRect(0,0,W,H);txt(c,`交互模块 ${id}`,18,22,C.muted,10,700);
 if(id==='1.1'){const data:any={real:['真实机器人轨迹','真实交互','采集成本高；失败与纠错难安全覆盖',C.red],physics:['物理模拟器','精确动作控制','资产构建与标定；外观/感知/动力学差距',C.orange],video:['通用视频模型','强视觉先验','缺少逐帧机器人动作控制接口',C.red]};['real','physics','video'].forEach((k,i)=>{const d=data[k],on=k===mode;box(c,18+i*178,40,166,60,on?d[3]:C.line,on?'#fff6ee':C.paper);txt(c,d[0],30+i*178,63,C.ink,11,750);txt(c,on&&expanded?d[2]:d[1],30+i*178,84,on?d[3]:C.muted,9,650)});const rows=[['真实轨迹','需重采','强','高'],['物理模拟器','✅','有限','高'],['通用视频','❌','强','中'],['BWM','✅','强','较低*']];txt(c,'来源',26,126,C.muted,9,700);txt(c,'候选动作响应',160,126,C.muted,9,700);txt(c,'视觉先验',315,126,C.muted,9,700);txt(c,'前期构建',430,126,C.muted,9,700);rows.forEach((r,i)=>{const y=136+i*23;box(c,18,y,522,20,i===3?C.green:C.line,i===3?'#e8f4ee':C.paper);txt(c,r[0],28,y+14,i===3?C.green:C.ink,9,i===3?800:650);txt(c,r[1],190,y+14,r[1]==='❌'?C.red:r[1]==='✅'?C.green:C.orange,9,700);txt(c,r[2],337,y+14,C.ink,9,650);txt(c,r[3],456,y+14,i===3?C.green:C.ink,9,650)});txt(c,'* 相对重新采集或重建资产；不是论文给出的训练成本测量',22,248,C.muted,8,550)}
 else if(id==='1.2'){txt(c,'同一动作指令',22,47,C.orange,11,750);['物理模拟器','通用视频模型','BWM'].forEach((n,i)=>{const y=72+i*55;txt(c,n,24,y+22,C.ink,10,700);c.strokeStyle=C.line;c.beginPath();c.moveTo(140,y+18);c.lineTo(500,y+18);c.stroke();let px=320+(i===1?18:value*14);c.fillStyle=i===2?C.green:i===1?C.red:C.orange;c.beginPath();c.arc(px,y+18,9,0,Math.PI*2);c.fill();txt(c,i===0?'响应动作，但视觉/动力学存在迁移边界':i===1?'画面变化与动作脱钩':'响应动作并保持真实视觉先验',140,y+43,i===2?C.green:i===1?C.red:C.orange,9,650)})}
 else if(id==='2.1'){const names=['不响应动作','响应但丢失状态','BWM'];names.forEach((n,i)=>{const x=18+i*178;box(c,x,55,166,145,i===2&&started?C.green:i<2&&started?C.red:C.line);txt(c,n,x+14,79,C.ink,11,750);const px=x+45+(started?(i===0?35:76):0);c.fillStyle=started&&i===1?C.purple:i===2?C.green:C.blue;c.fillRect(px,112,28,28);txt(c,started?(i===0?'变化与动作无关':i===1?'位置对，身份漂移':'动作与状态都保持'):'共同起点',x+14,177,started&&i<2?C.red:i===2?C.green:C.muted,9,650)})}
 else if(id==='3.1'){txt(c,`偏移：${value>0?'+':''}${value} 帧`,22,48,value===0?C.green:C.red,13,800);for(let i=0;i<7;i++){const x=58+i*70;box(c,x,70,42,38,C.blue,'#eef3f8');txt(c,`x${i}`,x+13,94,C.blue,10,700);box(c,x+value*12,155,42,26,value===0?C.green:C.orange,value===0?'#e6f3ed':'#fff2df');txt(c,`a${i}`,x+value*12+13,173,value===0?C.green:C.orange,9,700);c.strokeStyle=value===0?C.green:C.red;c.beginPath();c.moveTo(x+21,108);c.lineTo(x+value*12+21,155);c.stroke()}txt(c,'不变量：动作时间轴不变',176,226,C.blue,11,800);txt(c,'轨迹精度变化：示意，非论文实测',176,244,C.muted,9,550)}
 else if(id==='4.1'){const names=['Trajectory Replay','Overlapping Clip Sampling','Initial-Observation Enhancement'];names.forEach((n,i)=>{const x=18+i*178;box(c,x,50,166,52,i===step?C.blue:C.line,i===step?'#eaf0f7':C.paper);txt(c,n,x+10,78,i===step?C.blue:C.muted,9,700)});for(let i=0;i<9;i++){c.fillStyle=i===0&&step===2?C.green:i>=2&&i<=5&&step===1?C.orange:'#dfe6df';c.fillRect(31+i*54,132,42,32);txt(c,`a${i}`,41+i*54,190,C.orange,8,650)}c.strokeStyle=C.orange;c.beginPath();c.moveTo(26,201);c.lineTo(526,201);c.stroke();txt(c,'🔒 动作时间轴不变',190,226,C.blue,10,800);txt(c,!toggle&&step===0?'不可回放：Trajectory Replay已禁用':mode==='seed'?'SeedVR-2只恢复推理起始的初始环境观察':names[step],24,248,!toggle&&step===0?C.red:C.muted,9,650)}
 else if(id==='5.1'){const ns=['归一化','Action Encoder','Cross-Attention','AdaLN','去噪块'];ns.forEach((n,i)=>{const x=14+i*108;box(c,x,82,98,46,mode===String(i)?(i===3?C.purple:C.blue):C.line);txt(c,n,x+8,109,mode===String(i)?C.blue:C.muted,9,700);if(i<4){c.strokeStyle=C.line;c.beginPath();c.moveTo(x+98,105);c.lineTo(x+108,105);c.stroke()}});txt(c,'逐动作 token → Cross-Attention（帧级）',82,170,C.blue,11,700);txt(c,'P=3 边界动作；G=4 分组 → AdaLN（latent时间尺度）',82,197,C.purple,11,700);txt(c,'报告配置：dₐ=14',82,224,C.orange,10,750)}
 else if(id==='5.2'){const d:any={adaln:[61.12,49.16],cross:[59.54,43.42],both:[63.51,64.36]},v=d[mode]||d.both;bar(c,'EWMScore ↑',v[0],70,73,mode==='both'?C.green:C.orange,'论文·Table 9');bar(c,'TrajA ↑',v[1],70,145,mode==='both'?C.green:C.orange,'论文·Table 10')}
 else if(id==='6.1'){const tau=value/100;[['x₀ 干净',18,0],['历史 低噪',196,.16],['未来 z̃τ',374,tau]].forEach((q:any)=>{box(c,q[1],64,160,125,mode===q[0]?C.blue:C.line);for(let y=0;y<7;y++)for(let x=0;x<9;x++){const a=q[2]*(((x*7+y*11)%10)/10);c.fillStyle=`rgba(33,50,74,${a})`;c.fillRect(q[1]+12+x*15,95+y*11,8,8)}txt(c,q[0],q[1]+15,84,C.ink,11,750)});c.strokeStyle=C.red;c.lineWidth=3;c.beginPath();c.moveTo(382,205);c.lineTo(526,205);c.stroke();txt(c,'future-only loss',408,225,C.red,10,800);txt(c,'训练与推理使用相同的历史扰动',151,248,C.blue,10,750)}
 else if(id==='7.1'){txt(c,`rollout：${value} 块 × K=72帧`,22,43,C.blue,11,800);for(let i=0;i<Math.min(value,8);i++){c.fillStyle=i===value-1?C.green:'#dce7df';c.fillRect(30+i*62,63,48,25)}c.strokeStyle=C.red;c.beginPath();for(let i=0;i<value;i++){const x=36+i*62,y=208-(toggle?i*10:i*20)-(mode==='4'?Math.sin(i*2)*14:0);i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();txt(c,'误差累积曲线：示意，非论文实测',22,239,C.muted,9,650);const d:any={'4':[55.49,41.43],'8':[63.51,64.36],'16':[63.02,56.89]},v=d[mode]||d['8'];txt(c,`Tables 9–10：EWMScore ${v[0]} / TrajA ${v[1]}`,260,239,C.blue,9,700)}
 else if(id==='8.1'){const physical=mode==='physical';bar(c,physical?'仅真实':'真实数据',physical?50.67:71.50,100,65,C.blue,physical?'论文·Table 7':'论文·Table 3');bar(c,'BWM',physical?71:94.5,100,125,C.green,physical?'实体六任务':'WorldArena两任务');txt(c,['初始帧 + 动作序列','BWM自回归生成','观测—动作配对轨迹','用于模仿学习训练'][step%4],170,217,step?C.green:C.blue,12,800)}
 else if(id==='9.1'){const ns=['策略','动作','BWM预测','新观测'];ns.forEach((n,i)=>{const x=24+i*126;box(c,x,80,104,50,i===step?C.blue:C.line,i===step?'#eaf0f7':C.paper);txt(c,n,x+22,109,i===step?C.blue:C.muted,11,750);if(i<3)txt(c,'→',x+109,109,C.muted,14,700)});txt(c,`成功 ${counts.s}  /  失败 ${counts.f}`,205,174,counts.f?C.orange:C.green,13,800);txt(c,step===3?'完成一圈后可记录结果':'逐步推进闭环；不能跳过观测反馈',155,214,C.muted,10,650)}
 else if(id==='9.2'){const success=mode!=='all',hard=[64,56,52,32,64,36],pred=success?[100,80,64,96,100,84]:[88,80,44,36,80,24];for(let i=0;i<6;i++){const x=38+i*82;c.fillStyle=C.blue;c.fillRect(x,205-hard[i]*1.25,22,hard[i]*1.25);c.fillStyle=success?C.orange:C.green;c.fillRect(x+26,205-pred[i]*1.25,22,pred[i]*1.25);txt(c,String(i+1),x+17,225,C.muted,9,650);if(Math.abs(pred[i]-hard[i])>=30)txt(c,'⚠',x+26,64,C.red,12,800)}txt(c,success?'MAE 36.67 · r=0.158':'MAE 14.67 · r=0.908',190,246,success?C.red:C.green,12,800)}
 else if(id==='10.1'){const vals=[63.51,94.5,97.8,71,90.8],labs=['EWM','DE仿真','PE仿真r','DE实体','PE实体r'];const detail:any={ewm:'EWMScore 63.51 · Tables 1–2',deSim:'DE仿真 94.50% · Table 3',peSim:'PE仿真 r=0.978 · Table 4',deReal:'DE实体 71.00% · Table 7',peReal:'PE实体 r=0.908 · Table 8'};const cx=280,cy=132,R=76;c.strokeStyle=C.line;for(let k=1;k<=4;k++){c.beginPath();for(let i=0;i<5;i++){const a=-Math.PI/2+i*Math.PI*2/5,x=cx+Math.cos(a)*R*k/4,y=cy+Math.sin(a)*R*k/4;i?c.lineTo(x,y):c.moveTo(x,y)}c.closePath();c.stroke()}if(started){c.fillStyle='rgba(34,141,92,.2)';c.strokeStyle=C.green;c.beginPath();vals.forEach((v,i)=>{const a=-Math.PI/2+i*Math.PI*2/5,x=cx+Math.cos(a)*R*v/100,y=cy+Math.sin(a)*R*v/100;i?c.lineTo(x,y):c.moveTo(x,y)});c.closePath();c.fill();c.stroke()}labs.forEach((l,i)=>{const a=-Math.PI/2+i*Math.PI*2/5;txt(c,l,cx+Math.cos(a)*104-20,cy+Math.sin(a)*96,C.ink,9,650)});txt(c,started?detail[mode]:'点击“开始比较”显示证据',180,229,started?C.green:C.muted,10,750);txt(c,'不同协议并列展示，不计算新综合分',174,250,C.muted,9,650)}
 else if(id==='10.2'){const items=[['模型定义','已可用',C.green],['模型权重','已可用',C.green],['推理示例','已可用',C.green],['训练脚本','仓库存在，但README未宣称完整发布',C.orange],['数据构造','未提供一键完整流程',C.red],['功能接口','论文描述；仓库未提供完整端到端复现',C.orange]];(expanded?items:items.slice(0,3)).forEach((r,i)=>{box(c,24,45+i*32,512,25,r[2]);txt(c,r[0],36,62,C.ink,10,750);txt(c,r[1],160,62,r[2],9,650)});txt(c,'开源状态：commit 44acfd1b…',24,244,C.blue,9,750)}
}
function feedback(id:string,mode:string,value:number,toggle:boolean,step:number,started:boolean,expanded:boolean){if(id==='1.1')return mode==='real'?'真实轨迹最贴近部署分布，但采集成本与安全约束高。':mode==='physics'?'物理模拟器可控，但资产、标定和Sim-to-Real差距仍在。':'视觉逼真不等于能按逐帧机器人动作改变状态。';if(id==='1.2')return'同一动作下，响应性、视觉先验和构建边界必须分开判断。';if(id==='2.1')return started?'只有BWM示意同时保持动作响应和场景身份。':'从相同初始状态执行一次动作。';if(id==='3.1')return value===0?'✅ 动作与观测共享时间索引。':`❌ 偏移${value}帧：动作被归因给错误画面。`;if(id==='4.1')return!toggle&&step===0?'Trajectory Replay需要可回放模拟器；当前不可用。':'三项处理都锁住动作时间轴。';if(id==='5.2')return mode==='both'?'结合两条路径在Tables 9–10中为63.51/64.36。':'单路径结果较低，但只在该消融协议下成立。';if(id==='6.1')return'x₀始终干净、历史低噪、未来随τ变化；损失只覆盖未来。';if(id==='7.1')return toggle?'初始锚点帮助保持场景身份；曲线仅为机制示意。':'关闭锚点后漂移示意更快，不代表论文实测曲线。';if(id==='8.1')return mode==='physical'?'实体六任务：BWM增强71.00%，仅真实50.67%。':'WorldArena两任务：BWM 94.50%，真实数据71.50%。';if(id==='9.2')return mode==='all'?'加入失败后，实体评估MAE降至14.67、r升至0.908。':'只看成功会高估能力：MAE36.67、r仅0.158。';if(id==='10.1')return started?'Track1总体第二/开源第一；Track2 DE开源第一、PE开源第二。':'开始后查看五项原始证据。';if(id==='10.2')return expanded?'脚本存在不等于完整训练、数据与功能实验可一键复现。':'当前明确可用：模型定义、权重和推理。';return'操作控件，画面、数值和判断会同步更新。'}
export const BwmInteractive:React.FC<WidgetProps>=({moduleId})=>{const ref=useRef<HTMLCanvasElement>(null);const[mode,setMode]=useState(moduleId==='5.1'?'0':moduleId==='5.2'?'both':moduleId==='6.1'?'x₀ 干净':moduleId==='7.1'?'8':moduleId==='9.2'?'success':moduleId==='10.1'?'ewm':'real');const[value,setValue]=useState(moduleId==='6.1'?55:moduleId==='7.1'?4:moduleId==='3.1'?2:0);const[toggle,setToggle]=useState(true);const[step,setStep]=useState(0);const[started,setStarted]=useState(false);const[counts,setCounts]=useState({s:0,f:0});const[expanded,setExpanded]=useState(false);
useEffect(()=>{const el=ref.current;if(!el)return;let c:CanvasRenderingContext2D;try{c=setupCanvas(el,W,H)}catch{return}draw(c,moduleId,mode,value,toggle,step,started,counts,expanded);el.classList.add('is-ready')},[moduleId,mode,value,toggle,step,started,counts,expanded]);
const modes=(xs:[string,string][])=>xs.map(([v,l])=><button key={v} style={chip(mode===v)} onClick={()=>{if(moduleId==='1.1'&&mode===v)setExpanded(e=>!e);else setMode(v)}}>{l}</button>);
let controls:React.ReactNode=null;
if(moduleId==='1.1')controls=modes([['real','真实数据'],['physics','物理模拟器'],['video','视频模型']]);
else if(moduleId==='1.2')controls=<><label>动作指令：{value}</label><input type="range" min="-10" max="10" value={value} onChange={e=>setValue(+e.target.value)}/></>;
else if(moduleId==='2.1')controls=<button style={chip(started)} onClick={()=>setStarted(true)}>执行动作</button>;
else if(moduleId==='3.1')controls=<><label>动作偏移：{value}帧</label><input type="range" min="-3" max="3" step="1" value={value} onChange={e=>setValue(+e.target.value)}/></>;
else if(moduleId==='4.1')controls=<><button style={chip(false)} disabled={step===0||(!toggle&&step===1)} onClick={()=>setStep(s=>Math.max(toggle?0:1,s-1))}>上一步</button><button style={chip(false)} onClick={()=>setStep(s=>Math.min(2,s+1))}>下一步</button><button style={chip(toggle)} onClick={()=>{setToggle(v=>!v);if(toggle&&step===0)setStep(1)}}>可回放模拟器：{toggle?'开':'关'}</button><button style={chip(mode==='seed')} onClick={()=>setMode('seed')}>SeedVR-2</button></>;
else if(moduleId==='5.1')controls=modes([['0','归一化'],['1','Action Encoder'],['2','Cross-Attention'],['3','AdaLN'],['4','去噪块']]);
else if(moduleId==='5.2')controls=modes([['adaln','仅AdaLN'],['cross','仅Cross-Attention'],['both','两者结合']]);
else if(moduleId==='6.1')controls=<><label>τ：{(value/100).toFixed(2)}</label><input type="range" min="0" max="100" value={value} onChange={e=>setValue(+e.target.value)}/>{modes([['x₀ 干净','x₀'],['历史 低噪','历史'],['未来 z̃τ','未来']])}</>;
else if(moduleId==='7.1')controls=<><label>rollout块数：{value}</label><input type="range" min="1" max="8" value={value} onChange={e=>setValue(+e.target.value)}/><button style={chip(toggle)} onClick={()=>setToggle(v=>!v)}>初始环境锚点：{toggle?'开':'关'}</button>{modes([['4','4帧'],['8','8帧'],['16','16帧']])}</>;
else if(moduleId==='8.1')controls=<>{modes([['real','模拟环境'],['physical','实物机器人']])}<button style={chip(step>0)} onClick={()=>setStep(s=>(s+1)%4)}>推进生成过程</button></>;
else if(moduleId==='9.1')controls=<><button style={chip(false)} onClick={()=>setStep(s=>(s+1)%4)}>下一步</button><button disabled={step!==3} style={chip(false)} onClick={()=>setCounts(c=>({...c,s:c.s+1}))}>记录成功</button><button disabled={step!==3} style={chip(false)} onClick={()=>setCounts(c=>({...c,f:c.f+1}))}>记录失败</button></>;
else if(moduleId==='9.2')controls=modes([['success','只看成功'],['all','成功 + 失败']]);
else if(moduleId==='10.1')controls=<><button style={chip(started)} onClick={()=>setStarted(true)}>开始比较</button>{modes([['ewm','EWMScore'],['deSim','DE仿真'],['peSim','PE仿真r'],['deReal','DE实体'],['peReal','PE实体r']])}</>;
else if(moduleId==='10.2')controls=<><button style={chip(expanded)} onClick={()=>setExpanded(e=>!e)}>{expanded?'收起':'展开更多'}</button><a href="https://github.com/boundless-large-model/boundless-world-model#%EF%B8%8F-usage" target="_blank" rel="noreferrer" style={chip(true)}>快速上手</a></>;
return <div><canvas ref={ref} width={W} height={H} aria-label={`BWM交互模块${moduleId}`}/><div style={S}>{controls}</div><div className="feedback" style={{borderLeftColor:feedback(moduleId,mode,value,toggle,step,started,expanded).includes('❌')?C.red:C.green}}>{feedback(moduleId,mode,value,toggle,step,started,expanded)}</div></div>};
export default BwmInteractive;
