import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana-1';
import { Ana10 } from './ana-10';
import { Ana11 } from './ana-11';
import { Ana2 } from './ana-2';
import { Ana3 } from './ana-3';
import { Ana4 } from './ana-4';
import { Ana5 } from './ana-5';
import { Ana6 } from './ana-6';
import { Ana7 } from './ana-7';
import { Ana8 } from './ana-8';
import { Ana9 } from './ana-9';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { HeroTarget } from './hero-target';
import { M111 } from './m-1-1';
import { M1011 } from './m-10-1';
import { M211 } from './m-2-1';
import { M311 } from './m-3-1';
import { M411 } from './m-4-1';
import { M511 } from './m-5-1';
import { M611 } from './m-6-1';
import { M621 } from './m-6-2';
import { M711 } from './m-7-1';
import { M811 } from './m-8-1';
import { M911 } from './m-9-1';
import { M921 } from './m-9-2';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana-1'] = Ana1;
widgetRegistry['ana-10'] = Ana10;
widgetRegistry['ana-11'] = Ana11;
widgetRegistry['ana-2'] = Ana2;
widgetRegistry['ana-3'] = Ana3;
widgetRegistry['ana-4'] = Ana4;
widgetRegistry['ana-5'] = Ana5;
widgetRegistry['ana-6'] = Ana6;
widgetRegistry['ana-7'] = Ana7;
widgetRegistry['ana-8'] = Ana8;
widgetRegistry['ana-9'] = Ana9;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['hero-target'] = HeroTarget;
widgetRegistry['m-1-1'] = M111;
widgetRegistry['m-10-1'] = M1011;
widgetRegistry['m-2-1'] = M211;
widgetRegistry['m-3-1'] = M311;
widgetRegistry['m-4-1'] = M411;
widgetRegistry['m-5-1'] = M511;
widgetRegistry['m-6-1'] = M611;
widgetRegistry['m-6-2'] = M621;
widgetRegistry['m-7-1'] = M711;
widgetRegistry['m-8-1'] = M811;
widgetRegistry['m-9-1'] = M911;
widgetRegistry['m-9-2'] = M921;
