import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { HeroOld } from './heroold';
import { HeroNew } from './heronew';
import { AnaCh1 } from './anach1';
import { AnaCh2 } from './anach2';
import { AnaCh3 } from './anach3';
import { AnaCh4 } from './anach4';
import { AnaCh5 } from './anach5';
import { AnaCh6 } from './anach6';
import { AnaCh7 } from './anach7';
import { AnaCh8 } from './anach8';
import { AnaCh9 } from './anach9';
import { AnaCh10 } from './anach10';
import { Ch1Mod1 } from './ch1mod1';
import { Ch1Mod2 } from './ch1mod2';
import { Ch2Mod1 } from './ch2mod1';
import { Ch3Mod1 } from './ch3mod1';
import { Ch4Mod1 } from './ch4mod1';
import { Ch5Mod1 } from './ch5mod1';
import { Ch6Eq1, Ch6Eq2, Ch6Eq3 } from './ch6mod1';
import { Ch6Mod2 } from './ch6mod2';
import { Ch7Mod1 } from './ch7mod1';
import { Ch7Mod2 } from './ch7mod2';
import { Ch8Mod1 } from './ch8mod1';
import { Ch8Mod2 } from './ch8mod2';
import { Ch9Mod1 } from './ch9mod1';
import { Ch10Mod1 } from './ch10mod1';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};

widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['ana-ch1'] = AnaCh1;
widgetRegistry['ana-ch2'] = AnaCh2;
widgetRegistry['ana-ch3'] = AnaCh3;
widgetRegistry['ana-ch4'] = AnaCh4;
widgetRegistry['ana-ch5'] = AnaCh5;
widgetRegistry['ana-ch6'] = AnaCh6;
widgetRegistry['ana-ch7'] = AnaCh7;
widgetRegistry['ana-ch8'] = AnaCh8;
widgetRegistry['ana-ch9'] = AnaCh9;
widgetRegistry['ana-ch10'] = AnaCh10;
widgetRegistry['ch1-desiderata'] = Ch1Mod1;
widgetRegistry['ch1-gap'] = Ch1Mod2;
widgetRegistry['ch2-blackbox'] = Ch2Mod1;
widgetRegistry['ch3-insight'] = Ch3Mod1;
widgetRegistry['ch4-dpo'] = Ch4Mod1;
widgetRegistry['ch5-condition'] = Ch5Mod1;
widgetRegistry['ch6-unmask'] = Ch6Eq1;
widgetRegistry['ch6-iho'] = Ch6Eq1;
widgetRegistry['ch6-eq1'] = Ch6Eq1;
widgetRegistry['ch6-eq2'] = Ch6Eq2;
widgetRegistry['ch6-eq3'] = Ch6Eq3;
widgetRegistry['ch6-evus'] = Ch6Mod2;
widgetRegistry['ch7-cycles'] = Ch7Mod1;
widgetRegistry['ch7-pipe'] = Ch7Mod1;
widgetRegistry['ch7-algo'] = Ch7Mod2;
widgetRegistry['ch8-arch'] = Ch8Mod1;
widgetRegistry['ch8-setup'] = Ch8Mod1;
widgetRegistry['ch8-results'] = Ch8Mod2;
widgetRegistry['ch9-evus'] = Ch9Mod1;
widgetRegistry['ch10-results'] = Ch10Mod1;
