import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ch1Access } from './ch1-access';
import { Ch1Trio } from './ch1-trio';
import { Ch1Analogy } from './ch1-analogy';
import { Ch10Analogy } from './ch10-analogy';
import { Ch10Demos } from './ch10-demos';
import { Ch10Evidence } from './ch10-evidence';
import { Ch2Analogy } from './ch2-analogy';
import { Ch2Eyes } from './ch2-eyes';
import { Ch2Project } from './ch2-project';
import { Ch3Analogy } from './ch3-analogy';
import { Ch3Vocab } from './ch3-vocab';
import { Ch4Analogy } from './ch4-analogy';
import { Ch4Quantile } from './ch4-quantile';
import { Ch5Analogy } from './ch5-analogy';
import { Ch5Mixer } from './ch5-mixer';
import { Ch6Analogy } from './ch6-analogy';
import { Ch6Decisions } from './ch6-decisions';
import { Ch7Analogy } from './ch7-analogy';
import { Ch7Lora } from './ch7-lora';
import { Ch8Analogy } from './ch8-analogy';
import { Ch8Arch } from './ch8-arch';
import { Ch8Deploy } from './ch8-deploy';
import { Ch9Analogy } from './ch9-analogy';
import { Ch9Battlefield } from './ch9-battlefield';
import { Ch9Grounding } from './ch9-grounding';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ch1-access'] = Ch1Access;
widgetRegistry['ch1-trio'] = Ch1Trio;
widgetRegistry['ch1-analogy'] = Ch1Analogy;
widgetRegistry['ch10-analogy'] = Ch10Analogy;
widgetRegistry['ch10-demos'] = Ch10Demos;
widgetRegistry['ch10-evidence'] = Ch10Evidence;
widgetRegistry['ch2-analogy'] = Ch2Analogy;
widgetRegistry['ch2-eyes'] = Ch2Eyes;
widgetRegistry['ch2-project'] = Ch2Project;
widgetRegistry['ch3-analogy'] = Ch3Analogy;
widgetRegistry['ch3-vocab'] = Ch3Vocab;
widgetRegistry['ch4-analogy'] = Ch4Analogy;
widgetRegistry['ch4-quantile'] = Ch4Quantile;
widgetRegistry['ch5-analogy'] = Ch5Analogy;
widgetRegistry['ch5-mixer'] = Ch5Mixer;
widgetRegistry['ch6-analogy'] = Ch6Analogy;
widgetRegistry['ch6-decisions'] = Ch6Decisions;
widgetRegistry['ch7-analogy'] = Ch7Analogy;
widgetRegistry['ch7-lora'] = Ch7Lora;
widgetRegistry['ch8-analogy'] = Ch8Analogy;
widgetRegistry['ch8-arch'] = Ch8Arch;
widgetRegistry['ch8-deploy'] = Ch8Deploy;
widgetRegistry['ch9-analogy'] = Ch9Analogy;
widgetRegistry['ch9-battlefield'] = Ch9Battlefield;
widgetRegistry['ch9-grounding'] = Ch9Grounding;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
