import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { ArchitectureMap } from './architecture-map';
import { AsymmetrySwitch } from './asymmetry-switch';
import { CalibrationExplorer } from './calibration-explorer';
import { ControlVariateLab } from './control-variate-lab';
import { DarkroomAnalogy } from './darkroom-analogy';
import { DarkroomCoreWidget } from './darkroom-core';
import { EvidenceRace } from './evidence-race';
import { FlowTimeExplorer } from './flow-time-explorer';
import { HeroDarkroom } from './hero-darkroom';
import { LatentLiftComparator } from './latent-lift-comparator';
import { LossAblationExplorer } from './loss-ablation-explorer';
import { NoiseLoadLab } from './noise-load-lab';
import { RankSpectrumExplorer } from './rank-spectrum-explorer';
import { VelocityRecoveryStepper } from './velocity-recovery-stepper';
import { LandingKnowledgePreview } from './landing-knowledge-preview';
import { LatentPixelExplorer } from './latent-pixel-explorer';
import { VelocityTargetExplorer } from './velocity-target-explorer';
import { NoiseThroughNetwork } from './noise-through-network';
import { PixelTradeoffExplorer } from './pixel-tradeoff-explorer';
import { AsymflowOverview } from './asymflow-overview';
import { FlowProjectionTools } from './flow-projection-tools';
import { AsymflowRankLab } from './asymflow-rank-lab';
import { SpatialDecompositionLab } from './spatial-decomposition-lab';
import { VelocityRecoveryPath } from './velocity-recovery-path';
import { LatentPixelAlignment } from './latent-pixel-alignment';
import { TrajectoryCouplingLab } from './trajectory-coupling-lab';
import { FinetuningCorrectionLab } from './finetuning-correction-lab';
import { RankEvidenceWorkspace } from './rank-evidence-workspace';
import { FinetuningAblationEvidence } from './finetuning-ablation-evidence';
import { FinalPerformanceEvidence } from './final-performance-evidence';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['architecture-map'] = ArchitectureMap;
widgetRegistry['asymmetry-switch'] = AsymmetrySwitch;
widgetRegistry['calibration-explorer'] = CalibrationExplorer;
widgetRegistry['control-variate-lab'] = ControlVariateLab;
widgetRegistry['darkroom-analogy'] = DarkroomAnalogy;
widgetRegistry['darkroom-core'] = DarkroomCoreWidget;
widgetRegistry['evidence-race'] = EvidenceRace;
widgetRegistry['flow-time-explorer'] = FlowTimeExplorer;
widgetRegistry['hero-darkroom'] = HeroDarkroom;
widgetRegistry['latent-lift-comparator'] = LatentLiftComparator;
widgetRegistry['loss-ablation-explorer'] = LossAblationExplorer;
widgetRegistry['noise-load-lab'] = NoiseLoadLab;
widgetRegistry['rank-spectrum-explorer'] = RankSpectrumExplorer;
widgetRegistry['velocity-recovery-stepper'] = VelocityRecoveryStepper;
widgetRegistry['landing-knowledge-preview'] = LandingKnowledgePreview;
widgetRegistry['latent-pixel-explorer'] = LatentPixelExplorer;
widgetRegistry['velocity-target-explorer'] = VelocityTargetExplorer;
widgetRegistry['noise-through-network'] = NoiseThroughNetwork;
widgetRegistry['pixel-tradeoff-explorer'] = PixelTradeoffExplorer;
widgetRegistry['asymflow-overview'] = AsymflowOverview;
widgetRegistry['flow-projection-tools'] = FlowProjectionTools;
widgetRegistry['asymflow-rank-lab'] = AsymflowRankLab;
widgetRegistry['spatial-decomposition-lab'] = SpatialDecompositionLab;
widgetRegistry['velocity-recovery-path'] = VelocityRecoveryPath;
widgetRegistry['latent-pixel-alignment'] = LatentPixelAlignment;
widgetRegistry['trajectory-coupling-lab'] = TrajectoryCouplingLab;
widgetRegistry['finetuning-correction-lab'] = FinetuningCorrectionLab;
widgetRegistry['rank-evidence-workspace'] = RankEvidenceWorkspace;
widgetRegistry['finetuning-ablation-evidence'] = FinetuningAblationEvidence;
widgetRegistry['final-performance-evidence'] = FinalPerformanceEvidence;
