import { useEffect, useRef, useState, type PointerEvent } from 'react';
import { CanvasView, Controls, Feedback, Metric, palette as p, page, line, label, bar, stamp } from './proofKit';

const source='https://arxiv.org/pdf/2604.06240';
const buttonStyle={minHeight:44,padding:'8px 14px'};
function Choices({items,value,onChange}:{items:string[],value:number,onChange:(n:number)=>void}) { return <Controls>{items.map((s,i)=><button key={s} className={'chip'+(value===i?' active':'')} style={buttonStyle} aria-pressed={value===i} onClick={()=>onChange(i)}>{s}</button>)}</Controls>; }
function Source({children,page:pg}:{children:React.ReactNode,page:number}) {return <p><a href={`${source}#page=${pg}`} target="_blank" rel="noreferrer">原文：{children}</a></p>}
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));

export function ScreenshotSelect(){
 const [position,setPosition]=useState(9),[criterion,setCriterion]=useState(0),[mode,setMode]=useState(0);const dragging=useRef(false);
 const relevant=criterion===0?[2,3,4]:[7,9,11];const selected=mode===1?relevant:[position,position+1,position+2];const coverage=selected.filter(i=>relevant.includes(i)).length;
 function move(e:PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();setPosition(clamp(Math.round(((e.clientX-r.left)/r.width*1080-60)/80-1),0,9));setMode(0)}
 return <><Choices items={['价格','库存']} value={criterion} onChange={setCriterion}/><Choices items={['末尾3帧／移动窗口','逐项top-3']} value={mode} onChange={n=>{setMode(n);if(n===0)setPosition(9)}}/>
 <CanvasView label="教学示意：拖动三帧窗口，或用左右方向键移动" tabIndex={0} style={{touchAction:'none'}} onPointerDown={e=>{dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId);move(e)}} onPointerMove={e=>{if(dragging.current)move(e)}} onPointerUp={()=>{dragging.current=false}} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setMode(0);setPosition(n=>clamp(n+(e.key==='ArrowLeft'?-1:1),0,9))}}} draw={ctx=>{
  for(let i=0;i<12;i++){const x=60+i*80;page(ctx,x,30,65,65);label(ctx,String(i+1),x+22,67,p.ink,22);if(relevant.includes(i)){line(ctx,x+12,83,x+50,83,p.green,4)}if(selected.includes(i)){ctx.strokeStyle=p.orange;ctx.lineWidth=4;ctx.strokeRect(x-4,26,73,73)}}
  if(mode===0){ctx.strokeStyle=p.orange;ctx.lineWidth=3;ctx.strokeRect(56+position*80,22,233,85)}
  selected.forEach((i,j)=>{page(ctx,200+j*240,145,200,105);label(ctx,String(i+1),235+j*240,193,p.blue,34);stamp(ctx,335+j*240,200,relevant.includes(i))});
 }}/><Controls><button className="chip" style={buttonStyle} disabled={mode===0&&position===0} onClick={()=>{setMode(0);setPosition(n=>clamp(n-1,0,9))}}>窗口前移</button><button className="chip" style={buttonStyle} disabled={mode===0&&position===9} onClick={()=>{setMode(0);setPosition(n=>clamp(n+1,0,9))}}>窗口后移</button><Metric label="相关证据覆盖" value={`${coverage}/3`}/></Controls>
 <Feedback tone={coverage===3?'good':'neutral'}>{mode===1?`全轨迹扫描后，为${criterion===0?'价格':'库存'}逐项选出第${selected.map(i=>i+1).join('、')}帧；不是把所有截图塞入一次最终判断。`:`窗口位于第${position+1}至${position+3}帧，覆盖${coverage}份相关证据。末尾三帧未必包含早期价格证据。`}</Feedback><p>教学示意：12帧与相关位置为演示设定，绿色下划线表示相关帧，橙框表示当前选中。论文对每张截图、每项标准打相关性分，逐项取top-k；并列时优先较晚截图。筛选仍可能出错。</p><Source page={6}>p.5–6 §3.4、Algorithm 1；p.16–17 A.3.1</Source></>
}

const categories=[['矛盾','截图：CIDEr提升2.8%。','代理：提升6.2%。','证据与自述冲突，应扣分。',false,'2.8','6.2','≠'],['编造','所有截图均未给出价格。','代理：价格确定为99元。','无证据支撑确定金额，不能用合理猜测替代观察。',false,'?','99','≠'],['遗漏','仅查看了列表的一部分。','代理：已经检查全部条目。','检查范围不足，不能宣称全面完成。',false,'3/10','10/10','≠'],['有据推断','已充分查看相关页面，未出现目标项。','代理：在已检查范围内未找到该项。','限定范围且有充分依据的缺失推断可以接受。',true,'0','0','='],['视觉确认','截图已显示目标修改保存成功。','代理未重复解释每一步。','视觉证据已确认，不因缺少冗余文字而扣分。',true,'✓','✓','=']] as const;
export function EvidenceTaxonomy(){const [category,setCategory]=useState(0);const c=categories[category];return <><Choices items={categories.map(x=>x[0])} value={category} onChange={setCategory}/><CanvasView label={`${c[0]}：左侧视觉证据，右侧代理主张`} draw={ctx=>{page(ctx,110,35,360,205);page(ctx,610,35,360,205);label(ctx,c[5],240,150,p.blue,48);label(ctx,c[6],730,150,c[4]?p.green:p.red,48);label(ctx,c[7],525,150,p.ink,42);stamp(ctx,910,205,c[4]);}}/><p><b>视觉实情：</b>{c[1]} <b>代理主张：</b>{c[2]}</p><Feedback tone={c[4]?'good':'bad'}>{c[3]}</Feedback><p>先按动作文本评分，再用截图核对并重评分；显式冲突时截图优先。第一例来自论文BLIP案例，其余为教学示意。</p><Source page={28}>p.15 A.2、p.16 Figure 5、p.28 Table 7</Source></>}

const stages=[['生成标准','任务目标g','具体、不重叠的评分条目','初始生成不读取轨迹，避免事后迁就代理。'],['全量相关性','全部截图与各条目','截图×条目的相关性矩阵R','每帧都参与筛选，减少早期证据丢失。'],['逐项选图','矩阵R与每项k上限','每项自己的证据集合Sⱼ','不同标准可能需要不同截图，合并后还要去重。'],['分析证据','所选截图、动作记录、标准','有来源的证据分析','组织支持、矛盾和缺失，供后续判断使用。'],['消解条件','条件条目和实际证据','实际适用条目集合','根据观察决定分子、分母中的适用范围。'],['现实校验','代理自述与视觉实情','经视觉核验的事实','不能让代理自述覆盖截图中的明确矛盾。'],['整体重评分','标准、证据与核验事实','连续过程分r_proc','综合判断执行质量，处理级联与条件。'],['副作用检查','完整轨迹和用户授权','额外持久修改及评分修正','检查未请求修改，避免重复惩罚同一已罚项。'],['结果判定','目标、视觉事实、授权边界','二值结果r_out','独立判断用户目标是否完成，不由过程阈值代替。'],['失败诊断','评分、结果、相关轨迹位置','失败类型与位置d','保留可追溯解释，论文归纳为7类诊断。']];
export function VerifierPipeline(){const [stage,setStage]=useState(0);const pos=(i:number)=>({x:140+(i<5?i:9-i)*200,y:i<5?75:205});return <><CanvasView label="十步验证流程，点击节点选择阶段" onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*1080,y=(e.clientY-r.top)/r.height*280;const i=stages.findIndex((_,i)=>{const q=pos(i);return Math.hypot(q.x-x,q.y-y)<40});if(i>=0)setStage(i)}} draw={ctx=>{for(let i=0;i<9;i++){const a=pos(i),b=pos(i+1);line(ctx,a.x,a.y,b.x,b.y,i<stage?p.blue:p.border,5)}stages.forEach((_,i)=>{const q=pos(i);ctx.beginPath();ctx.arc(q.x,q.y,30,0,Math.PI*2);ctx.fillStyle=i===stage?p.orange:p.bg;ctx.fill();ctx.strokeStyle=i===stage?p.ink:p.border;ctx.lineWidth=i===stage?4:2;ctx.stroke();label(ctx,String(i+1),q.x-10,q.y+9,p.ink,24)})}}/><Choices items={stages.map((s,i)=>`${i+1}. ${s[0]}`)} value={stage} onChange={setStage}/><div className="hotspot-info"><p><b>输入：</b>{stages[stage][1]}</p><p><b>输出：</b>{stages[stage][2]}</p></div><Feedback tone="neutral">{stages[stage][3]}</Feedback><p>教学重绘，节点不执行真实LLM调用。可选重复运行第7–9步，过程分取中位数、结果取多数票；这不是十层神经网络。最终输出V(g,τ)=(r_proc,r_out,d)。</p><Source page={6}>p.6 Algorithm 1</Source></>}

const cases=[['只查运费','查询并比较运费，没有修改购物状态。符合委托。',true],['擅自加购','只要求查询却把商品加入购物车：这是额外持久修改，应专门检查，且不重复扣已罚项。',false],['未授权时停下','在未经授权的交易边界前正确停下，论文规则允许判成功。',true],['已授权却停下','用户已授权购买却提前停止，目标未完成，不能判为成功。',false]] as const;
export function SideEffects(){const [caseIndex,setCaseIndex]=useState(0);return <><Choices items={cases.map(x=>x[0])} value={caseIndex} onChange={setCaseIndex}/><CanvasView label="教学示意：任务单、购物篮与授权边界" draw={ctx=>{page(ctx,130,40,320,195);for(let i=0;i<3;i++)line(ctx,170,85+i*35,370,85+i*35,p.border,4);line(ctx,620,85,650,180,p.ink,5);line(ctx,650,180,850,180,p.ink,5);line(ctx,850,180,890,85,p.ink,5);line(ctx,620,85,890,85,p.ink,5);if(caseIndex===1){ctx.fillStyle=p.orange;ctx.fillRect(710,105,60,60)}if(caseIndex>=2){line(ctx,570,30,570,250,p.red,4);label(ctx,caseIndex===2?'未授权':'已授权',650,55,p.blue,24);ctx.fillStyle=p.blue;ctx.beginPath();ctx.moveTo(525,115);ctx.lineTo(555,140);ctx.lineTo(525,165);ctx.fill()}stamp(ctx,955,210,cases[caseIndex][2])}}/><Feedback tone={cases[caseIndex][2]?'good':'bad'}>{cases[caseIndex][1]}</Feedback><p>教学情景，不进行真实交易。权限边界是完成标准的一部分，不能仅检查主目标表面上是否达成。</p><Source page={18}>p.5 §3.5、p.18 Figure 7、p.27 Table 6</Source></>}

export function CostBudget(){const [m,setM]=useState(47);const s=Math.min(10,m),calls=8+m+s;return <><Controls><label htmlFor="cost-m">截图数量 M：{m}</label><input id="cost-m" aria-label="截图数量 M" type="range" min={10} max={100} step={1} value={m} style={{minHeight:44}} onChange={e=>setM(Number(e.target.value))}/><button className="chip" style={buttonStyle} onClick={()=>setM(47)}>恢复论文示例</button></Controls><CanvasView label={`调用数 ${calls}，由3、${m}、${s}、5组成`} draw={ctx=>{const vals=[3,m,s,5],colors=[p.purple,p.blue,p.green,p.orange];let x=80;vals.forEach((v,i)=>{const width=v/118*900;ctx.fillStyle=colors[i];ctx.fillRect(x,90,width,70);label(ctx,String(v),x+Math.max(2,width/2-10),195,p.ink,25);x+=width});line(ctx,80,220,980,220,p.border,2);label(ctx,String(calls),850,65,p.blue,40)}}/><Controls><Metric label="固定生成" value="3"/><Metric label="相关性扫描 M" value={String(m)}/><Metric label="去重证据 S" value={String(s)}/><Metric label="后处理" value="5"/></Controls><Feedback tone="neutral">当前调用数为3 + {m} + {s} + 5 = {calls}。47张截图时为65次调用；并行可缓解时延，但调用成本并未消失。</Feedback><p>演示固定N=3、K=5、S=min(10,M)，启用条件消解、无投票，不计独立诊断成本。S≤min(M,KN)。改变M后的预算为教学推演，不是新实验测量；调用数不能当作串行耗时。</p><Source page={28}>p.18 A.6、p.28 Table 8</Source></>}

const mainData=[[[.31,.45,.24],[.44,.22,.33],[.64,.01,.32]],[[.13,.60,.12],[.26,.40,.12],[.58,.08,.31]]];
const methodNames=['WebVoyager','WebJudge','Universal Verifier'];const models=['GPT-4o','o4-mini','GPT-5.2'];
function DataTable({headers,rows,caption}:{headers:string[],rows:(string|number)[][],caption:string}) {return <div style={{overflowX:'auto',maxWidth:'100%'}}><table className="paper"><caption>{caption}</caption><thead><tr>{headers.map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function drawBars(ctx:CanvasRenderingContext2D,values:number[],progress:number,higher:boolean){const best=higher?Math.max(...values):Math.min(...values);for(let tick=0;tick<=4;tick++){const x=160+tick*200;line(ctx,x,30,x,230,p.border,1);label(ctx,(tick/4).toFixed(2),x-15,260,p.ink,18)}values.forEach((v,i)=>{const y=42+i*62;label(ctx,String(i+1),90,y+25,p.ink,24);bar(ctx,160,y,800,34,v*progress,v===best?p.green:p.blue);label(ctx,(v*progress).toFixed(2),970,y+24,p.ink,22)})}
export function BenchmarkRace(){const [dataset,setDataset]=useState(0),[metric,setMetric]=useState(0),[progress,setProgress]=useState(0),[running,setRunning]=useState(false);useEffect(()=>{if(!running)return;const start=performance.now();let id=0;const tick=(t:number)=>{const n=window.matchMedia('(prefers-reduced-motion: reduce)').matches?1:clamp((t-start)/1500,0,1);setProgress(n);if(n<1)id=requestAnimationFrame(tick);else setRunning(false)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[running]);const reset=()=>{setRunning(false);setProgress(0)};const values=mainData[dataset].map(x=>x[metric]);const best=metric===0?Math.max(...values):Math.min(...values);return <><Choices items={['Internal','Browserbase']} value={dataset} onChange={n=>{reset();setDataset(n)}}/><Choices items={['κ 一致性 ↑','FPR 误报率 ↓','FNR 漏报率 ↓']} value={metric} onChange={n=>{reset();setMetric(n)}}/><Controls><button className="chip" style={buttonStyle} disabled={running} onClick={()=>{setProgress(0);setRunning(true)}}>{running?'比较中…':'开始比较'}</button><Metric label={metric===0?'越高越好':'越低越好'} value={['κ','FPR','FNR'][metric]}/></Controls><CanvasView label="三个验证器共用0至1坐标；表格提供全部精确数据" draw={ctx=>drawBars(ctx,values,progress,metric===0)}/><Feedback tone="neutral">{progress===0?'点击开始，三条柱在相同坐标上同步增长。':`${['κ','FPR','FNR'][metric]}当前最优：${methodNames.filter((_,i)=>values[i]===best).join('、')}，值${best.toFixed(2)}。${metric===2?'UV并非所有指标都最好；低误报仍伴随漏报取舍。':'UV主表误报率为Internal 1%、Browserbase 8%，并非所有场景零误报。'}`}</Feedback><DataTable caption={`${dataset===0?'Internal · 140条 · WebTailBench':'Browserbase · 106条 · OM2W'}；均为Fara-7B轨迹；结果标签`} headers={['图行','方法','骨干','κ ↑','FPR ↓','FNR ↓']} rows={mainData[dataset].map((r,i)=>[i+1,methodNames[i],models[i],...r.map(x=>x.toFixed(2))])}/><p>FPR：把失败判成功；FNR：把成功判失败；κ：扣除偶然一致的一致性系数。只在同一split、同一标签下比较。Browserbase主表使用UV-informed聚合标签；结果取多数票，过程分取中位数后以≥0.8二值化，过程阈值不决定结果。本图为Table 2结果值；Table 15另报三次运行均值±标准差。</p><Source page={8}>p.7 §5、p.8 Table 2、p.31 Table 15</Source></>}

export function AblationCompare(){const [mode,setMode]=useState(0);const rows:(string|number)[][]=mode===0?[[1,'WebVoyager','GPT-5.2','.43','.10','.44'],[2,'WebJudge','GPT-5.2','.33','.07','.57'],[3,'Universal Verifier','GPT-5.2','.64','.01','.32']]:mode===1?[[1,'UV评分器','GPT-5.1','.74','.12','.14'],[2,'UV评分器','GPT-5.2','.68','.00','.28']]:[[1,'UV vs 人工盲标','结果 κ','.39'],[2,'UV vs 知情标注','结果 κ','.63']];const values=mode===0?[.43,.33,.64]:mode===1?[.74,.68]:[.39,.63];return <><Choices items={['同骨干主表','固定标准评分器','盲评与知情']} value={mode} onChange={setMode}/><CanvasView label="当前协议的κ比较，共用0至1坐标" draw={ctx=>drawBars(ctx,values,1,true)}/><DataTable caption={mode===0?'Table 2 · Internal · 结果标签 · 同GPT-5.2骨干':mode===1?'Table 12 · Internal · 结果标签 · 标准固定由GPT-5.2生成':'Table 13 · Browserbase · 106条轨迹 · 结果标签'} headers={mode===2?['图行','比较对象','指标','κ ↑']:['图行','方法','骨干','κ ↑','FPR ↓','FNR ↓']} rows={rows}/><Feedback tone="neutral">{mode===0?'升级骨干不足以复制UV的综合表现；这并非完全隔离所有设计因素的因果实验。':mode===1?'最保守的GPT-5.2评分器误报率为0，但κ .68低于GPT-5.1的.74。Table 12的0%不能替换主表1%。':'揭示UV推理后的κ .63不能等同独立盲评的.39；知情标注协议会改变一致性。'}</Feedback><p>{mode===1?'本消融GPT-5.2过程κ为.61；不可与主表结果κ混用。':mode===2?'另一个协议Table 14包含103个双评审任务：人际结果κ从盲评.57变为知情.53，数值实际降低，不应按正文概括写为提高。':'同骨干比较只展示Internal结果，不外推到另一split。'}</p><Source page={mode===0?8:30}>{mode===0?'p.8 Table 2、p.22 B.3':mode===1?'p.30 Table 12':'p.30 Table 13、p.31 Table 14'}</Source><p><b>外推边界：</b>自动研究在同一Internal数据集上迭代；约70%专家质量、5%时间是作者观察，不是泛化定律。相同提示的结果κ仍在.64–.71间波动，需独立留出评估和多次运行。</p><p>Table 3以UV为参照，并非新增人工金标准：WebVoyager上的Fara-7B共594条轨迹，原生评估成功率74.6%，UV结果成功率37.9%。分歧本身不能独立证明谁正确。</p><Source page={9}>p.9 §6、Table 3；p.24–25 C.1；p.32–33 Tables 17–18</Source></>}
