import {useEffect,useRef,type CSSProperties,type ReactNode,type PointerEventHandler,type KeyboardEventHandler} from 'react';
import {setupCanvas,observeCanvas} from '../lib/canvasKit';

export const palette={bg:'#f5f8f0',light:'#e4ebdc',dark:'#76906a',blue:'#27446e',green:'#228d5c',red:'#c43f52',orange:'#f07e47',purple:'#7c3aed',ink:'#21324a',border:'#d7deea'};
type Draw=(ctx:CanvasRenderingContext2D,w:number,h:number,time:number)=>void;
interface CanvasProps {draw:Draw;height?:number;animate?:boolean;label:string;onPointerDown?:PointerEventHandler<HTMLCanvasElement>;onPointerMove?:PointerEventHandler<HTMLCanvasElement>;onPointerUp?:PointerEventHandler<HTMLCanvasElement>;onKeyDown?:KeyboardEventHandler<HTMLCanvasElement>;tabIndex?:number;style?:CSSProperties}
export function CanvasView({draw,height=280,animate=false,label:description,style,...events}:CanvasProps){
 const ref=useRef<HTMLCanvasElement>(null),drawRef=useRef(draw),paintRef=useRef<()=>void>(()=>{});drawRef.current=draw;
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;let frame=0,visible=false,disposed=false;const media=matchMedia('(prefers-reduced-motion: reduce)');const ctx=setupCanvas(canvas,1080,height);canvas.style.width='100%';canvas.style.height='auto';canvas.style.aspectRatio=`1080 / ${height}`;
 const paint=()=>{if(disposed)return;ctx.save();ctx.clearRect(0,0,1080,height);ctx.fillStyle=palette.bg;ctx.fillRect(0,0,1080,height);drawRef.current(ctx,1080,height,media.matches?0:performance.now());ctx.restore();canvas.classList.add('is-ready');};paintRef.current=paint;
 const stop=()=>{cancelAnimationFrame(frame);frame=0;};const tick=()=>{frame=0;paint();if(visible&&animate&&!media.matches&&!disposed)frame=requestAnimationFrame(tick);};const start=()=>{visible=true;stop();tick();};const leave=()=>{visible=false;stop();};const disconnect=observeCanvas(canvas,start,leave);const change=()=>{stop();paint();if(visible&&animate&&!media.matches)frame=requestAnimationFrame(tick);};media.addEventListener('change',change);paint();return()=>{disposed=true;stop();disconnect();media.removeEventListener('change',change);paintRef.current=()=>{};};},[height,animate]);
 useEffect(()=>{paintRef.current();},[draw]);
 return <canvas ref={ref} role="img" aria-label={description} {...events} onPointerCancel={events.onPointerUp} style={{display:'block',width:'100%',maxWidth:'100%',height:'auto',borderRadius:12,...style}}/>;
}
export function line(c:CanvasRenderingContext2D,x1:number,y1:number,x2:number,y2:number,color:string,width=2){c.save();c.beginPath();c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();c.restore();}
export function label(c:CanvasRenderingContext2D,text:string,x:number,y:number,color:string=palette.ink,size=20){c.save();c.fillStyle=color;c.font=`600 ${size}px system-ui, sans-serif`;c.textAlign='left';c.textBaseline='alphabetic';c.fillText(text,x,y);c.restore();}
export function page(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number){c.save();c.shadowColor='rgba(33,50,74,.10)';c.shadowBlur=12;c.shadowOffsetY=5;c.fillStyle='#fffef9';c.fillRect(x,y,w,h);c.shadowColor='transparent';c.strokeStyle=palette.border;c.lineWidth=1;c.strokeRect(x+.5,y+.5,w-1,h-1);c.fillStyle='#edf0e6';c.beginPath();c.moveTo(x+w-19,y);c.lineTo(x+w,y+19);c.lineTo(x+w-19,y+19);c.closePath();c.fill();c.restore();}
export function pencil(c:CanvasRenderingContext2D,x:number,y:number,angle:number,color:string){c.save();c.translate(x,y);c.rotate(angle);c.fillStyle=color;c.fillRect(-5,-60,10,54);c.fillStyle='#dcb586';c.beginPath();c.moveTo(-5,-6);c.lineTo(0,8);c.lineTo(5,-6);c.fill();c.fillStyle=palette.ink;c.beginPath();c.moveTo(-2,3);c.lineTo(0,8);c.lineTo(2,3);c.fill();c.fillStyle='#fff5';c.fillRect(-3,-58,2,48);c.restore();}
export function loupe(c:CanvasRenderingContext2D,x:number,y:number,r:number,color:string){c.save();line(c,x+r*.7,y+r*.7,x+r*1.55,y+r*1.55,color,Math.max(7,r*.23));c.beginPath();c.arc(x,y,r,0,2*Math.PI);c.fillStyle='rgba(225,239,249,.36)';c.fill();c.strokeStyle=color;c.lineWidth=5;c.stroke();c.beginPath();c.arc(x-3,y-3,r*.68,Math.PI,Math.PI*1.5);c.strokeStyle='#ffffffcc';c.lineWidth=3;c.stroke();c.restore();}
export function stamp(c:CanvasRenderingContext2D,x:number,y:number,ok:boolean){c.save();c.translate(x,y);c.rotate(-.12);const color=ok?palette.green:palette.red;c.strokeStyle=color;c.lineWidth=4;c.beginPath();c.arc(0,0,35,0,Math.PI*2);c.stroke();c.lineWidth=1.5;c.beginPath();c.arc(0,0,29,0,Math.PI*2);c.stroke();c.lineWidth=5;c.lineCap='round';c.beginPath();if(ok){c.moveTo(-16,0);c.lineTo(-4,12);c.lineTo(18,-14);}else{c.moveTo(-12,-12);c.lineTo(12,12);c.moveTo(12,-12);c.lineTo(-12,12);}c.stroke();c.restore();}
export function bar(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,value:number,color:string){c.save();c.fillStyle=palette.border;c.fillRect(x,y,w,h);c.fillStyle=color;c.fillRect(x,y,w*Math.max(0,Math.min(1,value)),h);c.restore();}
export function Controls({children}:{children:ReactNode}){return <div className="tutorial-controls" style={{display:'flex',flexWrap:'wrap',alignItems:'center',gap:12,margin:'18px 0',minWidth:0}}>{children}</div>;}
export function Metric({label:caption,value}:{label:string;value:ReactNode}){return <div style={{padding:'8px 12px',background:palette.bg,border:`1px solid ${palette.border}`,borderRadius:9,minWidth:0,maxWidth:'100%',overflowWrap:'anywhere'}}><span style={{display:'block',fontSize:13,color:palette.ink}}>{caption}</span><strong style={{color:palette.blue,fontSize:18}}>{value}</strong></div>;}
export function Feedback({tone,children}:{tone:'good'|'bad'|'neutral';children:ReactNode}){const color=tone==='good'?palette.green:tone==='bad'?palette.red:palette.blue;return <div role="status" aria-live="polite" style={{padding:'14px 16px',borderLeft:`4px solid ${color}`,borderRadius:8,background:palette.bg,color:palette.ink,lineHeight:1.75,margin:'12px 0',overflowWrap:'anywhere'}}>{children}</div>;}
